### ISSUE TITLE
Cannot start function emulator on v10.2.1

### ISSUE THREAD

**Issue by fthdgn** [firebase/firebase-tools#4238] opened 2022-03-02 10:03 UTC
### [REQUIRED] Environment info

**firebase-tools:** 10.2.1

**Platform:** Windows

### [REQUIRED] Test case

https://gist.github.com/fthdgn/dd6baa2d76fd7cd292d320d2106d7e61

### [REQUIRED] Steps to reproduce

* Create project structure with files provided on gist link. You can download and unzip it.
* Replace `<REDACTED>` on`.firebaserc` with a valid Firebase project
* Run `npm install`
* Run `npm run firebase:emulate`

### [REQUIRED] Expected behavior

The emulator starts.

### [REQUIRED] Actual behavior

The process fails.

Error: `runtime` field is required but was not found in firebase.json.
To fix this, add the following lines to the `functions` section of your firebase.json:
"runtime": "nodejs16

### Additional info
`"firebase-tools": "^9.23.3"` does not have this problem.

**Comment by taeold** [comment] 2022-03-02 23:18
This seems like a duplicate of https://github.com/firebase/firebase-tools/issues/4200.

The latest CLI release (v10.2.2) released today contains fix for this.

Alternatively, you can set `node.engine` config in your `package.json`:

```json
  "engines": {
    "node": "16"
  },
```

**Closed by taeold** 2022-03-02 23:18 UTC
Labels: bug
