### ISSUE TITLE
Firebase Cloud Functions retry=true doesn't work

### ISSUE THREAD

**Issue by fanwgwg** [firebase/firebase-tools#6392] opened 2023-09-22 15:58 UTC
### [REQUIRED] Environment info

**firebase-tools:** 12.5.4

**Platform:** macOS

### [REQUIRED] Test case

Setting a gen2 cloud function's config `retry: true` will cause error `Cannot set a retry policy on Cloud Function` when deploying. However, the official firebase documentation says this is supported https://firebase.google.com/docs/functions/retries#semantics_of_retry

### [REQUIRED] Steps to reproduce

```
exports.customeventhandler = onCustomEventPublished(
  {
    eventType: "firebase.extensions.storage-resize-images.v1.complete",
    retry: true,
  },
  (e) => {
    console.log(JSON.stringify(e));
  });
```

### [REQUIRED] Expected behavior

retry should set the expected retry policy

### [REQUIRED] Actual behavior

retry policy is not set

**Comment by colerogers** [comment] 2023-09-22 18:06
This is a duplicate of #5484

**Closed by colerogers** 2023-09-22 18:06 UTC
Labels: type: bug, api: functions
