### ISSUE TITLE
firebase serve on https

### ISSUE THREAD

**Issue by copypasteearth** [firebase/firebase-tools#1928] opened 2020-01-20 17:47 UTC
hello. I am looking for a command or option that I can use so that the firebase serve command starts the server on https instead of http. I've been looking all over to try to figure this out. I'm trying to get https so I can use things like Bluetooth.

thank you for your time

**Comment by abeisgoat** [comment] 2020-01-21 15:38
Hi!

This isn't doable (easily) due to the way HTTPS works. There are workarounds, but they're extremely convoluted.

The reason this is so complicated is because HTTPS isn't just something that your web server implements, it's a coordination between the server (which we control in the CLI), your browser (which you control, but the CLI doesn't) and what's called a certificate authority (which is controlled by some big company or someone like LetsEncrypt). 

When your server serves over HTTPS it encrypts the normal HTTP contents using a special key (certificate) which was issues by a certificate authority and when that content gets to your browser, the browser says "Okay, I trust X, Y and Z certificate authorities to issue certificates so since this certificate that the content is encrypted with was issued by authority Y then I believe this content is truly secure." 

Now here's the tricky part, these certificates are always pinned to a domain (or a group of domains) so you'll get a cert for `google.com` for example, they wont issue you one for a non-public name (i.e. `localhost`) so if we want to get HTTPS over `localhost`, we need to find a certificate authority that will bend the rules and issue us a certificate for `localhost`. Companies don't do this, so we need to create our own, so the process to enable HTTPS for development is basically...

1. Create your own fake certificate authority / root certificate
1. Configure your browser / operating system to trust this fake authority
1. Acting as the fake authority, issue yourself a cert for localhost
1. Reconfigure your server to serve over HTTPS with the new "real" cert

For details [see this blog post](https://www.freecodecamp.org/news/how-to-get-https-working-on-your-local-development-environment-in-5-minutes-7af615770eec/). Regardless most of these steps are outside the realm of the CLI and are *very* OS/Browser specific, so we can't really help.

Personally, if I really needed HTTPS over localhost, I wouldn't go through the trouble of creating my own root cert, I would either use a public staging URL which had a valid HTTPS cert or I would obtain a valid HTTPS cert and then edit my `/etc/hostnames` to redirect the matching domain to localhost and serve up the real cert locally.

Anyway, sadly, wontfix.

**Closed by abeisgoat** 2020-01-21 15:38 UTC

**Comment by knightcode** [comment] 2020-04-16 21:11
Really?

1. get fullchain.pem/privkey.pem from LetsEncrypt.org for `local.my.host.net` or self-sign
2. edit /etc/hosts:
```
127.0.0.1   localhost local.my.host.net
::1         localhost local.my.host.net
```
3. run server with privkey/fullchain
4. visit `https://local.my.host.net`

done.

**Comment by seanburlington** [comment] 2020-06-06 18:25
Or create a local cert authority 

I know it isn't trivial - but hey - this is web dev 

https://gist.github.com/seanburlington/c7a9bb11efebdf09bed26fc4d7cb6e00

The reason I want this is that `firebase serve` does honour my header settings in firebase.json so my site won't actually work in http mode

I could try and workaround this but 1) browsers are picky about security these days and 2) it's so much better to catch issues in dev by having a relistic setup

**Comment by antoniooi** [comment] 2020-08-07 11:33
Visual Studio can easily allow you to [use HTTPS for localhost](https://stackoverflow.com/questions/39183773/enable-ssl-in-visual-studio) though. I wish firebase can offer something similar so that we can test out something else, e.g. `SameSite` errors that caused by http over https, `navigator.clipboard.writeText` etc. Perhaps the firebase team can make use of the IIS Express of Windows 10 or Visual Studio?

**Comment by Thaina** [comment] 2022-04-27 10:35
I am fine just getting warning page that could just press advance > visit. I just want to 

`local-web-server` package is allow that kind of https and I don't have any problem about that. It's more of a problem to not allow serving https when many feature of html rely on it
