### ISSUE TITLE
Specify which file has JSON parsing error

### ISSUE THREAD

**Issue by abdulrahman** [firebase/firebase-tools#209] opened 2016-08-20 22:21 UTC
When I use the `firebase deploy` command I get this error:

> Error: There was an error loading firebase.json:
> 
> Trailing comma in object at 11:9
>         }
>         ^

My `firebase.json` file looks like this:

```
{
  "database": {
    "rules": "database.rules.json"
  },
  "hosting": {
    "public": "public"
  }
}
```

The json file doesn't even have line 11 !

**Comment by mbleigh** [comment] 2016-08-20 22:48
Could there be a trailing comma in your rules file?

**Comment by abdoosk** [comment] 2016-08-20 23:26
Yes, there was. Removed the comma and got no error :)
I never thought about checking the rules file.

Thank you Michael ♥

**Comment by lingtalfi** [comment] 2016-08-22 07:53
same problem here, using the "firebase serve" command.

```
public > firebase serve

Error: There was an error loading firebase.json:

Trailing comma in object at 6:3
  }
  ^

```

The problem is that it doesn't tell which firebase.json it is using, and there is no such files in the directory whence the command was fired:

```
public > ls
404.html         bower_components index.html       manifest.json    note-app.html    sw-import.js
```

**Comment by mbleigh** [comment] 2016-08-22 17:25
@lingtalfi the Firebase CLI looks up the directory path recursively until it finds a `firebase.json`. It looks like you're listing out your `public` directory. I'd recommend you go up a level and check `firebase.json` and `database.rules.json` (or another rules file) for issues.

**Comment by lingtalfi** [comment] 2016-08-22 17:33
Oh thanks, makes sense. So I went a level up, and now I have this error message (it's not the first time I already had problem with the "firebase serve" command some time ago):
```

pwapp-firebase > firebase serve

Error: There was an error loading firebase.json:

Trailing comma in object at 6:3
  }
  ^
```


But I see no trailling comma in my firebase.json file:


(firebase.json)
```json
{
  "database": {
    "rules": "database.rules.json"
  },
  "hosting": {
    "public": "public"
  }
}

```

Weird.

**Comment by mbleigh** [comment] 2016-08-22 17:43
As I mentioned, also look at `database.rules.json` as the Firebase CLI
parses it when initializing to make sure it's valid.

**Comment by lingtalfi** [comment] 2016-08-22 17:51
Oh I read too fast. Right, there was a trailling comma in "database.rules.json"; removed it and now it works just fine. Thank you. The poster should close this issue then.

**Comment by mbleigh** [comment] 2016-08-22 17:57
I'm going to leave this open with the changed title "Specify which file has JSON parsing error" -- the CLI ought to direct you to the place in which the error actually occurred.

**Comment by joehan** [comment] 2023-03-03 22:24
Someone fixed this! https://github.com/firebase/firebase-tools/blob/master/src/config.ts#L243

**Closed by joehan** 2023-03-03 22:24 UTC
Labels: polish
