### ISSUE TITLE
Can not work failurePolicy in function emulator.

### ISSUE THREAD

**Issue by ytetsuro** [firebase/firebase-tools#3468] opened 2021-06-08 12:22 UTC
The following programs will not work in the current emulator environment.
To be precise, retry by `failurePolicy` does not work in the emulator.

```javascript
const dummy = functions
  .runWith({
    failurePolicy: true,
  }).firestore.document(`hello/{world}`)
  .onCreate(async (snap, context) => {
   throw new Error('infinity loop.');
})
```

It would be great to be able to check with the emulator to avoid infinite loops.

Please submit feature requests through our [support page](https://firebase.google.com/support/contact/bugs-features/).

**Comment by samtstern** [comment] 2021-06-08 14:31
@ytetsuro thanks for the feature request!

**Comment by yuchenshi** [comment] 2021-11-29 21:26
Duplicate of #3738

**Closed by yuchenshi** 2021-11-29 21:26 UTC
Labels: type: feature request, emulator-suite, emulators: functions

**Comment by ChrisGibb** [comment] 2023-03-03 11:54
+1
