### ISSUE TITLE
Functions Emulator not loading `.env` files

### ISSUE THREAD

**Issue by junaga** [firebase/firebase-tools#6621] opened 2023-12-17 10:28 UTC
- `firebase --version`: `13.0.2`
- Platform: Linux

The documentation has an entire section, twice, about how the Firebase Functions Emulator loads `./.env` + `./.env.local`. Well, that feature just does not work. I tried everything.

**Comment by aalej** [comment] 2023-12-18 12:27
Hey @junaga, thanks for reaching out. I tried to reproduce the behavior you mentioned, but I did not encounter any issues with loading the variables from `.env`. 

Could you please file a new issue specifying the details using the provided template? This way, it would be more efficient in identifying the cause of the issue. 

It would also be helpful if you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or code snippets so that we can try to replicate it on our end. 

That said, I'll be closing this issue.

**Closed by aalej** 2023-12-18 12:27 UTC
Labels: type: bug, emulators: functions

**Comment by junaga** [comment] 2023-12-18 12:39
@aalej hi, i'll make a repo. brb

**Comment by junaga** [comment] 2023-12-18 12:55
okay it works for me too, unfortunately i do not remember which commit it failed on, and i did a rebase in the meantime too. but i know the issue somehow exists. sorry again @aalej, i should have started with a repro. have a nice day

**Comment by junaga** [comment] 2023-12-18 12:56
the only real change i had was upgrade to `default-jdk` from `openjdk-11-jdk`

**Comment by aalej** [comment] 2023-12-18 13:34
No worries, I'm glad to hear that you got it working! I'm not exactly sure how upgrading from `openjdk-11-jdk` to `default-jdk` would cause this, but in case you encounter this issue in the future, feel free to reach out to us again.
