### ISSUE TITLE
Initialize Function address is incorrect when exporting groups 

### ISSUE THREAD

**Issue by PSHalanYeats** [firebase/firebase-tools#3014] opened 2021-01-09 22:38 UTC
### [REQUIRED] Environment info

**firebase-tools:** 9.1.0

**Platform:** Windows 

### [REQUIRED] Test case

Directly from Firebase Example 

**metrics.js**

```
const functions = require('firebase-functions');
exports.usageStats = functions.https.onRequest((request, response) => {
  // ...
});
exports.nightlyReport = functions.https.onRequest((request, response) => {
  // ...
});
```

**index.js**

`exports.metrics = require('./metrics');
`

### [REQUIRED] Steps to reproduce

1. Create base method group and export it in index.js
2. Run Firebase emulator 
3. Note the `http function initialized`  Text

### [REQUIRED] Expected behavior

Output should be 
`functions[metrics-nightlyReport ]: http function initialized (http://localhost:5001/project/us-central1/metrics-nightlyReport).`

### [REQUIRED] Actual behavior

`functions[metrics-nightlyReport ]: http function initialized (http://localhost:5001/project/us-central1/metrics.nightlyReport).`

Note that a `.` instead of a `-` in the url for the address.

**Comment by samtstern** [comment] 2021-01-11 10:49
@PSHalanYeats this is a duplicate of #2966 which was fixed in v9.1.1:
https://github.com/firebase/firebase-tools/releases/tag/v9.1.1

If you update you should see the correct URLs

**Closed by samtstern** 2021-01-11 10:49 UTC
