### ISSUE TITLE
Storage Emulator `Create new folder` not working as advertised

### ISSUE THREAD

**Issue by coreform** [firebase/firebase-tools#4413] opened 2022-04-07 01:48 UTC
Not sure where the original issue went...

There is a button that seems to facilitate the creation of a new folder in Storage Emulator however no folder is created.

This poses a problem when working with folders and given that we are left to our own to download Storage objects from a production project, manually upload just so we can download along with a metadata json so as to import into the Storage Emulator. I now need to write a function to create the folders within which to upload the data that should be seeding the data (folders and files).

**Comment by vincekruger** [comment] 2022-04-08 15:09
same problem for me

**Comment by joehan** [comment] 2022-04-11 20:26
Hey @coreform - looks like this is a duplicate of https://github.com/firebase/firebase-tools-ui/issues/738. Since the underlying issue is in that repo, I'm going to close this and continue discussion over there.

**Closed by joehan** 2022-04-11 20:26 UTC
Labels: bug

**Comment by davidnussio** [comment] 2022-04-14 17:05
create folder stop working from firebase-tools@10.3.0
with firebase-tools@10.2.2 create folder is working

**Comment by scadasystems** [comment] 2022-04-22 06:32
You can create a folder by editing the address before uploading the file.

**Comment by yuchenshi** [comment] 2022-04-29 19:53
Fixed in Firebase CLI v10.7.2. You should be able to create folders as usual through the Emulator UI without any workaround after upgrade.
