### ISSUE TITLE
Emulator doesn't recognize firebase-admin

### ISSUE THREAD

**Issue by mpvkarthick** [firebase/firebase-tools#1452] opened 2019-06-30 03:55 UTC
### [REQUIRED] Environment info

**firebase-tools:**7.0.2

**Platform:**macOs

### [REQUIRED] Test case

Index.js
var admin = require("firebase-admin");

package.json
  "dependencies": {
    "firebase-admin": "^8.2.0"
  },

### [REQUIRED] Steps to reproduce

RUN
firebase emulators:exec index.js

### [REQUIRED] Expected behavior
emulator starts with no error

### [REQUIRED] Actual behavior
i  Starting emulators: ["functions"]
✔  functions: Using node@8 from host.
✔  functions: Emulator started at http://localhost:5001
i  functions: Watching "/Users/mpvkarthick/Documents/Business/MobileApp/google/firebase/code/events/http/functions" for Cloud Functions...
⚠  The Cloud Functions emulator requires the module "firebase-admin" to be installed. This package is in your package.json, but it's not available. You probably need to run "npm install" in your functions directory.
i  functions: Your functions could not be parsed due to an issue with your node_modules (see above)

**Comment by samtstern** [comment] 2019-07-01 16:12
The error says `You probably need to run "npm install" in your functions directory.
i functions: Your functions could not be parsed due to an issue with your node_modules`

Can you run:
```
cd functions
npm install
```

and then try again?  If you want to be extra careful you could `rm -rf functions/node_modules` first.

**Comment by mpvkarthick** [comment] 2019-07-06 06:36
I did do that. I even removed the node modules and then again executed npm install. Still no luck.

**Comment by adamelevate** [comment] 2019-07-06 16:27
Exact. same. issue. 😩

**Comment by bkendall** [comment] 2019-07-08 17:48
I created a new project (using `firebase init` - without installing dependencies) and saw the initial behavior you described. However, after installing the dependencies in the functions directory, I was greeted with a different error:

```
firebase init --project bkend-test-stuff
# ... all the init stuff: [functions], Javascript, no eslint, no installing dependencies

firebase emulators:exec index.js
i  Starting emulators: ["functions"]
✔  functions: Using node@8 from host.
✔  functions: Emulator started at http://localhost:5001
i  functions: Watching "/private/var/folders/nq/hzrbwr813ndbwnwnd7bbm14400ccww/T/tmp.M1IgxCNw/functions" for Cloud Functions...
⚠  The Cloud Functions emulator requires the module "firebase-admin" to be installed. This package is in your package.json, but it's not available. You probably need to run "npm install" in your functions directory.
i  functions: Your functions could not be parsed due to an issue with your node_modules (see above)

cd functions && npm i && cd -

firebase emulators:exec index.js
i  Starting emulators: ["functions"]
✔  functions: Using node@8 from host.
✔  functions: Emulator started at http://localhost:5001
i  functions: Watching "/private/var/folders/nq/hzrbwr813ndbwnwnd7bbm14400ccww/T/tmp.M1IgxCNw/functions" for Cloud Functions...
i  Running script: index.js
/bin/sh: index.js: command not found
⚠  Script exited unsuccessfully (code 127)
i  Shutting down emulators.
i  Stopping functions emulator
```

Can you give us a little more detail about your setup, or a more specific reproduction case? Without more information, this is difficult to debug. Thanks.

**Comment by adamelevate** [comment] 2019-07-08 18:06
Can't speak for @mpvkarthick, but my package.json is as below: 
`
  	"engines": {
    	"node": "8"
  	},
	"dependencies": {
	    "firebase-admin": "^8.2.0",
	    "firebase-functions": "^3.0.2",
	    "firebase-functions-helper": "^0.7.1",
  	},
`

Current Node install locally is: 8.9.4
And can definitely verify that "firebase-admin" folder and files are located in "functions>node_modules>firebase-admin"

I'm not sure what more is needed to get the emulator working?

**Comment by samtstern** [comment] 2019-07-08 18:33
What is the goal of running `firebase emulators:exec index.js`?  If you just want to start the emulators you should run `firebase emulators:start`.  If `index.js` is a node script you should probably run `firebase emulators:exec "node index.js"` to be more specific.

**Comment by mpvkarthick** [comment] 2019-07-10 18:21
My issue is resolved.
I ignored my current code base. I created new  from scratch. I just pasted my package.json and pasted functions from the previous code base. Now the emulator works. Of course I faced the problem Issue#1481. I downgraded my firebase-functions verion to 3.0.0 and it worked. But still scratching my head to find out why the old code base isn't working.

**Comment by samtstern** [comment] 2019-07-11 17:53
@mpvkarthick thanks for following up on this!  #1481 will be fixed in the next release.  Since your issue was resolved I am going to close this issue.

**Closed by samtstern** 2019-07-11 17:53 UTC
Labels: Needs: Attention, emulator-suite, emulators: functions
