### ISSUE TITLE
"Build failed ... npm ERR!" during function deployments

### ISSUE THREAD

**Issue by trex-quo** [firebase/firebase-tools#4819] opened 2022-08-02 23:27 UTC
### [REQUIRED] Environment info

**firebase-tools: 11.0.1**

**Platform: macOS Monterey 12.4**

### [REQUIRED] Test case

`firebase deploy --only functions:myFunction`

output:

```
✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing codebase default for deployment
i  functions: Loaded environment variables from .env, .env.prod.
i  functions: preparing functions directory for uploading...
i  functions: packaged /Users/user/Code/github-directory/functions (7.67 MB) for uploading
i  functions: ensuring required API cloudscheduler.googleapis.com is enabled...
✔  functions: required API cloudscheduler.googleapis.com is enabled
✔  functions: functions folder uploaded successfully
i  functions: updating Node.js 16 function myFunction(us-central1)...
Build failed: ...ssing: normalize-path@2.1.1 from lock file
npm ERR! Missing: extend-shallow@2.0.1 from lock file
npm ERR! Missing: fill-range@4.0.0 from lock file
npm ERR! Missing: extend-shallow@2.0.1 from lock file
npm ERR! Missing: is-number@3.0.0 from lock file
npm ERR! Missing: to-regex-range@2.1.1 from lock file
npm ERR! Missing: is-glob@3.1.0 from lock file
npm ERR! Missing: path-dirname@1.0.2 from lock file
npm ERR! Missing: binary-extensions@1.13.1 from lock file
npm ERR! Missing: kind-of@3.2.2 from lock file
npm ERR! Missing: json-stable-stringify@1.0.1 from lock file
npm ERR! Missing: jsonify@0.0.0 from lock file
npm ERR! Missing: has-flag@1.0.0 from lock file
npm ERR! Missing: uglify-to-browserify@1.0.2 from lock file
npm ERR! Missing: yargs@3.10.0 from lock file
npm ERR! Missing: camelcase@3.0.0 from lock file
npm ERR! Missing: cliui@3.2.0 from lock file
npm ERR! Missing: decamelize@1.2.0 from lock file
npm ERR! Missing: get-caller-file@1.0.3 from lock file
npm ERR! Missing: read-pkg-up@1.0.1 from lock file
npm ERR! Missing: require-main-filename@1.0.1 from lock file
npm ERR! Missing: string-width@1.0.2 from lock file
npm ERR! Missing: which-module@1.0.0 from lock file
npm ERR! Missing: y18n@3.2.2 from lock file
npm ERR! Missing: yargs-parser@4.2.1 from lock file
npm ERR! Missing: strip-ansi@3.0.1 from lock file
npm ERR! Missing: wrap-ansi@2.1.0 from lock file
npm ERR! Missing: find-up@1.1.2 from lock file
npm ERR! Missing: read-pkg@1.1.0 from lock file
npm ERR! Missing: path-exists@2.1.0 from lock file
npm ERR! Missing: load-json-file@1.1.0 from lock file
npm ERR! Missing: path-type@1.1.0 from lock file
npm ERR! Missing: parse-json@2.2.0 from lock file
npm ERR! Missing: pify@2.3.0 from lock file
npm ERR! Missing: strip-bom@2.0.0 from lock file
npm ERR! Missing: is-fullwidth-code-point@1.0.0 from lock file
npm ERR! Missing: is-utf8@0.2.1 from lock file
npm ERR! Missing: is-extendable@0.1.1 from lock file
npm ERR! Missing: is-buffer@1.1.6 from lock file
npm ERR! Missing: camelcase@1.2.1 from lock file
npm ERR! Missing: cliui@2.1.0 from lock file
npm ERR! Missing: window-size@0.1.0 from lock file
npm ERR! Missing: center-align@0.1.3 from lock file
npm ERR! Missing: right-align@0.1.3 from lock file
npm ERR! Missing: wordwrap@0.0.2 from lock file
npm ERR! Missing: align-text@0.1.4 from lock file
npm ERR! Missing: lazy-cache@1.0.4 from lock file
npm ERR! Missing: kind-of@3.2.2 from lock file
npm ERR! Missing: longest@1.0.1 from lock file
npm ERR! Missing: is-buffer@1.1.6 from lock file
npm ERR!
npm ERR! Clean install a project
npm ERR!
npm ERR! Usage:
npm ERR! npm ci
npm ERR!
npm ERR! Options:
npm ERR! [--no-audit] [--foreground-scripts] [--ignore-scripts]
npm ERR! [--script-shell <script-shell>]
npm ERR!
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR!
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in:
npm ERR!     /www-data-home/.npm/_logs/2022-08-02T23_09_49_780Z-debug-0.log; Error ID: beaf8772

Functions deploy had errors with the following functions:
	myFunction(us-central1)
i  functions: cleaning up build files...

Error: There was an error deploying functions

```

### [REQUIRED] Steps to reproduce

I don't have an exact list of steps to reproduce this issue, but it has been happening frequently since last week on most of my function deployments. Additionally, this is now even happening on my CircleCI deployments which is an isolated environment. I also have not recently upgraded any of my packages, leading me to believe something is happening on Firebase's end of things outside of just a breaking change on a package.

### [REQUIRED] Expected behavior

Deployment goes through successfully with no npm errors

### [REQUIRED] Actual behavior

Deployment fails with above error

**Comment by whiplashoo** [comment] 2022-08-03 12:12
I get slightly different error when trying to update my functions via `firebase deploy --only functions`:

```
Build failed: npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: @firebase/app-compat@0.1.30 from lock file
npm ERR! Missing: @firebase/app@0.7.29 from lock file
npm ERR! Missing: @firebase/component@0.5.17 from lock file
npm ERR! Missing: @firebase/logger@0.3.3 from lock file
npm ERR! Missing: @firebase/util@1.6.3 from lock file
npm ERR! Missing: @firebase/component@0.5.17 from lock file
npm ERR! Missing: @firebase/logger@0.3.3 from lock file
npm ERR! Missing: @firebase/util@1.6.3 from lock file
npm ERR! Missing: idb@7.0.1 from lock file
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [--no-audit] [--foreground-scripts] [--ignore-scripts]
npm ERR! [--script-shell <script-shell>]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info
```

All packages and `firebase-tools` are updated to their latest version. I also tried running `npm i` to make sure the package files are up-to-date.

**Comment by trex-quo** [comment] 2022-08-03 16:40
Here are two other similar issues. Deployments are completely broken for my team and me right now.
https://github.com/firebase/firebase-tools/issues/4822
https://github.com/firebase/firebase-tools/issues/4779

**Comment by taeold** [comment] 2022-08-03 17:46
We are investigating, though we aren't able to reproduce this error consistently on our side yet :(.

**Comment by whiplashoo** [comment] 2022-08-04 14:40
It seems that the instructions from @taeold from https://github.com/firebase/firebase-tools/issues/4822#issuecomment-1205219275 work. What I did:

- Switched to node v16.16.0 on my machine.
- Tried `npm ci` and got the aforementioned error.
- Ran `npm install` again on both the root and the functions folder.
- `firebase deploy --only functions` finally worked (albeit it took some more time than usual to update).

**Comment by taeold** [comment] 2022-08-04 17:05
Going to mark this a duplicate of https://github.com/firebase/firebase-tools/issues/4822 to consolidate our effort.

**Note to others** - Sudden appearance of `Build failed: npm ERR! code ERESOLVE` on your function deployment means your `package-lock.json` file had latent "bug" i.e. incompatible dependency graph that is now being surfaced. GCF platform recently upgraded to using node `16.16.0` which bundles `npm` binary that errors out when given invalid dep graph. Please try installing this version of node and run `npm ci` to reproduce the error locally.

`npm` core team isn't pursuing a plan to revert this change and recommend users to fix the conflicting dependencies. You can also try using the `--legacy-peer-deps` flag on `npm install` command to override the conflicting deps.

**Closed by taeold** 2022-08-04 17:05 UTC
Labels: bug

**Comment by risalfajar** [comment] 2022-11-12 12:00
In my case, this happens when I'm using pnpm instead of npm.

I think this should be mentioned in the docs or CLI.

**Comment by Ridermansb** [comment] 2023-02-15 09:42
What I did was add `.npmrc` file with content

```
legacy-peer-deps=true
```

Reference: [issues/241076152](https://issuetracker.google.com/issues/241076152)

**Comment by mr-chandan** [comment] 2024-10-10 13:58
remove package-lock.json and deploy it should work
