### ISSUE TITLE
Functions predeploy script exits silently if it contains an `=` sign

### ISSUE THREAD

**Issue by valeriangalliat** [firebase/firebase-tools#5596] opened 2023-03-14 23:25 UTC
### [REQUIRED] Environment info

**firebase-tools:** 11.24.1

**Platform:** macOS

### [REQUIRED] Test case

In `firebase.json`:

```json
{
  "functions": {
    "predeploy": [
      "echo a=b && echo hello"
    ]
}
```

### [REQUIRED] Steps to reproduce

```sh
firebase deploy --only functions
```

### [REQUIRED] Expected behavior

Before deploying, it echoes `a=b` then `hello` on the next line.

### [REQUIRED] Actual behavior

```
i  deploying functions
Running command: echo a=b && echo hello
✔  functions: Finished running predeploy script.
```

---

Logging `translatedCommand` [here](https://github.com/firebase/firebase-tools/blob/b3081110fe0e53ec4292132af697d609bf848805/src/deploy/lifecycleHooks.ts#L12-L19) gives the following:

```
"/path/to/node" "/path/to/node_modules/cross-env/dist/bin/cross-env-shell.js" "echo a=b && echo hello"
```

Which brings us to `npx cross-env-shell "echo a=b && echo hello"` not running the command as expected.

Turns out this is tracked in https://github.com/kentcdodds/cross-env/issues/246 but sadly cross-env is no more maintained and has been archived, which means this won't be fixed there.

It seems that if we want Firebase to not silently break when a `predeploy` command includes an `=` sign, we need to use something else than `cross-env` to run the script.

**Comment by taeold** [comment] 2023-03-15 01:55
Thanks for raising the issue @valeriangalliat!

Going to mark this as duplicate of https://github.com/firebase/firebase-tools/issues/5339.

We also don't have too much resource at hand to address this issue atm. It looks like more users are getting tripped up with the limitation - let me see if we can at least output a useful error message...

**Closed by taeold** 2023-03-15 01:55 UTC
Labels: type: bug
