### ISSUE TITLE
Intermittent failure: `curl -sL https://firebase.tools` exits with code 7

### ISSUE THREAD

**Issue by vijaytholpadi** [firebase/firebase-tools#4758] opened 2022-07-20 14:41 UTC
### [REQUIRED] Environment info

**firebase-tools:**
macOS. Trying to fetch the tools using curl in this case.

**Platform:**
macOS

### [REQUIRED] Test case

Attached in the Actual Behavior section. Please let me know if I can share more info.

### [REQUIRED] Steps to reproduce

- Run `curl -sL https://firebase.tools` on CircleCI
- Builds will intermittently fail

### [REQUIRED] Expected behavior

Executing `curl -sL https://firebase.tools` should install the firebase tool. And this happens on retrying.

### [REQUIRED] Actual behavior

`curl -sL https://firebase.tools` exits with code 7 intermittently. Just retying again works without an issue.

Screenshot from CircleCI:
![Screenshot 2022-07-20 at 10 37 34 PM](https://user-images.githubusercontent.com/1171868/180009858-05b6d553-67a1-45ff-b098-5d50923068ca.png)

**Comment by bkendall** [comment] 2022-07-20 22:53
Without more information, I'm going to assume the exit code is coming from `curl`, which means that it couldn't connect to the `firebase.tools` host. Unfortunately, there's not much we can do about that (since it'd just be that the internet is misbehaving, or CircleCI isn't letting the connection out, or... something), so without a reliable reproduction case I'm going to have to close this.

If you're seeing this continue, I'd consider (a) breaking off the `curl` command to make sure it _is_ a connection issue that's happening, and (b) reaching out to CircleCI to have them investigate why the connection is sometimes not made.

(FWIW, I did think that this might be a "the environment only has IPv6 capabilities", but we do advertise `AAAA` records for `firebase.tools`, so that shouldn't be what's happening)

**Closed by bkendall** 2022-07-20 22:53 UTC
Labels: bug

**Comment by nwainwright** [comment] 2022-07-21 13:18
@bkendall @vijaytholpadi it's also been happening for us too. For a few weeks. Intermittent but annoying :) We'll reach out to CircleCI but any tips would be appreciated.

**Comment by bkendall** [comment] 2022-07-21 17:10
@vijaytholpadi yes - doing `curl | bash` doesn't distinguish very well if it's `curl` returning the error code or the script itself. I imagine it's `curl` (since that error code would make sense), but it would be best to confirm.

**Comment by vijaytholpadi** [comment] 2022-08-09 13:42
@bkendall 

To update you and everyone else watching this thread, [CircleCI confirmed](https://discuss.circleci.com/t/intermittent-failures-firebase-tools-exited-with-code-exit-status-7/44761/12?u=vijaytholpadi) that they are able to reproduce this issue at their end for `curl` usage and have suggested to use `wget` instead to get the firebase tools.
