### ISSUE TITLE
Error: An unexpected error has occurred. - Error: read ECONNRESET

### ISSUE THREAD

**Issue by lborgman** [firebase/firebase-tools#1455] opened 2019-07-02 00:58 UTC
### [REQUIRED] Environment info

**firebase-tools:**
7.0.2

**Platform:**
Windows

### [REQUIRED] Test case

Sorry. I have no minimal test case. This is an intermittent error. But frequent now.

### [REQUIRED] Steps to reproduce
1. firebase serve --debug
2. Open some pages in web browser.
(Sorry, I have no idea yet what triggers the problem.)

### [REQUIRED] Expected behavior
Just normal functioning. I see nothing special. The web server just stops.

### [REQUIRED] Actual behavior

Normal output and then this:

127.0.0.1 - - [02/Jul/2019:00:45:26 +0000] "GET /__/firebase/6.1.0/firebase-firestore.js HTTP/1.1" 200 355679 "http://localhost:5000/caped-editor.html?loadFrom=local&key=YT-QM10xrItkoU" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
[2019-07-02T00:45:26.779Z] Error: read ECONNRESET
    at TLSWrap.onread (net.js:622:25)

Error: An unexpected error has occurred.

**Comment by samtstern** [comment] 2019-07-08 18:30
@lborgman thanks for filing this, just to set expectations since this is a bug that only reproduces occasionally we will probably not be able to find the root cause unless it happens to one of us by chance as well.

**Comment by lborgman** [comment] 2019-07-08 22:27
@samtstern
Thanks, yes, of course. But "intermittent" or "occasionally" are not really the right words here. It happens very often. I filed the bug just to see if you have heard of it. 

I think I have to investigate my PC. I'll notify you if I understand what is going on.

**Comment by lborgman** [comment] 2019-07-09 16:52
Some more info. Checked event log. Scanned my pc for virus etc. Went to intel.com and run a scan for drivers. Some part of the wifi stack could be updated so I did that.

Rebooted. Immediately, on first page reload, got exactly the same error (in net.js at 622:25, TLSWrap.onread).

There is definitively a bug that can be catched. Looks like a race condition, but since it is so frequent here is a good chance to find it. If you are interested, please contact me.

**Comment by lborgman** [comment] 2019-07-11 17:05
Even more info. I got hit by the problem with the Chrome extension "Apps Launcher". I think those problem might be resolved on my PC now. And Chrome behaves a bit different. (I noticed some strange delay or even dropped event from the UI the latest days.)

FYI: Windows defender did not catch this. I tried Kaspersky instead which found an issue, but did perhaps not resolve it completely. I am not sure, I have to little info at the moment.

There might have been some URL hijacking going on with some kind of middle-ware that caused the slightly strange behavior I noticed. And the crashes.

**Comment by samtstern** [comment] 2019-07-11 17:06
@lborgman thanks for going through all that debugging and following up as you did!  We really appreciate the effort. 

So it sounds like this is fixed for you now?  Should I close the issue?

**Comment by lborgman** [comment] 2019-07-11 17:15
@samtstern Yes, it looks like it was the malware. (You may want to forward that info, of course, to those trying to fix the problem with Google's Chrome extension "Apps Launcher". The extension has been taken down, but it was not removed from affected browsers.)

**Comment by samtstern** [comment] 2019-07-11 17:21
@lborgman thanks for the heads up!

**Closed by samtstern** 2019-07-11 17:21 UTC
Labels: api: hosting, type: bug
