### ISSUE TITLE
Local firestore emulator webchannel configure not work

### ISSUE THREAD

**Issue by hikaruna** [firebase/firebase-tools#1646] opened 2019-09-05 21:18 UTC
### [REQUIRED] Environment info

**firebase-tools:**
7.3.1

**Platform:**
Linux(use Docker node:12.9.1-stretch image)

### [REQUIRED] Test case

```json
// firebase.json
{
  "firestore": {
    "rules": "firestore.rules"
  },
  "emulators": {
    "firestore": {
      "host": "0.0.0.0",
      "webchannel-port": 10055
    }
  }
}
```

```console
$ npx firebase emulators:start --only firestore
```

### [REQUIRED] Steps to reproduce

```console
$ npm i firebase-tools
```

### [REQUIRED] Expected behavior

```console
root@8057431e08b7:/usr/src/app (master *)# npx firebase emulators:start --only firestore
firestore: Serving WebChannel traffic on at http://0.0.0.0:10055

```

- host configuration 
- port configuration
- webchannel host configuration
- webchannel port configuration

is working.
In particular, I want webchannel host 0.0.0.0.

### [REQUIRED] Actual behavior

```console
root@8057431e08b7:/usr/src/app (master *)# npx firebase emulators:start --only firestore --debug
[2019-09-05T20:57:30.281Z] ----------------------------------------------------------------------
[2019-09-05T20:57:30.293Z] Command:       /usr/local/bin/node /usr/src/app/node_modules/.bin/firebase emulators:start --only firestore --debug
[2019-09-05T20:57:30.295Z] CLI Version:   7.3.1
[2019-09-05T20:57:30.295Z] Platform:      linux
[2019-09-05T20:57:30.296Z] Node Version:  v12.9.1
[2019-09-05T20:57:30.298Z] Time:          Thu Sep 05 2019 20:57:30 GMT+0000 (Coordinated Universal Time)
[2019-09-05T20:57:30.298Z] ----------------------------------------------------------------------

i  Starting emulators: ["firestore"]
i  firestore: Serving WebChannel traffic on at http://0.0.0.0:8081
[2019-09-05T20:57:30.352Z] Ignoring unsupported arg: projectId
[2019-09-05T20:57:30.353Z] Ignoring unsupported arg: auto_download
[2019-09-05T20:57:30.355Z] Starting emulator firestore with command {"binary":"java","args":["-Duser.language=en","-jar","/root/.cache/firebase/emulators/cloud-firestore-emulator-v1.8.2.jar","--host","0.0.0.0","--port",8080,"--rules","/usr/src/app/firestore.rules","--webchannel_port",8081],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator"]}
i  firestore: Emulator logging to firestore-debug.log
[2019-09-05T20:57:33.244Z] API endpoint: http://0.0.0.0:8080

[2019-09-05T20:57:33.246Z] WebChannel endpoint: http://localhost:8081
If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:

   export FIRESTORE_EMULATOR_HOST=0.0.0.0:8080

Dev App Server is now running.


✔  firestore: Emulator started at http://0.0.0.0:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=0.0.0.0:8080
✔  All emulators started, it is now safe to connect.
```

#### Probrem1. Host configure not work
cli display ```[2019-09-05T20:57:33.244Z] API endpoint: http://0.0.0.0:8080```.
But, log display ```[2019-09-05T20:57:33.246Z] WebChannel endpoint: http://localhost:8081```.

Host is different!. And Host configure not work.

#### Probrem2. webchannel-port configure not work
or this feature does not exist?

**Comment by samtstern** [comment] 2019-09-05 21:29
@hikaruna right now this is all intended behavior.  The only valid option is `port` and we choose `port+1` as our preferred WebChannel port.

The reason for this is that @ryanpbrewster is working on making it so that, one day, we can serve both WebChannel and HTTP traffic over the same port in the emulator.  So we don't want to introduce new `webchannel-port` options that we'd break in the near future.

Is the current situation OK for your use case?

**Comment by samtstern** [comment] 2019-09-05 21:29
[closing as intended behavior but let's keep discussing!]

**Comment by hikaruna** [comment] 2019-09-05 21:43
Thank you @samtstern.

I think this issue is too early to be closed, Because the problem still remains.

Host becomes localhost( It is not host configuration value).
Isn't this supposed to be fixed "to work with settings"?

**Comment by samtstern** [comment] 2019-09-05 21:55
@hikaruna the only host we support is `localhost` ... are you in a situation where you can't use localhost?

**Comment by ryanpbrewster** [comment] 2019-09-05 23:12
Ah, gotcha, you want the webchannel traffic to inherit the normal hostname. Totally reasonable. I'll plumb that through.

**Comment by ryanpbrewster** [comment] 2019-09-05 23:47
Done, should go out with the next release. Thanks for filing this :)

**Closed by ryanpbrewster** 2019-09-05 23:47 UTC
Labels: emulator-suite, emulators: firestore
