### ISSUE TITLE
Environment Config settings add slashes

### ISSUE THREAD

**Issue by sketchthat** [firebase/firebase-tools#371] opened 2017-06-13 23:25 UTC
Running Firebase-Tools 3.9.1 on a Mac, when I store a `\` it adds slashes and converts to `\\`.

This is an issue when trying to store the Firebase Storage PEM file in environment settings.

```
--- BEGIN PRIVATE KEY ---\n
...
--- END PRIVATE KEY ---\n
```

Converts to 

```
--- BEGIN PRIVATE KEY ---\\n
...
--- END PRIVATE KEY ---\\n
```

Which causes the authentication to fail. 

This issue wasn't happening last week, so it appears to be a new issue.

**Comment by laurenzlong** [comment] 2017-06-16 16:27
Can you please add repro instructions, including the exact set command you used? Thanks.

**Comment by sketchthat** [comment] 2017-06-17 07:52
```
$ firebase functions:config:set foo.bar="Hello\World" --project my-project-0000
✔  Functions config updated.

Please deploy your functions for the change to take effect by running firebase deploy --only functions

$ firebase functions:config:get foo.bar --project my-project-0000
"Hello\\World"
```

Should it be adding slashes? Last week (Not sure of the version) I added a string with a slash and it didn't double up, but this week it does. So not sure how to handle it in code.

**Comment by sketchthat** [comment] 2017-06-17 07:54
In real-world apps I've been adding the firebase json credentials to the config so I can connect with the storage tools. Last week PEM uploaded correctly, this week it adds slashes on the `\n` and converts to `\\n`.

**Comment by laurenzlong** [comment] 2017-06-20 04:54
Thanks for the repro instructions, I've reproduced it and will work on a fix.

**Comment by laurenzlong** [comment] 2017-06-20 09:49
Hey @sketchthat , after some investigations, I figured out that this is an issue with one of our dependencies -  Cloud Runtime Configuration. I've filed the bug with the team, and will keep you posted on their progress.

**Comment by janakaj** [comment] 2017-07-03 06:46
I have the same issue.

**Comment by janakaj** [comment] 2017-08-04 14:31
Hi @laurenzlong I don't know why my comment was downvoted, but is there any update on this issue?

**Comment by patrickmcd** [comment] 2017-08-04 16:59
@janakaj Comments like "I have the same issue" and "is there any update" are spam to watchers of Github repos.

If you have the same issue as reported, upvote the original, and then please exercise patience rather than filling our inboxes with comments that don't add to the conversation.

**Comment by YuniorGlez** [comment] 2017-10-17 11:15
I found a walkthrough (or awful solution)  :S I don't wanna to do that but ... It's works >,< 

You can do it a `.replace(/\\n/g, '\n')` to the private_key 

```javascript
const serviceAccount = functions.config().fireenv;

admin.initializeApp({
   credential: admin.credential.cert({
      "projectId": serviceAccount.project_id,
      "private_key": serviceAccount.private_key.replace(/\\n/g, '\n'),
      "clientEmail": serviceAccount.client_email
   }),
   databaseURL: whatever,
   ...
});
```
@sketchthat @janakagamini @patrickmcd I know it was 4 months ago but .. :)

**Comment by sketchthat** [comment] 2017-10-17 22:01
@YuniorGlez - Are you using the environment details to initialise the admin library? Cloud Functions will do this by itself.

I needed the environment details to access Google Cloud Storage. I ended up including a `json` file into the build.

```
  const storage = await import('@google-cloud/storage');
  const storageCreds = require('credentials.json');

  const gcs = storage({
    projectId: storageCreds.project_id,
    credentials: storageCreds,
  });

  const bucket = gcs.bucket(functions.config().firebase.storageBucket);
```

**Comment by kaYcee** [comment] 2018-08-14 18:57
Has this issue been fixed? I just came across a similar issue when using a dollar sign in the value-part of `functions:config:set`. E.g. `firebase functions:config:set test.var="abc$def"` deploys fine. But `firebase functions:config:get test.var` gives only `"abc"`. The same issue arises when reading the environment variables with `functions.config()`.

**Comment by bkendall** [comment] 2019-01-09 00:34
Similar to #378 - should investigate this as well and do make a decision. Maybe documentation needs to be updated to talk about using special characters?

**Comment by worknudge** [comment] 2020-02-04 21:11
in Feb 2020 this still seems to be an issue. With no mention in the documentation. Any update?
I know we are supposed to up vote issues, but a year later I feels warrants a comment here.

**Comment by lukeinthecloud** [comment] 2020-02-04 21:16
@YuniorGlez Thanks for the save here. The amount of time I spent trying to figure out what was going on with my keys is too much.

This really needs to be updated.

**Comment by CosmicPangolin** [comment] 2020-03-24 19:47
@laurenzlong @worknudge @lukeinthecloud 

Also faced this.  Couldn't find a solution on Windows except spinning up a WSL with firebase CLI and using: 

`firebase functions:config:set service_account="$(cat service-account.json)"`

It's way too hard to securely access Google APIs from a Dart function (without saving credentials in code).  Some googleapis_auth functions like clientViaMetadataServer don't work on Node, GCloud Function Env Vars aren't exposed in Firebase Functions Interop, and getting the key into Firebase env config takes silly backflips :)

**Comment by cm45t3r** [comment] 2020-06-03 22:18
> Hey @sketchthat , after some investigations, I figured out that this is an issue with one of our dependencies - Cloud Runtime Configuration. I've filed the bug with the team, and will keep you posted on their progress.

Hi @laurenzlong, any update on this issue? thanks.

**Comment by quantuminformation** [comment] 2020-09-25 07:53
just found this today

I stored

```
  "hosting": {
    "base_url": "https://mentor-cv-staging.web.app"
  },```

which adds a slash and breaks my CORS setting

```js
app.use(cors({ origin:  functions.config().hosting.base_url}))
```

**Comment by quantuminformation** [comment] 2020-09-25 08:25
For now I just done

```js
app.use(cors({ origin: functions.config().hosting.base_url.replace(/\/$/, "") }))
```

**Comment by joehan** [comment] 2021-06-23 17:46
@taeold, passing this along to you to make sure it gets fixed in the incoming `env:*` commands.

**Comment by taeold** [comment] 2021-06-25 09:38
In fairness, this problem isn't specific to the Firebase CLI. Passing escape sequence to a program from shell is generally tricky. https://stackoverflow.com/questions/11433977/passing-new-lines-in-command-line-argument explains things better than I can.

To demo, here's a program that just spits out arguments it gets:

```js
// args.js
console.log(process.argv.slice(2))
```

```bash
$ node args.js "a\nb"
[ 'a\\nb' ]

$ node args.js "Hello\World"
[ 'Hello\\World' ]

$ node args.js "abc$def"
[ 'abc' ]
```

Firebase CLI is just working with the argument it gets.

Here's a trick - surround your strings with `$'` (this feature is called [ANSI-C Quoting](http://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html) - your shell probably implements it):

```bash
$ node args.js $'a\nb'
[ 'a\nb' ]

$ node args.js $'Hello\World'
[ 'Hello\\World' ] # \W isn't a valid escape character so nothing is done.

$ node args.js $'abc$def'
[ 'abc$def' ]
```

Given that, I'm not sure how I can explain the fact that this issue was reported as a regression. But hoping that the trick is useful for folks experiencing a similar issues.

**Comment by wmadden** [comment] 2021-07-28 11:18
@taeold this problem _is_ specific to the Firebase CLI.

Even if you correctly escape the arguments so that Node receives the string as intended, something in the Firebase CLI stack escapes the new line characters.

# Repro instructions

1. As you said above we know that escaping a string with `$''` doesn't cause newlines to be represented by `\\n` once the argument is interpreted by Node, and we can test that with your `args.js` script:
```
$ node args.js $'a\nb'
[ 'a\nb' ]
```

2. Set a functions config variable including a newline using the Firebase CLI using the same syntax, deploy it and read it out again
```
> firebase functions:config:set a.b=$'a\nb'
> firebase deploy --only functions
> firebase functions:config:get
{
  "a": {
    "b": "a\\nb"
  }
}
```

> Given that, I'm not sure how I can explain the fact that this issue was reported as a regression. But hoping that the trick is useful for folks experiencing a similar issues.

It's been four years now and the closest this issue has come to a response by the maintainers is being attributed to user error and closed for inactivity. That's a bit frustrating. It's really not hard to reproduce based on @sketchthat's initial description, and the end result is everyone is committing service account credentials to their source code.

Please address the issue or document the limitation that newlines will be incorrectly encoded by the CLI.

**Comment by taeold** [comment] 2021-07-28 15:48
@wmadden Thanks for giving your feedback. I'll go ahead and re-open the issue.

I'm having trouble reproducing the issue you are reporting. Here's what I got:

```
$ node -v
v14.15.4
$ firebase --version
9.16.0
$ firebase functions:config:set a.b=$'a\nb'
$ firebase functions:config:set c.d="c\nd"
$ firebase functions:config:get a.b
{
  "a": {
    "b": "a\nb"
  },
  "c": {
    "d": "c\\nd"
  },
}
```

(I tried running `firebase deploy` in between the config commands, but that didn't seem to change anything).

On my Mac, using zsh, things appear to work as expected. I tried running the command on a different platform (Ubuntu) and on a different terminal (bash) with same results.

I'm unsure where the bug might be - maybe this is a platform-specific issue? Old node version? Old firebase CLI version?

Do you mind sharing your setup with us?

**Comment by wmadden** [comment] 2021-07-28 15:51
No problem! I'm also on a Mac using zsh, here are my Node and Firebase versions:

```
$ node -v
v14.16.1
$ npx firebase --version
9.14.0
```

**Comment by wmadden** [comment] 2021-07-28 16:02
@taeold `npx` might be adding another layer of escaping. If I use your commands exactly as in your comment then it records `a\nb` correctly, but if I use `npx firebase functions config:set` it stores the result with double backslashes. 

I'm not sure if that would have caused the original issue, which might have predated `npx`, but it's worth noting now

```
$ npx firebase functions:config:set a.b=$'a\nb'; npx firebase functions:config:get
✔  Functions config updated.

Please deploy your functions for the change to take effect by running firebase deploy --only functions

{
  "a": {
    "b": "a\\nb"
  }
}
```

```
$ firebase functions:config:set a.b=$'a\nb'; firebase functions:config:get
✔  Functions config updated.

Please deploy your functions for the change to take effect by running firebase deploy --only functions

{
  "a": {
    "b": "a\nb"
  }
}
```

**Comment by taeold** [comment] 2021-07-28 17:35
😢  That's very strange. Wonder what's going on in`npx` that swallows the string quoting.

Here's yet another "it works on my machine" 🤦 

```
$ npx --version
6.14.10
$ npx firebase functions:config:set a.b=$'a\nb' && npx firebase functions:config:get                                                                                                           
✔  Functions config updated.

Please deploy your functions for the change to take effect by running firebase deploy --only functions

{
  "c": {
    "d": "c\\nd"
  },
  "a": {
    "b": "a\nb"
  },
}
```

Newline escaping is looking to be a big PITA, and Firebase CLI could be something more to make this process better. There are some updates to how environment configurations are managed rolling out soon, and I'll make sure this problem is considered in that rollout.

@wmadden You are not the original author of this issue, but wondering if at least your problem is addressed with the `$'` escaping. If so, feel free to close the issue.

**Comment by wmadden** [comment] 2021-07-28 17:49
@taeold I don't have adequate Github permissions to close the issue and, no offence, I'm not convinced it's adequately addressed. It took me a solid day and a half of experimentation and Googling to a) find this thread and b) give up and add `.replace(/\\n/g, '\n')` to my code.

People have been having issues with this since 2017 and, like the original author way back then, I'm trying to store a service account private key in a config variable. So it's probably safe to assume other people will do too and run into the same issues, if they don't just commit their [service account keys to their codebase](https://stackoverflow.com/questions/54571158/deploying-different-service-account-credentials-json-file-to-different-cloud-fun) 😬 

There is [low-key confusion](https://stackoverflow.com/questions/53161614/firebase-environmental-config-added-slashes-to-private-key-id/68559543#68559543) scattered around the web surrounding this issue, so it deserves a better solve than "couldn't reproduce".

Also, in case it helps:

```
$ npx --version
7.10.0
```

P.S. I appreciate you responding so quickly considering how long this ticket was open and unresolved ❤️

**Comment by taeold** [comment] 2021-07-28 19:09
@wmadden Great suggestions there. I went ahead and filed a FR on better support for multiline strings for firebase config. I can't promise that I will work on it right away, but as I mentioned before, I'll try to include this fragile UX in our discussions.

Since this issue seems to get good SEO, here is a summary of suggested workaround to avoid having extra slashes add to your config values:

### Option 1: Use ANSI-C quoting

```
$ firebase functions:config:set some.key=$'Hello\nWorld'
$ firebase functions:config:get some.key
"Hello\nWorld"
```

### Option 2: Write config value to a file and run the following commands:

```
$ firebase functions:config:set some.key="$(cat path/to/private.pem)"
$ firebase functions:config:get some.key
"-----BEGIN PRIVATE KEY-----\nMI...
```

**Closed** 2021-08-10 01:00 UTC
Labels: type: bug, api: functions, Needs: Author Feedback, no-recent-activity, closed-by-bot
