### ISSUE TITLE
emulators:export fails saying it didn not find any running emulator

### ISSUE THREAD

**Issue by danielo515** [firebase/firebase-tools#4718] opened 2022-07-07 07:21 UTC
### [REQUIRED] Environment info

**firebase-tools:** firebase --version: 10.1.1

**Platform:** macOS

### [REQUIRED] Steps to reproduce

1. Navigate to a firebase project directory. Run firebase init in an npm directory to initialise one.
2. Run the emulators with the following command:

```
firebase emulators:start --only firestore
```
3. Open a new terminal window in the same repository and run the following command:
```
firebase emulators:export ./seeds
```

### [REQUIRED] Expected behavior

I want to see the data exported to the folder

### [REQUIRED] Actual behavior

The command fails and complains that it did not found any running emulator.

Debug log file before trying to export:

```
[debug] [2022-07-07T07:17:29.304Z] ----------------------------------------------------------------------
[debug] [2022-07-07T07:17:29.305Z] Command:       /Users/danielo/.nvm/versions/node/v16.13.0/bin/node /Users/danielo/.nvm/versions/node/v16.13.0/bin/firebase emulators:start --only firestore,functions --export-on-exit=./seeds --debug
[debug] [2022-07-07T07:17:29.306Z] CLI Version:   10.1.1
[debug] [2022-07-07T07:17:29.306Z] Platform:      darwin
[debug] [2022-07-07T07:17:29.306Z] Node Version:  v16.13.0
[debug] [2022-07-07T07:17:29.307Z] Time:          Thu Jul 07 2022 09:17:29 GMT+0200 (Central European Summer Time)
[debug] [2022-07-07T07:17:29.308Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-07-07T07:17:29.356Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-07-07T07:17:29.357Z] > authorizing via signed-in user (rdanielo@gmail.com)
[info] i  emulators: Starting emulators: functions, firestore {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: functions, firestore"}}
[debug] [2022-07-07T07:17:29.372Z] [hub] writing locator at /var/folders/rz/6t__5md11ms0cfysw43yrybr0000gn/T/hub-axel-log.json
[warn] ⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, database, hosting, pubsub, storage {"metadata":{"emulator":{"name":"functions"},"message":"The following emulators are not running, calls to these services from the Functions emulator will affect production: \u001b[1mauth, database, hosting, pubsub, storage\u001b[22m"}}
[info] ✔  functions: Using node@16 from host. {"metadata":{"emulator":{"name":"functions"},"message":"Using node@16 from host."}}
[warn] ⚠  Your requested "node" version "16" doesn't match your global version "16" {"metadata":{"emulator":{"name":"functions"},"message":"Your requested \"node\" version \"16\" doesn't match your global version \"16\""}}
[debug] [2022-07-07T07:17:29.404Z] defaultcredentials: writing to file /Users/danielo/.config/firebase/rdanielo_gmail_com_application_default_credentials.json
[debug] [2022-07-07T07:17:29.407Z] Setting GAC to /Users/danielo/.config/firebase/rdanielo_gmail_com_application_default_credentials.json {"metadata":{"emulator":{"name":"functions"},"message":"Setting GAC to /Users/danielo/.config/firebase/rdanielo_gmail_com_application_default_credentials.json"}}
[debug] [2022-07-07T07:17:29.409Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/axel-log/adminSdkConfig [none]
[debug] [2022-07-07T07:17:29.693Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/axel-log/adminSdkConfig 200
[debug] [2022-07-07T07:17:29.694Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/axel-log/adminSdkConfig {"projectId":"axel-log","storageBucket":"axel-log.appspot.com","locationId":"europe-west"}
[debug] [2022-07-07T07:17:29.730Z] Ignoring unsupported arg: projectId {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: projectId"}}
[debug] [2022-07-07T07:17:29.730Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2022-07-07T07:17:29.730Z] Starting Firestore Emulator with command {"binary":"java","args":["-Dgoogle.cloud_firestore.debug_log_level=FINE","-Duser.language=en","-jar","/Users/danielo/.cache/firebase/emulators/cloud-firestore-emulator-v1.13.1.jar","--host","localhost","--port",5002,"--rules","/Users/danielo/mega/programacion/spa/axel-log/firestore.rules","--functions_emulator","localhost:5001"],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator","seed_from_export"],"joinArgs":false} {"metadata":{"emulator":{"name":"firestore"},"message":"Starting Firestore Emulator with command {\"binary\":\"java\",\"args\":[\"-Dgoogle.cloud_firestore.debug_log_level=FINE\",\"-Duser.language=en\",\"-jar\",\"/Users/danielo/.cache/firebase/emulators/cloud-firestore-emulator-v1.13.1.jar\",\"--host\",\"localhost\",\"--port\",5002,\"--rules\",\"/Users/danielo/mega/programacion/spa/axel-log/firestore.rules\",\"--functions_emulator\",\"localhost:5001\"],\"optionalArgs\":[\"port\",\"webchannel_port\",\"host\",\"rules\",\"functions_emulator\",\"seed_from_export\"],\"joinArgs\":false}"}}
[info] i  firestore: Firestore Emulator logging to firestore-debug.log {"metadata":{"emulator":{"name":"firestore"},"message":"Firestore Emulator logging to \u001b[1mfirestore-debug.log\u001b[22m"}}
[debug] [2022-07-07T07:17:30.941Z] Jul 07, 2022 9:17:30 AM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketServer start
INFO: Started WebSocket server on ws://localhost:60616
 {"metadata":{"emulator":{"name":"firestore"},"message":"Jul 07, 2022 9:17:30 AM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketServer start\nINFO: Started WebSocket server on ws://localhost:60616\n"}}
[debug] [2022-07-07T07:17:30.966Z] API endpoint: http://localhost:5002 {"metadata":{"emulator":{"name":"firestore"},"message":"API endpoint: http://localhost:5002"}}
[debug] [2022-07-07T07:17:30.966Z] 
If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:

   export FIRESTORE_EMULATOR_HOST=localhost:5002

Dev App Server is now running.

 {"metadata":{"emulator":{"name":"firestore"},"message":"\nIf you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:\n\n   export FIRESTORE_EMULATOR_HOST=localhost:5002\n\nDev App Server is now running.\n\n"}}
[debug] [2022-07-07T07:17:31.013Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2022-07-07T07:17:31.013Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: port"}}
[debug] [2022-07-07T07:17:31.013Z] Starting Emulator UI with command {"binary":"node","args":["/Users/danielo/.cache/firebase/emulators/ui-v1.6.4/server.bundle.js"],"optionalArgs":[],"joinArgs":false} {"metadata":{"emulator":{"name":"ui"},"message":"Starting Emulator UI with command {\"binary\":\"node\",\"args\":[\"/Users/danielo/.cache/firebase/emulators/ui-v1.6.4/server.bundle.js\"],\"optionalArgs\":[],\"joinArgs\":false}"}}
[info] i  ui: Emulator UI logging to ui-debug.log {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI logging to \u001b[1mui-debug.log\u001b[22m"}}
[debug] [2022-07-07T07:17:31.112Z] Web / API server started at localhost:4000
 {"metadata":{"emulator":{"name":"ui"},"message":"Web / API server started at localhost:4000\n"}}
[info] i  functions: Watching "/Users/danielo/mega/programacion/spa/axel-log/functions" for Cloud Functions... {"metadata":{"emulator":{"name":"functions"},"message":"Watching \"/Users/danielo/mega/programacion/spa/axel-log/functions\" for Cloud Functions..."}}
[debug] [2022-07-07T07:17:31.288Z] [worker-pool] addWorker(~diagnostic~) {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] addWorker(~diagnostic~)"}}
[debug] [2022-07-07T07:17:31.289Z] [worker-pool] Adding worker with key ~diagnostic~, total=1 {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] Adding worker with key ~diagnostic~, total=1"}}
[debug] [2022-07-07T07:17:31.289Z] [worker-pool] submitWork(triggerId=) {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] submitWork(triggerId=)"}}
[debug] [2022-07-07T07:17:31.289Z] [worker-~diagnostic~-830d15a1-2b67-47cf-99da-69789e42c396]: Assigning socketPath: /var/folders/rz/6t__5md11ms0cfysw43yrybr0000gn/T/fire_emu_31436.sock {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~diagnostic~-830d15a1-2b67-47cf-99da-69789e42c396]: Assigning socketPath: /var/folders/rz/6t__5md11ms0cfysw43yrybr0000gn/T/fire_emu_31436.sock"}}
[debug] [2022-07-07T07:17:31.290Z] [worker-~diagnostic~-830d15a1-2b67-47cf-99da-69789e42c396]: BUSY {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~diagnostic~-830d15a1-2b67-47cf-99da-69789e42c396]: BUSY"}}
[debug] [2022-07-07T07:17:31.406Z] [runtime-status] [31436] Functions runtime initialized. {"cwd":"/Users/danielo/mega/programacion/spa/axel-log/functions","node_version":"16.13.0"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] Functions runtime initialized. {\"cwd\":\"/Users/danielo/mega/programacion/spa/axel-log/functions\",\"node_version\":\"16.13.0\"}"}}
[debug] [2022-07-07T07:17:31.407Z] [runtime-status] [31436] Disabled runtime features: undefined {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] Disabled runtime features: undefined"}}
[debug] [2022-07-07T07:17:31.414Z] [runtime-status] [31436] Resolved module firebase-admin {"declared":true,"installed":true,"version":"11.0.0","resolution":"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-admin/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] Resolved module firebase-admin {\"declared\":true,\"installed\":true,\"version\":\"11.0.0\",\"resolution\":\"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-admin/lib/index.js\"}"}}
[debug] [2022-07-07T07:17:31.415Z] [runtime-status] [31436] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.21.2","resolution":"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.21.2\",\"resolution\":\"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-functions/lib/index.js\"}"}}
[debug] [2022-07-07T07:17:31.417Z] [runtime-status] [31436] Outgoing network have been stubbed. [{"name":"http","status":"mocked"},{"name":"http","status":"mocked"},{"name":"https","status":"mocked"},{"name":"https","status":"mocked"},{"name":"net","status":"mocked"}] {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] Outgoing network have been stubbed. [{\"name\":\"http\",\"status\":\"mocked\"},{\"name\":\"http\",\"status\":\"mocked\"},{\"name\":\"https\",\"status\":\"mocked\"},{\"name\":\"https\",\"status\":\"mocked\"},{\"name\":\"net\",\"status\":\"mocked\"}]"}}
[debug] [2022-07-07T07:17:31.417Z] [runtime-status] [31436] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.21.2","resolution":"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.21.2\",\"resolution\":\"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-functions/lib/index.js\"}"}}
[debug] [2022-07-07T07:17:31.478Z] [runtime-status] [31436] Checked functions.config() {"config":{}} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] Checked functions.config() {\"config\":{}}"}}
[debug] [2022-07-07T07:17:31.478Z] [runtime-status] [31436] firebase-functions has been stubbed. {"functionsResolution":{"declared":true,"installed":true,"version":"3.21.2","resolution":"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-functions/lib/index.js"}} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] firebase-functions has been stubbed. {\"functionsResolution\":{\"declared\":true,\"installed\":true,\"version\":\"3.21.2\",\"resolution\":\"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-functions/lib/index.js\"}}"}}
[debug] [2022-07-07T07:17:31.479Z] [runtime-status] [31436] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.21.2","resolution":"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.21.2\",\"resolution\":\"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-functions/lib/index.js\"}"}}
[debug] [2022-07-07T07:17:31.480Z] [runtime-status] [31436] Resolved module firebase-admin {"declared":true,"installed":true,"version":"11.0.0","resolution":"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-admin/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] Resolved module firebase-admin {\"declared\":true,\"installed\":true,\"version\":\"11.0.0\",\"resolution\":\"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-admin/lib/index.js\"}"}}
[debug] [2022-07-07T07:17:31.481Z] [runtime-status] [31436] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.21.2","resolution":"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.21.2\",\"resolution\":\"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-functions/lib/index.js\"}"}}
[debug] [2022-07-07T07:17:31.481Z] [runtime-status] [31436] firebase-admin has been stubbed. {"adminResolution":{"declared":true,"installed":true,"version":"11.0.0","resolution":"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-admin/lib/index.js"}} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] firebase-admin has been stubbed. {\"adminResolution\":{\"declared\":true,\"installed\":true,\"version\":\"11.0.0\",\"resolution\":\"/Users/danielo/mega/programacion/spa/axel-log/functions/node_modules/firebase-admin/lib/index.js\"}}"}}
[debug] [2022-07-07T07:17:31.486Z] [runtime-status] [31436] initializeApp(DEFAULT) {"storageBucket":"axel-log.appspot.com","projectId":"axel-log"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [31436] initializeApp(DEFAULT) {\"storageBucket\":\"axel-log.appspot.com\",\"projectId\":\"axel-log\"}"}}
[info] ✔  functions[us-central1-dev-migrateDolenciasToLog]: http function initialized (http://localhost:5001/axel-log/us-central1/dev-migrateDolenciasToLog). {"metadata":{"emulator":{"name":"functions"},"message":"\u001b[1mhttp\u001b[22m function initialized (http://localhost:5001/axel-log/us-central1/dev-migrateDolenciasToLog)."}}
[debug] [2022-07-07T07:17:31.525Z] addAuthTrigger {"eventTrigger":{"resource":"projects/axel-log","eventType":"providers/firebase.auth/eventTypes/user.create","service":"firebaseauth.googleapis.com"}}
[info] ✔  functions[us-central1-prod-setAdminUsers]: auth function initialized. {"metadata":{"emulator":{"name":"functions"},"message":"\u001b[1mauth\u001b[22m function initialized."}}
[info] 
┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://localhost:4000                │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Functions │ localhost:5001 │ http://localhost:4000/functions │
├───────────┼────────────────┼─────────────────────────────────┤
│ Firestore │ localhost:5002 │ http://localhost:4000/firestore │
└───────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
 
[debug] [2022-07-07T07:17:31.528Z] [worker-~diagnostic~-830d15a1-2b67-47cf-99da-69789e42c396]: IDLE {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~diagnostic~-830d15a1-2b67-47cf-99da-69789e42c396]: IDLE"}}

```

debug log file after the export attempt:
Doesn't matter anymore because the command succeeded when I was reproducing the issue to report it. I think the key part is that, the second time I started the emulators with the `--export-on-exit=./seeds`, which created the export folder and files. If this is the root cause of the problem, then this is super confusing, because I don't see the need to run the emulators with this flag if you plan to export them latter manually.

**Comment by yuchenshi** [comment] 2022-07-11 20:40
@danielo515 I agree with you that `--export-on-exit` shouldn't be needed for manual exports. I think the issue is more related to the fact that the export command cannot discover the running emulator suite. In order to debug this, try these steps:

1. `firebase emulators:start --only firestore --debug`
2. In a separate terminal **in the same directory** run `firebase emulators:export ./another_path_that_is_not_seeds --debug`
3. Copy and paste the debug output from both commands.

Hope this gets us more insights on why those two commands don't talk to each other.

**Comment by danielo515** [comment] 2022-07-20 08:41
> 2\. firebase emulators:export ./another_path_that_is_not_seeds --debug

@yuchenshi thanks for your message. I tried what you explained and, sadly (but happily), again, it worked without problem. Here are the debug informations.

Export command:
```bash
➜  firebase emulators:export ./another_path_that_is_not_seeds --debug
[2022-07-20T08:29:18.646Z] >>> HTTP REQUEST GET http://localhost:4400/

[2022-07-20T08:29:18.673Z] <<< HTTP RESPONSE 200 {"x-powered-by":"Express","vary":"Origin","content-type":"application/json; charset=utf-8","content-length":"51","etag":"W/\"33-rUGqrbawghfiThzd8R4KhxmE2H4\"","date":"Wed, 20 Jul 2022 08:29:18 GMT","connection":"keep-alive","keep-alive":"timeout=5"}
i  Found running emulator hub for project axel-log at http://localhost:4400
i  Creating export directory /Users/danielo/mega/programacion/spa/axel-log/another_path_that_is_not_seeds
i  Exporting data to: /Users/danielo/mega/programacion/spa/axel-log/another_path_that_is_not_seeds
[2022-07-20T08:29:18.676Z] >>> HTTP REQUEST POST http://localhost:4400/_admin/export
 {"path":"/Users/danielo/mega/programacion/spa/axel-log/another_path_that_is_not_seeds"}
[2022-07-20T08:29:20.039Z] <<< HTTP RESPONSE 200 {"x-powered-by":"Express","vary":"Origin","content-type":"application/json; charset=utf-8","content-length":"16","etag":"W/\"10-MxB4y4MLcx6QDsp8b8vgp7iFMFo\"","date":"Wed, 20 Jul 2022 08:29:20 GMT","connection":"keep-alive","keep-alive":"timeout=5"}
✔  Export complete
```

Emulator

```
[2022-07-20T08:28:55.640Z] Web / API server started at localhost:4000
 {"metadata":{"emulator":{"name":"ui"},"message":"Web / API server started at localhost:4000\n"}}

┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://localhost:4000                │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Firestore │ localhost:5002 │ http://localhost:4000/firestore │
└───────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.

i  emulators: Received export request. Exporting data to /Users/danielo/mega/programacion/spa/axel-log/another_path_that_is_not_seeds.
[2022-07-20T08:29:18.697Z] >>> HTTP REQUEST POST http://localhost:5002/emulator/v1/projects/axel-log:export
 {"database":"projects/axel-log/databases/(default)","export_directory":"firebase-export-1658305758696Yn5H2e","export_name":"firestore_export"}
[2022-07-20T08:29:18.717Z] Jul 20, 2022 10:29:18 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Jul 20, 2022 10:29:18 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\nINFO: Detected non-HTTP/2 connection.\n"}}
[2022-07-20T08:29:19.012Z] Jul 20, 2022 10:29:19 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Jul 20, 2022 10:29:19 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\nINFO: Detected HTTP/2 connection.\n"}}
[2022-07-20T08:29:20.027Z] <<< HTTP RESPONSE 200 {"content-type":"application/json","content-length":"4"}
[2022-07-20T08:29:20.029Z] hubExport: swapping firebase-export-1658305758696Yn5H2e with /Users/danielo/mega/programacion/spa/axel-log/another_path_that_is_not_seeds
✔  emulators: Export complete.


```

**Comment by lisajian** [comment] 2022-07-25 20:35
Sounds like this issue is no longer applicable, going ahead and closing the issue but let us know if you need any more help! Thanks!

**Closed by lisajian** 2022-07-25 20:35 UTC
Labels: Needs: Attention, emulator-suite, bug

**Comment by jovanialferez** [comment] 2023-04-27 15:11
got this error... figured out it was because i run the export on a different terminal window which had a default **node version** (with nvm), that is different from where the emulator is currently running.

**Comment by mgorbet** [comment] 2025-04-23 19:55
We are seeing a reproducible version of this bug but it requires running the emulator for 10+ days.  In our experience it has do to with Apple OSX removing the 'hub-XXXX' file from the /var/folders/.../T/ directory, so that it is no longer visible to the export code (specifically, the getLocatorFilePath function, line 28 of hub.js).

It seems that reading this file is insufficient to prevent it from being cleaned by OSX (for us, it's every 10 days or so at 03:35am).  The DB continues to run, but subsequent attempts to export result in a crash of our code.  We wrapped the above function in a try/catch and it lets our code run, but no longer exports.

Hope this helps someone... maybe Firebase can do an update that at least traps this error condition, and at best implements code to rewrite or 'touch' the hub file often enough to keep it active for long stretches of emulator testing.
