### ISSUE TITLE
Cannot deploy Angular SSR application using firebase deploy

### ISSUE THREAD

**Issue by craeft-io** [firebase/firebase-tools#7054] opened 2024-04-26 17:10 UTC
### [REQUIRED] Environment info

13.7.5

**firebase-tools:**

macOS / Ubuntu in GitHub Actions

**Platform:**

### [REQUIRED] Test case

Deployment of Angular using Firebase Webframeworks fails due to runtimeClassName error

### [REQUIRED] Steps to reproduce

1. Create firebase project and upgrade it to blaze plan
2. Create a new Angular Project using ng new. Select Y on the question to enable SSR
3. Add Angularfire using ng add @angular/fire
4. Enable ng deploy for hosting 
5. Without changes deploy hosting using ng deploy

### [REQUIRED] Expected behavior

Deployment of hosting and SSR Function should work without problems.

### [REQUIRED] Actual behavior

Deployment fails with result:
`Error: Failed to replace Run service projects/123456789/locations/us-east1/services/ssrtestdeployxxxxxx`

Google Cloud logging tells the following error
`spec.template.spec.runtimeClassName: When annotation [run.googleapis.com/base-images] set, runtimeClassName must be set to run.googleapis.com/linux-base-image-update`

**Comment by serialito74** [comment] 2024-04-26 19:18
Same issue 
```
[2024-04-26T16:25:42.194Z] FirebaseError: HTTP Error: 400, spec.template.spec.runtimeClassName: When annotation [run.googleapis.com/base-images] set, runtimeClassName must be set to run.googleapis.com/linux-base-image-update
    at responseToError (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:49:12)
    at RetryOperation._fn (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:297:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by krismkt2013** [comment] 2024-04-27 09:31
Same issue 

`spec.template.spec.runtimeClassName: When annotation [run.googleapis.com/base-images] set, runtimeClassName must be set to run.googleapis.com/linux-base-image-update`

Fail to finalize version

**Comment by DuanTranHuy** [comment] 2024-04-27 11:01
Same issue with Nextjs .Failed to replace Run service projects

**Comment by Mikkel84** [comment] 2024-04-27 13:00
Have the same issue when deploying Cloud Functions 2nd generation.

**Comment by Lzak** [comment] 2024-04-27 16:48
Also running into this same issue.

`Error: Failed to replace Run service projects/XXXXXX/locations/us-east1/services/ssrXXXXXX`
```
{
    "firebase": "10.11.1",
    "firebase-admin": "^11.8.0",
    "firebase-tools": "^13.7.5",
}
```

**Comment by SocialAnxty** [comment] 2024-04-27 21:28
Same exact issue as users above. Deployment has been working fine for weeks, today randomly getting.

FirebaseError: HTTP Error: 400, spec.template.spec.runtimeClassName: When annotation [run.googleapis.com/base-images] set, runtimeClassName must be set to run.googleapis.com/linux-base-image-update

**Comment by BugMakerJarvis** [comment] 2024-04-28 05:38
Same issue, any solutions?

**Comment by trichomes** [comment] 2024-04-28 06:13
Same situation as @Lzak deploying React + Next project.

**Comment by nylser** [comment] 2024-04-28 07:42
> Have the same issue when deploying Cloud Functions 2nd generation.

I get this issue when trying to add a Cloud SQL connection to Cloud Runs - this was working last week, seems like there was a change that impacts Cloud Run (Annotation logic)? This also seems to affect firebase then

**Comment by leach-mrt** [comment] 2024-04-29 04:10
Same issue as @Lzak from 14 hours ago.

**Comment by m3tasploit** [comment] 2024-04-29 04:31
Same issue in sveltekit deployment as well

**Comment by leach-mrt** [comment] 2024-04-29 08:46
Oh, the replaceService function is calling PUT.

https://github.com/firebase/firebase-tools/blob/24accb1ad7773045808e78794f7c946cc60bb0bf/src/gcp/run.ts#L219C35-L219C38

**Comment by benediktarnold** [comment] 2024-04-29 09:57
> Not sure who to blame here, but I think two parties have bugs:
> 
> 1. The cloud run http api should return the attribute `runtimeClassName` in the service template spec. The attribute is visible in the YAML view in the cloud console, but it's not mentioned in the API docs https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.services#Service
> 2. firebase-tools shouldn't do a GET and a PUT. Instead it should use a PATCH request to to add the tag https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.services/patch

Oh. I got the documentation links wrong. firebase-tools is using v1 endpoints. Not sure if v1 even had a patch endpoint, but it also lacks documentation for get and put ;-) https://cloud.google.com/run/docs/reference/rest/v1/projects.locations.services
Anyway, the problem remains the same.

**Comment by phminella** [comment] 2024-04-29 11:13
Same error here... for those in need to deploy immediately, disabling pintags `firebase experiments:disable pintags` before deploying should make it go through.

**Comment by benediktarnold** [comment] 2024-04-29 11:19
Another workaround: 
Use `us-central1` or `europe-west1` as the region for `frameworksBackend`. I tested both and didn't have the problem. Initially I used europe-west3 and had the error. 

Explanation: The cloud run admin api behaves different depending on the region. Some regions return the annotation `run.googleapis.com/base-images` for the GET request and some don't. So far I tested:

* europe-west3 (error)
* europe-west1 (works)
* us-central1 (works)

**Comment by drgarbage** [comment] 2024-04-29 11:21
> Same error here... for those in need to deploy immediately, disabling pintags `firebase experiments:disable pintags` before deploying should make it go through.

This works for me, thank you.



> Another workaround: Use `us-central1` or `europe-west1` as the region for `frameworksBackend`. I tested both and didn't have the problem. Initially I used europe-west3 and had the error.
> 
> Explanation: The cloud run admin api behaves different depending on the region. Some regions return the annotation `run.googleapis.com/base-images` for the GET request and some don't. So far I tested:
> 
> * europe-west3 (error)
> * europe-west1 (works)
> * us-central1 (works)

report:
* asia-east1 (error)

**Comment by aalej** [comment] 2024-04-29 11:30
Hey folks, thanks for all the information you shared, and apologies for the delay. Thanks @benediktarnold and @phminella for sharing your workarounds. I was able to reproduce the issue when setting the region to `europe-west3`. Let me try to bring someone from our team to look into this and provide more context.

**Comment by service-paradis** [comment] 2024-04-29 11:48
> Another workaround: Use `us-central1` or `europe-west1` as the region for `frameworksBackend`. I tested both and didn't have the problem. Initially I used europe-west3 and had the error.
> 
> Explanation: The cloud run admin api behaves different depending on the region. Some regions return the annotation `run.googleapis.com/base-images` for the GET request and some don't. So far I tested:
> 
> * europe-west3 (error)
> * europe-west1 (works)
> * us-central1 (works)

Good catch! I have the error with `northamerica-northeast1` and `us-east1`.

**Comment by c00ley** [comment] 2024-04-29 19:51
Likewise seeing this issue with updating cloud run labels via gcloud..

**Comment by c00ley** [comment] 2024-04-29 19:52
> Have the same issue when deploying Cloud Functions 2nd generation.

Same boat as you w respect to CF gen2

**Comment by Camille-D** [comment] 2024-04-29 20:40
Hello,

I am encountering the same issue as others when trying to deploy my Cloud Function for an Angular SSR application in the europe-west3 region. Initially, I tried disabling firebase experiments:disable pintags, but this did not resolve the problem.

Since re-enabling pintags, I have been facing a new error: "Invalid Request. Violations: {runtime_update_policy=Base image update feature is not applicable to 2nd Gen functions.}"

Is this issue related to the use of pintags? Are there any ongoing updates regarding this bug?

Thank you for your assistance.

**Comment by Camille-D** [comment] 2024-04-30 09:30
Hello,

I wanted to provide an update on my previous issue regarding the deployment of my Angular SSR Cloud Function in the europe-west3 region. Today, I retried `firebase experiments:disable pintags`, and unlike yesterday, it worked successfully. I was able to deploy my function without encountering the error from before.

Thank you for the support, and I hope this information might be helpful to others experiencing similar issues.

**Comment by ChTiSh** [comment] 2024-04-30 16:15
Same problem here, us-west1 giving the same error. and ```firebase experiments:disable pintags``` worked, thank you! @phminella

**Comment by siraisisatoru** [comment] 2024-05-01 09:02
Folks, I just tried to deploy my Nextjs project to Firebase without using `firebase experiments:disable pintags` and it works now.

```sh
[2024-05-01T08:03:11.225Z] >>> [apiv2][query] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<My project>/versions/<My Version> updateMask=status%2Cconfig
[2024-05-01T08:03:11.225Z] >>> [apiv2][body] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<My project>/versions/<My Version>  {"status":"FINALIZED","config":{"rewrites":[{"glob":"**","run":{"serviceId":"<My project>","region":"asia-east1","tag":"fh-<My Version> "}}],"redirects":[],"headers":[{"glob":"/_not-found","headers":{"x-next-cache-tags":"_N_T_/layout,_N_T_/_not-found/layout,_N_T_/_not-found/page,_N_T_/_not-found"}}],"cleanUrls":true,"trailingSlashBehavior":"REMOVE"}}
[2024-05-01T08:03:12.867Z] <<< [apiv2][status] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<My project>/versions/<My Version>  200
[2024-05-01T08:03:12.867Z] <<< [apiv2][body] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<My project>/versions/<My Version>  {"name":"projects/<My Project ID>/sites/<My project>/versions/<My Version> ","status":"FINALIZED","config":{"headers":[{"headers":{"x-next-cache-tags":"_N_T_/layout,_N_T_/_not-found/layout,_N_T_/_not-found/page,_N_T_/_not-found"},"glob":"/_not-found"}],"rewrites":[{"glob":"**","run":{"serviceId":"<My project>","region":"asia-east1","tag":"fh-<My Version> "}}],"cleanUrls":true,"trailingSlashBehavior":"REMOVE"},"labels":{"deployment-tool":"cli-firebase","firebase-web-framework":"next_ssr"},"createTime":"2024-05-01T07:41:47.528736Z","createUser":{"email":"<My Email>"},"finalizeTime":"2024-05-01T08:03:13.222627Z","finalizeUser":{"email":"<My Email>"}}
[2024-05-01T08:03:12.868Z] [hosting] finalized version for <My project>:[object Object]
✔  hosting[<My project>]: version finalized 
i  hosting[<My project>]: releasing new version... 
[2024-05-01T08:03:12.869Z] >>> [apiv2][query] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<My project>/channels/live/releases versionName=projects%2F<My Project ID>%2Fsites%2F<My project>%2Fversions%2F<My Version> 
[2024-05-01T08:03:12.869Z] >>> [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<My project>/channels/live/releases {}
[2024-05-01T08:03:13.418Z] <<< [apiv2][status] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<My project>/channels/live/releases 200
[2024-05-01T08:03:13.418Z] <<< [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<My project>/channels/live/releases {"name":"projects/<My Project ID>/sites/<My project>/channels/live/releases/<My release>","version":{"name":"projects/<My Project ID>/sites/<My project>/versions/<My Version> ","status":"FINALIZED","config":{"headers":[{"headers":{"x-next-cache-tags":"_N_T_/layout,_N_T_/_not-found/layout,_N_T_/_not-found/page,_N_T_/_not-found"},"glob":"/_not-found"}],"rewrites":[{"glob":"**","run":{"serviceId":"<My project>","region":"asia-east1","tag":"fh-<My Version> "}}],"cleanUrls":true,"trailingSlashBehavior":"REMOVE"},"labels":{"firebase-web-framework":"next_ssr","deployment-tool":"cli-firebase"},"createTime":"2024-05-01T07:41:47.528736Z","createUser":{"email":"<My Email>","imageUrl":"<My img>"},"finalizeTime":"2024-05-01T08:03:13.222627Z","finalizeUser":{"email":"<My Email>","imageUrl":"<My img>"}},"type":"DEPLOY","releaseTime":"2024-05-01T08:03:13.222Z","releaseUser":{"email":"<My Email>","imageUrl":"<My img>"}}
[2024-05-01T08:03:13.419Z] [hosting] release: {"name":"projects/<My Project ID>/sites/<My project>/channels/live/releases/<My release>","version":{"name":"projects/<My Project ID>/sites/<My project>/versions/<My Version> ","status":"FINALIZED","config":{"headers":[{"headers":{"x-next-cache-tags":"_N_T_/layout,_N_T_/_not-found/layout,_N_T_/_not-found/page,_N_T_/_not-found"},"glob":"/_not-found"}],"rewrites":[{"glob":"**","run":{"serviceId":"<My project>","region":"asia-east1","tag":"fh-<My Version> "}}],"cleanUrls":true,"trailingSlashBehavior":"REMOVE"},"labels":{"firebase-web-framework":"next_ssr","deployment-tool":"cli-firebase"},"createTime":"2024-05-01T07:41:47.528736Z","createUser":{"email":"<My Email>","imageUrl":"<My img>"},"finalizeTime":"2024-05-01T08:03:13.222627Z","finalizeUser":{"email":"<My Email>","imageUrl":"<My img>"}},"type":"DEPLOY","releaseTime":"2024-05-01T08:03:13.222Z","releaseUser":{"email":"<My Email>","imageUrl":"<My img>"}}
✔  hosting[<My project>]: release complete 

✔  Deploy complete! 
```
Additional info
```sh
"region":"asia-east1"
npm -v: 10.5.0
npm list -g: firebase-tools@13.7.5
next: ^14.2.3
```

**Comment by mlawd** [comment] 2024-05-01 21:10
Any update on this? I'm deploying with the region set to `europe-west1` in the `frameworksBackend` config and getting the above issue. Disabling the pintags experiment works locally, but not sure I can do this in CI without reworking them to not use `w9jds/firebase-action`

**Comment by garrettlove8** [comment] 2024-05-02 11:43
Not sure if this was luck or if it's officially fixed, but I just had a successful deploy in `us-east1` using `w9jds/firebase-action@v13.6.1`

**Comment by chrisryanouellette** [comment] 2024-05-02 23:35
I use `FirebaseExtended/action-hosting-deploy@v0` and was able to deploy today without disabling pintags to us-east1.

**Comment by colerogers** [comment] 2024-05-03 16:20
Hey folks, apologies for the headache. It seems there was a backend issue on the Cloud Run API that caused issues deploying/re-deploying 2nd gen functions. This applies to the Web Frameworks code path since we use the Run API directly. The fix has been rolling out to different regions starting a few days ago, so most of you should be unblocked now (or very soon)

**Comment by c00ley** [comment] 2024-05-03 23:41
Thanks @colerogers I noticed cloud run --update labels was working and no longer asking about, presumably, something to do with cloud run's (knative/k8s'runtimeClass)

**Closed as completed** 2024-05-27 01:34 UTC
Labels: type: bug, integration: web frameworks, reproducible
