### ISSUE TITLE
Import authentication data to firebase authentication emulator

### ISSUE THREAD

**Issue by damithmalalanayake** [firebase/firebase-tools#2843] opened 2020-11-20 06:37 UTC
Is there any way to import firebase auth data to the auth emulator?

**Comment by samtstern** [comment] 2020-11-20 11:12
@damithmalalanayake this is a duplicate of https://github.com/firebase/firebase-tools/issues/2749 please follow along over there.

**Closed by samtstern** 2020-11-20 11:12 UTC
