### ISSUE TITLE
link is not working

### ISSUE THREAD

**Issue by SundasKhanT** [firebase/firebase-tools#5859] opened 2023-05-18 07:51 UTC
After successfully deploying my web app, clicking on the provided link opens the Firebase documentation instead of my web app.

**Comment by aalej** [comment] 2023-05-18 09:20
Hi @SundasKhanT, from what I understand you’re unable to access your web app after deployment. For us to be able to start our investigation, it would be more helpful if you specify the details using the provided template in a new ticket. This way, it would be more efficient in identifying the cause of the issue. That being said, I'll be closing this for now.

**Closed by aalej** 2023-05-18 09:20 UTC
Labels: type: bug
