### ISSUE TITLE
Unable to complete $ firebase emulators: start

### ISSUE THREAD

**Issue by Bikila1** [firebase/firebase-tools#5670] opened 2023-04-07 17:06 UTC
[ui-debug.log](https://github.com/firebase/firebase-tools/files/11180265/ui-debug.log)

$ firebase emulators: start
i  emulators: Starting emulators: functions, hosting
!  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, pubsub, storage
i  hosting[back-end-327a1]: Serving hosting files from: build
+  hosting[back-end-327a1]: Local server: http://127.0.0.1:5000
i  ui: Emulator UI logging to ui-debug.log
+  functions: Using node@18 from host.
!!  functions: Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: SyntaxError: Cannot use import statement outside a module

┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://127.0.0.1:4000/          
     │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI       
      │
├───────────┼────────────────┼─────────────────────────────────┤
│ Functions │ 127.0.0.1:5001 │ http://127.0.0.1:4000/functions │
├───────────┼────────────────┼─────────────────────────────────┤
│ Hosting   │ 127.0.0.1:5000 │ n/a                       
      │
└───────────┴────────────────┴─────────────────────────────────┘

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.

**Comment by aalej** [comment] 2023-04-10 12:26
Hi @Bikila1, based on the logs you provided, it looks like the emulators were able to start but the functions are not being loaded. For us to have a better understanding of what is causing this, could you provide detailed steps on how to reproduce the issue, such as how you set up functions. This is so that we can try to replicate it on our end.

Also, could you let us know what version of `firebase-tools` and which platform(e.g macOS, Windows, etc.) you’re using? Thanks!

**Comment by iSuslov** [comment] 2023-04-14 18:47
@Bikila1 it seems that you have your code for cloud functions:
- Emitted by typescript or purely written in javascript that is not using [commonjs](https://nodejs.org/docs/latest/api/modules.html#modules-commonjs-modules) module syntax.
- **Or**
- You intentionally want to use `es6` modules but don't have `"type": "module"` flag in your `package.json`

Fixing any of the above should do the trick. 

PS: if you using typescript + node v18, and want to use modern module system, this is the [closest](https://stackoverflow.com/a/72380008/2555999) combination of compile settings that will give you all the latest and greatest experience:

>tsconfig.json
```json
 {
  "compilerOptions": {
    "module": "ES2022",
    "lib": ["ES2022"],
    "moduleResolution": "node",
    "target": "ES2022",
    // ....
  }
  // ....
}
```
However be aware of the fact that `fetch` is still [not officially supported by](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60924) node v18.

**Comment by joehan** [comment] 2023-04-18 17:51
Hey @Bikila1, the answer provided by @iSuslov is correct here - this error `Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: SyntaxError: Cannot use import statement outside a module` confirms this. 

Closing as WAI.

**Closed by joehan** 2023-04-18 17:51 UTC
Labels: type: bug, Needs: Author Feedback, emulators: functions, emulators: hosting
