### ISSUE TITLE
Uploading a .png image with .putData() creates an octet-stream object instead of a png object in storage emulator

### ISSUE THREAD

**Issue by Wizzel1** [firebase/firebase-tools#4982] opened 2022-09-15 17:37 UTC
### [REQUIRED] Environment info

**firebase-tools:** 11.9.0

**Platform:** Windows 10

### [REQUIRED] Steps to reproduce

1. Create an app that has access to the emulator.
2. Convert a png image to bytes
3. Upload the data with `.putData(data, SettableMetadata(contentType: 'image/png'));`
4. Check the result in storage emulator

### [REQUIRED] Expected behavior
As in version 11.7.0, I expected to have a image/png object added to the storage emulator.

### [REQUIRED] Actual behavior
Instead it adds a application/octet-stream.

**Comment by tonyjhuang** [comment] 2022-09-20 18:02
what sdk are you using?

**Comment by Wizzel1** [comment] 2022-09-20 20:03
I use the flutter SDK https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage

**Comment by balazss** [comment] 2022-10-15 00:42
I have a similar issue with `11.8.1` when using `uploadBytesResumable` with Node client. Only happens with PNGs.

Error is:
`error FirebaseError: Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown)`

**Comment by sebschre** [comment] 2022-10-19 08:38
I also have a similar issue with any file that is larger than ~200kB:
`FirebaseError: Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown)`
The type is always `application/octet-stream` and the size is always `262.14 kB`

**Comment by LanderBeeuwsaert** [comment] 2022-11-02 10:45
We have the same issue when we do upload() via firebase admin to the storage emulator, since updating from 11.9.0 to 11.16.0

**Comment by rulamon** [comment] 2022-11-02 16:44
I've been having a similar issue as well in the emulator: when adding a file to the emulator through firebase admin's upload() the type is always application/octet-stream.

**Comment by Yuangwang** [comment] 2022-11-07 23:50
Hi, I think the discussion here has been for two separate issues.

1. Some of you are having issues with resumable uploads erroring out and also having the type `application/octet-stream` (@sebschre, @balazss, and maybe @Wizzel1). I think this was reported before (https://github.com/firebase/firebase-tools/issues/4959) and fixed in this pr (https://github.com/firebase/firebase-tools/pull/5018). Try updating to the latest  firebase-tools release and your issue should hopefully be fixed, if not please report back and we can take a closer look!
2. There is another issue that I was able to reproduce where some admin sdks are not setting the file type properly, its always being set to `application/octet-stream`. The fix for this is a WIP. 

@LanderBeeuwsaert and @rulamon I think you are running into this second issue. Which admin sdk are you using?

**Comment by LanderBeeuwsaert** [comment] 2022-11-07 23:53
Hi @Yuangwang, I'm running 11.2.0

**Comment by Yuangwang** [comment] 2022-11-07 23:57
@LanderBeeuwsaert Sorry I think I was a bit unclear, which one of these from https://firebase.google.com/docs/admin/setup#prerequisites are you using?<img width="732" alt="image" src="https://user-images.githubusercontent.com/11743511/200440490-dba11f41-aca3-441e-983b-8e2ec51a1c4b.png">

**Comment by LanderBeeuwsaert** [comment] 2022-11-07 23:59
@Yuangwang ah apologies, the Node.js SDK, package firebase-admin, 11.2.0

**Comment by Yuangwang** [comment] 2022-11-07 23:59
Thanks! this will help in debugging

**Comment by Yuangwang** [comment] 2022-11-10 21:17
Merged in fix for admin sdk issue https://github.com/firebase/firebase-tools/pull/5229 it should be out with the new release. I also followed the steps to reproduce the original bug and it seems to be fixed so I'm closing this for now.

**Closed by Yuangwang** 2022-11-10 21:17 UTC
Labels: priority: p1, emulators: storage, bug
