### ISSUE TITLE
Not able to deploy my project

### ISSUE THREAD

**Issue by abenandh** [firebase/firebase-tools#7111] opened 2024-05-05 19:18 UTC
<img width="910" alt="image" src="https://github.com/firebase/firebase-tools/assets/98703438/3d9d93ef-31d0-43c1-b068-8e94422840f8">
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/15214193/firebase-debug.log)

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment] 2024-05-06 11:03
Hey @abenandh, from what I can tell based on the title of the report, you’re having an issue with deploying to Firebase. We would need other information for us to be able to start our initial investigation. 

Please file a new issue and specify the details using the provided template. This way, it would be more efficient in identifying the cause of the issue. That said, I'll be closing this.

**Closed by aalej** 2024-05-06 11:03 UTC
Labels: type: bug
