### ISSUE TITLE
firebase functions:shell : Ignoring trigger --- service "pubsub.googleapis.com" is not yet supported

### ISSUE THREAD

**Issue by ljcremer** [firebase/firebase-tools#1296] opened 2019-05-15 09:55 UTC
### [REQUIRED] Environment info

firebase-tools:6.9.2

Platform:Windows

### [REQUIRED] Test case
firebase functions:shell

### [REQUIRED] Steps to reproduce
The functions are firebase functions in the following format:
exports.helloPubSub = functions.pubsub.topic('topic-name').onPublish((message) => {
  // ...
});

They are emulated using the following:
firebase functions:shell

### [REQUIRED] Expected behavior
I am expecting that all functions are being emulated

### [REQUIRED] Actual behavior
+  functions: Using node@8 from host.
+  functions: Emulator started at http://localhost:5001
i  functions: Watching "C:\Users\ljcremer\Google Drive\Development\TroopTravel\v2019.1\firebase-cloud-functions-nodejs\functions" for Cloud Functions...
!  Default "firebase-admin" instance created!
!  Ignoring trigger "crons-checkFligthQueue" because the service "pubsub.googleapis.com" is not yet supported.
!  Ignoring trigger "crons-skyscannerSearchRoute" because the service "pubsub.googleapis.com" is not yet supported.
!  Ignoring trigger "crons-getGeoTimezone" because the service "pubsub.googleapis.com" is not yet supported.
!  Ignoring trigger "poiCalcs-calc" because the Cloud Firestore emulator is not running.
!  Ignoring trigger "tt_functions-getCityCaps" because the Cloud Firestore emulator is not running.
i  functions: HTTP trigger initialized at http://localhost:5001/trooptravel-v1/us-central1/tt_create_trip-analyze_trip
i  functions: HTTP trigger initialized at http://localhost:5001/trooptravel-v1/us-central1/tt_create_trip-add_destinations
!  Ignoring trigger "notifySlack-onPubSub" because the service "pubsub.googleapis.com" is not yet supported.
!  Ignoring trigger "skyscanner_imports-loadGeo" because the service "pubsub.googleapis.com" is not yet supported.
!  Ignoring trigger "hotels_booking_dot_com-pubSubGetTripHotels" because the service "pubsub.googleapis.com" is not yet supported.
i  functions: HTTP trigger initialized at http://localhost:5001/trooptravel-v1/us-central1/hotels_booking_dot_com-httpGetTripHotels
i  functions: HTTP trigger initialized at http://localhost:5001/trooptravel-v1/us-central1/hotels_booking_dot_com-httpGetDestinationHotels
i  functions: HTTP trigger initialized at http://localhost:5001/trooptravel-v1/us-central1/hotels_booking_dot_com-httpGetHotelDetails
!  Ignoring trigger "flights_kiwi-pubSubGetTripFlights" because the service "pubsub.googleapis.com" is not yet supported.
i  functions: HTTP trigger initialized at http://localhost:5001/trooptravel-v1/us-central1/flights_kiwi-httpGetTripFlights
i  functions: HTTP trigger initialized at http://localhost:5001/trooptravel-v1/us-central1/flights_kiwi-httpGetDestinationFlights
i  functions: HTTP trigger initialized at http://localhost:5001/trooptravel-v1/us-central1/flights_kiwi-httpGetRouteFlights
!  Ignoring trigger "destination_functions-destinationCreated" because the Cloud Firestore emulator is not running.
!  Ignoring trigger "destination_functions-destinationChanged" because the Cloud Firestore emulator is not running.
!  Ignoring trigger "trip_functions-tripCreated" because the Cloud Firestore emulator is not running.
!  Ignoring trigger "destination_flight_functions-pubsubCalcTripFlightStats" because the service "pubsub.googleapis.com" is not yet supported.
!  Ignoring trigger "destination_flight_functions-pubSubcalcDestinationFlightStats" because the service "pubsub.googleapis.com" is not yet supported.
!  Ignoring trigger "destination_flight_functions-pubSubcalcDestinationArrWin" because the service "pubsub.googleapis.com" is not yet supported.
i  functions: HTTP trigger initialized at http://localhost:5001/trooptravel-v1/us-central1/destination_flight_functions-httpCalcTripFlightStats
i  functions: HTTP trigger initialized at http://localhost:5001/trooptravel-v1/us-central1/destination_hotel_functions-httpCalcTripHotels
i  functions: HTTP trigger initialized at http://localhost:5001/trooptravel-v1/us-central1/destination_hotel_functions-httpCalcDestinationHotels
!  Ignoring trigger "tt_office_functions-pubSubGetOfficeDetails" because the service "pubsub.googleapis.com" is not yet supported.
!  Ignoring trigger "tt_office_functions-pubSubGetAllOfficeDetails" because the service "pubsub.googleapis.com" is not yet supported.
!  Ignoring trigger "tt_office_functions-pubSubGetOfficeLayer" because the service "pubsub.googleapis.com" is not yet supported.
!  Ignoring trigger "security_travel_advisory-getSecurityTravelAdvisory" because the service "pubsub.googleapis.com" is not yet supported.

**Comment by samtstern** [comment] 2019-05-15 13:56
The shell is completely broken right now but we have a fix coming in #1260 (original issue is #1243).

For now please downgrade your CLI to version 6.8.0 and it will work.

**Comment by samtstern** [comment] 2019-05-15 13:57
Closing as a duplicate of #1243

**Closed by samtstern** 2019-05-15 13:57 UTC

**Comment by ljcremer** [comment] 2019-05-15 14:37
Thank Sam. I downgraded to 6.8.0 again but now I get the following error where it used to work previously. Any Ideas what might cause this:

Error: EPERM: operation not permitted, rename 'C:\Users\ljcremer\.config\configstore\firebase-tools.json.2572117863' -> 'C:\Users\ljcremer\.config\configstore\firebase-tools.json'
    at Object.fs.renameSync (fs.js:766:18)
    at Function.writeFileSync [as sync] (C:\Users\ljcremer\Google Drive\Development\TroopTravel\v2019.1\firebase-cloud-functions-nodejs\functions\node_modules\configstore\node_modules\write-file-atomic\index.js:124:8)
    at Configstore.set (C:\Users\ljcremer\Google Drive\Development\TroopTravel\v2019.1\firebase-cloud-functions-nodejs\functions\node_modules\configstore\index.js:62:21)
    at new Configstore (C:\Users\ljcremer\Google Drive\Development\TroopTravel\v2019.1\firebase-cloud-functions-nodejs\functions\node_modules\configstore\index.js:27:11)
    at Object.<anonymous> (C:\Users\ljcremer\Google Drive\Development\TroopTravel\v2019.1\firebase-cloud-functions-nodejs\functions\node_modules\firebase-tools\lib\configstore.js:4:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\ljcremer\Google Drive\Development\TroopTravel\v2019.1\firebase-cloud-functions-nodejs\functions\node_modules\firebase-tools\lib\previews.js:3:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\ljcremer\Google Drive\Development\TroopTravel\v2019.1\firebase-cloud-functions-nodejs\functions\node_modules\firebase-tools\lib\commands\index.js:2:16)
    at Module._compile (module.js:653:30)]
!  functions: Error from emulator. [object Object]
No functions emulated.

**Comment by jimmykane** [comment] 2019-05-21 13:29
Hi this is not related to the referenced issue I am getting with 6.10.0 : 

```
(node:23119) ExperimentalWarning: The fs.promises API is experimental
✔  functions: Using node@10 from host.
✔  functions: Emulator started at http://localhost:5000
i  functions: Watching "/Users/dimtrioskanellopoulos/Projects/track-tools/functions" for Cloud Functions...
i  Your code has been provided a "firebase-admin" instance.
i  functions: HTTP trigger initialized at http://localhost:5000/quantified-self-io/europe-west2/stWorkoutDownloadAsFit
i  functions: HTTP trigger initialized at http://localhost:5000/quantified-self-io/us-central1/authRedirect
i  functions: HTTP trigger initialized at http://localhost:5000/quantified-self-io/us-central1/authToken
Ignoring trigger "scheduledFunction" because the service "pubsub.googleapis.com" is not yet supported.

```
why Ignoring trigger ?

**Comment by samtstern** [comment] 2019-05-21 18:42
@jimmykane I assume that output is from `firebase emulators:start`?  That's working as intended right now.  There is no way for us to "emulate" a PubSub function in a way that would be useful, since it will never be triggered by any other emulator.

Right now we support:
  * Firestore functions
  * HTTP functions (including callable)

In the future we definitely want to add support for pubsub though!

**Comment by jimmykane** [comment] 2019-05-22 10:02
@samtstern Oh ok. I thought that due to the title of this ticket that was the issue. Sorry then it looks ok I can trigger that via the shell

**Comment by nafonso** [comment] 2019-07-04 09:47
> @jimmykane I assume that output is from `firebase emulators:start`? That's working as intended right now. There is no way for us to "emulate" a PubSub function in a way that would be useful, since it will never be triggered by any other emulator.
> 
> Right now we support:
> 
> * Firestore functions
> * HTTP functions (including callable)
> 
> In the future we definitely want to add support for pubsub though!

So I guess this is the same issue with using auth binds? ATM I was trying to setup a trigger on user created but I get the same message but with "firebaseauth.googleapis.com". Is this also planned soon? Is there another way to test locally functions that require auth services?

Also, what's the difference between firebase serve and emulators? Because with serve the exact same error happens.

**Comment by samtstern** [comment] 2019-07-08 19:22
> Is this also planned soon? Is there another way to test locally functions that require auth services?

In the future we would like to add more emulators, such as auth and PubSub, which would allow us to emulate those triggers.  But this is a lot of work, so I would not say it's coming soon.

> Is there another way to test locally functions that require auth services?

`functions:shell` works for any trigger type but you have to manually invoke it with data.  You can also use the `firebase-functions-test` library to write unit tests.

> Also, what's the difference between firebase serve and emulators? Because with serve the exact same error happens.

The biggest difference is how the functions emulator behaves.  We will clarify this in the future and deduplicate some of the functionality.
