### ISSUE TITLE
RTDB emulator "indexOn" rule always produces an exception.

### ISSUE THREAD

**Issue by russellwheatley** [firebase/firebase-tools#4368] opened 2022-03-29 14:20 UTC
### [REQUIRED] Environment info

**firebase-tools:** 10.5.0

**environment:** macOS 11.6 Big Sur

### [REQUIRED] Test case

RTDB rules required:
```json
{
  "rules": {
    ".read": false,
    ".write": false,
    "tests": {
      ".read": true,
      ".write": true,
      ".indexOn": ["search"]
}
```
Reproducible sample code:
```dart
import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;
import 'package:flutter/material.dart';

// The port we've set the Firebase Database emulator to run on via the
// `firebase.json` configuration file.
const emulatorPort = 9000;
// Android device emulators consider localhost of the host machine as 10.0.2.2
// so let's use that if running on Android.
final emulatorHost =
    (!kIsWeb && defaultTargetPlatform == TargetPlatform.android)
        ? '10.0.2.2'
        : 'localhost';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: FirebaseOptions( <INSERT YOUR OWN DB OPTIONS>),
  );
  
  FirebaseDatabase.instance.useDatabaseEmulator(emulatorHost, emulatorPort);

  runApp(
     MaterialApp(
      title: 'Flutter Database Example',
      home: MyHomePage(),
    ),
  );
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('RTDB reproducible sample'),
      ),
      body: Column(
        children: [
          ElevatedButton(
            onPressed: () async {
              DatabaseReference _testsRef = FirebaseDatabase.instance.ref('tests');
              await _testsRef.set({
                'first':{'search':2},
                'second':{'search':3},
                'third':{'search':4},
              });
             DataSnapshot response = await _testsRef.orderByChild('search').startAfter(1).get();
            },
            child: const Text('Press to see error'),
          ),
        ],
      ),
    );
  }
}
```

1. Run `firebase emulators:start --only database` with the rules noted above.
2. Insert your Firebase database options as noted above.
3. Create a Flutter project (`flutter create testProject`) and copy/paste the above code in "main.dart".
4. Run your flutter project on whatever platform you wish (i.e. android, ios, etc).
5. Press the button that appears in the UI, and view the following exception appear in your console:

```bash
Index not defined, add ".indexOn": "search", for path "/tests", to the rules
```

If you remove the call to the database emulator, `useDatabaseEmulator()`, you will note that this exception does not occur when querying the live database.

### [REQUIRED] Steps to reproduce
See above.

### [REQUIRED] Expected behavior

I expect the "indexOn" rule to work for the RTDB emulator like it does for the live database.

### [REQUIRED] Actual behavior

The following exception appears when trying to use `orderByChild`:
```bash
Index not defined, add ".indexOn": "search", for path "/tests", to the rules
```

**Comment by IanWyszynski** [comment] 2022-04-04 22:38
Does the same exception get thrown when `once` is used instead of get here?
```
await _testsRef.orderByChild('search').startAfter(1).get();
```

**Comment by IanWyszynski** [comment] 2022-04-07 19:22
Are the rules definitely being set? 

Could you try fetching them from the emulator to make sure? Something like:
```
curl http://localhost:9000/.settings/rules.json?access_token=1234
```

I was not able to reproduce this issue using the REST API w/ a local emulator:

```
$ curl http://localhost:9000/.settings/rules.json?access_token=1234 -X PUT -d '{ "rules": { ".read": false, ".write": false, "tests": { ".read": true, ".write": true, ".indexOn": ["search"] } } }'
{"status":"ok"}

$ curl -X PUT -d '{"tests": {"first": {"search": 2}, "second": {"search": 3}, "third": {"search": 4}}}' http://localhost:9000/tests.json?access_token=1234
{"tests":{"first":{"search":2},"second":{"search":3},"third":{"search":4}}}

$ curl http://localhost:9000/tests.json?orderBy="\"search\""\&limit=1
{"tests":{"first":{"search":2},"second":{"search":3},"third":{"search":4}}}
```

Now getting rid of the index:
```
$ curl http://localhost:9000/.settings/rules.json?access_token=1234 -X PUT -d '{ "rules": { ".read": false, ".write": false, "tests": { ".read": true, ".write": true } } }'
{"status":"ok"}

$ curl http://localhost:9000/tests.json?orderBy="\"search\""\&limit=1
{
  "error" : "Index not defined, add \".indexOn\": \"search\", for path \"/tests\", to the rules"
}
```

**Comment by russellwheatley** [comment] 2022-04-26 11:58
@IanWyszynski, I apologise for the late response. I think you're right. I have these rules set:

```json
{
  "rules": {
    ".read": false,
    ".write": false,
    "tests": {
      ".read": true,
      ".write": true,
      ".indexOn": [
        "search"
      ]
    }
  }
}
```

But once I call `curl http://localhost:9000/.settings/rules.json\?access_token\=1234 `, I get these rules back:
```json
{
    "rules": {
        ".read": true,
        ".write": true
    }
}
``` 

I'm calling ` firebase emulators:start --only database` from [here](https://github.com/firebase/flutterfire/blob/master/.github/workflows/scripts) which has the RTDB rules referenced [here](https://github.com/firebase/flutterfire/blob/master/.github/workflows/scripts/firebase.json#L6). The RTDB rules file is [here](https://github.com/firebase/flutterfire/blob/master/.github/workflows/scripts/database.rules.json).

Any reason why it isn't being picked up?

**Comment by russellwheatley** [comment] 2022-04-26 14:03
I've just realised that you're setting your rules using a curl PUT request which is why there might be a discrepancy? I'm using the `database-rules.json` file which might be why you were unable to reproduce 🤔

**Comment by mikehardy** [comment] 2022-04-27 12:21
:wave: I work with @russellwheatley (they are doing mostly Flutter bindings for Firebase, I'm doing mostly react-native bindings for Firebase) and I have seen the same thing. It appears the rules.json is not picked up and I have to manually set them, I put a workaround in like so

https://github.com/invertase/react-native-firebase/blob/0fd4b4fc65467c4342442b22afb20a7f8cff0ada/packages/database/e2e/helpers.js#L41-L45

```javascript
    // The database emulator does not load rules correctly. We force them pre-test.
    testingUtils.initializeTestEnvironment({
      projectId: 'react-native-firebase-testing',
      database: { databaseName: DB_NAME, rules: DB_RULES, host: 'localhost', port: 9000 },
    }),
```

...via the `@firebase/rules-unit-testing` package

**Comment by jhuleatt** [comment] 2022-05-13 17:51
I'm experiencing the same issue in CLI version `10.9.2`.

**Comment by bkendall** [comment] 2022-05-16 20:16
@jhuleatt could you sync with @IanWyszynski about this?

**Comment by jhuleatt** [comment] 2022-05-19 15:35
I wasn't able to reproduce the issue again with CLI version `9.23.3`, `10.9.2`, or `11.0.0` (even in a project where it was happening before).

@IanWyszynski stepped through the rules update code with me and said everything looks ok. When the emulator suite finds a rules file, the rules are actually updated via a PUT request:

https://github.com/firebase/firebase-tools/blob/4bba5e9ea06df700059ccf2aa9c40eb1ce732b0a/src/emulator/databaseEmulator.ts#L173

Not really sure what's going on here 🤔 Only guess is it could be something with the wrong emulated namespace being read/written to?

**Comment by IanWyszynski** [comment] 2022-05-19 16:03
> But once I call `curl http://localhost:9000/.settings/rules.json\?access_token\=1234 `, I get these rules back:
> 
> ```json
> {
>     "rules": {
>         ".read": true,
>         ".write": true
>     }
> }
> ```
>...
> Any reason why it isn't being picked up?

By default, `firebase emulator:start --only database` uses the default project RTDB instance: `flutterfire-e2e-tests-default-rtdb`, so in order to query the rules being used, you need:
```
curl http://localhost:9000/.settings/rules.json?access_token=1234\&ns=flutterfire-e2e-tests-default-rtdb
```

When I do this, I see:
```
{
  "rules": {
    ".read": false,
    ".write": false,
    "denied_read": {
      ".read": false,
      ".write": false
    },
    "messages": {
      ".read": true,
      ".write": true
    },
    "counter": {
      ".read": true,
      ".write": true
    },
    "tests": {
      ".read": true,
      ".write": true,
      ".indexOn": [
        ".value",
        "number"
      ],
      "ordered": {
        ".read": true,
        ".write": true,
        ".indexOn": [
          "value"
        ]
      }
    }
  }
}
```
To reiterate, if you call `get()` on a query (meaning any combination of `start/endAt`, `limit*`, `orderBy*`), that location _must_ be indexed. If no query is specified, a key index is used.

**Comment by Erfa** [comment] 2023-04-14 22:25
I had this problem when trying to unit test my cloud functions that use `firebase-admin`. I want to run it against the RTDB emulator. It seems like the rules are only added to a project called `<firebase project name>-default-rtdb`, but in the unit tests it was using a different project called `not-a-project`. That's fine by me, but I need the rules there as well.

So I had a look at what `@firebase/rules-unit-testing` does to apply the rules and turns out it's just a simple PUT request. I stole that, and this workaround works for me:

```typescript
import { promises as fs } from "fs"

beforeAll(async () => {
  const rules = await fs.readFile("../database.rules.json", "utf-8")
  await fetch("http://localhost:9000/.settings/rules.json?ns=not-a-project", {
    method: "PUT",
    headers: {Authorization: "Bearer owner"},
    body: rules,
  })
})
```

**Comment by joehan** [comment] 2023-04-18 17:49
Glad that you found a workaround. Going to close this issue for now since its pretty out of date - if you are facing similar issues, please open a new issue.

**Closed by joehan** 2023-04-18 17:49 UTC
Labels: type: bug, emulators: database
