### ISSUE TITLE
Cannot use firebase-admin 12 since npm package for firebase-frameworks version 0.11.2 not available on npm

### ISSUE THREAD

**Issue by jntakpe** [firebase/firebase-tools#6692] opened 2024-01-16 12:11 UTC
I cannot build an application with firebase-admin 12.
The version [0.11.2](https://github.com/FirebaseExtended/firebase-framework-tools/releases/tag/firebase-frameworks-v0.11.2) of `firebase-tools` fixes that issue but it is not available on [npm](https://www.npmjs.com/package/firebase-frameworks?activeTab=versions) .

### [REQUIRED] Environment info

**firebase-tools:** 13.0.3

**Platform:** OSX Sonoma

### [REQUIRED] Test case

Successfully exec : `npx firebase-tools@latest deploy --only hosting --project myproject --json`

### [REQUIRED] Steps to reproduce

Add the following dependency to your build: ` "firebase-admin": "^12.0.0"`

### [REQUIRED] Expected behavior

The application builds

### [REQUIRED] Actual behavior

The application fails to build due to the following error : 

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: ras-website@0.1.0
> npm ERR! Found: firebase-admin@12.0.0
> npm ERR! node_modules/firebase-admin
> npm ERR!   firebase-admin@"^12.0.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer firebase-admin@"^11.0.1" from firebase-frameworks@0.11.1
> npm ERR! node_modules/firebase-frameworks
> npm ERR!   firebase-frameworks@"^0.11.0" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! 
> npm ERR! For a full report see:
> npm ERR! /Users/jocelyn.ntakpe/.npm/_logs/2024-01-16T11_56_07_557Z-eresolve-report.txt

**Comment by jntakpe** [comment] 2024-01-16 12:13
Could be a duplicate of #6688

**Comment by aalej** [comment] 2024-01-16 12:18
Hey @jntakpe, thanks for raising this. Looking at the report, I think this might be a duplicate of #6688. I have reached out to our team about the issue. For now, I’m going to go ahead and mark this as a duplicate.

**Closed by aalej** 2024-01-16 12:18 UTC
Labels: type: bug, integration: web frameworks
