### ISSUE TITLE
specifying build arguments while running 'firebase deploy' or' flutter deploy --only hosting'

### ISSUE THREAD

**Issue by rehan-505** [firebase/firebase-tools#5941] opened 2023-06-07 03:15 UTC
0

I am using firebase hosting to host my flutter web app. Everytime I run firebase deploy or firebase deploy --only hosting, it builds the web app using 'flutter build web'. How to give arguments to flutter build web here.

While deploying, I want to build my app with these arguments : flutter build web --web-renderer html --release to solve network image error.

OR

Is there any way I can tell firebase deploy to stop running flutter build web and just use existing build which I created using the arguments of my choice.

**Comment by aalej** [comment] 2023-06-07 12:09
Hi @rehan-505, thanks for reaching out. It looks like the issue you filed is similar to #5937. I see that you've already seen the issue, feel free to add more information/inquiries on that thread. That said, I'll go ahead and close this as a duplicate.

For your second question. From what I can tell, you want to instead use the existing web build from running `flutter run -d chrome --web-renderer html`. You can try to change `"source": "."` to `"public": "build/web"` in your `firebase.json` file. Running `firebase deploy` should deploy the existing build. 

```json
{
  "hosting": {
    "public": "build/web",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
  }
}
```

Do note that changing `"source": "."` to `"public": "build/web"`, you opt out of the new behavior of automatic build when running `firebase deploy`.

**Closed by aalej** 2023-06-07 12:09 UTC
Labels: type: feature request, integration: web frameworks

**Comment by jung-hunsoo** [comment] 2024-05-20 05:28
@dylkane The problem is when running `firebase deploy`, it wipes all the arguments out and perform `flutter build` before the deployment. :-)

**Comment by Chezlui** [comment] 2024-06-18 17:24
@aalej I have that configuration and still overrides my --profile built version

**Comment by BhadrakshB** [comment] 2024-07-22 17:52
I have found a way around.  You need to take a look at the index.html file in these folders

 - build/web/index.html
 - .firebase/<project-id>/hosting/index.html
 - web/index.html

In each of these files add the following script tag:

`<script type="text/javascript">
    window.flutterWebRenderer = "html";
  </script>`

Then run these two commands:

`1) flutter build web --web-renderer html --release
2) firebase deploy --only hosting`

I think this will fix the image issue that you might have
