### ISSUE TITLE
Firebase Deploy Fails TOS acceptance

### ISSUE THREAD

**Issue by tomas-carv-com** [firebase/firebase-tools#5855] opened 2023-05-17 10:57 UTC
I can run cmd to deploy project locally, but it fails in CI with:

```
extensions: By installing an extension instance onto a Firebase project, you accept the Firebase Extensions User Terms of Service: https://firebase.google.com/terms/extensions/user

Error: HTTP Error: 403, Firebase Extensions Terms of Service Private API has not been used in project XYZ before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseextensionstos-pa.googleapis.com/overview?project=XYZ then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
yes: standard output: Broken pipe
```

First of all, that link does not work / exist.

Second, TOS has been accepted, I run that cmd locally and accepted TOS (even though this should not be the required thing if you run CI)

Also there should be a way to do that manually if is such big of a deal.

**Comment by nikita-mishchenko** [comment] 2023-05-25 11:42
Are there any updates on this? This is a blocker for updating firebase-tools to version 12+.
Problem was introduced in version 12.0.0 and still there.

**Comment by joehan** [comment] 2023-05-30 21:52
Hey @tomas-carv-com and @nikita-mishchenko , this is an odd one. This call (should be) made against the Firebase CLI consumer project, not your project. I just confirmed that it is enabled on that project, so I suspect that something strange is happening with the headers that is making this hit your project instead. 

Could you check if the project number in the error message matches the project number of the project you are trying to deploy on? Additionally,`--debug` logs would be very helpful for figuring out whats happening here.

**Comment by takahashi-shotaro** [comment] 2023-06-09 10:12
XXX is project name
YYY is project id

```
...
The following extension instances will be configured:
	************************

[2023-06-09T10:04:03.144Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-06-09T10:04:03.144Z] [iam] checking project XXX for permissions ["firebase.projects.get","firebaseextensions.instances.update"]
[2023-06-09T10:04:03.144Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/XXX:testIamPermissions [none]
[2023-06-09T10:04:03.144Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/XXX:testIamPermissions x-goog-quota-user=projects/XXX
[2023-06-09T10:04:03.144Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/XXX:testIamPermissions {"permissions":["firebase.projects.get","firebaseextensions.instances.update"]}
[2023-06-09T10:04:03.208Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/XXX:testIamPermissions 200
[2023-06-09T10:04:03.208Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/XXX:testIamPermissions {"permissions":["firebase.projects.get","firebaseextensions.instances.update"]}
[2023-06-09T10:04:03.209Z] Checking if latest AppDeveloper TOS has been accepted by XXX...
i  extensions: By installing an extension instance onto a Firebase project, you accept the Firebase Extensions User Terms of Service: https://firebase.google.com/terms/extensions/user 
[2023-06-09T10:04:03.209Z] >>> [apiv2][query] GET https://firebaseextensionstos-pa.googleapis.com/v1/projects/XXX/appdevtos [none]
[2023-06-09T10:04:03.408Z] <<< [apiv2][status] GET https://firebaseextensionstos-pa.googleapis.com/v1/projects/XXX/appdevtos 403
[2023-06-09T10:04:03.408Z] <<< [apiv2][body] GET https://firebaseextensionstos-pa.googleapis.com/v1/projects/XXX/appdevtos {"error":{"code":403,"message":"Firebase Extensions Terms of Service Private API has not been used in project YYY before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseextensionstos-pa.googleapis.com/overview?project=YYY then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Google developers console API activation","url":"https://console.developers.google.com/apis/api/firebaseextensionstos-pa.googleapis.com/overview?project=YYY"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"SERVICE_DISABLED","domain":"googleapis.com","metadata":{"service":"firebaseextensionstos-pa.googleapis.com","consumer":"projects/YYY"}}]}}

Error: HTTP Error: 403, Firebase Extensions Terms of Service Private API has not been used in project YYY before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseextensionstos-pa.googleapis.com/overview?project=YYY then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
[2023-06-09T10:04:03.410Z] Error Context: {
  "body": {
    "error": {
      "code": 403,
      "message": "Firebase Extensions Terms of Service Private API has not been used in project YYY before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseextensionstos-pa.googleapis.com/overview?project=YYY then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
      "status": "PERMISSION_DENIED",
      "details": [
        {
          "@type": "type.googleapis.com/google.rpc.Help",
          "links": [
            {
              "description": "Google developers console API activation",
              "url": "https://console.developers.google.com/apis/api/firebaseextensionstos-pa.googleapis.com/overview?project=YYY"
            }
          ]
        },
        {
          "@type": "type.googleapis.com/google.rpc.ErrorInfo",
          "reason": "SERVICE_DISABLED",
          "domain": "googleapis.com",
          "metadata": {
            "service": "firebaseextensionstos-pa.googleapis.com",
            "consumer": "projects/YYY"
          }
        }
      ]
    }
  },
  "response": {
    "statusCode": 403
  }
}
error Command failed with exit code 1.
```

**Comment by itsmasabdi** [comment] 2023-06-25 09:17
Having the same issue. Any updates on this?

Interesting that I can deploy on my local machine but not on github actions. I suspect that versions might be different and hence I can get it to work on my local.

I'm using  FIREBASE_VERSION=12.4.0

**Comment by CalHoll** [comment] 2023-07-07 03:57
Hit this issue with GH Actions - url broken? Haven't tried v11 revert, is this confirmed to work?

**Comment by joehan** [comment] 2023-07-11 17:45
Duplicate of #6060 - will prioritize a fix for this.

**Closed by joehan** 2023-07-11 17:45 UTC
Labels: type: bug, api: extensions
