### ISSUE TITLE
Update "marked-terminal" to get rid of "incorrect peer dependency" warning

### ISSUE THREAD

**Issue by hakimio** [firebase/firebase-tools#4104] opened 2022-01-27 11:56 UTC
### [REQUIRED] Environment info

**firebase-tools:** 10.1.2

**Platform:** Windows

### [REQUIRED] Test case

Try to install firebase-tools with yarn package manager

### [REQUIRED] Steps to reproduce

Try to install firebase-tools with yarn package manager

### [REQUIRED] Expected behavior

No errors or warnings.

### [REQUIRED] Actual behavior

Yarn produces following warning:
```
warning "firebase-tools > marked-terminal@3.3.0" has incorrect peer dependency "marked@^0.4.0 || ^0.5.0 || ^0.6.0 || ^0.7.0".
```

**Comment by hakimio** [comment] 2022-01-27 12:03
Other warnings coming from firebase-tools:
```
warning firebase-tools > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning firebase-tools > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning firebase-tools > universal-analytics > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning firebase-tools > universal-analytics > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning firebase-tools > request > har-validator@5.1.5: this library is no longer supported
```

**Comment by bkendall** [comment] 2022-01-27 16:46
Duplicate of #4099

**Closed by bkendall** 2022-01-27 16:46 UTC
