### ISSUE TITLE
Functions config clone does not overwrite existing variables

### ISSUE THREAD

**Issue by ahaverty** [firebase/firebase-tools#867] opened 2018-08-14 17:23 UTC
### Version info
"firebase-tools": "4.1.0"

### Platform Information
MacOs

### Steps to reproduce

1. Set multiple firebase functions config variables on one project
```bash
firebase use project-a
firebase functions:config:set test1.a="test1"
firebase functions:config:set test2.a="test2"
```
2. Set different config variables on another project
```bash
firebase use project-b
firebase functions:config:set test3.a="test3"
firebase functions:config:set test4.a="test4"
```
3. Clone one config to the other project
```bash
firebase use project-b
firebase functions:config:clone --from project-a
firebase functions:config:get
```

### Expected behavior
An exact copy of the source project is overwritten on the other project
e.g:
```json
{
    
    "test1": {
        "a": "test1"
    },
    "test2": {
        "a": "test2"
    }
}
```

### Actual behavior
The config is copied to the other project, but it's existing variables are not unset
e.g:
```json
{
    "test1": {
        "a": "test1"
    },
    "test2": {
        "a": "test2"
    },
    "test3": {
        "a": "test3"
    },
    "test4": {
        "a": "test4"
    }
}
```

**Comment by joehan** [comment] 2019-01-14 21:06
Hey @ahaverty, thanks for reporting this! This is actually the intended behavior of clone - it can also be used to copy parts of one config to another via the --only and --except flags, so we don't want it to delete all existing variables. However, the docs for this (https://firebase.google.com/docs/functions/config-env) aren't very clear about how clone functions here - I'm going to close this and file an internal bug to improve the docs.

**Closed by joehan** 2019-01-14 21:06 UTC
Labels: bug, functions

**Comment by LeonardoRick** [comment] 2021-02-25 21:40
never head about `--only`and `--except`. That should definetly be on docs. Thanks a lot!
