### ISSUE TITLE
Error: Error finding next executable: failed to spawn 'npm'

### ISSUE THREAD

**Issue by digpolo** [firebase/firebase-tools#6398] opened 2023-09-23 23:51 UTC
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by Vigneshkna** [comment] 2023-09-24 20:15
Try killing the development serve [http://localhost:3000](http://localhost:3000)  and then run `npm install or npm i`, it works for me

**Comment by simonhrmo** [comment] 2023-09-24 20:27
Same issue here, tried with versions: 

node 20.6.0
npm 9.8.1 
firebase ^10.4.0
firebase-admin ^11.10.1
firebase-functions 4.4.1 

could it be connected to issue https://github.com/firebase/firebase-tools/issues/6173#issuecomment-1723763941?

**Comment by Vigneshkna** [comment] 2023-09-25 07:57
@simonhrmo try updating next version to v13.5.X

**Comment by aalej** [comment] 2023-09-25 15:45
Hey everyone, looking at the error message provided, it seems like this issue is a duplicate of #6173. This should be fixed in #6372 which will be available in the next release. 

I am closing this issue as a duplicate. If anyone thinks I have made a mistake, let me know and I will reopen the issue. Apologies for the inconvenience this has caused.

**Closed by aalej** 2023-09-25 15:45 UTC
Labels: type: bug, integration: web frameworks
