### ISSUE TITLE
Deploying functions fails on ENV config variables with TypeError: Cannot read property '<propertyName>' of undefined

### ISSUE THREAD

**Issue by joemsak** [firebase/firebase-tools#785] opened 2018-05-29 14:47 UTC
Coming here due to https://github.com/firebase/firebase-tools/issues/678#issuecomment-369787461 and could not find an existing issue

### Version info
3.18.5

### Platform Information
Mac OS X High Sierra
Version 10.13.4 (17E202)

### Steps to reproduce

firebase functions:config:set firebase_db.api_key=abc123
< edit function to use `functions.config().firebase_db.api_key` >
firebase deploy

config set/get debug logs:
[set-var.log](https://github.com/firebase/firebase-tools/files/2048678/set-var.log)
[get-var.log](https://github.com/firebase/firebase-tools/files/2048677/get-var.log)

### Expected behavior

App deploys, functions deploy, function reads env vars

### Actual behavior

Deploy fails due to this particular var not being found (I have set one other config var and it is referenced earlier in my file without any error)

```
sidenote for whatever it's worth:

the other key set command was:
firebase functions:config:set mailgun.api_key=xyz321

the other key code to read was:
functions.config().mailgun.api_key

(no errors)
```

Deploy log:
[deploy-error.log](https://github.com/firebase/firebase-tools/files/2048684/deploy-error.log)

[set-var.log](https://github.com/firebase/firebase-tools/files/2048678/set-var.log)
[get-var.log](https://github.com/firebase/firebase-tools/files/2048677/get-var.log)
[deploy-error.log](https://github.com/firebase/firebase-tools/files/2048684/deploy-error.log)

Link to the firebase function that prompts the error during deploy:
https://github.com/joemsak/beeseeking-vue/blob/master/functions/index.js

**Comment by laurenzlong** [comment] 2018-05-30 00:05
Hi this is a duplicate of https://github.com/firebase/firebase-tools/issues/492. In the meanwhile, you can work around it by naming it something that doesn't have "firebase" in the key.

**Closed by laurenzlong** 2018-05-30 00:05 UTC
