### ISSUE TITLE
Version 8.3.0: Unable to load functions code.  TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by decurtic** [firebase/firebase-tools#2252] opened 2020-05-19 22:17 UTC
### [REQUIRED] Environment info

8.3.0
**firebase-tools:** 
8.3.0

Windows

### [REQUIRED] Test case

See log in Steps to Reproduce

### [REQUIRED] Steps to reproduce

On firebase version 8.3.0.
Run npm i -g firebase-tools
Installs successfully
Run firebase serve
Get following log portion: 

=== Serving from 'C:\[obscured]'...

i  hosting: Serving hosting files from: public
+  hosting: Local server: http://localhost:5000
!  Your requested "node" version "8" doesn't match your global version "13"
i  functions: Watching "C:\[obscured]\functions" for Cloud Functions...
!  functions: Your GOOGLE_APPLICATION_CREDENTIALS environment variable points to C:\[obscured].json. Non-emulated services will access production using these credentials. Be careful!
!  TypeError: Cannot convert object to primitive value
    at Proxy.<anonymous> (C:\[obscured]\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:311:83)
    at Object.<anonymous> (C:\[obscured]\functions\index.js:3:7)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at C:\[obscured]\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:660:33
    at Generator.next (<anonymous>)
!  We were unable to load your functions code. (see above)
i  hosting: 127.0.0.1 - - [19/May/2020:21:41:26 +0000] "GET /__/firebase/init.js HTTP/1.1" 200 - "http://localhost:5000/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
...

To fix:
Run 'npm i -g firebase-tools@8.2.0'
Actual behavior becomes expected behavior, no errors.

### [REQUIRED] Expected behavior

Load cloud functions when emulating server locally

### [REQUIRED] Actual behavior
Emulated local server loaded, but without cloud functions

See above

**Comment by bkendall** [comment] 2020-05-19 22:25
Duplicate of #2248

**Closed by bkendall** 2020-05-19 22:25 UTC
