### ISSUE TITLE
Firebase deploy Issue.

### ISSUE THREAD

**Issue by koz01** [firebase/firebase-tools#654] opened 2018-02-01 02:40 UTC
Hi Firebase developer, Please help me.
When i deploy firebase could function, i facing the following error.

D:\Development\functions-firecast\functions>firebase deploy --only functions

=== Deploying to 'onthegomex-c10e8'...

i  deploying functions
Running command: npm --prefix $RESOURCE_DIR run lint
npm ERR! path D:\Development\functions-firecast\$RESOURCE_DIR\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'D:\Development\functions-firecast\$RESOURCE_DIR\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-02-01T02_29_22_303Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code4294963238

D:\Development\functions-firecast\functions>

**Comment by merlinnot** [comment] 2018-02-01 02:49
Take a look at this: https://github.com/firebase/firebase-tools/issues/610#issuecomment-361752596

Next time you can try to look up the issue by yourself first 😋

If it fixes your problem, please remeber to close the issue.

**Comment by koz01** [comment] 2018-02-01 03:08
I already look up this  #610 (comment) but it can't fix me.

**Comment by merlinnot** [comment] 2018-02-01 03:15
Ping @tinaliang @mbleigh

**Comment by tinaliang** [comment] 2018-02-01 06:20
@koz01 what platform are you running this on? Could you also run `firebase deploy --only functions --debug` and paste the output here?

**Closed** 2018-02-01 07:09 UTC

**Comment by seungha-kim** [comment] 2018-02-08 02:26
Would you tell me why you close this issue? Did you resolve this issue?

**Comment by FatmaMM** [comment] 2018-02-11 08:59
npm install -g git://github.com/firebase/firebase-tools#master
fixed the issue

**Comment by yvanvds** [comment] 2018-02-18 22:52
I got the same issue with a generic deploy command. Installing the tools from github, as opposed to the instructions on the google site, solves the issue.

**Comment by Maruthi-Manoj** [comment] 2018-02-25 17:49
I got the same error. Just copy these files node_modules, .eslintrc.json, package.json into $RESOURCE_DIR file. And then deploy.

**Comment by Xsmael** [comment] 2018-03-16 22:16
@Maruthi-Manoj 

And where am i supposed to find these files ?

**Comment by Maruthi-Manoj** [comment] 2018-03-28 07:26
@Xsmael 
Go to the location where you installed firebase. you can find node_modules, .eslintrc.json, package.json files in functions folder.

**Comment by fdambrosio** [comment] 2018-04-09 14:24
I have the same problem, running `npm install -g git://github.com/firebase/firebase-tools#master` not fix my problem: 
firebase deploy --only functions

**Comment by ArjunAtlast** [comment] 2018-06-14 15:04
Can you run the commands
`npm --prefix "$RESOURCE_DIR" run lint` and `npm --prefix "$RESOURCE_DIR" run build` seperately.

**Comment by wlaa41** [comment] 2018-06-18 10:50
The sane problem .... Nothing solved it

**Comment by laurenzlong** [comment] 2018-06-19 23:00
For each new person that is landing on this issue, please open a separate issue, since each case is unique and may not be related, we really need to see the logs for your specific case  to be able  to diagnose anything.

**Comment by Thaina** [comment] 2018-06-25 06:50
For me change this to this fix it

Yes, my function folder was named `functions`

![image](https://user-images.githubusercontent.com/1042507/41834480-a628d8ae-787e-11e8-893a-8d1d59667076.png)

**Comment by claudio910103** [comment] 2018-06-26 16:51
Tenía el mismo problema y o solucioné gracias a lo que comento @Thaina 
### Gracias

**Comment by Thaina** [comment] 2018-06-26 17:04
People, I want to add that my fix is just a hack to make it work in the meantime

The real problem seem like firebase try to use `$RESOURCE_DIR` for an environment variable around the project to find the folder name of the functions. I'm not sure why it does not work as they expected. But it better to have someone report this bug as a separate issue and have firebase people truly fix the root cause

**Comment by fdambrosio** [comment] 2018-06-27 09:02
thanks @Thaina  you've found the problem

**Comment by vasu2652** [comment] 2018-06-29 06:09
This is a known problem with the Firebase CLI 3.17.0 through at least 3.17.3, but only on Windows. You can fix this on your machine by editing firebase.json at the root of your project and replacing $RESOURCE_DIR with %RESOURCE_DIR% in the npm commands you see there. The former is the unix syntax way to use an environment variable, whereas the latter is the Windows command shell syntax. Since you're using Windows, you need to use the Windows syntax.

The team is looking into ways to prevent having to make changes to the config files you use, as it's not really convenient for teams that works across platform to keep changing the same file back and forth.

**Comment by russellinho** [comment] 2018-07-06 15:56
Nice m8

**Comment by ShahnawazHussain125** [comment] 2018-07-15 13:21
@Thaina Thanks. I solve my problem

**Comment by laurenzlong** [comment] 2018-07-21 00:09
Please see https://github.com/firebase/firebase-tools/issues/822#issuecomment-406754186 for discussion of problems with RESOURCE_DIR on Windows

**Comment by themichaelbanda** [comment] 2018-08-12 21:42
@Thaina Thank you, such an obvious solution.

**Comment by ghousshah** [comment] 2018-12-11 13:21
> For me change this to this fix it
> 
> Yes, my function folder was named `functions`
> 
> ![image](https://user-images.githubusercontent.com/1042507/41834480-a628d8ae-787e-11e8-893a-8d1d59667076.png)

Thankyou

**Comment by pelx** [comment] 2020-02-06 16:02
I have the same problem. Fixes above don't help;)

**Comment by russellinho** [comment] 2020-02-06 18:38
@pelx Screenshot?

**Comment by pelx** [comment] 2020-02-06 18:49
I moved on, sorry, the problem has gone after I reinstalled firebase-tools and initialized the app without lint... I think the lint option was causing the problem. Thank you for you reply, I will try to replicate.

**Comment by LionelZoc** [comment] 2020-04-03 18:53
to resolve it for my case i replace the lint script in functions/package.json by 
**"lint": "node ./node_modules/eslint/bin/eslint.js ."**
the previous was "lint": "eslint ."
