### ISSUE TITLE
Timestamps not persisting Firestore

### ISSUE THREAD

**Issue by wizlif** [firebase/firebase-tools#3649] opened 2021-08-07 06:31 UTC
### [REQUIRED] Environment info

**firebase-tools: 9.16.0**

**Platform: macOs**

### [REQUIRED] Steps to reproduce

- Add a timestamp value to any document then refresh the browser.

![screencast-localhost_4000-2021 08 07-09_13_04](https://user-images.githubusercontent.com/15793624/128644365-328e9924-f724-4fd9-a522-513b456e4c53.gif)

### [REQUIRED] Expected behaviour

- The value disappears like it was never saved

**Comment by riker09** [comment] 2021-08-10 08:55
Duplicate of #3645 

But I'm affected by this as well

**Comment by yuchenshi** [comment] 2021-08-16 16:35
Fixed in v9.16.5

**Closed by yuchenshi** 2021-08-16 16:35 UTC
