### ISSUE TITLE
Firestore emulator having problem with CORS.

### ISSUE THREAD

**Issue by gel-prog** [firebase/firebase-tools#2550] opened 2020-08-14 13:01 UTC
### [REQUIRED] Environment info

**firebase-tools:** 8.7.0

**Platform:** Windows/WSL

### [REQUIRED] Test case

1. Create a new project with `firebase init`.
2. Enable `functions` and `firestore`
3. Run `firebase:emulators:start`
4. Go to `http://localhost:4000/firestore` and create a document

### [REQUIRED] Steps to reproduce

1. Create a new project with `firebase init`.
2. Enable `functions` and `firestore`
3. Run `firebase:emulators:start`
4. Go to `http://localhost:4000/firestore` and create a document

### [REQUIRED] Expected behavior
Should be able to create and see the newly created document.

### [REQUIRED] Actual behavior
Getting errors when trying to fetch the new document.

```
Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:8080/v1/projects/myProject/databases/(default)/documents:listCollectionIds
```

Seems to be a problem given CORS. If I use Firefox instead of Chrome:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/v1/projects/myProject/databases/(default)/documents:listCollectionIds. (Reason: CORS request did not succeed).
```

**Comment by samtstern** [comment] 2020-08-14 13:42
@gel-prog I believe this is a duplicate of this known issue: https://github.com/firebase/firebase-tools-ui/issues/332

Please follow along over there!

**Closed by samtstern** 2020-08-14 13:42 UTC
