### ISSUE TITLE
Cant upload functions with relative paths anymore

### ISSUE THREAD

**Issue by larssn** [firebase/firebase-tools#2875] opened 2020-11-30 17:02 UTC
### [REQUIRED] Environment info

**firebase-tools:** 8.16.2

**Platform:** macOS

### [REQUIRED] Test case

Maybe I'm going crazy here, but I had relative paths working last week. Doesn't work this week, the upload fails at the "prepare" step.
I'm simply creating an empty file `test.txt` (in `functions/test.txt`), and then trying to read it in my function.

Index.ts:
```
import * as fs from 'fs';
fs.readFileSync('test.txt');
```

[THIS](https://stackoverflow.com/a/54356761/536485) answer by Doug seems to indicate it being correct, but I keep getting:
```
✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

Error: ENOENT: no such file or directory, open 'test.txt'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (cf/functions/src/index.ts:7:4)

I've tried various paths: `'./test.txt', 'test.txt', '../test.txt'` but nothing works.

### [REQUIRED] Steps to reproduce

See above.

### [REQUIRED] Expected behavior

That Doug's answer is still valid.

### [REQUIRED] Actual behavior

It's apparently not!?

But it's weird because I can read EJS template files just fine, and thats in a relative folder called `views`, which works.

**Comment by samtstern** [comment] 2020-11-30 19:19
@larssn what if you do this:

```
fs.readFileSync(__dirname + 'test.txt');
```

See: https://www.digitalocean.com/community/tutorials/nodejs-how-to-use__dirname

**Comment by larssn** [comment] 2020-11-30 21:45
Well Doug says:  

> Don't try to build a full path to the file, as you shouldn't assume where your code deployment is effectively mounted in the server instance.

Which makes sense. But I tried __dirname, and then the error outputs my local path. If you're sure thats ok, I can probably make it work tomorrow.

**Comment by samtstern** [comment] 2020-11-30 23:15
@larssn a few things:

1. `__dirname` is safe to use, it's made exactly for the purpose of resolving data files based on their relative location to code.
2. When you do `fs.readFileSync('file.txt')` it reads relative to **where you ran the `node` command** not relative to the source file containing that statement.  So that's generally unstable.
3. It looks like you're doing `readFileSync` in the global scope, meaning outside of any `function() {}` scope. When you do `firebase deploy` we fork a new `node` process and `require()` your code to discover all the exported triggers.  This executes everything in the global scope so that we can see the exports. So when you combine that with (2) that can be an issue, since you can't control what we use as the working directory when we fork that process.  I think Doug's answer was assuming that you were running inside a function scope or something similar.

**Comment by larssn** [comment] 2020-12-01 08:36
@samtstern Thanks for elaborating Sam. The real reason I'm asking is I'm setting up OpenApi for our REST endpoints, and I fire off a command like this:
```
import * as swaggerValidation from 'openapi-validator-middleware';
swaggerValidation.init('./openapi/spec.yaml');
```

It resides in `myfunctions/functions/src/endpoints/v1/v1.ts`
and the spec is in `myfunctions/openapi/spec.yaml`

I managed to deploy this just fine last week, but I can't this week. I don't see why it wouldn't work this week, so wondering if anything changed.

Anyway this deploys:
`swaggerValidation.init(__dirname + '/../../../openapi/spec.yaml');`, but I can't imagine this working when deployed, or do you do some kind of path rewriting when deployed?

**Comment by samtstern** [comment] 2020-12-01 20:17
@larssn I used `firebase init` to create a brand new project.  I then wrote this simple function:

**functions/index.js**
```js
const functions = require('firebase-functions');
const fs = require('fs');
const path = require('path');

exports.readTextFile = functions.https.onRequest((request, response) => {
  const txtPath = path.join(__dirname, 'text.txt');
  const txtContent = fs.readFileSync(txtPath).toString();
  response.send(`Hello from Firebase: ${txtContent}`);
});
```

The `functions/text.txt` file contains:
```
This is my file content.
```

When I run the local emulator everything works:
```
$ http http://localhost:5001/ota-fir-dumpster/us-central1/readTextFile
HTTP/1.1 200 OK
connection: keep-alive
content-length: 46
content-type: text/html; charset=utf-8
date: Tue, 01 Dec 2020 20:14:30 GMT
etag: W/"2e-bCP0RkM3Dzka6EdNMb4bkgsk8hw"
x-powered-by: Express

Hello from Firebase: This is my file content.
```

I then deployed the same HTTP function to production and called it there:
```
$ http https://us-central1-ota-fir-dumpster.cloudfunctions.net/readTextFile
HTTP/1.1 200 OK
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 46
Content-Type: text/html; charset=utf-8
Date: Tue, 01 Dec 2020 20:16:19 GMT
Etag: W/"2e-bCP0RkM3Dzka6EdNMb4bkgsk8hw"
Function-Execution-Id: nd0z3dei0h6b
Server: Google Frontend
X-Cloud-Trace-Context: e15acee20858aa43a4e157419d62942e;o=1
X-Powered-By: Express

Hello from Firebase: This is my file content.
```

So at this point I think I can confidently say there's not an issue with the Firebase CLI or with how reading local files works in Cloud Functions.  If you're experiencing failures it has to be something specific to your project setup, which isn't really something we can dig into for you.

If you think I missed something and there's a bug in our code somewhere, please let me know how to reproduce it and I will re-open this issue for more investigation.

**Closed by samtstern** 2020-12-01 20:17 UTC
Labels: Needs: Attention

**Comment by jim-alexander** [comment] 2022-07-28 02:46
God this is annoying. 

I Went in to change some minor behaviour of an existing function, and now I'm stuffing around trying to find a path to a file that is used as a template. 

Having no luck with __dirname getting the same error with `rror: ENOENT: no such file or directory, open '/workspace/lib/....`

**Comment by bkendall** [comment] 2022-07-29 18:23
@jim-alexander if you're having new issues that the comments above don't help with, can you provide a reproduction case in a new issue for us? Thanks.
