### ISSUE TITLE
Firebase emulator return empty data whereas working fine after deploying

### ISSUE THREAD

**Issue by 786lokesh** [firebase/firebase-tools#2183] opened 2020-04-28 13:07 UTC
**firebase-tools:** 8.1.1

**Platform:** Ubuntu

### [REQUIRED] Steps to reproduce
I am not sure how I ran into this problem. I just followed the doc to run and debug the functions on emulator. After "firebase init", I selected the firestore, functions and datastore emulators and all the dependencies were successfully installed.
Later I started the emulator and it's start the firestore, functions and datastore emulators on different port.
Then I tried to execute my function and got no data in response.
```
export const activeServices = functions.https.onRequest((request, response) => {
    let services = new Array<string>();
    admin.firestore().collection(newServices).get()
    .then(serviceSnapshot => {
        serviceSnapshot.docs.forEach(doc => {
            if(doc.data().service_active){
                services.push(doc.data().service_name)
            }
        })
        const successResponse = common.success("success", 200, "Services retrieved", services)
        response.send(successResponse)
    })
    .catch(error => {
        const errorResponse = common.error("fail", 500, "Failed to get active services")
        console.error(errorResponse)
        response.send(errorResponse)
    })
})
```
I tried to execute this and it return nothing and executed the same functions after deploying. And I got the response.

**Comment by samtstern** [comment] 2020-04-28 13:09
@786lokesh can you provide:

- The code you're running
- What you expected it to do
- What it actually did

The above is not enough information to help you.

**Comment by 786lokesh** [comment] 2020-04-28 13:23
@samtstern I have updated my query.

**Comment by samtstern** [comment] 2020-04-28 13:25
Have you written any data into the Firestore emulator?  If not, I would not expect `admin.firestore().collection(newServices).get()` to return anything.  The Firestore emulator starts up a completely empty database.

Closing because I think this is working as intended right now.  Use the Admin SDK to add data to the Firestore emulator for testing.

**Closed by samtstern** 2020-04-28 13:25 UTC
Labels: Needs: Attention

**Comment by 786lokesh** [comment] 2020-04-28 13:33
@samtstern I didn't know this, how can I add the data in firebase emulator ?

**Comment by samtstern** [comment] 2020-04-28 13:34
You can write to it using the Admin SDK.

**Comment by 786lokesh** [comment] 2020-04-28 13:44
I couldn't find any relevant link to do this. Can you walk me through this with an example ?

**Comment by samtstern** [comment] 2020-04-28 14:07
Sure you can write a simple script like this:

**index.js**
```js
const admin = require("firebase-admin");
admin.initializeApp();

admin.firestore().doc('/foo/bar').set({
  hello: 'world'
});
```

And then you can execute it like this while the emulator is running:
```bash
FIRESTORE_EMULATOR_HOST="localhost:8080" node index.js
```

**Comment by 786lokesh** [comment] 2020-05-01 05:27
@samtstern So every time, I need to set the data first and then call API ? I have lot of collections with documents in database. Is there a short way to, I can directly use the database ?

**Comment by samtstern** [comment] 2020-05-01 12:14
@786lokesh once you have filled the emulator with data once you can save it using `firebase emulators:export ./your-data` in another terminal and later import the same data by using `firebase emulators:start --import ./your-data`

**Comment by 786lokesh** [comment] 2020-05-02 04:55
@samtstern Can't I make a testing database on firebase ? Actually I also want to access the authentication API. And by exporting and importing the data seems like, I will be limited to firestore database.

**Comment by 786lokesh** [comment] 2020-05-02 05:03
As far ad I have seen, If I launch only functions
`firebase emulators:Start --only functions`
This will try to communicate with production, I also tried, but says this:
```
functions: The Cloud Firestore emulator is not running, so calls to Firestore will affect production.
⚠  External network resource requested!
```

**Comment by 786lokesh** [comment] 2020-05-03 04:54
@samtstern Please reopen this ticket. I have updated the same query.

**Comment by 786lokesh** [comment] 2020-05-04 13:51
unfortunately I will have to open another issue as this has become unresponsive.

**Comment by samtstern** [comment] 2020-05-04 14:05
@786lokesh please don't do that, issues on GitHub are not a paid support channel and we respond when we can.   My last response was on Friday afternoon and now it is Monday morning, I don't work over the weekend.

A few things:

1. Yes when you don't run the Cloud Firestore emulator we try to connect to production, this is working as intended.
2. It sounds like what you want is to create a separate Firebase project (in production) to use for testing with the Cloud Functions emulator.  This will allow you to preserve Auth, Firestore, Realtime Database, etc between runs.

**Comment by azoom-n-d-hoang** [comment] 2020-05-06 09:27
> @786lokesh once you have filled the emulator with data once you can save it using `firebase emulators:export ./your-data` in another terminal and later import the same data by using `firebase emulators:start --import ./your-data`

@samtstern i did extactly what you said above. But when start emulator again (only firestore) with data export from previous step, then firestore is empty. [here](https://github.com/azoom-n-d-hoang/emulator-demo) is my code and detail description

**Comment by samtstern** [comment] 2020-05-06 12:18
@azoom-n-d-hoang if import/export is not working for you please file a new issue.

**Comment by Tzahile** [comment] 2020-08-15 17:01
In my case, I try to communicate with the realtime-database.
When I start the emulators, my app gets the data from the production realtime-database (I see real data on the host emulator), but the realtime-database emulator is empty.
Therefore, populating the emulator manually doesn't seem to affect.

Is there a way to communicate with the production-database?
My function doesn't leave any stamp, so I'm not worried about using production data

thanks

**Comment by samtstern** [comment] 2020-08-17 09:40
@Tzahile I don't quite understand the situation you're describing but here's how it works:

  * If you are running **both** the Cloud Functions emulator and the Realtime Database emulator then:
    * Writes to the RTDB emulator will trigger cloud functions in the functions emulator
    * Reads and writes from functions using `firebase-admin` will use data from the RTDB emulator
  * If you are running **only** the Cloud Functions emulator
    * Your RTDB functions will never fire
    * Reads and writes from functions using `firebase-admin` will use data from production

**Comment by NandhaGopiFrost** [comment] 2021-02-07 07:50
Even am facing the same issue
1. I have manually entered data using emulator UI, when I try to get the data back, exists is false always for me

My firestore emulator run on localhost:5000

`db.collection("myfirstcollection").doc("dataexitsinthedocument").get()
        .then(snapShot=>{
            if(snapShot.exists){
                console.log(snapShot.data())
            }else{
              console.log("no data to fetch")
            }
        })
        .catch(error=>{console.log(error);console.log(error)})
        .finally(()=>{
          console.log("exit on final")
        })`

I have connected to my firestore using
`if (window.location.hostname === "localhost") {
    db.useEmulator("localhost", 5000);
    console.log("using emulator")
}`
