### ISSUE TITLE
Storage Emulator Rules runtime exited unexpectedly

### ISSUE THREAD

**Issue by brodao** [firebase/firebase-tools#3568] opened 2021-07-09 15:06 UTC
### [REQUIRED] Environment info

**firebase-tools:** 9.16.0

**Platform:** Windows

### [REQUIRED] Steps to reproduce

1. Download `firebase-tools-win.exe`
2. Execute `firebase-tools-win init`
3. Select `Storage: Configure a security rules file for Cloud Storage` and `Emulators: Set up local emulators for Firebase products` and press `enter`
4. Select `Authentication Emulator` and `Store Emulator` and press enter
5. On next requests accept default
6. Execute `firebase emulators:start`

### [REQUIRED] Expected behavior

Running `auth` and `store` emulators.

### [REQUIRED] Actual behavior

`Auth` and `store` emulators not running.

```
[2021-07-09T15:02:11.810Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.co
m/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2021-07-09T15:02:11.811Z] > authorizing via FIREBASE_TOKEN environment variable
i  emulators: Starting emulators: auth, storage {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: auth, storage"}}
!  emulators: It seems that you are running multiple instances of the emulator suite for project ac-autohomeapp. This may result in unexpected behavior.
[2021-07-09T15:02:13.857Z] [hub] writing locator at C:\Users\brodao\AppData\Local\Temp\hub-ac-autohomeapp.json
[2021-07-09T15:02:19.729Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"storage"},"message":"Ignoring unsupported arg: port"}}

Error: Storage Emulator Rules runtime exited unexpectedly.
```

**Comment by samtstern** [comment] 2021-07-12 15:49
Could you run `firebase --debug emulators:start` and show the logs?

**Comment by brodao** [comment] 2021-07-17 12:11
@samtstern 

Thanks in advance

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/6834667/firebase-debug.log)

**Comment by abeisgoat** [comment] 2021-07-21 18:59
Can you provide the contents of your `firebase.json`?

**Comment by Hibrix-net** [comment] 2021-07-21 20:19
Similar issue here. The Firebase emulator is also not exporting any data after shutdown.

**Comment by brodao** [comment] 2021-07-23 20:10
@abeisgoat 

Thanks in advance. The ``storage.rules`` content is default

```
{
  "emulators": {
    "auth": {
      "port": 9099
    },
    "storage": {
      "port": 9199
    },
    "ui": {
      "enabled": true
    }
  },
  "storage": {
    "rules": "storage.rules"
  }
}
```

```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth!=null;
    }
  }
}
```

**Comment by OutdatedGuy** [comment] 2021-10-03 21:59
Same issue with me. Emulator doesn't terminate successfully.
I'm having trouble with exporting data due to unexpected termination of emulator.

**Comment by tonyjhuang** [comment] 2022-07-29 05:03
filed internal bug to track, b/240637643

**Comment by Yuangwang** [comment] 2022-08-12 18:07
Hi @brodao I've tried taking a look at this but I couldn't quite reproduce the issue. Looking at your debug log, I see that its missing a section that says the Java version so could you please make sure you have Java setup properly? It could also be the case that this issue has been fixed at some point so could you please go through the the windows setup steps again? https://firebase.google.com/docs/cli#install-cli-windows

I'm closing this for now but please feel free to reopen if you try and still have the same issue

**Closed by Yuangwang** 2022-08-12 18:07 UTC
Labels: Needs: Attention, emulator-suite, emulators: storage
