### ISSUE TITLE
Firebase functions keeps asking "to accept incoming network connections?"

### ISSUE THREAD

**Issue by jamiegalbreath** [firebase/firebase-tools#5683] opened 2023-04-12 09:57 UTC
Firebase functions emulator keeps asking "Do you want the application “firebase” to accept incoming network connections?" 
Pops up everytime I save.

How do I stop this?
Have tried macOS settings with no luck

[alert](https://i.stack.imgur.com/YqhXi.jpg)

node v14.21.3
macOS 13.2.1
firebase-tools 11.24.0

**Comment by jamiegalbreath** [comment] 2023-04-12 10:50
If you need more info I am happy to provide, just not sure what would be useful.

**Comment by aalej** [comment] 2023-04-12 11:36
Hi @jamiegalbreath, thanks for reaching out to us. This is an odd issue and I’m not completely sure what’s causing it, but it might have something to do with your Network settings. Could you try checking your Network setting to see if Firebase is being blocked by your Firewall. Also, could you try updating to the latest version of `firebase-tools`, which is v11.26.0, to see if the issue would still occur there?

Lastly, could you provide any specific steps to reproduce this issue, such as commands you ran, does it occur when accessing a function or only when starting the emulator?

**Comment by jamiegalbreath** [comment] 2023-04-12 11:43
Sure thing, i've updated firebase-tools with no change.
It happens when the emulator is running and everytime I run the function or save the file whilst amending the function.

See screenshot with network/firewall settings

![Screenshot 2023-04-12 at 12 39 12](https://user-images.githubusercontent.com/5307969/231446055-ec8df747-f4d7-48c8-a2d5-999a8b63272b.jpg)

Any thoughts?

**Comment by jamiegalbreath** [comment] 2023-04-12 12:08
I've done a test and turning off the firewall restarting and this seems to have stopped the issue. Thanks.

**Comment by aalej** [comment] 2023-04-12 15:14
It might be worth trying to enable the "Automatically allow signed software to receive incoming connections" option in your Network > Firewall Options.

Just a warning, after testing you should turn your Firewall back on to avoid malicious software that will try to access your network. Given that the issue is being caused by your Network settings, there is not much we can do on the emulators side. That said, I'll be closing this ticket.

**Closed by aalej** 2023-04-12 15:14 UTC
Labels: type: bug, Needs: Attention, emulators: functions
