### ISSUE TITLE
Please run firebase login --reauth (when using FIREBASE_TOKEN)

### ISSUE THREAD

**Issue by heygambo** [firebase/firebase-tools#342] opened 2017-05-22 15:19 UTC
I've removed and reinstalled `firebase-tools` using `npm` and `yarn`.
For some reason even after running `firebase login --reauth` it will still complain about it.
 
⚠  Your CLI authentication needs to be updated to take advantage of new features.
⚠  Please run firebase login --reauth

versions:
firebase-tools 3.9.0
node v7.2.1
nvm 0.33.0

Does anyone know how to get rid of this warning?

**Comment by justinbmeyer** [comment] 2017-06-14 17:29
yes, I'm seeing the same problem.  Any resolution?

**Comment by nerdyglasses** [comment] 2017-07-12 07:18
I'm still getting: 

```
✔  Database Rules for abc have been downloaded to database.rules.json.
Future modifications to database.rules.json will update Database Rules when you run
firebase deploy.

=== Functions Setup

A functions directory will be created in your project with a Node.js
package pre-configured. Functions can be deployed with firebase deploy.


Error: This command requires new authorization scopes not granted to your current session. Please run firebase login --reauth
```

Running reauth doesn't help.

**Comment by nerdyglasses** [comment] 2017-07-13 07:24
After months I have finally found the issue.

I've had `export FIREBASE_TOKEN=abc` in my `~/.zshenv` file and forgot about it.

Now everything works fine!

I wish there would have been a note that I'm using my `FIREBASE_TOKEN` or that this is something I should have looked for.

e.g.

⚠ Your CLI authentication needs to be updated to take advantage of new features.
⚠ Note that you're using the FIREBASE_TOKEN environment variable.
⚠ Please renew or remove that and try again.

**Comment by muhammadghazali** [comment] 2017-08-25 23:46
Another way that works for me to work around this issue is by logging out and re-login the Firebase CLI.

**Comment by nerdyglasses** [comment] 2017-08-25 23:51
> Another way that works for me to work around this issue is by logging out and re-login the Firebase CLI.

this was my first guess as well. But if that doesn't work, then have a look at the terminal environment variables.

**Comment by mohanramphp** [comment] 2017-09-17 12:47
I found what was the problem. Please follow steps below

**Step 1** Create firebase project @ [Firebase console](https://firebase.google.com/console/)
**Step 2** Login into firebase via cmd `firebase login`
**Step 3** Run `firebase init` Initialize app by selecting existing app you created in **Step 1**
**Step 4** Run `firebase deploy` should deploy your application

**Comment by nerdyglasses** [comment] 2017-09-17 12:50
> I found what was the problem. Please follow steps below
> Step 1 Create firebase project @ Firebase console
> Step 2 Login into firebase via cmd firebase login
> Step 3 Run firebase init Initialize app by selecting existing app you created in Step 1
> Step 4 Run firebase deploy should deploy your application

This was my first guess as well. But if that doesn't work, then have a look at the terminal environment variables.

This ticket is still open because of my suggestion to add a note about old firebase tokens: 
https://github.com/firebase/firebase-tools/issues/342#issuecomment-314994814

**Comment by mohanramphp** [comment] 2017-09-17 12:53
@nerdyglasses I face same issue and once i created project first in firebase console and then it worked. Can you brief what sequence or steps to reproduce your issue

**Comment by nerdyglasses** [comment] 2017-09-17 12:55
@mohanramphp put this in your .bashrc or .zshrc, then start a new browser session:
`export FIREBASE_TOKEN=94th393g8h2g23g`

and run firebase deploy.

**Comment by alltej** [comment] 2017-10-29 09:36
What works for me is to run `firebase logout` and then login  with `firebase login`.

**Comment by nerdyglasses** [comment] 2017-10-29 12:05
@alltej did you have a `FIREBASE_TOKEN` from firebase 2 in your shell's environment?
My point is that this will make the firebase 3 cli break.

**Comment by Overdrivr** [comment] 2018-03-22 09:40
I got this error by passing a wrong project id to the `-P` flag.

Basically, I thought I could define projects in my firebaserc file like this:

```
{
  "projects": {
    "staging": "firebase-staging-project-id"
    "production": "firebase-production-project-id"
  }
}
```
And call
```
firebase deploy --token "$FIREBASE_TOKEN" -P staging
```
But it fails with the error described here.

While passing the full project id like below
```
firebase deploy --token "$FIREBASE_TOKEN" -P firebase-staging-project-id
```
works without problem. So maybe this P flag should need a more informative message ? Also, is this the expected behavior or a bug ?

**Comment by NikolaJankovic** [comment] 2018-04-10 01:06
I had the same issue as @Overdrivr - passing the wrong project name raised the auth prompt and 500 error subsequently. 

Passing an invalid project name should really be caught and have a more appropriate error message.

**Comment by nerdyglasses** [comment] 2018-05-18 09:29
@mmorrison24 make sure it's not in your export list in the terminal.

run `export` and see if there is a `FIREBASE_TOKEN` outputted.

**Comment by philip-firstorder** [comment] 2018-06-02 23:53
I ran `export` but there is no FIREBASE_TOKEN, still getting the error

**Comment by guruprasaad123** [comment] 2018-09-28 13:28
In my case am unable to even` login `.<br>So CLI wont allow me to even `initialize` a project.<br>Looks like am trapped.
![firebase-cli](https://user-images.githubusercontent.com/19173193/46211104-49566980-c350-11e8-9318-32a5508b4c17.PNG)

**Comment by bkendall** [comment] 2019-01-09 00:50
I see that the original error (regarding `FIREBASE_TOKEN`) was resolved. There's still some questions regarding warning when using the environment to authenticate, which is actually something that is currently being worked on internally (though, slowly). I'm closing this issue as there's not been recent activity on it. If anyone is still having issues with authentication, I'd ask that you open a new bug with the appropriate information! Thanks!

**Closed by bkendall** 2019-01-09 00:50 UTC

**Comment by BuddhaNag12** [comment] 2019-07-12 16:00
> In my case am unable to even`login`.
> So CLI wont allow me to even `initialize` a project.
> Looks like am trapped.
> ![firebase-cli](https://user-images.githubusercontent.com/19173193/46211104-49566980-c350-11e8-9318-32a5508b4c17.PNG)

i'm having the same problem please suggest a help

**Comment by bkendall** [comment] 2019-07-12 16:05
@BuddhaNag12 please open a new issue so we can better track this. Thank you.

**Comment by kichus14** [comment] 2019-07-30 10:47
Use `firebase login --no-localhost`. This will prompt to paste the authorization code displayed in the screen after successful login

**Comment by Josephpious** [comment] 2020-09-26 18:29
Copy the code and paste but it still give error

**Comment by MollyXuemn** [comment] 2021-03-14 09:40
me too, please pose any new issue to solve this:
Waiting for authentication...
(node:10492) UnhandledPromiseRejectionWarning: FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
    at Client.doRequest (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:211:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:10492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
