### ISSUE TITLE
searchParams does not work Firebase Hosting

### ISSUE THREAD

**Issue by huseyinseyit** [firebase/firebase-tools#7320] opened 2024-06-13 07:58 UTC
<

### [REQUIRED] Environment info

Firebase CLI: 13.11.2
Windows,
Next.js 14.2.3

### [REQUIRED] Test case
A new project was created, a search was done using searchParams. Localhost works properly without any problems.
firebase experiments:enable webframeworks activated.
npm run build. 
Firebase deploy process completes successfully but https://xxx.web.app does not work
### [REQUIRED] Steps to reproduce
A new project was created,
a search was done using searchParams. 
firebase experiments:enable webframeworks activated.
npm run build.
Firebase deploy
### [REQUIRED] Expected behavior

Works on firebase hosting too.

### [REQUIRED] Actual behavior

Localhost works properly without any problems but firebase hosting dont work. There is no error in the console.

**Comment by aalej** [comment] 2024-06-13 18:04
Hey @huseyinseyit, thanks for reaching out. Currently, I’m unable to reproduce the behavior you mentioned. I tried creating a new Next.js project and used `searchParams`. After running `firebase deploy` and checking the deployed application, I was able to verify that the query parameters from the URL were being read.

I’m using [this](https://github.com/aalej/issues-7320) to try and replicate the issue. If I'm missing anything or if I made a mistake, please let me know. Alternatively, any chance you could share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) with us or sample code snippets? This will help us accurately reproduce the issue.

**Comment by huseyinseyit** [comment] 2024-06-14 06:34
First of all, thank you, 
I have added the project structure, the visual is below, and I am also adding the inventory page.tsx,
`import { Suspense } from 'react';
import CardWrapper from '../../components/cards';
import Search from '../../components/search';
import Pagination from './pagination';
import Table from './table';

export default async function Page({
    searchParams,
}: {
    searchParams?: {
        query?: string;
        page?: string;
    };
}) {
    const query = searchParams?.query || '';
    //const currentPage = Number(searchParams?.page) || 1;
    const currentPage = 1;
    const totalPages = 1;
    return (
        <div className="h-full bg-gray-800 border-t border-l border-gray-600 p-3">
            <div className="overflow-hidden flex justify-between items-center">
                <h1 className="text-white text-2xl font-bold pb-3">Inventory</h1>
                <div className="flex items-center">
                    <div className="ml-auto">
                        <div className="flex items-center">
                            <button className="bg-slate-500 text-[14px] text-white px-3 py-1 rounded">
                                Export
                            </button>
                            <button className="bg-slate-500 text-[14px] text-white px-3 py-1 rounded ml-2">
                                New Model
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div className='overflow-hidden'>
                <div className="flex justify-around gap-4">
                    <CardWrapper />
                </div>
            </div>


            <div className="mt-4 flex items-center justify-between">
                <Search placeholder="Search model..." />
            </div>
            {<Suspense key={query + currentPage} >
                <Table query={query} currentPage={currentPage} />
            </Suspense>}
            <div className="mt-5 flex w-full justify-center">
                {<Pagination totalPages={totalPages} />}
            </div>
        </div>
    );
}`

![g1](https://github.com/firebase/firebase-tools/assets/95279270/fa1d70b8-a7bf-469e-9e9d-656aa042319b)

**Comment by aalej** [comment] 2024-06-17 15:21
Thanks for sharing code snippets. I copied the code you provided, but it looks like it uses some components you created like `CardWrapper`, `Search`, etc. I removed those components so that I can run the application.

```tsx
// app/page.tsx
export default async function Page({
 searchParams,
}: {
 searchParams?: { query?: string; page?: string };
}) {
 const query = searchParams?.query || "";
 //const currentPage = Number(searchParams?.page) || 1;
 const currentPage = 1;
 const totalPages = 1;
 return (
   <div className="h-full bg-gray-800 border-t border-l border-gray-600 p-3">
     <div className="overflow-hidden flex justify-between items-center">
       <h1 className="text-white text-2xl font-bold pb-3">Inventory</h1>
       <div className="flex items-center">
         <div className="ml-auto">
           <div className="flex items-center">
             <button className="bg-slate-500 text-[14px] text-white px-3 py-1 rounded">
               Export
             </button>
             <button className="bg-slate-500 text-[14px] text-white px-3 py-1 rounded ml-2">
               New Model
             </button>
           </div>
         </div>
       </div>
     </div>
     <div className="overflow-hidden">
       <div className="flex justify-around gap-4"></div>
     </div>
     <div className="mt-4 flex items-center justify-between"></div>
     The query is: {query}
     <div className="mt-5 flex w-full justify-center"></div>
   </div>
 );
}
```

I’m still unable to reproduce the issue. The query string parameters are accessible in `searchParams`. Could you provide an MCVE so that we can replicate the issue on our end?

**Comment by huseyinseyit** [comment] 2024-06-18 06:27
Hi, it doesn't make any sense after removing the components. I also add the code of the components;
search.tsx
`'use client';

import { MagnifyingGlassIcon } from '@heroicons/react/24/outline';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { useDebouncedCallback } from 'use-debounce';

export default function Search({ placeholder }: { placeholder: string }) {
  const searchParams = useSearchParams();
  const pathname = usePathname();
  const { replace } = useRouter();


  const handleSearch = useDebouncedCallback((term) => {
    const params = new URLSearchParams(searchParams);
    params.set('page', '1');
    if (term) {
      params.set('query', term);
    } else {
      params.delete('query');
    }
    replace(`${pathname}?${params.toString()}`);
  }, 300);
  return (
    <div className="relative flex flex-1 flex-shrink-0">
      <label htmlFor="search" className="sr-only">
        Search
      </label>
      <input
        className="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
        placeholder={placeholder}
        onChange={(e) => {
          handleSearch(e.target.value);
        }}
        defaultValue={searchParams.get('query')?.toString()}
      />
      <MagnifyingGlassIcon className="absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900" />
    </div>
  );
}
`


`

export default function CardWrapper() {

  return (
    <>
      <Card title="# of All Models" value="1380" circleColor="bg-cyan-500" />
      <Card title="High Risk" value="150" circleColor="bg-red-700" />
      <Card title="Medium Risk" value="380" circleColor="bg-orange-500" />
      <Card title="Ready for Review" value="10" circleColor="bg-teal-500" />
      <Card title="Returned" value="140" circleColor="bg-slate-500" />
    </>
  );
}

export function Card({
  title,
  value,
  circleColor,
}: {
  title: string;
  value: number | string;
  circleColor: string;
}) {


  return (
    <div className="bg-transparent border border-white rounded-lg flex-grow h-24 p-5 w-60 relative">

      <h4 className="text-white">{title}</h4>
      <p className="text-white text-lg font-bold pt-2">{value}</p>
      <div className="absolute top-0 right-0 mt-2 mr-2">
        <div
          className={`h-6 w-6 rounded-full ${circleColor}`}
        ></div>
      </div>
    </div>
  );
}
`


Also, I wonder why it works on local but not on firebase hosting.

**Comment by chalosalvador** [comment] 2024-07-31 18:04
@huseyinseyit I'm glad you got it working.

Regarding your question, the server is usually available immediately after the deployment is complete, but it may depend on your specific configuration.

I'm going to close this issue since everything seems fine.

**Closed by chalosalvador** 2024-07-31 18:04 UTC
Labels: type: bug, Needs: Attention, integration: web frameworks
