### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS doesn't work on Gitlab CI

### ISSUE THREAD

**Issue by aug70** [firebase/firebase-tools#5650] opened 2023-04-03 15:09 UTC
Similar to https://github.com/firebase/firebase-tools/issues/4971 but this is on Gitlab CI
There's a CICD var defined as "File" which contains the json downloaded from gcloud.
This variable is defined as a file and added to env but auth still fails

### [REQUIRED] Environment info

Gitlab CI, env var GOOGLE_APPLICATION_CREDENTIALS exists as a file, file content is verified.

11.25.2

**firebase-tools:**

Linux Alpine

**Platform:**

Build on GitLab CI with Alpine

### [REQUIRED] Test case
Deploy content to firebase

### [REQUIRED] Steps to reproduce

Run CI job

Run CI job which should authenticate.

### [REQUIRED] Expected behavior

Must authenticate and work.

### [REQUIRED] Actual behavior
Fails to authenticate.

Debug flag is in the commands
$ export NOW=$(date '+%Y-%m-%d %H:%M:%S')
$ cat $GOOGLE_APPLICATION_CREDENTIALS > key.json
$ export GOOGLE_APPLICATION_CREDENTIALS=key.json
$ pwd
/builds/[redacted]/[redacted]
$ firebase --version
11.25.2
$ env
....
GOOGLE_APPLICATION_CREDENTIALS=key.json
....
$ cat key.json
{
  "type": "service_account",
  "project_id": "[redacted]",
  "private_key_id": "[redacted]",
  "private_key": "[redacted]",
  "client_email": "[redacted]",
  "client_id": "[redacted]",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-[redacted].iam.gserviceaccount.com"
}
$ firebase use --debug --non-interactive [redacted]
[2023-04-03T14:39:34.380Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-04-03T14:39:34.382Z] > authorizing via FIREBASE_TOKEN environment variable
⚠  Authenticating with `FIREBASE_TOKEN` is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS`: https://cloud.google.com/docs/authentication/getting-started 
[2023-04-03T14:39:34.388Z] > refreshing access token with scopes: []
[2023-04-03T14:39:34.398Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[2023-04-03T14:39:34.403Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[2023-04-03T14:39:34.846Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[2023-04-03T14:39:34.848Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[2023-04-03T14:39:34.867Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 400
[2023-04-03T14:39:34.868Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[2023-04-03T14:39:34.871Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/[redacted] [none]
[2023-04-03T14:39:35.107Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/[redacted] 401
[2023-04-03T14:39:35.108Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/[redacted] {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}
[2023-04-03T14:39:35.111Z] HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
Error: Invalid project selection, please verify project [redacted] exists and you have access.

**Comment by FabienDeborde** [comment] 2023-04-07 16:34
No idea if this can help, but I had a similar problem using CLI on localhost, and putting the file path inside quotes seemed to solve the issue. 
(`GOOGLE_APPLICATION_CREDENTIALS=path/to/file.json` => `GOOGLE_APPLICATION_CREDENTIALS="path/to/file.json"`)

**Comment by aug70** [comment] 2023-04-08 02:21
Thanks @FabienDeborde just to rule it out, I tried it as you suggested, it still fails. May be you had spaces or other characters that needed escaping on your path but I don't have anything special.

**Comment by savelyevdm** [comment] 2023-04-14 17:33
Same issue happened to me.

**Comment by p8952** [comment] 2023-04-17 16:51
We have this same issue with [firebase-admin-node](https://github.com/firebase/firebase-admin-node), so it seems to be a general issue.

Previously this code worked:
```
process.env.GOOGLE_APPLICATION_CREDENTIALS =
  "./gcp-service-account-staging.json";

import Firebase from "firebase-admin";

Firebase.initializeApp();

Promise.resolve().then(() => {
  return Firebase.firestore()
    .collection("usersPublic")
    .get()
    .then((querySnapshot) => {
      querySnapshot.docs.forEach((documentSnapshot) => {
        console.log(documentSnapshot.id);
      });
    });
});
```

Using the private key generated from:
```
https://console.firebase.google.com/project/<FirebaseProjectId>/settings/serviceaccounts/adminsdk
```

However we now get this error:

```
{
  code: 16,
  details: 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.',
  metadata: Metadata {
    internalRepr: Map(3) {
      'google.rpc.errorinfo-bin' => [
        Buffer(125) [Uint8Array] [
           10,  20,  65,  67,  67,  69,  83,  83,  95,  84,  79,  75,
           69,  78,  95,  69,  88,  80,  73,  82,  69,  68,  18,  14,
          103, 111, 111, 103, 108, 101,  97, 112, 105, 115,  46,  99,
          111, 109,  26,  35,  10,   7, 115, 101, 114, 118, 105,  99,
          101,  18,  24, 102, 105, 114, 101, 115, 116, 111, 114, 101,
           46, 103, 111, 111, 103, 108, 101,  97, 112, 105, 115,  46,
           99, 111, 109,  26,  48,  10,   6, 109, 101, 116, 104, 111,
          100,  18,  38, 103, 111, 111, 103, 108, 101,  46, 102, 105,
          114, 101, 115, 116,
          ... 25 more items
        ]
      ],
      'grpc-status-details-bin' => [
        Buffer(385) [Uint8Array] [
            8,  16,  18, 208,   1,  82, 101, 113, 117, 101, 115, 116,
           32, 104,  97, 100,  32, 105, 110, 118,  97, 108, 105, 100,
           32,  97, 117, 116, 104, 101, 110, 116, 105,  99,  97, 116,
          105, 111, 110,  32,  99, 114, 101, 100, 101, 110, 116, 105,
           97, 108, 115,  46,  32,  69, 120, 112, 101,  99, 116, 101,
          100,  32,  79,  65, 117, 116, 104,  32,  50,  32,  97,  99,
           99, 101, 115, 115,  32, 116, 111, 107, 101, 110,  44,  32,
          108, 111, 103, 105, 110,  32,  99, 111, 111, 107, 105, 101,
           32, 111, 114,  32,
          ... 285 more items
        ]
      ],
      'www-authenticate' => [ 'Bearer realm="https://accounts.google.com/"' ]
    },
    options: {}
  },
  statusDetails: [
    ErrorInfo {
      metadata: {
        service: 'firestore.googleapis.com',
        method: 'google.firestore.v1.Firestore.RunQuery'
      },
      reason: 'ACCESS_TOKEN_EXPIRED',
      domain: 'googleapis.com'
    }
  ],
  reason: 'ACCESS_TOKEN_EXPIRED',
  domain: 'googleapis.com',
  errorInfoMetadata: {
    service: 'firestore.googleapis.com',
    method: 'google.firestore.v1.Firestore.RunQuery'
  }
}
```

This error persists even when generating a new private key, so I don't believe the error message stating `ACCESS_TOKEN_EXPIRED` is accurate.

**Comment by godinhojoao** [comment] 2023-04-28 11:03
+1

**Comment by joehan** [comment] 2023-05-02 18:08
Hey all, sorry for the confusion here. The original issue seems to have been caused by accidentally having the FIREBASE_TOKEN env var set when running commands. When set, FIREBASE_TOKEN is used instead of GOOGLE_APPLICATION_CREDENTIALS, so the solution here is to `unset FIREBASE_TOKEN`.

It seems like the issue @p8952 is likely a different issue that lead to the same error message - if you are facing this same issue with firebase-admin-node, please move discussion to https://github.com/firebase/firebase-admin-node/issues/2153

Closing this since the original issue is WAI.

**Closed by joehan** 2023-05-02 18:08 UTC
Labels: type: bug, api: core

**Comment by aug70** [comment] 2023-05-03 01:13
Weird. But it worked.
