### ISSUE TITLE
Issue with Firebase CLI login session

### ISSUE THREAD

**Issue by orthinkzai** [firebase/firebase-tools#6727] opened 2024-01-30 08:34 UTC
cli version: 13.1.0
os: MacOs 14.1 (m3)
login method: Google sign in

It seems that the Firebase CLI login session is resetting after a day or two. When attempting to deploy, I encounter the following error:

"Error: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie, or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."

As a result, I need to re-authenticate with `firebase login --reauth` and then through the website, entering my password and granting Firebase CLI access to my Google Account repeatedly every few days.

**Comment by orthinkzai** [comment] 2024-01-30 12:46
actually yes, my account is under google workspace, will check that out thanks!

**Comment by aalej** [comment] 2024-01-31 13:35
Hey @orthinkzai, I’m going to close this issue for now as a duplicate of #1846. However, if you think that the cause of this issue may be different, feel free to ask this to be reopened and share the contents of your `firebase-debug.log` file so that we can further investigate this.

**Closed by aalej** 2024-01-31 13:35 UTC
Labels: type: bug, api: core, Needs: Attention
