### ISSUE TITLE
Deploy function without deleting older functions?

### ISSUE THREAD

**Issue by fvcaputo** [firebase/firebase-tools#1156] opened 2019-02-22 17:26 UTC
When deploying functions I noticed there is a flag `--force` that will delete functions if they are not on the source code.

However I want to know if there is a way to do the opposite? Without going to the interactive mode, is there a way that I can run the deploy command and **do not** delete the functions that are not present anymore?

**Comment by bkendall** [comment] 2019-02-22 17:48
Duplicate of #999

The current way of doing this is to use the `--only` flag to list all the functions you want deployed (along with the `--non-interactive` flag). e.g. `firebase deploy --only functions:foo,functions:bar`

**Closed by bkendall** 2019-02-22 17:48 UTC
Labels: feature request
