### ISSUE TITLE
request.body empty in emulator when using hosting rewrite to target a function

### ISSUE THREAD

**Issue by tomknappramos** [firebase/firebase-tools#2914] opened 2020-12-09 11:39 UTC
### Environment info

**firebase-tools:** 8.18.0

**Platform:**
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Test case

request
```
POST http://localhost:5000/api/hello
{
    "value": 12345,
    "hello": "world"
}
```

firebase.json
```json
    "rewrites": [
      { "source": "/api/**", "function": "api" },
      { "source": "**", "destination": "/index.html" }
    ]
```

code
```js
exports.api = functions.https.onRequest(async (request, response) => {
  console.log('request.rawBody:');
  console.log(request.rawBody);

  console.log('request.body:');
  console.log(request.body);

  response.send('hello');
});
```

### Steps to reproduce

Setup a hosting rewrite to a function, call the function via the hosting rewrite url with a request body.

### Expected behavior

To see request.body.

### Actual behavior

```
[hosting] Rewriting /api/hello to http://localhost:5001/id/us-central1/api for local Function api
i  functions: Beginning execution of "api"
>  request.rawBody:
>  undefined
>  request.body:
>  {}
```

### NOTE: 

The body exists when I don't use the rewrite and directly call http://localhost:5001/id/us-central1/api/hello.

Also, when I use v8.16.2, the body seems to parsed just fine...
```
[hosting] Rewriting /api/hello to http://localhost:5001/id/us-central1/api for local Function api
i  functions: Beginning execution of "api"
>  request.rawBody:
>  <Buffer 7b 0a 20 20 20 20 22 76 61 6c 75 65 22 3a 20 31 32 33 34 35 2c 0a 20 20 20 20 22 68 65 6c 6c 6f 22 3a 20 22 77 6f 72 6c 64 22 0a 7d 0a>
>  request.body:
>  { value: 12345, hello: 'world' }
```

**Comment by tomknappramos** [comment] 2020-12-09 11:47
updated test case

**Comment by samtstern** [comment] 2020-12-09 12:12
@tomknappramos thank you for the clear report
@bkendall this feels like a bug to me, and maybe something you could fix while you're already working on https://github.com/firebase/firebase-tools/pull/2912

**Comment by BrandiATMuhkuh** [comment] 2020-12-09 20:10
I have the same issue. I think it's from the last release. But the relase of the cloud function. Because I have the same issue when deploying to the google servers. Not only on the emulator :/

**Comment by BrandiATMuhkuh** [comment] 2020-12-09 20:13
@samtstern I also think it's the header issue. I'm using `express.json()` and that relies on the `application/json` header to be sent. If it's not sent, it won't populate the `req.body`

**Comment by tomknappramos** [comment] 2020-12-09 23:09
@BrandiATMuhkuh This is just a guess, but it seemed like the hosting emulator perhaps wasn't forwarding the headers to the function emulator properly??

I had the application/json header in Postman, so the header was there. Just seemed not to make it through.

**Comment by bkendall** [comment] 2020-12-10 00:09
Could you give newly released `v8.18.1` a try? That fixed up the headers issue and if _that_ is the root cause of this missing body information, then you should be good to go. If not, I'll dig a bit more.

**Comment by BrandiATMuhkuh** [comment] 2020-12-10 07:05
@bkendall I can confirm it's fixed with `v8.18.1`. Thanks for the quick fix!

**Comment by samtstern** [comment] 2020-12-10 08:49
@BrandiATMuhkuh thank you!

**Closed by samtstern** 2020-12-10 08:49 UTC
Labels: type: bug

**Comment by CTOverton** [comment] 2022-06-10 06:19
Running into a similar issue but I can't seem to get clarification. In my case I'm using a `GET` request. 
> (yes I know it's not ideal to use body with `GET`, but I'm just trying to figure out if firebase is simply not allowing it at all)

Wierd thing is, running the local cloud functions emulator all requests work fine and body exists, but in production the body is not.
