### ISSUE TITLE
getServersideprops in nextjs project gives 500:Internal Server error when deployed.

### ISSUE THREAD

**Issue by manastelavane** [firebase/firebase-tools#5919] opened 2023-06-01 05:27 UTC
Hey, When I deployed my nextJs website to firebase hosting, it deployed successfully, but on the deployed URL , I am getting 500:Internal Server Error. When this website just contained static pages, it deployed successfully and I was able to view pages on deployed link. But adding getServerSideProps to code gave 500:Internal Server Error. Also, when I deployed the same code on Vercel, it deployed successfully(which shows there is no error in my code). Also, the code works perfectly locally. My project is under blaze plan of firebase.

### [REQUIRED] Environment info

**firebase-tools:** 12.1.0

**Platform:** Ubuntu 22.04

**NextJs:** 13.4.1

### [REQUIRED] Test case

In a Next.js project, I have this file src/pages/auth/sign-up.tsx:
```
import { GetServerSideProps, GetServerSidePropsContext } from 'next';
import SignUpPage from 'src/components/pages/SignUpPage/SignUpPage';
import { checkSSRTokenAndRedirect } from 'src/utils/auth-redirect';

export const getServerSideProps: GetServerSideProps<{}> = async (
  context: GetServerSidePropsContext
) => {
  return checkSSRTokenAndRedirect({ context,  });
};

export default function SignUp() {
  return <SignUpPage />;
}
```
### [REQUIRED] Steps to reproduce

- npx create-next-app@latest
- firebase init –  Next.js project was detected and confirmed
- firebase deploy
- Link of website: https://possible-fabric-320701.web.app/auth/sign-up

### [REQUIRED] Expected behavior

- Fetch data and display it

### [REQUIRED] Actual behavior

- Internal Server Error
- 
![image](https://github.com/firebase/firebase-tools/assets/82931004/f24d3517-345f-4f3d-b4e2-22adec55baa1)

![image](https://github.com/firebase/firebase-tools/assets/82931004/ed3fac60-4341-4494-aefb-d5a67cea4c78)

More info about package.json , firebase.json, .firebaserc can be found here:
https://stackoverflow.com/questions/76358018/nextjs-website-deployed-but-i-cannot-see-anything-on-website

**Comment by looptheloop88** [comment] 2023-06-01 07:17
Hi @manastelavane, thanks for the report. There’s already an issue filed with similar error encountered after adding getServersideprops in pages or routes, so I will close this issue and mark as a duplicate of #5915.

This issue is reproducible and has already been brought to the attention of our engineers. Please keep an eye out on the first issue to get updates.

**Closed by looptheloop88** 2023-06-01 07:17 UTC
Labels: type: bug
