### ISSUE TITLE
A kind ofproblem??

### ISSUE THREAD

**Issue by parshuXX** [firebase/firebase-tools#5427] opened 2023-01-15 07:21 UTC
C:\Users\user>curl -sL https://firebase.tools | bash
/usr/bin/bash: line 160: sudo: command not found
-- Checking for existing firebase-tools on PATH...
which: no firebase in (/mingw64/bin:/usr/bin:/c/Users/user/bin:/c/Python311/Scripts:/c/Python311:/c/Program Files/Common Files/Oracle/Java/javapath:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Users/user/AppData/Local/Android/Sdk/platforms/android-33:/c/Users/user/AppData/Local/Android/Sdk/platform-tools:/cmd:/c/Program Files/PuTTY:/c/Program Files/nodejs:/c/ProgramData/chocolatey/bin:/c/Users/user/AppData/Local/Microsoft/WindowsApps:/c/Users/user/AppData/Local/Programs/Microsoft VS Code/bin:/c/Flutter/flutter/bin:/c/Users/user/AppData/Local/Android/Sdk:/c/Users/user/AppData/Local/Android/Sdk/platform-tools:/bin:/c/Program Files/Java/jre1.8.0_351/bin:/c/Program Files/Java/jdk-19/bin:/c/Users/user/AppData/Local/Pub/Cache/bin:/c/a:/c/Users/user/AppData/Roaming/npm)
-- Checking your machine type...
Your operating system is not supported, if you think it should be please file a bug.
https://github.com/firebase/firebase-tools/
-- All done!

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment] 2023-01-16 12:29
Hi @parshuXX, I understand that you’re having an issue with installing the Firebase CLI. It would be more helpful if you could specify other details using the provided template in a new ticket. This way, it would be more efficient in identifying the cause of the issue. 

Also, since it looks like you’re using a Windows machine, could you try following this [documentation](https://firebase.google.com/docs/cli#install-cli-windows). This is because the command `curl -sL https://firebase.tools | bash` seems to be for [macOS and Linux](https://firebase.google.com/docs/cli#install-cli-mac-linux) machines.

That being said, I'll be closing this for now.

**Closed by aalej** 2023-01-16 12:29 UTC
Labels: bug
