### ISSUE TITLE
Documentation: debug() function for Firestore emulator

### ISSUE THREAD

**Issue by gaeldestrem** [firebase/firebase-tools#1166] opened 2019-03-12 15:38 UTC
According your changelog, you have introduced a debug(...) function for the firestore emulator in the v6.14.0 but we couldn't find any documentation for it.

![image](https://user-images.githubusercontent.com/5053593/54213211-558c4880-44e4-11e9-8155-64e3a72a1c60.png)

Can you help us on how to use it?

**Comment by ryanpbrewster** [comment] 2019-03-12 16:03
Ah, very perceptive :smile:. Keeping in mind that this feature is not yet well-documented:

When running the Firestore emulator, you can use the `debug(...)` function in your security rules to cause the emulator to print out the value passed into the function. So for example:

```
service cloud.firestore {
  match /databases/{db}/documents {
    match /{doc=**} {
      allow read, write: if debug(request.auth) != null;
    }
  }
}
```

will allow any request from an authenticated user, and will additionally print out the value of `request.auth` (to stdout in whatever terminal you're running the emulator from).

**Comment by mpppk** [comment] 2019-11-27 07:00
In firestore emulator v1.10.2, the emulator seems to only output the debug log to the `firestore.log`, not stdout.

**Comment by ryanpbrewster** [comment] 2019-11-27 19:25
In this case I'm assuming you're running the Firestore emulator via
```
firebase emulators:start --only firestore
```
or something like it. This "wrapper" command starts up the Firestore emulator and routes its stdout into the local `firestore-debug.log` file.

**Comment by akauppi** [comment] 2020-08-27 18:45
I'd find the `debug()` useful, especially if it prints to `stdout`.

**Comment by yuchenshi** [comment] 2020-08-27 21:43
Somehow we forgot to close this issue, but `debug()` was supported since the OP, and we've documented it as well at https://firebase.google.com/docs/reference/rules/rules.debug . Cheers!

**Closed by yuchenshi** 2020-08-27 21:43 UTC

**Comment by M3kH** [comment] 2021-01-10 01:15
I'm currently trying to use the `debug` function within the emulator but doesn't seem to output any result on `firestore-debug.log`. Any direction on how I can get that working?

**Comment by tojacob** [comment] 2021-04-20 22:57
> I'm currently trying to use the `debug` function within the emulator but doesn't seem to output any result on `firestore-debug.log`. Any direction on how I can get that working?

Estoy igual... Lo resolviste?

**Comment by kiptoomm** [comment] 2021-05-22 08:57
> Somehow we forgot to close this issue, but `debug()` was supported since the OP, and we've documented it as well at https://firebase.google.com/docs/reference/rules/rules.debug . Cheers!

The page you linked doesn't show how to 'import' the debug function. I'm trying to use it and getting `ERROR Unexpected 'debug'`. Is this function not available as a context variable, or how should we import it?

**Comment by yuchenshi** [comment] 2021-05-24 17:21
@kiptoomm There is no need to import it -- you would just use that as if it were a global function (inside Firestore service). Your error sounds like a specific compilation error in your rules and I'd suggest reaching out to Firebase Support where you can share your rules privately and get help.

**Comment by carboni-rob** [comment] 2021-09-18 09:10
I can confirm I am not getting anything logged in my `firestore-debug.log` from the following ruleset:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /users/{userId} {
      allow read, write: if
      debug(
        debug(request.auth.uid) == debug(userId)
      );
    }
  }
}
```

**Comment by pedrofsantoscom** [comment] 2021-11-11 10:04
I'm also not getting the output from `debug()` on stdout or `firestore-debug.log`
