### ISSUE TITLE
Namespaced functions not working with "firebase serve --only functions"

### ISSUE THREAD

**Issue by SamyPesse** [firebase/firebase-tools#402] opened 2017-07-19 10:07 UTC
Our application is using namespaced functions:

```js
module.exports = {
    something: {
        aCloudFunctions
    },
    github: {
        onWebhook
    }
}
```

`github.onWebhook` is an HTTP cloud function.

It works well once deployed in production, but when testing locally using `firebase serve --only functions`, it crash with:

```
/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/supervisor/worker.js:68
      throw new Error(`No function found with name ${cloudfunction.entryPoint || name}`);
      ^

Error: No function found with name github-onWebhook
```

**Comment by laurenzlong** [comment] 2017-10-04 18:47
Duplicate of https://github.com/firebase/firebase-tools/issues/481

**Closed by laurenzlong** 2017-10-04 18:47 UTC
