### ISSUE TITLE
database:get broken from v8.15.1 and onwards

### ISSUE THREAD

**Issue by BrandiATMuhkuh** [firebase/firebase-tools#2822] opened 2020-11-15 07:57 UTC
### [REQUIRED] Environment info

**firebase-tools:** 8.15.1

**Platform:** windows

### [REQUIRED] Test case
`yarn firebase database:get -o data.json  /` provides no `data.json` given version is `"v8.15.1"`

### [REQUIRED] Steps to reproduce

- broken Case
   - Set `"firebase-tools": "v8.15.1"` in your `package.json`
   - Run `yarn firebase database:get -o data.json  /`
- Working case
   - Set `"firebase-tools": "v8.15.0"` in your `package.json`
   - Run `yarn firebase database:get -o data.json  /`

### [REQUIRED] Expected behavior
Seeing a `data.json` file. 

### [REQUIRED] Actual behavior
No `data.json` file

**Comment by bkendall** [comment] 2020-11-16 17:27
I'm unable to replicate this with either `firebase-tools@v8.15.1` installed globally or with `scripts.firebase: "firebase"` in my `package.json` and running `yarn firebase ...`.

Can you please run the command with the debug flag and provide the debug output? Also, what node version are you using?

**Comment by BrandiATMuhkuh** [comment] 2020-11-19 13:23
I tested it again. It's exactly `v8.15.1` and above that causes the issue. 
My `node` version is `v15.2.0` and my yarn version is `1.22.4`. Also I'm using windows 10 with all updated installed.

**Comment by bkendall** [comment] 2020-11-19 16:59
I think this actually has the same root cause as #2819. I'll work with @sarajmunjal to figure out what needs to change.

**Comment by BrandiATMuhkuh** [comment] 2020-11-25 10:27
From what I can "see". It seems like the data get's downloaded, but not retured to `stdout`. Looking at my network consumtion, it's clear a download happens. So i'm not sure if it's connected to https://github.com/firebase/firebase-tools/issues/2819

**Comment by nico75005** [comment] 2020-11-29 05:26
It doesn't work with my outdated 8.11.0 version.
Doing a 
```
firebase --project my_project database:get /myParentNode/myChildNode --export -o "to_my_computer_path.json"
```
seems to download randomly a certain amount of data. Doing it directly from the console, the file I'm looking for is about 40MB. When I use `database:get` I get different sizes for every try, usually a few hundred KB at max.

Any news on that end?

**Comment by bkendall** [comment] 2020-12-04 00:15
This should be fixed in https://github.com/firebase/firebase-tools/releases/tag/v8.17.0

Thanks

**Closed by bkendall** 2020-12-04 00:15 UTC
Labels: Needs: Attention, api: database, type: bug

**Comment by BrandiATMuhkuh** [comment] 2020-12-04 10:42
Thanks you. I have tested it, and it works again as expected!
