### ISSUE TITLE
win10 Firebase CLI: worked but now fails on startup

### ISSUE THREAD

**Issue by GavinBrelstaff** [firebase/firebase-tools#1826] opened 2019-11-21 10:35 UTC
### [REQUIRED] Environment info

The version command crashes: but either 
7.80 or 7.81

Windows 10 Pro
Version	10.0.18362 Build 18362

### [REQUIRED] Test case
As first reported here: https://groups.google.com/d/msg/firebase-talk/DxXrj3oHTmw/ejKBG0IEBwAJ
Everything worked fine for months 
until a recent update of either Firebase or npm 
done as instructed within the CLI's message of the day text.

I update to v.7.80 (or perhaps v7.81)  and to the latest npm and then open the Firebase CLI shell by double clicking the Windows desktop shortcut with **target:** C:\Users\username\Desktop\firebase-cli.exe with the **Start in:** C:\Users\username\mysitedir

### [REQUIRED] Steps to reproduce

Step: open the Firebase CLI shell and wait

### [REQUIRED] Expected behavior

The terminal prompt eventually appears **without** error messages

### [REQUIRED] Actual behavior

The terminal prompt appears **with** error messages
`
################################################################################

     Welcome to...
     ######## #### ########  ######## ########     ###     ######  ########  ##
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##        ##
     ######    ##  ########  ######   ########  #########  ######  ######    ##
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########  ##

################################################################################

~ Let's make sure your Firebase CLI is ready...
 + Looks like your CLI is set up.!

~ Checking your Firebase credentialsundefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.listSpawn.on (C:\snapshot\firepit\welcome.js: 100:31)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:595:12)

>`

**Comment by GavinBrelstaff** [comment] 2019-11-21 17:46
Rolling back fixes the issue:
npm install -g firebase-tools@7.7.0

so it is an upgrade problem - probably mangling the credentials access

**Comment by samtstern** [comment] 2019-11-21 17:58
@abeisgoat sounds like it's a Firepit-specific issue with the latest release?

**Comment by abeisgoat** [comment] 2019-11-25 19:17
Yeah looks like an issue with the response format from the CLI, will take a look

**Comment by alrowaihi** [comment] 2020-01-03 20:29
hey @abeisgoat , according to your question , yes both builds ( firebase-tools-win.exe and -instant ) failed to start , and actually I started running -instant , when I failed to get it work , I downloaded the other one which behaved the same

**Comment by abeisgoat** [comment] 2020-01-03 20:41
Okay, thanks for the quick reply, I think this is actually a dupe of #1796 so let's handle it over there :)

**Closed by abeisgoat** 2020-01-03 20:41 UTC
Labels: firepit
