### ISSUE TITLE
[Regression] Latest firebase-tools release breaks deploy --only firestore:indexes / --only firestore:rules

### ISSUE THREAD

**Issue by erno** [firebase/firebase-tools#4711] opened 2022-07-06 12:13 UTC
The docs still say these are valid (eg https://firebase.google.com/docs/firestore/query-data/indexing).

But now they yield error messages saying "Error: Filters specified with colons (e.g. --only functions:func1,functions:func2) are only supported for functions and hosting".

The regression seems to have been introduced in https://github.com/firebase/firebase-tools/pull/4666

A working workaround for us was pinning firebase-tools to the previous release (npm install -g firebase-tools@11.1.0) in our CI.

**Comment by dereekb** [comment] 2022-07-07 21:01
Ran into the same thing on my CI:

https://app.circleci.com/pipelines/github/dereekb/dbx-components/1256/workflows/63e94a13-63d9-413d-ab6b-d2051f6436f2/jobs/3363/parallel-runs/0/steps/0-104

**Comment by bkendall** [comment] 2022-07-08 14:14
Duplicate #4698

**Comment by bkendall** [comment] 2022-07-08 14:14
Duplicate of #4698

**Closed** 2022-07-11 20:13 UTC
Labels: bug
