### ISSUE TITLE
Firebase Auth Emulator is missing tenant-related endpoints

### ISSUE THREAD

**Issue by jakebiesinger-storyhealth** [firebase/firebase-tools#3366] opened 2021-05-13 22:41 UTC
* Operating System version: Mac OS 11.2.3
  * Firebase SDK version: 9.10.2
  * Firebase Product: auth
  * Node.js version: 12.21.0
  * NPM version: 7.7.0

#### Steps to reproduce:

While running the Firebase Auth Emulator, all tenant-related admin endpoints are broken, yielding 404's.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

// run-tests.sh
```
FIREBASE_AUTH_EMULATOR_HOST="localhost:9099" firebase -P dev emulators:exec --only firestore,auth "jest --rootDir . "
```

// some.test.ts

```

// Boilerplate for getting the test infra ready

import * as testing from '@firebase/rules-unit-testing';
import { default as testAdmin } from 'firebase-functions-test';

const PROJECT_ID = process.env.GCLOUD_PROJECT!;
let testApp: ReturnType<typeof testing.initializeAdminApp>;
let test: ReturnType<typeof testAdmin>;

const setupMocksAndApps = () => {
    jest.clearAllMocks();

    testApp = testing.initializeAdminApp({ projectId: PROJECT_ID });
    test = testAdmin({
        projectId: PROJECT_ID,
    });

    jest.doMock('../external/clients', () => ({
        db: testApp.firestore(),
    }));
};

setupMocksAndApps();


import * as admin from 'firebase-admin';

admin.initializeApp({ projectId: PROJECT_ID });

beforeEach(async () => {
    setupMocksAndApps();

    await testing.clearFirestoreData({
        projectId: PROJECT_ID,
    });
});

afterEach(async () => {
    await Promise.all(testing.apps().map((app) => app.delete()));
    await test.cleanup();
});


describe('tenants', () => {
  it('fails on all tenant stuff', () => {
    
    const users = await admin.auth().listUsers();  // Works fine
    
    console.log(admin.auth().tenantManager()); // Works fine. Output below.

    console.log(JSON.stringify(await admin.auth().tenantManager().listTenants()));   // Fails with     An internal error has occurred. Raw server response: "{"error":{"code":404,"message":"Not Found","errors":[{"message":"Not Fo
und","reason":"notFound"}],"status":"NOT_FOUND"}}"

    // Also fails with the same 404 error.
    await admin
            .auth()
            .tenantManager()
            .createTenant({
                anonymousSignInEnabled: false,
                displayName: 'fakeTenant',
                emailSignInConfig: { enabled: true, passwordRequired: true },
                multiFactorConfig: { state: 'ENABLED', factorIds: ['phone'] },
            });

  });
});

```

The TenantManager JSON is as follows:

```
    TenantManager {             
      app: FirebaseApp {                                                                                                         
        firebaseInternals_: FirebaseNamespaceInternals {    
          firebase_: [FirebaseNamespace],
          apps_: [Object]                                                                                                        
        }, 
        services_: { auth: [Auth] },
        isDeleted_: false,
        name_: '[DEFAULT]',                                                                                                      
        options_: {                                             
          projectId: 'someProject',                          
          credential: [ComputeEngineCredential]                                                                                  
        },                                                                                                                       
        INTERNAL: FirebaseAppInternals {                                                                                         
          credential_: [ComputeEngineCredential],
          tokenListeners_: []                                                                                                    
        }                                                       
      },                                                        
      authRequestHandler: AuthRequestHandler {                                                                                   
        app: FirebaseApp {                                      
          firebaseInternals_: [FirebaseNamespaceInternals],     
          services_: [Object],
          isDeleted_: false,                                                                                                     
          name_: '[DEFAULT]',                                                                                                    
          options_: [Object],
          INTERNAL: [FirebaseAppInternals]                                                                                       
        },                                                                                                                       
        httpClient: AuthHttpClient { retry: [Object], app: [FirebaseApp] },                                                      
        tenantMgmtResourceBuilder: AuthResourceUrlBuilder {
          app: [FirebaseApp],                                                                                                    
          version: 'v2',                                                                                                         
          urlFormat: 'http://localhost:9099/identitytoolkit.googleapis.com/{version}/projects/{projectId}{api}'                  
        }                 
      },                                                        
      tenantsMap: {}                                                                                                             
    }         
```

**Comment by vladfaust** [comment] 2021-08-01 07:19
Just letting you know that my team needs that as well for local development of a multi-tenant application. For now, we're launching a separate set of emulators for a tenant; which is far from ideal

**Comment by emanuele-scarsella** [comment] 2023-07-15 16:08
This issues makes local development of multi-tenant applications impractical and my team needs it for a project we're developing, we're going to put it aside and develop the application without multi-tenancy in the hope of implementing it before production as soon as this gets fixed.

**Comment by DibyodyutiMondal** [comment] 2023-07-19 02:39
@emanuele-scarsella Out of curiosity, does the problem still exist on the latest version? This post was posted 2 years ago, and I was forced to take another (very long and convoluted) direction to implement multi-tenancy, and I forgot about this issue.

**Comment by emanuele-scarsella** [comment] 2023-07-19 16:06
@DibyodyutiMondal Thank you for pointing out to me how old this question is, I was making some preliminary research after I read online that multi-tenancy was not supported by the emulator suit and when I saw the issue still open I assumed it was still the case... anyway I've made a quick test and I can confirm it's now fixed.
Maybe it's now time to close this issue, thank you again.

**Comment by christhompsongoogle** [comment] 2023-07-19 18:27
Thank you both, I assumed this had not been implemented yet. After some investigation it looks like Lisa implemented the endpoints in https://github.com/firebase/firebase-tools/pull/3777

**Closed by christhompsongoogle** 2023-07-19 18:27 UTC
Labels: type: feature request, emulator-suite, emulators: auth
