### ISSUE TITLE
Fatal error occurs when importing on a mac from an export created on windows machine

### ISSUE THREAD

**Issue by TylerJGabb** [firebase/firebase-tools#2650] opened 2020-09-28 15:58 UTC
### [REQUIRED] Environment info

**firebase-tools:**
On the Mac machine: `8.7.0`
On the Windows machine: `8.9.2`

**Platform:**
Export created on Windows
Export import attempted on Mac
### [REQUIRED] Steps to reproduce

1. Download the attached zip file [test.zip](https://github.com/firebase/firebase-tools/files/5293499/test.zip) that contains an export created from a windows machine, containing one firestore collection named test, with one document.
**OR**
Create an export on a windows machine, with one collection, and one document in said collection. 
2. On a Darwin machine, attempt to import this exported data
`firebase emulators:start --import ./test` **OR** `firebase emulators:start --import ${your_export_folder_name}`

### [REQUIRED] Expected behavior

Firebase emulators should load and start successfully

### [REQUIRED] Actual behavior
Fails to start, crashes with fatal error (code 1), with following exception printed in debug logs:
<pre>
Exception in thread "main" com.google.cloud.datastore.core.exception.DatastoreException: /Users/tylergabb/git/pilot-pay/test/firestore_export/all_namespaces\all_kinds\all_namespaces_all_kinds.export_metadata (No such file or directory)
	at com.google.cloud.datastore.emulator.impl.ExportImportUtil.parseBackupFile(ExportImportUtil.java:316)
	at com.google.cloud.datastore.emulator.impl.ExportImportUtil.fetchEntities(ExportImportUtil.java:62)
	at com.google.cloud.datastore.emulator.firestore.CloudFirestore.main(CloudFirestore.java:89)
Caused by: java.io.FileNotFoundException: /Users/tylergabb/git/pilot-pay/test/firestore_export/all_namespaces\all_kinds\all_namespaces_all_kinds.export_metadata (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)
	at com.google.cloud.datastore.emulator.impl.ExportImportUtil.parseBackupFile(ExportImportUtil.java:312)
	... 2 more

</pre>

<pre>[2020-09-28T15:46:31.216Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-09-28T15:46:31.217Z] > authorizing via signed-in user
i  emulators: Starting emulators: functions, firestore, hosting {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: functions, firestore, hosting"}}
[2020-09-28T15:46:31.232Z] [hub] writing locator at /var/folders/t9/p6h23vlj56g_34fc2md0p4440000gn/T/hub-pilot-pay.json
[2020-09-28T15:46:31.253Z] defaultcredentials: writing to file /Users/tylergabb/.config/firebase/tylerjgabb_gmail_com_application_default_credentials.json
[2020-09-28T15:46:31.255Z] Setting GAC to /Users/tylergabb/.config/firebase/tylerjgabb_gmail_com_application_default_credentials.json {"metadata":{"emulator":{"name":"functions"},"message":"Setting GAC to /Users/tylergabb/.config/firebase/tylerjgabb_gmail_com_application_default_credentials.json"}}
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: database, pubsub {"metadata":{"emulator":{"name":"functions"},"message":"The following emulators are not running, calls to these services from the Functions emulator will affect production: \u001b[1mdatabase, pubsub\u001b[22m"}}
⚠  Your requested "node" version "10" doesn't match your global version "12" {"metadata":{"emulator":{"name":"functions"},"message":"Your requested \"node\" version \"10\" doesn't match your global version \"12\""}}
i  firestore: Importing data from /Users/tylergabb/git/pilot-pay/test/firestore_export/firestore_export.overall_export_metadata {"metadata":{"emulator":{"name":"firestore"},"message":"Importing data from /Users/tylergabb/git/pilot-pay/test/firestore_export/firestore_export.overall_export_metadata"}}
[2020-09-28T15:46:31.270Z] Ignoring unsupported arg: projectId {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: projectId"}}
[2020-09-28T15:46:31.271Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: auto_download"}}
[2020-09-28T15:46:31.271Z] Starting Firestore Emulator with command {"binary":"java","args":["-Duser.language=en","-jar","/Users/tylergabb/.cache/firebase/emulators/cloud-firestore-emulator-v1.11.5.jar","--host","localhost","--port",8080,"--seed_from_export","/Users/tylergabb/git/pilot-pay/test/firestore_export/firestore_export.overall_export_metadata","--rules","/Users/tylergabb/git/pilot-pay/firestore.rules","--functions_emulator","localhost:5001"],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator","seed_from_export"],"joinArgs":false} {"metadata":{"emulator":{"name":"firestore"},"message":"Starting Firestore Emulator with command {\"binary\":\"java\",\"args\":[\"-Duser.language=en\",\"-jar\",\"/Users/tylergabb/.cache/firebase/emulators/cloud-firestore-emulator-v1.11.5.jar\",\"--host\",\"localhost\",\"--port\",8080,\"--seed_from_export\",\"/Users/tylergabb/git/pilot-pay/test/firestore_export/firestore_export.overall_export_metadata\",\"--rules\",\"/Users/tylergabb/git/pilot-pay/firestore.rules\",\"--functions_emulator\",\"localhost:5001\"],\"optionalArgs\":[\"port\",\"webchannel_port\",\"host\",\"rules\",\"functions_emulator\",\"seed_from_export\"],\"joinArgs\":false}"}}
i  firestore: Firestore Emulator logging to firestore-debug.log {"metadata":{"emulator":{"name":"firestore"},"message":"Firestore Emulator logging to \u001b[1mfirestore-debug.log\u001b[22m"}}
[2020-09-28T15:46:31.643Z] Exception in thread "main"  {"metadata":{"emulator":{"name":"firestore"},"message":"Exception in thread \"main\" "}}
[2020-09-28T15:46:31.644Z] com.google.cloud.datastore.core.exception.DatastoreException: /Users/tylergabb/git/pilot-pay/test/firestore_export/all_namespaces\all_kinds\all_namespaces_all_kinds.export_metadata (No such file or directory)
	at com.google.cloud.datastore.emulator.impl.ExportImportUtil.parseBackupFile(ExportImportUtil.java:316)
	at com.google.cloud.datastore.emulator.impl.ExportImportUtil.fetchEntities(ExportImportUtil.java:62)
	at com.google.cloud.datastore.emulator.firestore.CloudFirestore.main(CloudFirestore.java:89)
 {"metadata":{"emulator":{"name":"firestore"},"message":"com.google.cloud.datastore.core.exception.DatastoreException: /Users/tylergabb/git/pilot-pay/test/firestore_export/all_namespaces\\all_kinds\\all_namespaces_all_kinds.export_metadata (No such file or directory)\n\tat com.google.cloud.datastore.emulator.impl.ExportImportUtil.parseBackupFile(ExportImportUtil.java:316)\n\tat com.google.cloud.datastore.emulator.impl.ExportImportUtil.fetchEntities(ExportImportUtil.java:62)\n\tat com.google.cloud.datastore.emulator.firestore.CloudFirestore.main(CloudFirestore.java:89)\n"}}
[2020-09-28T15:46:31.644Z] Caused by: java.io.FileNotFoundException: /Users/tylergabb/git/pilot-pay/test/firestore_export/all_namespaces\all_kinds\all_namespaces_all_kinds.export_metadata (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
 {"metadata":{"emulator":{"name":"firestore"},"message":"Caused by: java.io.FileNotFoundException: /Users/tylergabb/git/pilot-pay/test/firestore_export/all_namespaces\\all_kinds\\all_namespaces_all_kinds.export_metadata (No such file or directory)\n\tat java.base/java.io.FileInputStream.open0(Native Method)\n\tat java.base/java.io.FileInputStream.open(FileInputStream.java:212)\n"}}
[2020-09-28T15:46:31.644Z] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)
	at com.google.cloud.datastore.emulator.impl.ExportImportUtil.parseBackupFile(ExportImportUtil.java:312)
	... 2 more
 {"metadata":{"emulator":{"name":"firestore"},"message":"\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)\n\tat com.google.cloud.datastore.emulator.impl.ExportImportUtil.parseBackupFile(ExportImportUtil.java:312)\n\t... 2 more\n"}}
⚠  firestore: Fatal error occurred: 
   Firestore Emulator has exited with code: 1, 
   stopping all running emulators {"metadata":{"emulator":{"name":"firestore"},"message":"Fatal error occurred: \n   Firestore Emulator has exited with code: 1, \n   stopping all running emulators"}}
i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}
i  functions: Stopping Functions Emulator {"metadata":{"emulator":{"name":"functions"},"message":"Stopping Functions Emulator"}}
i  firestore: Stopping Firestore Emulator {"metadata":{"emulator":{"name":"firestore"},"message":"Stopping Firestore Emulator"}}
[2020-09-28T15:46:35.661Z] Firestore Emulator: Unable to terminate process (PID=3835) {"metadata":{"emulator":{"name":"firestore"},"message":"Firestore Emulator: Unable to terminate process (PID=3835)"}}
⚠  firestore: Error stopping Firestore Emulator {"metadata":{"emulator":{"name":"firestore"},"message":"Error stopping Firestore Emulator"}}
</pre>

**Comment by samtstern** [comment] 2020-09-28 16:00
@TylerJGabb thank you for the detailed issue!  This is a duplicate of https://github.com/firebase/firebase-tools/issues/2421, so we can continue discussing there.

**Closed by samtstern** 2020-09-28 16:00 UTC
