### ISSUE TITLE
Stuck Running pod install.. after adding firebase dependencies

### ISSUE THREAD

**Issue by Prateek-Kerketta01** [firebase/firebase-tools#5644] opened 2023-03-31 16:05 UTC
### [REQUIRED] Environment info

**firebase-tools:**11.25.2

**Platform:**macOS

<img width="411" alt="Picture 1" src="https://user-images.githubusercontent.com/123981233/229172259-36f610d3-9652-46df-8c2c-66b7cceed611.png">

**Comment by aalej** [comment] 2023-03-31 16:58
Hi @Prateek-Kerketta01. It looks like you’re having issues related to the FlutterFire SDKs. If you are, I would recommend filling an issue to the [flutterfire repository](https://github.com/firebase/flutterfire/issues). The issue you described looks similar to [#2533](https://github.com/firebase/flutterfire/issues/2533).

However if your issue is not related to FlutterFire, could you file a new ticket providing more details, such as steps to reproduce the issue. This so that we can try to replicate it on our end. That said, I’ll be closing this ticket. Thanks!

**Closed by aalej** 2023-03-31 16:58 UTC
Labels: type: bug
