### ISSUE TITLE
[debug] [2023-06-13T09:25:56.887Z] Error: Unable to find the next dep, try NPM installing?     at getConfig (C:\Users\DELL\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\next\index.js:382:19)     at build (C:\Users\DELL\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\next\index.js:62:65)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     at async prepareFrameworks (C:\Users\DELL\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\index.js:211:33)     at async deploy (C:\Users\DELL\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\index.js:55:13) [error]  [error] Error: An unexpected error has occurred.

### ISSUE THREAD

**Issue by mohitkumar008** [firebase/firebase-tools#5971] opened 2023-06-13 09:26 UTC
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment] 2023-06-13 09:48
Hi @mohitkumar008, could you please file a new issue specifying the details using the provided template. This way, it would be more efficient in identifying the cause of the issue. That being said, I'll be closing this for now.

**Closed as completed by aalej** 2023-06-13 09:48 UTC
Labels: type: bug
