### ISSUE TITLE
Firestore startAfter query doesn't work from the browser with the firestore emulator

### ISSUE THREAD

**Issue by petert37** [firebase/firebase-tools#1706] opened 2019-10-09 15:47 UTC
### [REQUIRED] Environment info

**firebase-tools:** 7.5.0
**@firebase/testing** 0.13.4
**Firestore emulator** cloud-firestore-emulator-v1.9.0.jar

**Platform:** Windows 10

**Java**
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

### [REQUIRED] Test case

The firestore collection **startAfter** query runs for a long time, and then doesn't return a result. This only happens when using the **Firestore Emulator** and when the firestore client is running in the **browser**. Running the same client code from NodeJs works properly. Using the hosted Firestore from the browser also works. Queries without startAfter in them (eg. the first one in the example) also work.

setup.js
```javascript
const {initializeAdminApp, firestore, clearFirestoreData} = require("@firebase/testing");

async function setup() {
    await clearFirestoreData({projectId: "emulator-test"});
    const adminApp = initializeAdminApp({projectId: "emulator-test"});
    const adminDb = adminApp.firestore();
    await adminDb.doc("myCollection/doc1").set({value: "document 1", time: firestore.Timestamp.fromDate(new Date("2019-10-09"))});
    await adminDb.doc("myCollection/doc2").set({value: "document 2", time: firestore.Timestamp.fromDate(new Date("2019-10-10"))});
}

setup();
```

index.html
```html
<script src="https://www.gstatic.com/firebasejs/7.1.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.1.0/firebase-firestore.js"></script>

<script>
    async function demo() {

        firebase.initializeApp({"projectId": "emulator-test"});
        firebase.firestore().settings({
            host: "localhost:8080",
            ssl: false
        });   
        
        const snapshot = await firebase.firestore().collection("myCollection")
            .orderBy("time")
            .limit(1)
            .get();
        console.log("snapshot 1", snapshot.docs[0].data());
        const snapshot2 = await firebase.firestore().collection("myCollection")
            .orderBy("time")
            .startAfter(snapshot.docs[0])
            .limit(1)
            .get();
        console.log("snapshot 2", snapshot2 && snapshot2.docs && snapshot2.docs[0] && snapshot2.docs[0].data() || "failed");
    
    }
    
    demo();
</script>
```

### [REQUIRED] Steps to reproduce

1. Start the firestore emulator (`firebase emulators:start --only firestore`)
2. Run setup.js in an empty firebase project with NodeJs (`node setup.js`) (The project only has firestore enabled, the @firebase/testing package is installed with npm)
3. Open index.html in a browser (Tested in chrome and firefox)

### [REQUIRED] Expected behavior

The console output in the browser is the following:
```
index.html:17 snapshot 1 {time: oo, value: "document 1"}
index.html:23 snapshot 2 {time: oo, value: "document 2"}
```

### [REQUIRED] Actual behavior

The console output in the browser is the following:
```
index.html:17 snapshot 1 {time: oo, value: "document 1"}
index.html:23 snapshot 2 failed
```

In firestore-debug.log there is an error:
```
Oct 09, 2019 5:23:43 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Oct 09, 2019 5:23:43 PM com.google.cloud.datastore.emulator.firestore.webchannel.JsonToProtoConverter toListenRequest
WARNING: invalid message: {"database":"projects/emulator-test/databases/(default)","addTarget":{"query":{"structuredQuery":{"from":[{"collectionId":"myCollection"}],"orderBy":[{"field":{"fieldPath":"time"},"direction":"ASCENDING"},{"field":{"fieldPath":"__name__"},"direction":"ASCENDING"}],"limit":{"value":1},"startAt":{"before":false,"values":[{"timestampValue":{"seconds":"1570579200","nanos":0}},{"referenceValue":"projects/emulator-test/databases/(default)/documents/myCollection/doc1"}]}},"parent":"projects/emulator-test/databases/(default)/documents"},"targetId":4}}
Oct 09, 2019 5:23:43 PM com.google.net.webchannel.server.common.ChannelProcessor run
WARNING: Failed to consume the event.
java.lang.RuntimeException: com.google.protobuf.InvalidProtocolBufferException: JsonObject
	at com.google.cloud.datastore.emulator.firestore.webchannel.JsonToProtoConverter.toListenRequest(JsonToProtoConverter.java:22)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreListenHandler.onMessage(FirestoreV1WebChannelAdapter.java:175)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreListenHandler.onMessage(FirestoreV1WebChannelAdapter.java:145)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.onMessage(ChannelInternalImpl.java:484)
	at com.google.net.webchannel.server.v8.ForwardChannel.deliverMessage(ForwardChannel.java:114)
	at com.google.net.webchannel.server.v8.ForwardChannel.processPendingRequest(ForwardChannel.java:93)
	at com.google.net.webchannel.server.v8.ForwardChannel.consume(ForwardChannel.java:67)
	at com.google.net.webchannel.server.v8.ForwardChannel.add(ForwardChannel.java:60)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.handleRequestParams(ChannelInternalImpl.java:260)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.handle(ChannelInternalImpl.java:122)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.consume(ChannelInternalImpl.java:78)
	at com.google.net.webchannel.server.common.ChannelProcessor.run(ChannelProcessor.java:80)
Caused by: com.google.protobuf.InvalidProtocolBufferException: JsonObject
	at com.google.cloud.datastore.emulator.firestore.webchannel.jsonformatfork.JsonFormat$ParserImpl.merge(JsonFormat.java:1349)
	at com.google.cloud.datastore.emulator.firestore.webchannel.jsonformatfork.JsonFormat$Parser.merge(JsonFormat.java:451)
	at com.google.cloud.datastore.emulator.firestore.webchannel.JsonToProtoConverter.toListenRequest(JsonToProtoConverter.java:19)
	... 11 more
```

**Comment by samtstern** [comment] 2019-10-09 20:01
@petert37 thank you for the very clear report!  @yuchenshi or @ryanpbrewster should be able to take a look.

**Comment by yuchenshi** [comment] 2019-10-09 20:53
I've reproduced this. In fact, all timestamps are not handled correctly. Internal tracking ID: 37282237. A fix is on its way.

**Comment by yuchenshi** [comment] 2019-10-10 20:51
This is now fixed by https://github.com/firebase/firebase-js-sdk/pull/2249 and will go out with the next JS SDK release. I'm closing this bug since there is no more action on the Firebase CLI / Emulators. Feel free to upgrade the SDK and try again once it is available.

**Closed by yuchenshi** 2019-10-10 20:51 UTC
Labels: emulator-suite, emulators: firestore
