### ISSUE TITLE
Support for specifying firebase.json to use in command line

### ISSUE THREAD

**Issue by rhodgkins** [firebase/firebase-tools#2374] opened 2020-06-17 08:44 UTC
We have a scenario where we want to deploy a shared hosting code base to different Firebase projects but some of the other components (e.g. functions) are different/don't need to be included.

What we currently do is have a `other-firebase.json` and when deploying in Cloud Build swap this out with `firebase.json` and then deploy using `firebase-tools`.

It would be great if we could specify which `firebase.json` to use when running the `firebase` command, i.e. `firebase --config other-firebase.json deploy`.

**Comment by samtstern** [comment] 2020-06-17 22:20
@rhodgkins thanks for the feedback!  I believe this is a duplicate of https://github.com/firebase/firebase-tools/issues/1115

**Closed by samtstern** 2020-06-17 22:20 UTC
Labels: type: feature request

**Comment by rhodgkins** [comment] 2020-06-18 06:17
@samtstern ah apologies I did have a search but didn’t go as far back as 18 months...!
