### ISSUE TITLE
firebase login --no-localhost failing with 400 error

### ISSUE THREAD

**Issue by markgoho** [firebase/firebase-tools#8012] opened 2024-12-01 19:26 UTC
### [REQUIRED] Environment info

**firebase-tools:** 13.4.1

**Platform:** Codespaces

### [REQUIRED] Test case

Tried to run `firebase login --no-localhost`

### [REQUIRED] Steps to reproduce

Run the `login` command
Y/n to analytics (doesn't matter)
Click auth link
confirm session code
copy auth code
paste into terminal

### [REQUIRED] Expected behavior

Would expect auth to work properly.

### [REQUIRED] Actual behavior

```log
[debug] [2024-12-01T19:21:53.465Z] ----------------------------------------------------------------------
[debug] [2024-12-01T19:21:53.467Z] Command:       /home/vscode/.bun/bin/bun /workspaces/rochester-parks/node_modules/.bin/firebase login --no-localhost
[debug] [2024-12-01T19:21:53.467Z] CLI Version:   13.4.1
[debug] [2024-12-01T19:21:53.467Z] Platform:      linux
[debug] [2024-12-01T19:21:53.467Z] Node Version:  v22.6.0
[debug] [2024-12-01T19:21:53.471Z] Time:          Sun Dec 01 2024 19:21:53 GMT+0000 (Coordinated Universal Time)
[debug] [2024-12-01T19:21:53.471Z] Env Overrides: GITHUB_API_URL
[debug] [2024-12-01T19:21:53.471Z] ----------------------------------------------------------------------
[debug] 
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[debug] [2024-12-01T19:22:02.069Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[debug] [2024-12-01T19:22:02.070Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"9140c2db-12a7-46bc-b05a-29dc45d6f0b4"}
[debug] [2024-12-01T19:22:02.264Z] <<< [apiv2][status] POST https://auth.firebase.tools/attest 200
[debug] [2024-12-01T19:22:02.264Z] <<< [apiv2][body] POST https://auth.firebase.tools/attest {"token":"vJHyRwnRuFNVgXT20NyW6Kla0s3GWbfROOgOJyupouI"}
[info] 
[info] To sign in to the Firebase CLI:
[info] 
[info] 1. Take note of your session ID:
[info] 
[info]    9140C
[info] 
[info] 2. Visit the URL below on any device and follow the instructions to get your code:
[info] 
[info]    https://auth.firebase.tools/login?code_challenge=OmgSHWbx1E-ITQtDloPTLJ3WDWa3HCk2_KQnYox-whY&session=9140c2db-12a7-46bc-b05a-29dc45d6f0b4&attest=vJHyRwnRuFNVgXT20NyW6Kla0s3GWbfROOgOJyupouI
[info] 
[info] 3. Paste or enter the authorization code below once you have it:
[info] 
[debug] [2024-12-01T19:22:24.961Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-12-01T19:22:24.961Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-12-01T19:22:24.982Z] <<< [apiv2][status] POST https://accounts.google.com/o/oauth2/token 400
[debug] [2024-12-01T19:22:24.982Z] <<< [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-12-01T19:22:24.983Z] Token Fetch Error: FirebaseError: HTTP Error: 400, Bad multipart/form-data request.
    at new FirebaseError (/workspaces/rochester-parks/node_modules/firebase-tools/lib/error.js:10:9)
    at responseToError (/workspaces/rochester-parks/node_modules/firebase-tools/lib/responseToError.js:49:24)
    at <anonymous> (/workspaces/rochester-parks/node_modules/firebase-tools/lib/apiv2.js:297:61)
    at processTicksAndRejections (native:7:39)
[error] 
[error] Error: Unable to authenticate using the provided code. Please try again.
```

**Comment by senderMinader** [comment] 2024-12-04 12:22
Same issue for me. I try to code a firestore + cloud task app. So here are the command i've wrote:
```
nvm use 18
npm install -g firebase-tools
firebase --version // output 13.27.0
firebase logout // ensure that no account is actually logged in
firebase login
```
Then i'm blocked like this
![Capture d’écran du 2024-12-04 15-18-32](https://github.com/user-attachments/assets/2448262c-d2f8-4673-a825-682ad4ab9018)


So i've decided to use --no-localhost flag
```
firebase login --reauth --no-localhost --debug
```

after all the instruction, i've pasted the given code then always error, there are the logs:

sedera@fedora:~/DEV/firebase2$ firebase login --reauth --no-localhost --debug
[2024-12-04T12:10:53.163Z] Object ".database" in "firebase.json" has unknown property: {"additionalProperty":"target"}
[2024-12-04T12:10:53.165Z] Field ".database" in "firebase.json" is possibly invalid: should be array
[2024-12-04T12:10:53.165Z] Field ".database" in "firebase.json" is possibly invalid: should match some schema in anyOf
[2024-12-04T12:10:53.174Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[2024-12-04T12:10:53.174Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"fc6ad196-791a-4260-a930-694e23eea0f2"}
(node:21723) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
[2024-12-04T12:10:54.043Z] <<< [apiv2][status] POST https://auth.firebase.tools/attest 200
[2024-12-04T12:10:54.044Z] <<< [apiv2][body] POST https://auth.firebase.tools/attest {"token":"5uCBQ34YSu7SGnFeGx9_yGA8ES6Ma2LqQJg3A5rVQSY"}

To sign in to the Firebase CLI:

1. Take note of your session ID:

   FC6AD

2. Visit the URL below on any device and follow the instructions to get your code:

   https://auth.firebase.tools/login?code_challenge=T73Gx0dArgmq_fY5yx2Yh-5JofPWcfZOlDrQ6WOlJyk&session=fc6ad196-791a-4260-a930-694e23eea0f2&attest=5uCBQ34YSu7SGnFeGx9_yGA8ES6Ma2LqQJg3A5rVQSY

3. Paste or enter the authorization code below once you have it:

? Enter authorization code: 
4/0AeanS0YjLkUaGXvfSzLc64XFJZ3leymHCZV-CakDta2oa9ZFZM-M2-soedc0PIH9zqv9iw
[2024-12-04T12:12:39.149Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[2024-12-04T12:12:39.150Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[2024-12-04T12:12:40.018Z] <<< [apiv2][status] POST https://accounts.google.com/o/oauth2/token 500
[2024-12-04T12:12:40.018Z] <<< [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[2024-12-04T12:12:40.020Z] Token Fetch Error: FirebaseError: Request to https://accounts.google.com/o/oauth2/token had HTTP Error: 500, internal_failure
    at responseToError (/home/sedera/.nvm/versions/node/v18.19.1/lib/node_modules/firebase-tools/lib/responseToError.js:52:12)
    at RetryOperation._fn (/home/sedera/.nvm/versions/node/v18.19.1/lib/node_modules/firebase-tools/lib/apiv2.js:312:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci

Error: Unable to authenticate using the provided code. Please try again.

**I ve tried version 13.13.1 - 13.13.3 also, still the same issue**

**Comment by aalej** [comment] 2024-12-04 15:54
Hey @markgoho, thanks for reaching out. I'm trying to reproduce this issue, but so far I haven't encountered any errors when running `firebase login --no-localhost` on GitHub Codespaces. 

My best guess is that there might be something interfering with the formatting or sending of the form data. Could you share additional details on how you configured your Codespaces so that I can try to replicate the setup you have?

Also, any chance you could try creating a blank Codespace and try `firebase login --no-localhost` in that instance? Are you able to successfully run the command, or does it also error out?

**Comment by markgoho** [comment] 2024-12-04 18:25
@aalej here's a fresh repo, still didn't work

https://github.com/markgoho/test-firebase-login

**Comment by markgoho** [comment] 2024-12-04 18:33
Update: there's a good chance this is due to an issue with how Bun does fetch with form data

I've reported the issue there https://github.com/oven-sh/bun/issues/15580

**Comment by aalej** [comment] 2024-12-05 13:32
Thanks for sharing a repo for the issue. I tried forking https://github.com/markgoho/test-firebase-login to create the Codespaces, and running `bunx firebase-tools login --no-localhost` reproduces the error. 

In my case, I initially used Node.js for my Codespaces. Here's my `devcontainer.json`:
```json
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/javascript-node
{
	"name": "Node.js",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm",
	"features": {
		"ghcr.io/devcontainers/features/node:1": {
			"nodeGypDependencies": true,
			"installYarnUsingApt": true,
			"version": "22.6.0",
			"pnpmVersion": "latest",
			"nvmVersion": "latest"
		}
	}
}
```

Since the issue occurs when using Bun, I think your observations are correct and that the issue may be with how Bun handles form data in fetch requests, thanks for opening up that report in Bun. 

For now, since the issue doesn't seem to stem from firebase-tools, I'm going to go ahead and close this. If you think this is a mistake, and that the issue is indeed with `firebase-tools`, feel free to ask this issue to be reopened.

**Closed by aalej** 2024-12-05 13:32 UTC
Labels: type: bug, api: core, Needs: Attention
