### ISSUE TITLE
Missing "version" data with non transactional commits

### ISSUE THREAD

**Issue by onurdialpad** [firebase/firebase-tools#7435] opened 2024-07-11 17:02 UTC
### [REQUIRED] Environment info

**firebase-tools:13.13.1**

**Platform:macOS**

### [REQUIRED] Test case

```
import requests

emulator_url = 'http://127.0.0.1:54510/v1/projects/testbed-test:commit'

payload = b'{"mode": "NON_TRANSACTIONAL", "mutations": [{"delete": {"partitionId": {"projectId": "testbed-test", "namespaceId": ""}, "path": [{"kind": "HookTestModel", "name": "NONEXISTENT_KEY_NAME"}]}}]}'

headers = {'Content-Length': '192', 'Content-Type': 'application/json'}

# POST request to the emulator
resp = requests.post(emulator_url, headers=headers, data=payload)

# check response's data
data = resp.json()

# data  must include "version" field based on the reference https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/commit#MutationResult
Note: Datastore emulator behaves as expected.

print(data)
```

### [REQUIRED] Steps to reproduce

Explained above

### [REQUIRED] Expected behavior

response must contain "version" field
### [REQUIRED] Actual behavior
response doesn't have "version" field

**Comment by aalej** [comment] 2024-07-12 16:51
Hey @onurdialpad, thanks for always providing a detailed report! I’m able to reproduce the behavior mentioned. I’ll reach out to our engineering team so they can take a look.

**Comment by harshyyy21** [comment] 2024-07-15 18:59
Hi @onurdialpad! Are you only seeing this issue present in non-transactional commits?

**Comment by onurdialpad** [comment] 2024-07-15 19:03
Hi @harshyyy21 yes it's a valid issue with `NON_TRANSACTIONAL` mode as explained in the sample test case

**Comment by harshyyy21** [comment] 2024-08-22 16:17
Hi @onurdialpad, still trying to get a fix out for this, apologize for the delay. It looks like the issue might actually be for both NON_TRANSACTIONAL and TRANSACTIONAL commits, but only when the entity you're trying to delete doesn't already exist. Would you be able to confirm that?

**Comment by onurdialpad** [comment] 2024-08-22 18:27
Hello @harshyyy21 yes you are right, if there is an entity, then the response has `version` field, if there is no entity then response doesn't have `version` field

**Comment by harshyyy21** [comment] 2024-09-19 16:21
Hey @onurdialpad, this should be fixed in the latest release: https://cloud.google.com/sdk/docs/release-notes#cloud_firestore_emulator. Going to mark this closed but feel free to re-open if there's still additional issues regarding this, thanks!

**Closed by harshyyy21** 2024-09-19 16:21 UTC
Labels: type: bug, emulators: firestore, reproducible
