### ISSUE TITLE
firebase deploy in Next.js

### ISSUE THREAD

**Issue by gitVangercol** [firebase/firebase-tools#6184] opened 2023-07-25 23:39 UTC
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment] 2023-07-26 09:12
Hi @gitVangercol, could you please file a new issue specifying the details using the provided template. This way, it would be more efficient in identifying the cause of the issue. Also, since there are no details on this report, I'll be closing this for now

**Closed by aalej** 2023-07-26 09:12 UTC
Labels: type: bug
