### ISSUE TITLE
Firebase Functions + Firestore: Permission errors

### ISSUE THREAD

**Issue by pal03377** [firebase/firebase-tools#2314] opened 2020-05-30 23:16 UTC
### [REQUIRED] Environment info

Node Version v10.15.3  
NPM Version 6.4.1

**firebase-tools: 8.4.1** 

**Platform: Windows 10 Pro**

### [REQUIRED] Test case

https://github.com/pal03377/firebase-tools-issue-example

### [REQUIRED] Steps to reproduce
Clone the repo and run `firebase emulators:start`

Alternative (how I set up the repository): Create a new basic Firebase project with just Cloud Functions and Firestore set up (security rules set to production, forbidding any client-side access). Try to write to a Firestore document in the Cloud Functions. Run `firebase emulators:start`.

### [REQUIRED] Expected behavior

The simulated Firebase Functions Code does not have to follow Firestore security rules and is able to write to a document in `test/testdoc`.

### [REQUIRED] Actual behavior

I get a permission error 
`[info] >  (node:35432) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED:  {"user":"(node:35432) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED: ","metadata":{"emulator":{"name":"functions"},"message":"\u001b[90m> \u001b[39m (node:35432) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED: "}}`

### Logging files generated from `firebase emulators:start --debug`
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/4706767/firebase-debug.log)
[firestore-debug.log](https://github.com/firebase/firebase-tools/files/4706768/firestore-debug.log)

### Additional information
I initially got this error in a larger projects in which I have set up the `GOOGLE_APPLICATION_CREDENTIALS` and in which I'm using an exported function with `exports.something = async () => { ... }`. So I guess neither of these are the cause of the error.

**Comment by pal03377** [comment] 2020-05-30 23:26
Downgrading does not help as I then get #2301 all the time.

**Comment by pal03377** [comment] 2020-05-30 23:52
It seems downgrading to `7.14.0` (apparently the version I was using before I upgraded and the issue occurred) helps.

**Comment by samtstern** [comment] 2020-06-01 12:52
This is a duplicate of #2310 see that issue for some investigations and workarounds.  Thank you for reporting!

**Closed by samtstern** 2020-06-01 12:52 UTC
