### ISSUE TITLE
[7.0] Why `firebase serve` runs index.js every time it receives requests?

### ISSUE THREAD

**Issue by rnarkk** [firebase/firebase-tools#1427] opened 2019-06-21 17:40 UTC
### [REQUIRED] Environment info

**firebase-tools:**
7.0.0

**Platform:**
Debian 9

**Comment by samtstern** [comment] 2019-06-21 17:43
There is not really any information here but taking a guess and marking this as a duplicate of #1353

**Closed by samtstern** 2019-06-21 17:43 UTC
