### ISSUE TITLE
Emulator not handling 0.0.0.0 hostname definition in firebase.json

### ISSUE THREAD

**Issue by StorminGorman** [firebase/firebase-tools#2742] opened 2020-10-26 16:29 UTC
### [REQUIRED] Environment info

firebase-tools: 8.13.1

Platform: MacOS Catalina 

### [REQUIRED] Test case

Try to make the emulators host on external network interfaces on the local network.

### [REQUIRED] Steps to reproduce
Add the following to the firebase.json to host on external network interfaces
```
  "emulators": {
    "functions": {
      "port": 5001,
      "host": "0.0.0.0"
    },
    "firestore": {
      "port": 9090
    },
    "database": {
      "port": 9000,
      "host": "0.0.0.0"
    },
    "hosting": {
      "port": 5000,
      "host": "0.0.0.0"
    }
  }
```
Then run `firebase --debug emulators:start`

Emulators fail to start

### [REQUIRED] Expected behavior

Should be able to host emulators on external network interfaces.

### [REQUIRED] Actual behavior

emulators fail to start.
`WARN com.firebase.core.namespace.NamespaceActorSystem - Request for ns: checkit-portico has incorrect domain. Current domain: 0.0.0.0, expected domain: firebaseio-staging.com\n"}}`

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/5440058/firebase-debug.log)

**Comment by samtstern** [comment] 2020-10-26 16:33
@StorminGorman thanks for the report!  This looks like a duplicate of https://github.com/firebase/firebase-tools/issues/2633 so let's discuss over there.

**Closed by samtstern** 2020-10-26 16:33 UTC

**Comment by StorminGorman** [comment] 2020-10-26 16:37
I think a big clue for me is 

```
WARN com.firebase.core.namespace.NamespaceActorSystem - Request for ns: checkit-portico has incorrect domain. Current domain: 0.0.0.0, expected domain: firebaseio-staging.com\n"}}
```

In the log ... why would it expect `firebaseio-staging.com` when the host is configured as `0.0.0.0` ?
