### ISSUE TITLE
Import users with cli auth:import

### ISSUE THREAD

**Issue by bpingris** [firebase/firebase-tools#4145] opened 2022-02-09 09:03 UTC
### [REQUIRED] Environment info

**firebase-tools:**
10.1.2

**Platform:**
macOS
### [REQUIRED] Test case

I want to import some users from an external service to firebase.

### [REQUIRED] Steps to reproduce

I created a `users.json` file with the following content:
```json
{
    "users":  [
        {
            "localId": "6163ee1c5235bc04593462fe",
            "email": "jon.foo@example.com",
            "passwordHash": "12c95403688627611328f4e293f76520939563f87ee3d8c2e97e5f0fac4690ba",
            "salt": "M2U4MjRhNWEtMGFlMS00YjZmLThmMjUtNTU0NDMyZTc5NTRm"
        }
    ]
}
```
and ran this command:
```bash
firebase auth:import users.json \
--hash-algo=SHA256 \
--rounds=1 \
--hash-input-order=SALT_FIRST \
--project my-project-id
```

### [REQUIRED] Expected behavior
The users defined in my `users.json` should be uploaded to firebase, or if any error happened I should have it displayed on my terminal.

### [REQUIRED] Actual behavior
The import failed and I have no information except the following:
```
Processing users.json (310 bytes)
Starting importing 1 account(s).
Encountered problems while importing accounts. Details:

```

If I ran with --debug flag , I can see the error but it seems wrong:
```
[{"account":"{}","reason":"localId is missing"}]
```
but, as you can see in my `users.json`, the `localId` property is set.

**Comment by nappernick** [comment] 2022-02-09 16:34
Same issue.

**Comment by antoine10245** [comment] 2022-02-10 12:31
Im experiencing it too!  using `firebase 10.1.5`, on macOS Monterey(12.1)

**Comment by bpingris** [comment] 2022-02-10 13:20
To resolve this in the meantime, I used the Go admin SDK to import my users (btw all SDK seem not to be developed with the same feature: the Node one does not have an option to specify the order of the salt).
I had to face some issues though, you can find more information on my [SO post](https://stackoverflow.com/questions/71034926/import-external-user-to-firebase)

**Comment by isaactan001** [comment] 2022-02-10 17:05
Use the CSV format instead of JSON works for me

**Comment by yuchenshi** [comment] 2022-02-14 21:19
Duplicate of #4157

**Closed by yuchenshi** 2022-02-14 21:19 UTC
Labels: bug
