### ISSUE TITLE
⬢  functions: Failed to load function definition from source: FirebaseError: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error

### ISSUE THREAD

**Issue by Vivekdpp** [firebase/firebase-tools#6460] opened 2023-10-19 16:42 UTC
[debug] [2023-10-19T16:34:47.797Z] ----------------------------------------------------------------------
[debug] [2023-10-19T16:34:47.798Z] Command:       /usr/local/bin/node /usr/local/bin/firebase emulators:start --only functions
[debug] [2023-10-19T16:34:47.798Z] CLI Version:   12.6.2
[debug] [2023-10-19T16:34:47.798Z] Platform:      darwin
[debug] [2023-10-19T16:34:47.798Z] Node Version:  v18.18.0
[debug] [2023-10-19T16:34:47.799Z] Time:          Thu Oct 19 2023 10:34:47 GMT-0600 (Mountain Daylight Time)
[debug] [2023-10-19T16:34:47.799Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-10-19T16:34:47.851Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-10-19T16:34:47.851Z] > authorizing via signed-in user (vp.dppatel@gmail.com)
[info] i  emulators: Starting emulators: functions {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: functions"}}
[debug] [2023-10-19T16:34:48.060Z] [logging] Logging Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-10-19T16:34:48.060Z] assigned listening specs for emulators {"user":{"hub":[{"address":"127.0.0.1","family":"IPv4","port":4400},{"address":"::1","family":"IPv6","port":4400}],"ui":[{"address":"127.0.0.1","family":"IPv4","port":4000},{"address":"::1","family":"IPv6","port":4000}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4500}]},"metadata":{"message":"assigned listening specs for emulators"}}
[debug] [2023-10-19T16:34:48.064Z] [hub] writing locator at /var/folders/bs/g_k5jb1j7sld_wc5qqfx423m0000gn/T/hub-challenge-e0ac9.json
[debug] [2023-10-19T16:34:48.200Z] [functions] Functions Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-10-19T16:34:48.200Z] [eventarc] Eventarc Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[debug] [2023-10-19T16:34:48.200Z] late-assigned ports for functions and eventarc emulators {"user":{"hub":[{"address":"127.0.0.1","family":"IPv4","port":4400},{"address":"::1","family":"IPv6","port":4400}],"ui":[{"address":"127.0.0.1","family":"IPv4","port":4000},{"address":"::1","family":"IPv6","port":4000}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4500}],"functions":[{"address":"127.0.0.1","family":"IPv4","port":5001}],"eventarc":[{"address":"127.0.0.1","family":"IPv4","port":9299}]},"metadata":{"message":"late-assigned ports for functions and eventarc emulators"}}
[warn] ⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting, pubsub, storage {"metadata":{"emulator":{"name":"functions"},"message":"The following emulators are not running, calls to these services from the Functions emulator will affect production: \u001b[1mauth, firestore, database, hosting, pubsub, storage\u001b[22m"}}
[debug] [2023-10-19T16:34:48.205Z] defaultcredentials: writing to file /Users/vivekdpatel/.config/firebase/vp_dppatel_gmail.com_application_default_credentials.json
[debug] [2023-10-19T16:34:48.209Z] Setting GAC to /Users/vivekdpatel/.config/firebase/vp_dppatel_gmail.com_application_default_credentials.json {"metadata":{"emulator":{"name":"functions"},"message":"Setting GAC to /Users/vivekdpatel/.config/firebase/vp_dppatel_gmail.com_application_default_credentials.json"}}
[debug] [2023-10-19T16:34:48.210Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/challenge-e0ac9/adminSdkConfig [none]
[debug] [2023-10-19T16:34:48.453Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/challenge-e0ac9/adminSdkConfig 200
[debug] [2023-10-19T16:34:48.453Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/challenge-e0ac9/adminSdkConfig {"projectId":"challenge-e0ac9","storageBucket":"challenge-e0ac9.appspot.com"}
[debug] [2023-10-19T16:34:48.473Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2023-10-19T16:34:48.473Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: port"}}
[debug] [2023-10-19T16:34:48.473Z] Starting Emulator UI with command {"binary":"node","args":["/Users/vivekdpatel/.cache/firebase/emulators/ui-v1.11.7/server/server.js"],"optionalArgs":[],"joinArgs":false} {"metadata":{"emulator":{"name":"ui"},"message":"Starting Emulator UI with command {\"binary\":\"node\",\"args\":[\"/Users/vivekdpatel/.cache/firebase/emulators/ui-v1.11.7/server/server.js\"],\"optionalArgs\":[],\"joinArgs\":false}"}}
[info] i  ui: Emulator UI logging to ui-debug.log {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI logging to \u001b[1mui-debug.log\u001b[22m"}}
[debug] [2023-10-19T16:34:48.543Z] Web / API server started at 127.0.0.1:4000
 {"metadata":{"emulator":{"name":"ui"},"message":"Web / API server started at 127.0.0.1:4000\n"}}
[debug] [2023-10-19T16:34:48.543Z] Web / API server started at ::1:4000
 {"metadata":{"emulator":{"name":"ui"},"message":"Web / API server started at ::1:4000\n"}}
[info] i  functions: Watching "/Users/vivekdpatel/Downloads/Developer_Interview_preparation/Projects/Amazon_clone/amazon-clone/functions" for Cloud Functions... {"metadata":{"emulator":{"name":"functions"},"message":"Watching \"/Users/vivekdpatel/Downloads/Developer_Interview_preparation/Projects/Amazon_clone/amazon-clone/functions\" for Cloud Functions..."}}
[debug] [2023-10-19T16:34:48.733Z] Validating nodejs source
[debug] [2023-10-19T16:34:49.222Z] > [functions] package.json contents: {
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "18"
  },
  "main": "index.js",
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.18.2",
    "firebase-admin": "^11.8.0",
    "firebase-functions": "^4.3.1",
    "stripe": "^14.1.0"
  },
  "devDependencies": {
    "eslint": "^8.15.0",
    "eslint-config-google": "^0.14.0",
    "firebase-functions-test": "^3.1.0"
  },
  "private": true
}
[debug] [2023-10-19T16:34:49.222Z] Building nodejs source
[debug] [2023-10-19T16:34:49.223Z] Failed to find version of module node: reached end of search path /Users/vivekdpatel/Downloads/Developer_Interview_preparation/Projects/Amazon_clone/amazon-clone/functions/node_modules
[info] ✔  functions: Using node@18 from host. 
[debug] [2023-10-19T16:34:49.224Z] Could not find functions.yaml. Must use http discovery
[debug] [2023-10-19T16:34:49.228Z] Found firebase-functions binary at '/Users/vivekdpatel/Downloads/Developer_Interview_preparation/Projects/Amazon_clone/amazon-clone/functions/node_modules/.bin/firebase-functions'
[info] Serving at port 8738

[debug] [2023-10-19T16:34:49.428Z] Got response code 400; body Failed to generate manifest from function source: ReferenceError: functions is not defined
[info] shutdown requested via /__/quitquitquit

[error] ⬢  functions: Failed to load function definition from source: FirebaseError: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error {"metadata":{"emulator":{"name":"functions"},"message":"Failed to load function definition from source: FirebaseError: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error"}}
[info] 
┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://127.0.0.1:4000/               │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Functions │ 127.0.0.1:5001 │ http://127.0.0.1:4000/functions │
└───────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at 127.0.0.1:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.

**Comment by aalej** [comment] 2023-10-19 18:12
Hi @Vivekdpp, based on the debug logs you provided, it looks like you’re encountering this issue because there is a runtime/syntax error with your code which is preventing Firebase Tools from analyzing your functions. Could you double check your code to make sure that there aren't any syntax errors. 

It would be difficult to troubleshoot the error without additional information. Could you please file a new issue and specify the details using the provided template. Also, it would be helpful if you can provide code snippets as this will help us identify the cause of the error. That said, I'll be closing this for now.

**Closed by aalej** 2023-10-19 18:12 UTC
Labels: type: bug, emulators: functions

**Comment by jelling** [comment] 2023-10-20 09:04
@Vivekdpp does your project build when it's not trying to start in the emulator? 

Either way, please add your support for better error messages on #6463
