### ISSUE TITLE
`linkWithRedirect` does not trigger emulators blocking function

### ISSUE THREAD

**Issue by sheunglaili** [firebase/firebase-tools#6168] opened 2023-07-20 21:15 UTC
### [REQUIRED] Environment info

**firebase-tools:**  12.4.4

**Platform:** macOS

### [REQUIRED] Test case

When calling `signInAnonymously` to signIn as anonymous user, and later call `linkWithRedirect` to `GoogleProvider`. 

The credential is being retrieved after redirect back to original page. 

but the `beforeUserCreated` blocking function was not triggered.

### [REQUIRED] Steps to reproduce

1. create a `beforeUserCreated` functions
2. connect auth to local emulators
3. handle redirect result with `getRedirectResult`
4. sign in with `signInAnonymously` 
5. link account with `linkWithRedirect`

### [REQUIRED] Expected behavior

As [document](https://firebase.google.com/docs/auth/extend-with-blocking-functions?gen=2nd#understanding_blocking_functions) mentioned, `Linking another identity provider to an account re-triggers any registered beforeUserSignedIn functions.` 

### [REQUIRED] Actual behavior

No `beforeUserCreated` blocking function is being trigger.

**Comment by aalej** [comment] 2023-07-21 14:39
Hi @sheunglaili, thanks for reaching out. From what I can tell, you noticed that `beforeUserSignedIn` is not being triggered when you use `linkWithRedirect`. I’m unable to reproduce the issue you mentioned. It also looks like the reason why `beforeUserCreated` is not being triggered is because anonymous authentication does not trigger blocking functions according to the [docs](https://firebase.google.com/docs/auth/extend-with-blocking-functions?gen=2nd#understanding_blocking_functions).

Could you try checking if you're able to encounter the issue using [this](https://github.com/aalej/issues-6168)? In case I’m missing anything or if I made a mistake, please let me know. By any chance, could you also provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) where the issue is reproducible so that we can replicate it on our end?

**Comment by sheunglaili** [comment] 2023-07-21 18:33
Hi @aalej , thank you for putting the time in putting this up. 

I am able run the repository and `beforeUserSignedIn` did trigger. 

I might have a typo in my original post and I was expecting `beforeUserCreated` to triggered since I expected linking the anonymous user to Google Provider sort of means creating a new account but perhaps I got the wrong impression and misread the document. Apologies for that.

So am I right in saying linking an anonymous user wouldn't trigger `beforeUserCreated` but only `beforeUserSignedIn` ? As I am writing a function to try to create a user profile when user upgrade their account into linked account.

**Comment by aalej** [comment] 2023-07-24 14:28
Based on the [docs](https://firebase.google.com/docs/auth/extend-with-blocking-functions?gen=2nd#understanding_blocking_functions), anonymous authentication will not trigger blocking functions(e.g. `beforeUserSignedIn` and `beforeUserCreated`), but when linking an identity provider to the account, it re-triggers any registered `beforeUserSignedIn` functions. So in the scenario you mentioned:
1. Anonymous sign in
   1. No blocking function triggered
2. Linking an identity provider
    1. Only `beforeUserSignedIn` is triggered

Since it looks like this behavior is WAI, I’ll go ahead and close this ticket. Thanks!

**Comment by sheunglaili** [comment] 2023-07-24 14:29
Thanks @aalej !

**Closed by aalej** 2023-07-24 14:28 UTC
Labels: type: bug, Needs: Attention, emulators: auth
