### ISSUE TITLE
!= Queries not working in Firestore Emulator

### ISSUE THREAD

**Issue by thekip** [firebase/firebase-tools#2722] opened 2020-10-20 08:38 UTC
### Environment info

**firebase-tools:**  8.12.1
**Platform:** MacOS 10.15.6

###  [REQUIRED]  Test case

Assume we have few records in `campaigns` collection in Firestore Emulator, some of them have `processedMark: '2020-10'` some of them not.

The query:

```ts
 const collection = await app.firestore().collection('campaigns')
      .where('processedMark', '!=', '2020-10')
      .get();
```

Should return items where `processedMark` not equals `2020-10`, but return all instead. 

As stated in Release page support for `!=` style queries was included in emulator in version [v8.6.0](https://github.com/firebase/firebase-tools/releases/tag/v8.6.0) but it actually doesn't work. 

### [REQUIRED] Steps to reproduce

1. Start emulator
2. Write a nodejs query to Firestore emulator using not equality comparison.

### [REQUIRED] Expected behavior

Should return items where `processedMark` not equals `2020-10`

### [REQUIRED] Actual behavior

Returns all items from collection

**Comment by samtstern** [comment] 2020-10-20 09:52
@thekip thanks for reporting! This is a duplicate of https://github.com/firebase/firebase-tools/issues/2652 you can follow along there.

**Closed by samtstern** 2020-10-20 09:52 UTC
