### ISSUE TITLE
Node.js v6.11.x or greater is required to run the Emulator!

### ISSUE THREAD

**Issue by m-revetria** [firebase/firebase-tools#611] opened 2018-01-19 18:15 UTC
Hi, I've started to experience this issue after I updated to firebase-tools 3.17 in a firebase project that was working fine previously.

### Version info

```sh
$ firebase --version
3.17.1
$ node -v
v6.11.1
$ npm -v
3.10.10
```

### Steps to reproduce

Run command `firebase serve --only functions,hosting`

### Expected behavior

Firebase emulator is up and running fine.

### Actual behavior

The previous command outputs next messages:

```
=== Serving from '<path-to-project>/firebase'...

i  functions: Preparing to emulate functions.
Node.js v6.11.x or greater is required to run the Emulator!
⚠  functions: Error from emulator. Error: Emulator crashed! Check the log file...
i  hosting: Serving hosting files from: public
✔  hosting: Local server: http://localhost:5000
```

However, I'm able to deploy to firebase correctly, the cloud functions seems to be working fine on the cloud.

-------------

BTW, `firebase-debug.log` is not showing anything useful to me to trace this error.
Is there a way to see more info about the error thrown by emulator?

**Comment by laurenzlong** [comment] 2018-01-19 19:05
v3.17.2 has now been released and should have fixed the problem, please let me know if it doesn't. Thanks for reporting!

**Comment by m-revetria** [comment] 2018-01-19 19:27
Hi, thanks for your reply.

I'm now using firebase-tools@3.17.2 and `firebase serve` is working fine: hosting and functions are available. But if I run `firebase serve --only functions,hosting` I get the same error than before.

**Comment by laurenzlong** [comment] 2018-01-19 19:31
Can you try "npm uninstall -g firebase-tools && npm install -g firebase-tools"

**Comment by m-revetria** [comment] 2018-01-19 20:38
I've tried it out and still the same error.

I also tried next (I saw it as part of previous command's output) without any luck:

```
> node scripts/upgrade-warning


If you're upgrading @google-cloud/functions-emulator, these
are the recommended upgrade steps:

1.  Stop the currently running emulator, if any:

        functions stop

2.  Uninstall the current emulator, if any:

        npm uninstall -g @google-cloud/functions-emulator

3.  Install the new version of the emulator:

        npm install -g @google-cloud/functions-emulator

If you have trouble after upgrading, try deleting the config
directory found in:

    ~/.config/configstore/@google-cloud/functions-emulator

Then restart the emulator. You can also check for any renegade
Node.js emulator processes that may need to be killed:

    ps aux | grep node
```

**Comment by laurenzlong** [comment] 2018-01-19 22:26
@m-revetria What you pasted above is just a warning message from the install, it's not an error message.

**Comment by m-revetria** [comment] 2018-01-19 22:41
Yup I know, I said I tried to solve the error following that warning message. But I’m still getting the same error when I run `firebase serve —only hosting,functions`: 

```
=== Serving from '<path-to-project>/firebase'...

i  functions: Preparing to emulate functions.
Node.js v6.11.x or greater is required to run the Emulator!
⚠  functions: Error from emulator. Error: Emulator crashed! Check the log file...
i  hosting: Serving hosting files from: public
✔  hosting: Local server: http://localhost:5000
```

I’ve ran the command you suggested, it didn’t solve the error.

**Comment by laurenzlong** [comment] 2018-01-19 22:45
@m-revetria Can you run again with the --debug flag?

**Comment by laurenzlong** [comment] 2018-01-20 00:55
Duplicate of https://github.com/firebase/firebase-tools/issues/609, please follow along there now.

**Closed by laurenzlong** 2018-01-20 00:55 UTC
