### ISSUE TITLE
Cannot clone functions configs that have arrays

### ISSUE THREAD

**Issue by ahaverty** [firebase/firebase-tools#283] opened 2017-03-20 18:58 UTC
Cloning a config from another project adds an additional `\"` to the start and end of any string value

Using firebase:config:clone with firebase-tools v3.5.0

**Comment by laurenzlong** [comment] 2017-03-20 20:46
Hey @ahaverty  could you please give more instructions for a repro? The project that you're cloning from - how did you set the config values for it? Was it set using an older version of the CLI? Or was it also set using v3.5.0?

**Comment by ahaverty** [comment] 2017-03-20 23:02
Hi @laurenzlong, I wanted to double check so I unset project 1 and set everything again (using v3.5.0), I'm now trying to clone to project 2, but I'm getting different errors now.

```
firebase functions:config:clone --from myproject1
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled

Error: Invalid argument, each config value must have a 2-part key (e.g. foo.bar).
```

I'm guessing this is something to do with me using unsupported arrays in my config? (See #284 ) I've changed plans and will probably use a bash script to handle deploying my three projects instead of the clone function, so I'm happy to leave this issue, but I can help/test out if you need anything.

**Comment by laurenzlong** [comment] 2017-03-21 01:13
Thanks for the clarification @ahaverty , to confirm - you were able to successfully set your config in project 1 even when you used arrays? If that's the case, then not being able to clone them is definitely a bug. It would also be helpful if you can provide me the command you used to successfully set the configs in project1.

**Comment by ahaverty** [comment] 2017-03-21 09:19
Thanks @laurenzlong , see https://github.com/firebase/firebase-tools/issues/284#issuecomment-287889958 on how i set the arrays in project 1. I won't have a chance until Wednesday to check if that alone caused the failed clone or not. The rest of the config was simple strings. Thanks for looking

**Comment by laurenzlong** [comment] 2017-03-22 21:10
I was able to reproduce it. I've renamed the issue, and will work on a fix!

**Comment by ahaverty** [comment] 2017-03-22 21:33
Thanks @laurenzlong sorry no repro, this one slipped my mind 🙃

**Comment by laurenzlong** [comment] 2017-05-25 21:31
Closing this issue now since we are not supporting array configs yet. (See https://github.com/firebase/firebase-tools/issues/284). Sorry for the delayed response on this!

**Closed by laurenzlong** 2017-05-25 21:31 UTC
