### ISSUE TITLE
Web Framework Hosting - Sveltekit

### ISSUE THREAD

**Issue by xariusdesai** [firebase/firebase-tools#5158] opened 2022-10-22 19:23 UTC
### [REQUIRED] Environment info

**firebase-tools:**
11.15.0

**Platform:**
macOS

### [REQUIRED] Steps to reproduce

Create skeleton Sveltekit project
firebase experiments:enable webframeworks
Firebase init hosting
Svelte project auto detected
No other changes to other config files
firebase serve - site working as expected using Vite development server
firebase deploy - builds sveltekit app and then fails during build process

### [REQUIRED] Expected behavior

Build process finishes and deploys to hosting

### [REQUIRED] Actual behavior

Get the following error:
Error: An unexpected error has occurred.

Looking at the log, it seems as if it is trying to get to the client folder, but the path has my base path in twice.
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/9845124/firebase-debug.log)

**Comment by kddige** [comment] 2022-10-22 20:37
Might be duplicate of #5144 - no solution yet, but problem might have been found looking at the comments.

**Comment by Nushio** [comment] 2022-10-24 17:33
We'll need a new svelte adapter for this to work, as well as a very small amount of work to the firebase-tool. I'll send the pr later this afternoon for the firebase-tool but I need a bit more time to figure out the best path forward (Either adapt svelte-firebase-adapter to fit this tool, or, make a new tool altogether)

**Comment by simonnepomuk** [comment] 2022-11-14 09:00
I wrote an [adapter for SvelteKit](https://www.npmjs.com/package/sveltekit-adapter-firebase) which works fine for the _traditional_ Firebase deployment. I'm now trying to integrate web framework support to leverage the features that come with it but I'm a bit stuck. My approach was to build everything and utilize the [custom express integration](https://firebase.google.com/docs/hosting/express). I've [opened a PR](https://github.com/simonnepomuk/monorepo/pull/2) to show what my approach is and filed an issue for framework support [here](https://github.com/FirebaseExtended/firebase-framework-tools/issues/53).   
Any input is very much appreciated!

**Comment by simonnepomuk** [comment] 2022-11-18 12:17
@TheIronDev  I think [this PR](https://github.com/firebase/firebase-tools/pull/5248) in combination with [this one](https://github.com/simonnepomuk/monorepo/pull/2) should fix the issue.

**Comment by TheIronDev** [comment] 2022-12-21 16:20
Hi @simonnepomuk ,

First, apologies for the delayed response. And also thank you for opening up the PR(s)!!!!

I know we have some work chasing down SvelteKit integration. I'll check with the project lead (@jamesdaniels ) to see if the 2 PRs match what our team is doing.

Thank you!
Tyler

**Comment by simonnepomuk** [comment] 2022-12-21 16:52
Hey @TheIronDev,

Thanks for the follow up! No worries about the delay, I can understand that this isn't a priority right now. 

If you outline the requirements on your end, I'll be happy to adapt the PRs. The reason I went towards the pre-build everything approach is that the run the `build` script and bundle the output approach the Firebase CLI seems to go for fails in monorepo scenarios where only a global `node_modules` folder exists (e.g. Nx).  But I'm willing to change that aspect of my adapter if it breaks the workflow which is intended for the Firebase CLI.

Thanks!

**Comment by simpros** [comment] 2023-04-11 17:39
This can probably be closed with #5525

**Comment by jamesdaniels** [comment] 2023-04-12 02:05
Built in support for SvelteKit landed in the latest release.

**Closed by jamesdaniels** 2023-04-12 02:05 UTC
Labels: type: bug, integration: web frameworks

**Comment by akashlama1998-icloud** [comment] 2023-05-07 21:31
I'm using SvelteKit v1.16.2 and my package.json looks something like 👇. It's a bog-standard sveltekit skeleton app with tailwindcss added. And firebase hosting on experimental webframeworks doesn't seem to be working as expected.

```json
{
  "name": "sveltekit-sample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
    "lint": "prettier --plugin-search-dir . --check . && eslint .",
    "format": "prettier --plugin-search-dir . --write .",
    "prepare": "husky install"
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^2.0.1",
    "@sveltejs/kit": "^1.16.2",
    "@typescript-eslint/eslint-plugin": "^5.59.2",
    "@typescript-eslint/parser": "^5.59.2",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.40.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-svelte": "^2.27.3",
    "husky": "^8.0.3",
    "postcss": "^8.4.23",
    "prettier": "^2.8.8",
    "prettier-plugin-svelte": "^2.10.0",
    "prettier-plugin-tailwindcss": "^0.2.8",
    "svelte": "^3.59.0",
    "svelte-check": "^3.3.1",
    "tailwindcss": "^3.3.2",
    "tslib": "^2.5.0",
    "typescript": "^5.0.4",
    "vite": "^4.3.5"
  },
  "type": "module"
}
```

Here's the view of my project structure 👇

![image](https://user-images.githubusercontent.com/76813466/236703417-95e160e8-2ff3-4bf5-8bf1-c06694cf6171.png)

Here are the logs, npm and node version 👇

![image](https://user-images.githubusercontent.com/76813466/236703322-bc15f823-c612-470d-9391-ee65a88cc344.png)

**Comment by akashlama1998-icloud** [comment] 2023-05-08 09:27
I'm using SvelteKit v1.16.2 and my package.json looks something like 👇. It's a bog-standard sveltekit skeleton app with tailwindcss added. And firebase hosting on experimental webframeworks doesn't seem to be working as expected.

```json
{
  "name": "sveltekit-sample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
    "lint": "prettier --plugin-search-dir . --check . && eslint .",
    "format": "prettier --plugin-search-dir . --write .",
    "prepare": "husky install"
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^2.0.1",
    "@sveltejs/kit": "^1.16.2",
    "@typescript-eslint/eslint-plugin": "^5.59.2",
    "@typescript-eslint/parser": "^5.59.2",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.40.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-svelte": "^2.27.3",
    "husky": "^8.0.3",
    "postcss": "^8.4.23",
    "prettier": "^2.8.8",
    "prettier-plugin-svelte": "^2.10.0",
    "prettier-plugin-tailwindcss": "^0.2.8",
    "svelte": "^3.59.0",
    "svelte-check": "^3.3.1",
    "tailwindcss": "^3.3.2",
    "tslib": "^2.5.0",
    "typescript": "^5.0.4",
    "vite": "^4.3.5"
  },
  "type": "module"
}
```

Here's the view of my project structure 👇

![image](https://user-images.githubusercontent.com/76813466/236787873-aee1aac5-702d-4798-8350-65186f164471.png)

Here are the logs, npm, pnpm and node version 👇. I tried both npm and pnpm both had the same error.

![image](https://user-images.githubusercontent.com/76813466/236787700-7f0b50fa-acb1-44da-829e-806e8486bba0.png)

**Comment by abegehr** [comment] 2023-08-11 23:17
@akashlama1998-icloud, I was facing a similar issue and had to make vita a dependency (not devDependency).
