### ISSUE TITLE
Functions emulator needs pre-heating - slower test times on first test run

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-tools#3488] opened 2021-06-13 10:27 UTC
### Environment info

- macOS 11.4
- `firebase-tools` 9.12.1

### Test case

Running tests with Jest, execution times are ~1s longer on the first runs (~1700 ms vs. ~700 ms).

My expectation is that after launching Firebase Emulators, functions would be "pre-heated" so that their performance is relatively same. Only after this, Firebase emulator should "open shop" (start responding to the ports).

Note that this is not a timing issue. I can wait eg. 10 seconds between launching the emulators and running the first tests, and *also then* the first tests are slow.

### Steps to reproduce

```
$ git clone https://github.com/akauppi/firebase-jest-testing.git
$ cd firebase-jest-testing
$ npm install
```

In a separate terminal (starts the emulators):

```
$ npm run start
...
```

```
$ npm run test:fns:all
...
    ✓ Central user information is distributed to a project where the user is a member (1456 ms)
...
    ✓ returns a greeting (279 ms)
```

Now, run the same test again:

```
    ✓ Central user information is distributed to a project where the user is a member (698 ms)
...
    ✓ returns a greeting (74 ms)
```

I've noticed variations in these two tests.

Repeat (restart the server). The first test run again shows longer execution times.

### Expected behavior

The execution times of all test runs should be relatively similar, starting with the 1st run.

### Actual behavior

1st run involving Cloud Functions is slower.

### Why this matters

When running the tests in CI, it's always the _1st run_, with execution times ~1700 ms .. >2000 ms, leading to timeout:

```
    ✕ Central user information is distributed to a project where the user is a member (2005 ms)
```

To make the tests less flaky, I should increase the timeout, but would rather see this fixed in the Emulator level.

### Work-around

I can do the pre-heating in Jest `beforeAll` block (partial code): 

```
  beforeAll( () => {
    l = listener_EXP("projects/1/userInfo");
  })
```

This provides us a third set of test execution times - when someone's also pre-heated the Firestore client / Firebase Emulator communications (listens to the collection before the tests do).

```
    ✓ Central user information is distributed to a project where the user is a member (411 ms)
```

Execution times are now in the 278..411 ms window.

What we do here is simply moving some of the timing away from the tests; it affects the reports, but not really overall performance.

Even here, the first run is considerably slower:

```
    ✓ Central user information is distributed to a project where the user is a member (1173 ms)
```

### Notes

While lazy-loading functions is preferable in production - and occasional longer execution times are a known fact - this is not the case with emulation. In emulation, it is exactly the *initial run* that normally matters (gets reported).

**Comment by samtstern** [comment] 2021-06-14 09:25
@akauppi thank you for the detailed report! This is actually the intended behavior right now. The functions emulator is actually a swarm of subprocesses. Each function execution goes through a "worker" subprocess. If a worker finishes a request without an error, it stays warm/idle in a pool which is available to service future requests. So the first time you run a function we have to spawn a new worker, but the 2nd request can re-use the worker.  If two requests come in at once, we may re-use a worker for one request and spawn a new worker for the second.

In order to eliminate this performance hit we'd have to eagerly launch one worker per function at the time of starting the emulators. That is an unnecessarily greedy use of resources and could significantly slow down startup time on some platforms where spawning a subprocess is slow.  The most common emulator use case is starting the emulators fresh for each unit test run (CI, etc) in which case this "optimization" would actually make things slower overall, not faster.

So for those reasons I am going to close this issue as intended behavior for now, although if enough people disagree with me I am happy to revisit this decision in the future.

**Closed by samtstern** 2021-06-14 09:25 UTC

**Comment by akauppi** [comment] 2021-06-15 13:53
Thanks for the explanation, @samtstern 

```
 PASS  test-fns/userInfo.test.js
  userInfo shadowing
    ✓ Central user information is distributed to a project where the user is a member (3356 ms)
    ✓ Central user information is not distributed to a project where the user is not a member (847 ms)

 PASS  test-fns/logging.test.js
  Can proxy application logs
    ✓ good log entries (2013 ms)
```

My test results (on a fast machine) are so dismal (3356 ms vs 350 ms; 2013 ms vs 75 ms) that I think I'll do a "priming" script for the functions that wakes them up.

I am also optimising for CI. I do get your point on slowing the startup of emulators, but would claim that the right measure of CI to optimize for is "all tests pass". Your logic may lead to faster fails in certain cases, but for all tests to complete, the functions must be spawned up one time or the other.

Disclaimer: I do not claim to know how big companies do CI tests. Mine are petty (2 functions), but I might want to know more.

**Comment by samtstern** [comment] 2021-06-15 14:02
@akauppi that's extremely slow, I would expect the "cold start" delay to be more in the ~100ms range not 3 seconds. Can you try again with just a simple 'Hello World' function and measure the latency?

**Comment by akauppi** [comment] 2021-06-15 15:00
Sure. Here are the results:

||plain Firebase CLI|under Docker|
|---|---|---|
|cold start (ms)|950, 264|938, 791|
|subsequent (ms)|63, 56|66, 76, 61|

This is with a function that:

```
exports.greet = functions.https.onCall((msg, context) => {
    return `Greetings, ${msg}.`;
});
```

The Docker difference seems to be negligible (which is good news!).

Machine: Mac Mini 2018 (core i3), 16MB RAM

**Comment by akauppi** [comment] 2021-07-21 08:55
I implemented the "wake up" for Cloud Functions, yesterday.

As stated, the problem had become worse with Docker and I came to the following approach:

- when Cloud Functions are launched under emulation
   - not in CI (meaning: under Docker)
      - in addition to defining themselves, they also exercise the Cloud Functions immediately, thus waking them up.

I used the possibility to also log the delays of the wake-ups. They are:

- HTTPS callable: 4630 ms
- Watching Firestore and acting on it: 3537ms

>I would expect the "cold start" delay to be more in the ~100ms range not 3 seconds.

Well, it is not. :( I am perfectly fine with ~100ms time frame and that's something I would also expect.

Our joined goal is fast testing. 

>The most common emulator use case is starting the emulators fresh for each unit test run (CI, etc) 

I don't do unit tests on the Cloud Functions - only end-to-end tests. There, I try to minimise the number of times emulators are launched, because that itself is a long process.

But... as said, I left CI out of this, because it was not hitting timeouts (was under 2s per test). Let me know if something should be done about the Docker issue (I think it should!).

I suggest we add "Docker" mention to the title, and re-open the issue.

Sincerely,
to @samtstern

**Comment by samtstern** [comment] 2021-07-26 12:35
@akauppi I am actually no longer on the Firebase team so I think if you want someone to look into this issue it might be @yuchenshi or @abeisgoat 

Just out of curiosity I decided to try my own measurements with one simple emulatoed function:

```js
const functions = require("firebase-functions");

exports.helloWorld = functions.https.onRequest((request, response) => {
  response.json({
    time: new Date().toISOString()
  });
});
```

The first time I saw cold start of `253ms` and warm start of `37ms`:
```
$ time curl http://localhost:5001/demo-project-12345/us-central1/helloWorld
{"time":"2021-07-26T12:31:49.296Z"}
real    0m0.253s
user    0m0.015s
sys     0m0.063s
samstern@samstern-macbookpro3 tmp.Q8FySFUG 
$ time curl http://localhost:5001/demo-project-12345/us-central1/helloWorld
{"time":"2021-07-26T12:31:51.392Z"}
real    0m0.037s
user    0m0.013s
sys     0m0.020s
```

The second time was similar. Cold start of `191ms` and warm start of `43ms`:
```
$ time curl http://localhost:5001/demo-project-12345/us-central1/helloWorld
{"time":"2021-07-26T12:32:29.039Z"}
real    0m0.191s
user    0m0.012s
sys     0m0.019s
samstern@samstern-macbookpro3 tmp.Q8FySFUG 
$ time curl http://localhost:5001/demo-project-12345/us-central1/helloWorld
{"time":"2021-07-26T12:32:30.606Z"}
real    0m0.043s
user    0m0.015s
sys     0m0.021s
```

This is just on my 2018 Intel MacBook, so no Docker or anything. Clearly there is some large difference between your setup and mine, the goal should be to figure out what that is and then determine if there is an emulator-specific cold start issue which is not present in production.

**Comment by akauppi** [comment] 2021-07-26 12:43
@samtstern I'm sorry to hear you're no longer on the Firebase team. You were one of the best!!  (meaningful insights in issues and friendly attitude - well done)

>This is just on my 2018 Intel MacBook, so no Docker or anything. Clearly there is some large difference between your setup and mine, the goal should be to figure out what that is and then determine if there is an emulator-specific cold start issue which is not present in production.

I agree. I am relieved to know this is not everyone's problem. Anyways, I've made "defensive manoeuvres" on my side ;) so the pain this causes is currently under control. If I can narrow down to what's causing the sluggishness, I will - but that may be 2023 or 24.

And this issue is closed, so I think... all is fine. I wish you all the best in your current team.
