### ISSUE TITLE
firebase tools breaks result JSON with terminal escape sequences

### ISSUE THREAD

**Issue by muravjov** [firebase/firebase-tools#2368] opened 2020-06-16 12:38 UTC
### [REQUIRED] Environment info

**firebase-tools: 8.4.2**

**Platform: Ubuntu**

### [REQUIRED] Test case

```
$ curl -L https://firebase.tools/bin/linux/latest > ./firebase
$ chmod a+x ./firebase

$ ./firebase -V
8.4.2

$ GOOGLE_APPLICATION_CREDENTIALS=my-project-dev.json ./firebase --project my-project-dev firestore:indexes > ops/firestore.indexes.json 

$ git diff
diff --git a/ops/firestore.indexes.json b/ops/firestore.indexes.json
index 64ce58c..0b919c0 100644
--- a/ops/firestore.indexes.json
+++ b/ops/firestore.indexes.json
@@ -1,4 +1,4 @@
-{
+0;Firebase CLI^G{
   "indexes": [
     {
       "collectionGroup": "event",

```
### [REQUIRED] Steps to reproduce

Create a firebase project with some collections and indexes.
Run the commands from the test case above.

### [REQUIRED] Expected behavior

Result JSON is not broken

### [REQUIRED] Actual behavior

Result JSON file is prefixed with 
```
+0;Firebase CLI^G
```

**Comment by samtstern** [comment] 2020-06-16 12:48
This is a duplicate of #1774, potential fix is in #2330

**Closed by samtstern** 2020-06-16 12:48 UTC
