### ISSUE TITLE
Storage emulator import/export data error

### ISSUE THREAD

**Issue by rulaman123** [firebase/firebase-tools#4322] opened 2022-03-17 21:30 UTC
Hi, after starting the storage emulator with import the ui only shows a white page and i get that error:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
2react-dom.production.min.js:225 FirebaseError: Firebase Storage: Object '...' does not exist. (storage/object-not-found)
```

### [REQUIRED] Environment info

**firebase-tools:** v10.4.0

**Platform:** Windows

### [REQUIRED] Steps to reproduce

Upload image to storage emulator. 
Export image and close emulator.
Open storage emulator with import data.
Error.

**Comment by xero88** [comment] 2022-03-19 16:24
same issue for me, I throught it was related to my M1, but it's seams not. 

On my old mac (where it's ok) : firebase-cli version is 10.2.1
On my new mac (where it's bugged) : firebase-cli version is 10.4.0

**Comment by ermartinez13** [comment] 2022-03-22 15:43
I've been running into the same issue when I went from version 10.2.1 to 10.4.1. I downgraded to version 10.3.1 and found the bug still present. Only when I went back to v10.2.1 did the bug disappear.

**Comment by torstenek** [comment] 2022-03-25 11:07
Adding some more info:

### [REQUIRED] Environment info

I can reproduce this on 
- MB Pro M1 Max 
- MP Pro 2019

### [REQUIRED] Steps to reproduce

1. Start with an empty $FIREBASE_EMULATOR_DATA directory. 

2. Start the emulator with 

`firebase emulators:start --project myproject -only 'storage' --import $FIREBASE_EMULATOR_DATA --export-on-exit`

Now upload, for example, an image `myfile.jpg` to the bucket (for example by using the web UI). The problem is the same if you upload it via the firebase dart package. 

3. Stop the emulator gracefully and note the "Export complete" log entry indicating that everything went OK. 

4. Start the emulators again

`firebase emulators:start --project myproject -only 'storage' --import $FIREBASE_EMULATOR_DATA --export-on-exit`

Note the log message

`Could not find file "myproject%252Fmyfile.jpg" in storage export. `

5. Verify that the file is indeed missing from the storage emulator.

**Comment by torstenek** [comment] 2022-03-27 16:32
The sequence %252F in the filename could be the result of a double URI encoding.

**Comment by tonyjhuang** [comment] 2022-03-29 20:27
Potential duplicate of https://github.com/firebase/firebase-tools/issues/4326

**Comment by sceee** [comment] 2022-03-31 14:23
Jumping in here as I'm facing the same issue and have more information to add:
After starting the emulator with importing previously exported Storage data, accessing the storage bucket "directory" via the Emulator UI brings me to a white page with an exception in the browser:
```
FirebaseError: Firebase Storage: Object 'directory/subdirectory/filename' does not exist. (storage/object-not-found)
Not Found
```

I checked the `storage_export\blobs` directory in the file system and there, the file seems to be present but in my case the file name looks like this:
```
my-app.appspot.com%5Cdirectory%5Csubdirectory%5Cfilename
```
So in my case the `%5C` are URL encoded backslashes (probably because the export was made on Windows).
By the comments above I am unsure if that's also an issue. Shouldn't these be forward slashes (or url encoded forward slashes -> `%2F`) according to https://github.com/firebase/firebase-tools/issues/4322#issuecomment-1079965782 ?
I guess this will also be an issue when going cross-platform.

**Comment by alvinchevolleaux** [comment] 2022-04-04 18:33
I'm having the same issue of the blank page and error messages:
```
FirebaseError: Firebase Storage: Object 'filename.jpeg' does not exist. (storage/object-not-found)
Not Found

Failed to load resource: the server responded with a status of 404 (Not Found) :9199/v0/b/bucketname/filename.jpeg
```
with a subsequent
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

I do have URL encoding of the filenames in the exported storage blobs. They're in the following format `bucketname%2Ffilename.jpeg`. 

I'm on Mac OS with an Intel chip.

**Comment by coreform** [comment] 2022-04-05 05:37
I don't see any logs regarding imports to Storage when importing a production backup that uses Storage. The Emulator Suite Storage tab is also empty of files after such an import.

**Comment by tohhsinpei** [comment] 2022-04-05 18:32
Thanks all for the reports. The main issue looks like a duplicate of #4326 and should be fixed in #4358, which was included in yesterday's release. Let me know if the problem persists.

@sceee You're right, there is still an issue with importing/ exporting across platforms. I'll put in a fix sometime this week; will close this once that is in.

**Comment by sceee** [comment] 2022-04-05 18:44
@tohhsinpei thanks. I can confirm that the main issue (Emulator UI crashes on same OS export/import & file not available) is fixed with 10.5.0.

But importing a Windows export on a Mac still makes the emulator UI crash and the file not being available via the API as you wrote. I'm looking forward to the fix, thank you!

**Comment by coreform** [comment] 2022-04-06 01:41
When attempting to seed the emulators with a production backup with firestore-tools 10.6.0, firestore is populated but there is still no sign of Storage logs or data after: firebase emulators:start --import=../backupFolder/

**Comment by tonyjhuang** [comment] 2022-04-06 15:26
Hi @coreform, can you file a new issue? This seems unrelated to the original comment in this one.

**Comment by alvinchevolleaux** [comment] 2022-04-06 15:28
Can confirm this is working for me now using 10.6.0.

**Closed** 2022-04-08 17:00 UTC
Labels: emulator-suite, emulators: storage, bug
