### ISSUE TITLE
404 for Firebase SDKs from reserved URLs

### ISSUE THREAD

**Issue by aravindvnair99** [firebase/firebase-tools#2263] opened 2020-05-21 07:21 UTC
### Environment info

**firebase-tools:** 8.3.0

**Platform:** Windows 10 1909

### Test case

 Load Firebase SDKs from reserved URLs using `/__/firebase/js-sdk-version/firebase-sdk-name.js`

### Steps to reproduce

Add the necessary SDKs on the front-end and load the page with firebase-tools@8.3.0

### Expected behaviour

Scripts should be loaded successfully with HTTP status 200

### Actual behaviour

 Leads to HTTP status 404. The bug exists on 8.3.0 as if I roll back to 8.2.0, everything works fine.

**Comment by aravindvnair99** [comment] 2020-05-21 07:39
I'm not sure if this is what is causing the error: https://github.com/firebase/firebase-tools/commit/06580cedc6997913a06181ae7813d9c24ea3807e#diff-7761002eb017281bcdf91e9d8fbebdbbR53

I see a further commit to it after 8.3.0 was released: https://github.com/firebase/firebase-tools/commit/0bec742a91d490b9688e1bb36fb7894f078747f5

**Comment by jamescrowley** [comment] 2020-05-21 11:27
I have the same issue having upgraded to 8.3.0 on macOS. Downgrading to 8.2.0 fixes the issue.

**Comment by samtstern** [comment] 2020-05-21 14:10
This is a duplicate of #2248 which was a regression in `8.3.0`.  The current best workaround is to downgrade to `8.2.0` until the next release.

**Closed by samtstern** 2020-05-21 14:10 UTC
