### ISSUE TITLE
@angular-devkit/build-angular:browser (app:build:production) is not a recognized builder

### ISSUE THREAD

**Issue by sirozha** [firebase/firebase-tools#6908] opened 2024-03-25 06:29 UTC
Building the project via `ng build` succeeds, but after running the `firebase deploy --only hosting` command I get an error

```
Thank you for trying our early preview of Angular support on Firebase Hosting.
During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.

Documentation: https://firebase.google.com/docs/hosting/frameworks/angular
File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X


Error: @angular-devkit/build-angular:browser (app:build:production) is not a recognized builder. Please check your angular.json
```

### [REQUIRED] Environment info

13.5.2

**firebase-tools:**

13.5.2

**Platform:**

macOS

### [REQUIRED] Steps to reproduce

ng build && firebase deploy --only hosting

### [REQUIRED] Expected behavior

deploy success

### [REQUIRED] Actual behavior

firebase deploy --only hosting

**Comment by sirozha** [comment] 2024-03-30 04:07
@9kubczas4 Hi
Versions of angular 17.3.1 and 17.3.2 both reproduce the error

**Comment by iJinWei** [comment] 2024-04-02 02:59
@9kubczas4 Hi there any updates on this issue as I am having the same error as well I am using angular 17.3.2.

**Comment by dengoroff** [comment] 2024-04-02 11:34
Also works for me on version 17.3.2, thanks @sirozha  for raising issue

**Comment by henrylangenhoven** [comment] 2024-04-05 07:13
Same issue for me.

Angular CLI: 17.3.3
Node: 20.11.1
Package Manager: npm 10.5.0
OS: linux x64

Angular: 17.3.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@angular/fire                   17.0.1
@schematics/angular             17.3.3
rxjs                            7.8.1
typescript                      5.4.3
zone.js                         0.14.4
firebase                      10.9.0
firebase-tools            13.7.0

**Comment by henrylangenhoven** [comment] 2024-04-05 19:55
Hey @9kubczas4 

Here are two jobs where this happend:

- https://github.com/henrylangenhoven/bagtag/actions/runs/8551359576/job/23430322493
- https://github.com/henrylangenhoven/bagtag/actions/runs/8566274204/job/23475738315

I've since switched to a fresh firebase project, so the firebase project associated with these builds are no longer available. 
I should have a 3rd attempt branch available soon.

**Comment by henrylangenhoven** [comment] 2024-04-06 09:07
I've since generated a new Angular project from scratch, and did the same setup.
The preview deployments seems to be working fine: https://github.com/henrylangenhoven/try-angularfire/actions/runs/8579920572

So my current solution is to start my project from scratch.
Its early enough to do so for me.

Thanks @9kubczas4 for looking at it.

**Comment by 9kubczas4** [comment] 2024-04-12 17:54
@sirozha please let me if you have an example repository where I could reproduce this issue.

**Comment by aalej** [comment] 2024-04-23 14:18
I’m able to reproduce this issue using the information provided in https://github.com/firebase/firebase-tools/issues/7029. Sharing the [mcve](https://github.com/aalej/issues-7029) here.

**Comment by lenfromkits** [comment] 2024-04-30 05:31
Thanks @aalej .  Your workaround worked.  I edited my firebase.json file after the my steps listed in #7029 to reproduce the problem.  I changed my json from this:

```
{
  "hosting": [
    {
      "target": "app",
      "source": ".",
      "frameworksBackend": {}
    }
  ]
}
```

to this:

```
{
  "hosting": [
    {
      "target": "app",
      "public": "www",
      "frameworksBackend": {}
    }
  ]
}
```

And then I did a "firebase deploy" and it deployed.

**Comment by 9kubczas4** [comment] 2024-06-05 09:26
The issue was fixed by https://github.com/firebase/firebase-tools/pull/7264. It'll be available in the next release of `firebase-tools`.

**Closed by 9kubczas4** 2024-06-05 09:26 UTC
Labels: type: bug, Needs: Attention, integration: web frameworks
