### ISSUE TITLE
9.16.0 Timestamp disappears and destroys data that was created after it

### ISSUE THREAD

**Issue by honeyneeck** [firebase/firebase-tools#3650] opened 2021-08-08 17:06 UTC
### Environment info:

**firebase-tools:** 9.16.0

**Platform:** Windows10

### Test case for disappearing timestamps:

![2021-08-08 20-26-04_Trim](https://user-images.githubusercontent.com/22796372/128638981-6c4518b8-273a-4d5c-8a3d-afdc1bddb2c5.gif)

### Steps to reproduce disappearing timestamp:

1. Create a timestamp in any document
2. Refresh the page.

### Steps to reproduce disappearing values:

1. In a document or any other map, first create a timestamp and then create other data types below it.
2. Refresh the page

### Expected behavior

Timestamps should persist and not damage data declared after them.

### Actual behavior

Timestamps disappear and destroy data after them.

**This doesn't happen on the Live Firebase console.**

This also doesn't happen when creating document and providing values during its initialization using popup.

_I don't know how Firestore works, but my guess would be timestamps are lacking the "end" byte or something when created through the **Add field** option. Wonder if I am right :)_ 

<details>
<summary>Logs</summary>
[2021-08-08T17:01:24.419Z] [worker-~diagnostic~-23d389c1-7f88-4e95-9301-abbd4a9d6f0e]: IDLE {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~diagnostic~-23d389c1-7f88-4e95-9301-abbd4a9d6f0e]: IDLE"}}
[2021-08-08T17:01:32.321Z] Aug 08, 2021 9:01:32 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:01:32 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
[2021-08-08T17:01:32.581Z] Aug 08, 2021 9:01:32 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:01:32 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
[2021-08-08T17:01:33.203Z] Aug 08, 2021 9:01:33 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:01:33 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
[2021-08-08T17:02:09.163Z] Aug 08, 2021 9:02:09 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:02:09 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
[2021-08-08T17:03:22.167Z] Aug 08, 2021 9:02:09 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Aug 08, 2021 9:02:09 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Aug 08, 2021 9:02:09 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
Aug 08, 2021 9:02:20 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Aug 08, 2021 9:02:20 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Aug 08, 2021 9:02:21 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Aug 08, 2021 9:02:21 PM com.google.cloud.datastore.emulator.firestore.webchannel.JsonToProtoConverter toWriteRequest
WARNING: invalid message: {"streamToken":"MA==","writes":[{"update":{"name":"projects/portfolio-67c2f/databases/(default)/documents/companies/Bj8Ebbs6WAc3knBLKW1w","fields":{"timestamp":{"timestampValue":{"seconds":1628442138,"nanos":869000000}}}},"updateMask":{"fieldPaths":["timestamp"]},"currentDocument":{"exists":true}}]}
Aug 08, 2021 9:02:21 PM com.google.net.webchannel.server.common.ChannelProcessor run
WARNING: Failed to consume the event.
java.lang.RuntimeException: com.google.protobuf.InvalidProtocolBufferException: JsonObject
        at com.google.cloud.datastore.emulator.firestore.webchannel.JsonToProtoConverter.toWriteRequest(JsonToProtoConverter.java:33)
        at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.onMessage(FirestoreV1WebChannelAdapter.java:141)
        at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.onMessage(FirestoreV1WebChannelAdapter.java:111)
        at com.google.net.webchannel.server.v8.ChannelInternalImpl.onMessage(ChannelInternalImpl.java:485)
        at com.google.net.webchannel.server.v8.ForwardChannel.deliverMessage(ForwardChannel.java:114)
        at com.google.net.webchannel.server.v8.ForwardChannel.processPendingRequest(ForwardChannel.java:93)
        at com.google.net.webchannel.server.v8.ForwardChannel.consume(ForwardChannel.java:67)
        at com.google.net.webchannel.server.v8.ForwardChannel.add(ForwardChannel.java:60)
        at com.google.net.webchannel.server.v8.ChannelInternalImpl.handleRequestParams(ChannelInternalImpl.java:260)
        at com.google.net.webchannel.server.v8.ChannelInternalImpl.processSessionRequest(ChannelInternalImpl.java:317)
        at com.google.net.webchannel.server.v8.ChannelInternalImpl.handle(ChannelInternalImpl.java:142)
        at com.google.net.webchannel.server.v8.ChannelInternalImpl.consume(ChannelInternalImpl.java:78)
        at com.google.net.webchannel.server.common.ChannelProcessor.run(ChannelProcessor.java:80)
Caused by: com.google.protobuf.InvalidProtocolBufferException: JsonObject
        at com.google.cloud.datastore.emulator.firestore.webchannel.jsonformatfork.JsonFormat$ParserImpl.merge(JsonFormat.java:1348)
        at com.google.cloud.datastore.emulator.firestore.webchannel.jsonformatfork.JsonFormat$Parser.merge(JsonFormat.java:452)
        at com.google.cloud.datastore.emulator.firestore.webchannel.JsonToProtoConverter.toWriteRequest(JsonToProtoConverter.java:30)
        ... 12 more

 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:02:09 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\nAug 08, 2021 9:02:09 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\nAug 08, 2021 9:02:09 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected HTTP/2 connection.\r\nAug 08, 2021 9:02:20 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\nAug 08, 2021 9:02:20 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\nAug 08, 2021 9:02:21 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\nAug 08, 2021 9:02:21 PM com.google.cloud.datastore.emulator.firestore.webchannel.JsonToProtoConverter toWriteRequest\r\nWARNING: invalid message: {\"streamToken\":\"MA==\",\"writes\":[{\"update\":{\"name\":\"projects/portfolio-67c2f/databases/(default)/documents/companies/Bj8Ebbs6WAc3knBLKW1w\",\"fields\":{\"timestamp\":{\"timestampValue\":{\"seconds\":1628442138,\"nanos\":869000000}}}},\"updateMask\":{\"fieldPaths\":[\"timestamp\"]},\"currentDocument\":{\"exists\":true}}]}\r\nAug 08, 2021 9:02:21 PM com.google.net.webchannel.server.common.ChannelProcessor run\r\nWARNING: Failed to consume the event.\r\njava.lang.RuntimeException: com.google.protobuf.InvalidProtocolBufferException: JsonObject\r\n\tat com.google.cloud.datastore.emulator.firestore.webchannel.JsonToProtoConverter.toWriteRequest(JsonToProtoConverter.java:33)\r\n\tat com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.onMessage(FirestoreV1WebChannelAdapter.java:141)\r\n\tat com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.onMessage(FirestoreV1WebChannelAdapter.java:111)\r\n\tat com.google.net.webchannel.server.v8.ChannelInternalImpl.onMessage(ChannelInternalImpl.java:485)\r\n\tat com.google.net.webchannel.server.v8.ForwardChannel.deliverMessage(ForwardChannel.java:114)\r\n\tat com.google.net.webchannel.server.v8.ForwardChannel.processPendingRequest(ForwardChannel.java:93)\r\n\tat com.google.net.webchannel.server.v8.ForwardChannel.consume(ForwardChannel.java:67)\r\n\tat com.google.net.webchannel.server.v8.ForwardChannel.add(ForwardChannel.java:60)\r\n\tat com.google.net.webchannel.server.v8.ChannelInternalImpl.handleRequestParams(ChannelInternalImpl.java:260)\r\n\tat com.google.net.webchannel.server.v8.ChannelInternalImpl.processSessionRequest(ChannelInternalImpl.java:317)\r\n\tat com.google.net.webchannel.server.v8.ChannelInternalImpl.handle(ChannelInternalImpl.java:142)\r\n\tat com.google.net.webchannel.server.v8.ChannelInternalImpl.consume(ChannelInternalImpl.java:78)\r\n\tat com.google.net.webchannel.server.common.ChannelProcessor.run(ChannelProcessor.java:80)\r\nCaused by: com.google.protobuf.InvalidProtocolBufferException: JsonObject\r\n\tat com.google.cloud.datastore.emulator.firestore.webchannel.jsonformatfork.JsonFormat$ParserImpl.merge(JsonFormat.java:1348)\r\n\tat com.google.cloud.datastore.emulator.firestore.webchannel.jsonformatfork.JsonFormat$Parser.merge(JsonFormat.java:452)\r\n\tat com.google.cloud.datastore.emulator.firestore.webchannel.JsonToProtoConverter.toWriteRequest(JsonToProtoConverter.java:30)\r\n\t... 12 more\r\n\r\n"}}
[2021-08-08T17:03:24.022Z] Aug 08, 2021 9:03:24 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Aug 08, 2021 9:03:24 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:03:24 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\nAug 08, 2021 9:03:24 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
[2021-08-08T17:03:24.032Z] Aug 08, 2021 9:03:24 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:03:24 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
[2021-08-08T17:03:24.353Z] Aug 08, 2021 9:03:24 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketChannelHandler initChannel
INFO: Connected to new websocket client
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:03:24 PM com.google.cloud.datastore.emulator.firestore.websocket.WebSocketChannelHandler initChannel\r\nINFO: Connected to new websocket client\r\n"}}
[2021-08-08T17:03:32.087Z] Aug 08, 2021 9:03:32 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:03:32 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
[2021-08-08T17:03:34.593Z] Aug 08, 2021 9:03:34 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:03:34 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
[2021-08-08T17:03:34.851Z] Aug 08, 2021 9:03:34 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:03:34 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
[2021-08-08T17:03:34.927Z] Aug 08, 2021 9:03:34 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:03:34 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
[2021-08-08T17:03:36.022Z] Aug 08, 2021 9:03:36 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Aug 08, 2021 9:03:36 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\r\nINFO: Detected non-HTTP/2 connection.\r\n"}}
</details>

**Comment by honeyneeck** [comment] 2021-08-08 17:08
@google-oss-bot  Could you instead save me free work and tell exactly what I am missing? Bot.

**Comment by yuchenshi** [comment] 2021-08-09 20:46
Duplicate of https://github.com/firebase/firebase-tools-ui/issues/617

**Closed by yuchenshi** 2021-08-09 20:46 UTC

**Comment by yuchenshi** [comment] 2021-08-11 21:11
Fix released in Firebase CLI v9.16.1.
