### ISSUE TITLE
Cannot read property lookup of undefined 

### ISSUE THREAD

**Issue by clentoo** [firebase/firebase-tools#3171] opened 2021-02-18 11:28 UTC
I am trying to use Cloud functions to work on payment authentication with stripe in an e-commerce store project. The code for the index.js file after installing functions using firebase CLI goes thus:

```js
const functions = require("firebase-functions");
const express = require("express");
const cors = require("cors");

// API

// App Config
const app = express();

// Middlewares
app.use(cors({origin: true}));
app.use(express.json());
app.use(express.static("public"));

// API routes
app.get("/api/",
    (request, response) => response.status(200).send("hello world"));

// Listen Command
exports.api = functions.https.onRequest(app);
```

To emulate before deploying I run firebase emulators:start in the command line and get this error immediately I click on the link to access the emulator UI in chrome:

```
TypeError: Cannot read property 'lookup' of undefined
    at ServerResponse.header (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:766:37)
    at ServerResponse.json (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:264:10)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\hub.js:29:17
    at Layer.handle [as handle_request] (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\body-parser\lib\types\json.js:110:7)
    at Layer.handle [as handle_request] (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\router\index.js:275:10)

```

**Comment by yuchenshi** [comment] 2021-02-24 00:37
This seems to be an issue with the Emulator Hub API, a server in `firebase-tools` repo. Transferring over there. @samtstern would you mind taking a look?

**Comment by samtstern** [comment] 2021-02-26 18:16
@clentoo I was not able to reproduce this. I copied your `index.js` and `package.json` exactly into a brand new project. I am able to run `emulators:start` successfully and then access the Emulator UI.

I am also able to curl the function:
```
$ curl http://localhost:5050/fir-dumpster/us-central1/api/api/
hello world
```

**Comment by clentoo** [comment] 2021-02-27 13:41
Wow. The only thing I noticed is my node version in the project is 12 but my global version on my laptop is 12.18.0. Also, the firebase-admin remains 9.2.0 in the package.json file even after running npm install -g firebase-tools@latest.

**Comment by samtstern** [comment] 2021-03-02 16:41
@clentoo ok well in the meantime there's not much we can do since I can't actually get this error to happen on my side. If you can figure out how we can reproduce it more reliably please let me know!

**Comment by samtstern** [comment] 2021-03-02 16:41
> Also, the firebase-admin remains 9.2.0 in the package.json file even after running npm install -g firebase-tools@latest.

That's expected unless you add `--save`

**Closed** 2021-03-16 01:00 UTC
Labels: Needs: Author Feedback, closed-by-bot, no-recent-activity
