### ISSUE TITLE
Functions emulator can't bind correctly to non-localhost IP on Linux

### ISSUE THREAD

**Issue by bitfabrikken** [firebase/firebase-tools#1769] opened 2019-11-05 13:15 UTC
### [REQUIRED] Environment info

**firebase-tools:**
7.6.2

**Platform:**
Debian 10 (Buster)
nodejs v8.16.2

### [REQUIRED] Test case
Use an ip for host in firebase.json that's not localhost and 127.0.0.1, e.g.:
```firebase.json
{
  "functions": {
    "predeploy": [],
    "region": "europe-west1",
    "source": "functions",
    "host": "10.0.10.2",
    "port": 5000
  },
  "emulators": {
    "functions": {
      "host": "10.0.10.2",
      "port":5000
    },
    "firestore": {
      "rules": "firestore.rules",
      "indexes": "firestore.indexes.json",
      "host": "10.0.10.2",
      "port": 8000
    }
  }
}
```

### [REQUIRED] Steps to reproduce
start emulator with "firebase emulators:start --only functions"
output: 
```
i  Starting emulators: ["functions"]
✔  functions: Using node@8 from host.
Error: TIMEOUT: Port 5000 was not active within 30000ms
```

### [REQUIRED] Expected behavior
Should start listening on the host suppplied in firebase.json and keep doing it

### [REQUIRED] Actual behavior
Listens for 30 seconds, then returns the error "Error: TIMEOUT: Port 5000 was not active within 30000ms"
If I change host from 10.0.10.2 to localhost or 127.0.0.1 in firebase.json, everything works just fine.

EDIT: I just found out that during the 30 second "hang", the emulator is actually active and listening and serving functions. I confirmed this by going to http://10.0.10.2:5000 in a browser and got {"status":"alive"}
It would appear there's some kind of issue where the emulator can't detect that it actually succeeds in listening.

--debug doesn't help much:
```
firebase emulators:start --only functions --debug
[2019-11-05T13:05:19.840Z] ----------------------------------------------------------------------
[2019-11-05T13:05:19.843Z] Command:       /home/dan/.nvm/versions/node/v8.16.2/bin/node /home/dan/.nvm/versions/node/v8.16.2/bin/firebase emulators:start --only functions --debug
[2019-11-05T13:05:19.843Z] CLI Version:   7.6.2
[2019-11-05T13:05:19.843Z] Platform:      linux
[2019-11-05T13:05:19.843Z] Node Version:  v8.16.2
[2019-11-05T13:05:19.843Z] Time:          Tue Nov 05 2019 14:05:19 GMT+0100 (CET)
[2019-11-05T13:05:19.843Z] ----------------------------------------------------------------------
[2019-11-05T13:05:19.843Z] 
i  Starting emulators: ["functions"]
✔  functions: Using node@8 from host.
i  Shutting down emulators.

Error: TIMEOUT: Port 5000 was not active within 30000ms
```

**Comment by bitfabrikken** [comment] 2019-11-05 13:20
Just to clarify - ip and port 10.0.10.2:5000 is working and available on my machine - have confirmed that with other servers, e.g. react-native's metro bundler on port 8081

**Comment by samtstern** [comment] 2019-11-05 18:16
@bitfabrikken thanks for this!  This is a duplicate of https://github.com/firebase/firebase-tools/issues/1722.  I am going to close this, I added some of your details there.

**Closed by samtstern** 2019-11-05 18:16 UTC
