### ISSUE TITLE
Firebase emulator doesn't allow editing timestamps

### ISSUE THREAD

**Issue by jakeleventhal** [firebase/firebase-tools#4534] opened 2022-05-08 15:56 UTC
### [REQUIRED] Environment info

**firebase-tools:** 10.7.1

**Platform:** macOS

### [REQUIRED] Test case

Have a timestamp stored in the emulator - you can't edit it in the UI

### [REQUIRED] Steps to reproduce

Have a timestamp stored in the emulator - you can't edit it in the UI.

### [REQUIRED] Expected behavior

UI allows editing

### [REQUIRED] Actual behavior

<img width="734" alt="Screen Shot 2022-05-08 at 11 55 16 AM" src="https://user-images.githubusercontent.com/15133828/167304429-b9a81d8c-f348-48b0-bd66-834440a591dc.png">

**Comment by yuchenshi** [comment] 2022-05-09 20:11
Duplicate of https://github.com/firebase/firebase-tools-ui/issues/601,

Please let us know the browser and version you're using by commenting on the issue above -- this may be browser-specific.

**Closed by yuchenshi** 2022-05-09 20:11 UTC
Labels: bug
