### ISSUE TITLE
Error: Unexpected server error. At /.inspect/coverage.json?ns=foo

### ISSUE THREAD

**Issue by intersrc** [firebase/firebase-tools#1537] opened 2019-07-23 13:24 UTC
### [REQUIRED] Environment info

**firebase-tools:** 7.1.1

**Platform:** macOS

### [REQUIRED] Test case

The example project from:
https://github.com/firebase/quickstart-nodejs/tree/master/database-emulator/javascript-quickstart

### [REQUIRED] Steps to reproduce

1. Start up a Database Emulator
2. Visit http://localhost:9000/.inspect/coverage.json?ns=foo

### [REQUIRED] Expected behavior

No error occurs.

### [REQUIRED] Actual behavior

The page shows:
```
{
  "error" : "Unexpected server error"
}
```

And here is the log:
```log
20:49:58.413 [NamespaceSystem-akka.actor.default-dispatcher-3] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
20:49:58.622 [main] INFO com.firebase.server.forge.App$ - Listening on port 9000
20:50:39.569 [FirebaseWorkerPool-1-4] ERROR com.firebase.server.forge.FakeServerChannelHandlers$$anon$5$$anon$7 - Some other error happened on: [NamespaceRequest namespace=database-emulator-example path=List(.inspect, coverage) suffix=JsonSuffix params=com.firebase.server.http.HttpRequestParameters@2342754 request=HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
GET /.inspect/coverage.json?ns=database-emulator-example HTTP/1.1
Host: localhost:9000
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Cookie: _ga=GA1.1.1901127390.1530592416; brzcrz_local=203f6781-aa16-4510-b425-591a3861c6fe; Webstorm-392ea4b6=2846d058-128d-450f-b339-3fcd5f44c57c
Content-Length: 0 isLocalRequest=true remoteAddress=/127.0.0.1:61835 userAgent=None]
java.lang.NullPointerException: null
	at com.firebase.server.rest.RestRouter.runHandler(RestRouter.scala:74)
	at com.firebase.server.rest.RestRouter.$anonfun$route$4(RestRouter.scala:67)
	at com.firebase.util.result.package$Result.flatMap(package.scala:56)
	at com.firebase.util.result.package$Result.flatMap$(package.scala:54)
	at com.firebase.util.result.package$Value.flatMap(package.scala:163)
	at com.firebase.server.rest.RestRouter.$anonfun$route$2(RestRouter.scala:66)
	at com.firebase.util.result.package$Result.flatMap(package.scala:56)
	at com.firebase.util.result.package$Result.flatMap$(package.scala:54)
	at com.firebase.util.result.package$Value.flatMap(package.scala:163)
	at com.firebase.server.rest.RestRouter.route(RestRouter.scala:64)
	at com.firebase.server.rest.RestInspectHandler.handleGet(RestInspectHandler.scala:76)
	at com.firebase.server.rest.RestInspectHandler.handleGet$(RestInspectHandler.scala:75)
	at com.firebase.server.rest.RestInspectJsonHandler.handleGet(RestInspectHandler.scala:86)
	at com.firebase.server.rest.RestHandler.processRequest(RestHandler.scala:171)
	at com.firebase.server.rest.RestHandler.handleIncomingRequest(RestHandler.scala:134)
	at com.firebase.server.rest.RestHandler.$anonfun$handleLocalRequest$1(RestHandler.scala:108)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by samtstern** [comment] 2019-07-23 15:38
@IanWyszynski or @ryanpbrewster want to take a look at this one?

**Comment by ryanpbrewster** [comment] 2019-07-23 18:42
I cannot reproduce this. Does this error occur reliably?

**Comment by intersrc** [comment] 2019-07-24 03:27
> I cannot reproduce this. Does this error occur reliably?

Yes.
Is something missing in my Java environment?
My Java version:
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by ryanpbrewster** [comment] 2019-07-24 04:40
Yep, that's it. Tracking down the issue now.

**Comment by ryanpbrewster** [comment] 2019-07-24 07:21
Found a fix, I'll update this issue when it's released.

**Comment by ryanpbrewster** [comment] 2019-07-24 22:02
Fixed by https://github.com/firebase/firebase-tools/pull/1543, which will go out with the next release. Thanks for reporting this :)

**Closed by ryanpbrewster** 2019-07-24 22:02 UTC
Labels: emulator-suite, emulators: database
