### ISSUE TITLE
Firebase Storage Triggers "onObjectFinalized" when creating a "folder" in the Emulator UI.

### ISSUE THREAD

**Issue by lucasdavidferrero** [firebase/firebase-tools#7388] opened 2024-06-26 12:22 UTC
### [REQUIRED] Environment info

**firebase-tools: 13.11.2**

**Platform: Windows 10**

### [REQUIRED] Test case
1. Create a folder from de Emulators UI
2. Trigger get executed.

### [REQUIRED] Steps to reproduce
In the emulators UI under Storage tab, you click the button "create new folder". Create a new folder then.
![2024-06-26_09h13_38](https://github.com/firebase/firebase-tools/assets/15804058/359f5a39-eb61-49f5-927f-b76cfe33d98c)

After that, a cloud function trigger gets executed:
```js
export const resizeImage = onObjectFinalized({
    region: 'southamerica-east1',
    cpu: 2,
    timeoutSeconds: 120,
    memory: '512MiB',
    retry: true
}, async (event: CloudEvent<StorageObjectData>) => {
        const fileBucket = event.data.bucket;
        const filePath = event.data.name as string;
        const contentType = event.data.contentType as string;

        // Check if the object created is a folder
        if (contentType === 'application/octet-stream') {
            return logger.log("Object created is a folder. Skipping processing.");
        }
}
```
The condition gets evaluated truly, and the console shows the log. 

### [REQUIRED] Expected behavior
Trigger should not be executed if we create a folder.

### [REQUIRED] Actual behavior
Trigger gets triggered when we create only a folder from the Emulators UI.

It was discussed in S.O: [https://stackoverflow.com/questions/78662447/how-to-know-that-an-object-is-a-folder-using-cloud-functions-with-cloud-storage?noredirect=1#comment138687370_78662447](https://stackoverflow.com/questions/78662447/how-to-know-that-an-object-is-a-folder-using-cloud-functions-with-cloud-storage?noredirect=1#comment138687370_78662447)

**Comment by aalej** [comment] 2024-06-28 11:29
Hey @lucasdavidferrero, thanks for creating a detailed report. I followed the steps you provided and was able to reproduce the behavior on the emulators. However, I also tried deploying this on an actual project and got the same results.

I deployed the function you provided and added some changes for logging:
```js
import { logger } from "firebase-functions";
import { onObjectFinalized } from "firebase-functions/v2/storage";

export const resizeImage = onObjectFinalized(async (event) => {
   logger.log("onObjectFinalized start")
   const fileBucket = event.data.bucket;
   const filePath = event.data.name;
   const contentType = event.data.contentType;

   logger.log(filePath)

   // Check if the object created is a folder
   if (contentType === 'application/octet-stream') {
       return logger.log("Object created is a folder. Skipping processing.");
   }
})
```
After deploying, I created a new folder using the Firebase Console and checked if the function was executed:

![image](https://github.com/firebase/firebase-tools/assets/118378103/e566388d-3928-4367-9647-1d8b4fea8fcc)

Given that the emulator matches the behavior on production, I think this is working as intended. That said, I’ll go ahead and close this.

**Closed by aalej** 2024-06-28 11:29 UTC
Labels: type: bug, emulators: functions, emulators: storage
