### ISSUE TITLE
`firebase deploy` progress shows `NaN/undefined` sometimes

### ISSUE THREAD

**Issue by bmeurer** [firebase/firebase-tools#1028] opened 2018-11-20 06:44 UTC
Using `firebase deploy` on a project sometimes gives a weird progress, see [screenshot](https://pbs.twimg.com/media/DsS34daXoAYZl_x.jpg).

![Screenshot](https://pbs.twimg.com/media/DsS34daXoAYZl_x.jpg)

### Version info

```
$ firebase --version
6.1.0
$ node --version
v10.1.0
```

### Platform Information

macOS 10.13.6

### Steps to reproduce

Doesn't happen all the time, got it like 10% of the times with just

```
firebase deploy
```

### Expected behavior

Show proper progress, i.e. `123/321`

### Actual behavior

Shows messed up progress `NaN/undefined` (the `NaN` is probably there because of `undefined` is converted to a Number somewhere).

**Comment by bkendall** [comment] 2018-11-20 18:34
Dupe of #1020

**Closed by bkendall** 2018-11-20 18:34 UTC
Labels: duplicate
