### ISSUE TITLE
url_launcher not working from firebase

### ISSUE THREAD

**Issue by eugeneH1** [firebase/firebase-tools#6335] opened 2023-09-08 06:04 UTC
### [REQUIRED] Environment info

12.4.7

**firebase-tools:**

macOS

**Platform:**

### [REQUIRED] Test case

I've tried various implementations of url_launcher, specifically I want to phone number to open on the phone app and email addressed to open in default mail client.
Note: This is a flutter web project not a mobile app. 
It runs in debug and release build from local host but does nothing when running from firebase.

### [REQUIRED] Steps to reproduce

access my website "www.dtl-solutions.co.za" click on contact us. An error that I can't understand is being found in the
main.dart.js file.

### [REQUIRED] Expected behavior

When running in a browser on a mobile phone, the phone number should be called using the default caller client and when email is clicked it should open default email client with email address filled ink

### [REQUIRED] Actual behavior

when I inspect the browser it point me to an error in the main.dart.js file

**Comment by eugeneH1** [comment] 2023-09-08 06:05
Additional note: flutter channel -> stable
plugins are all the latest

**Comment by aalej** [comment] 2023-09-08 09:13
Hi @eugeneH1. It’s currently a bit difficult to narrow down if the issue is caused by the url_launcher Flutter package, Firebase Tools deployment to Hosting, or something else entirely. Could you provide additional information such as, but not limited to:

- The error message you’re encountering 
- Steps you took to deploy your Flutter app to Firebase Hosting. 
- Confirmation if you are using the [Web Frameworks](https://firebase.google.com/docs/hosting/frameworks/flutter) feature to deploy your app
- A [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example). It would be easier to debug and investigate what caused the issue in an MCVE compared to an actual app

Thanks!

**Comment by eugeneH1** [comment] 2023-09-08 09:45
Hi @aalej  thanks so much for your reply!

Uncaught MissingPluginException(No implementation found for method launch on channel plugins.flutter.io/url_launcher)

I used the firebase cli tool from Android Studio to deploy the project.
I believe the commands were:
firebase experiments:enable webframeworks
firebase init hosting
firebase deploy

I've also tried redeploying with "firebase deploy --only hosting"

Please let me know if there's any more information I can give you.
Thanks very much for the help!!

**Comment by eugeneH1** [comment] 2023-09-08 09:46
@aalej 
I forgot to mention that I get no errors when running in debug from android studio or when using "flutter run --release"

**Comment by eugeneH1** [comment] 2023-09-08 10:29
I've managed to resolve the issue. 
I ran "flutter clean" followed by "flutter pub get" and then redeployed using "firebase deploy --only hosting"

**Comment by aalej** [comment] 2023-09-08 11:10
That’s good to hear, @eugeneH1. Thanks for letting us know that the issue is now resolved. I’ll go ahead and close this. Based on the solution you provided, it seems like this might be more related to the Flutter package, I would recommend filling an issue in [Flutter GitHub repository](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+url_launcher%22) if you encounter any issues moving forward.

**Closed by aalej** 2023-09-08 11:10 UTC
Labels: type: bug, Needs: Attention, integration: web frameworks
