### ISSUE TITLE
Can't use `firebase`in Google Cloud Shell

### ISSUE THREAD

**Issue by steren** [firebase/firebase-tools#4598] opened 2022-05-30 23:24 UTC
```
$ firebase --version
/usr/local/nvm/versions/node/v16.1.0/lib/node_modules/firebase-tools/lib/emulator/portUtils.js:9
dns.setDefaultResultOrder("ipv4first");
    ^

TypeError: dns.setDefaultResultOrder is not a function
    at Object.<anonymous> (/usr/local/nvm/versions/node/v16.1.0/lib/node_modules/firebase-tools/lib/emulator/portUtils.js:9:5)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/usr/local/nvm/versions/node/v16.1.0/lib/node_modules/firebase-tools/lib/emulator/registry.js:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    ```

**Comment by bkendall** [comment] 2022-05-30 23:36
Duplicate of #4580.

Please update your node version to >= 16.2.0

**Closed by bkendall** 2022-05-30 23:36 UTC
Labels: bug
