### ISSUE TITLE
Cloud Runtime Config is currently experiencing issues and not able to deploy

### ISSUE THREAD

**Issue by chasemorell** [firebase/firebase-tools#7958] opened 2024-11-16 17:00 UTC
### [REQUIRED] Environment info

**firebase-tools:** 13.25.0

**Platform:** macOS

### [REQUIRED] Test case
when running firebase deploy --only functions i get the following error:

`Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.`

### [REQUIRED] Steps to reproduce

Run firebase deploy --only functions on a Firebase Project

### [REQUIRED] Expected behavior

Not to fail

### [REQUIRED] Actual behavior

`[2024-11-16T16:55:51.158Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2024-11-16T16:55:51.159Z] > authorizing via signed-in user (MYEMAIL)
[2024-11-16T16:55:51.159Z] [iam] checking project myproject for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[2024-11-16T16:55:51.159Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:51.160Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:51.160Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/myproject:testIamPermissions [none]
[2024-11-16T16:55:51.160Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/myproject:testIamPermissions x-goog-quota-user=projects/myproject
[2024-11-16T16:55:51.160Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/myproject:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}
[2024-11-16T16:55:51.374Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/myproject:testIamPermissions 200
[2024-11-16T16:55:51.374Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/myproject:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}
[2024-11-16T16:55:51.374Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:51.374Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:51.375Z] >>> [apiv2][query] POST https://iam.googleapis.com/v1/projects/myproject/serviceAccounts/myproject@appspot.gserviceaccount.com:testIamPermissions [none]
[2024-11-16T16:55:51.375Z] >>> [apiv2][body] POST https://iam.googleapis.com/v1/projects/myproject/serviceAccounts/myproject@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[2024-11-16T16:55:51.630Z] <<< [apiv2][status] POST https://iam.googleapis.com/v1/projects/myproject/serviceAccounts/myproject@appspot.gserviceaccount.com:testIamPermissions 200
[2024-11-16T16:55:51.630Z] <<< [apiv2][body] POST https://iam.googleapis.com/v1/projects/myproject/serviceAccounts/myproject@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}

=== Deploying to 'myproject'...

i  deploying functions 
✔  functions: Finished running predeploy script. 
[2024-11-16T16:55:51.632Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:51.632Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:51.632Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/myproject [none]
[2024-11-16T16:55:52.035Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/myproject 200
[2024-11-16T16:55:52.036Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/myproject {"projectId":"myproject","projectNumber":"REDACTED","displayName":"myproject","name":"projects/myproject","resources":{"hostingSite":"myproject","realtimeDatabaseInstance":"myproject-default-rtdb","storageBucket":"myproject.appspot.com","locationId":"us-central"},"state":"ACTIVE","etag":"REDACTED"}
i  functions: preparing codebase default for deployment 
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled... 
[2024-11-16T16:55:52.036Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:52.037Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:52.037Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:52.037Z] Checked if tokens are valid: true, expires at: 1731778057819
i  functions: ensuring required API cloudbuild.googleapis.com is enabled... 
[2024-11-16T16:55:52.037Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:52.037Z] Checked if tokens are valid: true, expires at: 1731778057819
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled... 
[2024-11-16T16:55:52.037Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:52.037Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:52.037Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/cloudfunctions.googleapis.com [none]
[2024-11-16T16:55:52.037Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/cloudfunctions.googleapis.com x-goog-quota-user=projects/myproject
[2024-11-16T16:55:52.038Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/runtimeconfig.googleapis.com [none]
[2024-11-16T16:55:52.038Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/runtimeconfig.googleapis.com x-goog-quota-user=projects/myproject
[2024-11-16T16:55:52.039Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/cloudbuild.googleapis.com [none]
[2024-11-16T16:55:52.039Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/cloudbuild.googleapis.com x-goog-quota-user=projects/myproject
[2024-11-16T16:55:52.039Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/artifactregistry.googleapis.com [none]
[2024-11-16T16:55:52.040Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/artifactregistry.googleapis.com x-goog-quota-user=projects/myproject
[2024-11-16T16:55:52.465Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/cloudfunctions.googleapis.com 200
[2024-11-16T16:55:52.465Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/cloudfunctions.googleapis.com [omitted]
✔  functions: required API cloudfunctions.googleapis.com is enabled 
[2024-11-16T16:55:52.478Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/artifactregistry.googleapis.com 200
[2024-11-16T16:55:52.478Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/artifactregistry.googleapis.com [omitted]
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled 
[2024-11-16T16:55:52.487Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/cloudbuild.googleapis.com 200
[2024-11-16T16:55:52.487Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/cloudbuild.googleapis.com [omitted]
✔  functions: required API cloudbuild.googleapis.com is enabled 
[2024-11-16T16:55:52.513Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/runtimeconfig.googleapis.com 200
[2024-11-16T16:55:52.513Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/myproject/services/runtimeconfig.googleapis.com [omitted]
[2024-11-16T16:55:52.513Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:52.513Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:52.513Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/myproject/adminSdkConfig [none]
[2024-11-16T16:55:53.077Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/myproject/adminSdkConfig 200
[2024-11-16T16:55:53.077Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/myproject/adminSdkConfig {"projectId":"myproject","databaseURL":"https://myproject-default-rtdb.firebaseio.com","storageBucket":"myproject.appspot.com","locationId":"us-central"}
[2024-11-16T16:55:53.078Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:53.078Z] Checked if tokens are valid: true, expires at: 1731778057819
[2024-11-16T16:55:53.078Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/myproject/configs [none]
[2024-11-16T16:55:53.406Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/myproject/configs 500
[2024-11-16T16:55:53.406Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/myproject/configs {"error":{"code":500,"message":"Internal error encountered.","status":"INTERNAL"}}
[2024-11-16T16:55:54.409Z] *** [apiv2] Attempting the request again. Attempt number 2
[2024-11-16T16:55:54.410Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/myproject/configs [none]
[2024-11-16T16:55:54.620Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/myproject/configs 500
[2024-11-16T16:55:54.620Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/myproject/configs {"error":{"code":500,"message":"Internal error encountered.","status":"INTERNAL"}}
Request to https://runtimeconfig.googleapis.com/v1beta1/projects/myproject/configs had HTTP Error: 500, Internal error encountered.

Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.`

**Comment by arcaughey** [comment] 2024-11-16 17:10
I am experiencing this issue also when attempting to deploy a single function from the CLI using the command firebase deploy --only functions:functionName --debug :  {"error":{"code":500,"message":"Internal error encountered.","status":"INTERNAL"}}
Request to https://runtimeconfig.googleapis.com/v1beta1/projects/.../configs had HTTP Error: 500, Internal error encountered.

Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.

**Comment by dondy1996** [comment] 2024-11-16 18:37
I also have this issue as of today

**Comment by marie2** [comment] 2024-11-16 21:23
same here !

**Comment by inf3rnus** [comment] 2024-11-17 01:12
same

**Comment by OrcunJoyoLabs** [comment] 2024-11-17 01:45
+1

**Comment by KarthikNedunchezhiyan** [comment] 2024-11-17 01:59
Facing the same problem.

**Comment by jpv123** [comment] 2024-11-17 02:36
Unfortunately the issue has persisted throughout the day, I have been attempting multiple times since this morning but it appears that Google has not yet detected the outage. This is evident from the status page for both GCP and Firebase which do not acknowledge the problem.

**Comment by juanmosv** [comment] 2024-11-17 02:44
+1

**Comment by KarthikNedunchezhiyan** [comment] 2024-11-17 04:06
I see my deployments are working now.

**Comment by revmatchcrew** [comment] 2024-11-17 05:27
Someone figured out a temporary workaround: https://github.com/firebase/firebase-tools/issues/7341#issuecomment-2480906838

**Comment by dannycortesv** [comment] 2024-11-17 10:36
Same here!

**Comment by juan-carvajal** [comment] 2024-11-17 14:40
Experiencing exact same issue

**Comment by juan-carvajal** [comment] 2024-11-17 14:41
Workaround described here appears to work: https://github.com/firebase/firebase-tools/issues/7341#issuecomment-2480906838

**Comment by diegoesolorzano** [comment] 2024-11-17 16:08
I am having the same issue since yesterday. Is it still happening or is it only me?

**Comment by rscsam** [comment] 2024-11-17 18:50
> Workaround described here appears to work: [#7341 (comment)](https://github.com/firebase/firebase-tools/issues/7341#issuecomment-2480906838)

This will solve your issue, but please do not do this if you used `firebase functions:config:set` to set runtime environment variables. If you are working with an older functions codebase that does not use the new environment approach, this will likely break your application.

**Comment by sandrocodigo** [comment] 2024-11-17 18:59
Tengo el mismo problema: Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.

**Comment by galvarez-designli** [comment] 2024-11-17 20:07
Same here while trying to deploy functions

**Comment by andresfelipe9619** [comment] 2024-11-17 20:25
same here

**Comment by vasquez1805** [comment] 2024-11-17 23:17
Facing same issue

**Comment by ReedGraff** [comment] 2024-11-17 23:52
cfbr: same problem here

**Comment by thedatawalrus** [comment] 2024-11-18 00:44
same here

**Comment by Takayuki-Y5991** [comment] 2024-11-18 02:15
`firebase deploy --only functions:functionName`

The firebase-tools version is 13.11.0.
It seems to have been successful.
If you need to take urgent action, you may want to downgrade and try again.
*I just happened to run it without updating.

**Comment by jayharr-is** [comment] 2024-11-18 02:47
> The firebase-tools version is 13.11.0. It seems to have been successful. If you need to take urgent action, you may want to downgrade and try again.

Downgrading `firebase-tools` to `13.11.0` did not fix this issue for me.

It looks like **all Firebase function deploys are down right now across all projects and multiple regions**. This outage has been happening intermittently for the last 48hr but is not reflected on the [status dashboard](https://status.firebase.google.com/).

The [only suggested workaround](https://github.com/firebase/firebase-tools/issues/7341#issuecomment-2480906838) involves disabling an API likely used by most teams.

This is a big outage. If you're a Google employee reading this right now, please escalate it!

**Comment by joelmeaders** [comment] 2024-11-18 03:59
Same issue.

**Comment by aalej** [comment] 2024-11-18 10:03
Hey folks, apologies for the issue this has caused. Checking with our Firebase Support team, this issue has been escalated to our engineers. I'll keep you all posted for any updates.

**Comment by aalej** [comment] 2024-11-18 11:22
Hey folks, our engineers have identified the cause of the issue and rolled out a fix. I tried redeploying my functions and no errors are being raised. Could you try redeploying your functions? If you're still encountering errors, please let me know.

**Comment by galvarez-designli** [comment] 2024-11-18 14:28
Working again thanks!

**Comment by jayharr-is** [comment] 2024-11-18 17:37
Deploys are back up for our team this morning. 👍

Thank you for the quick resolution!

**Comment by aalej** [comment] 2024-11-18 19:04
Thanks for confirming! Since this issue is resolved, I'll go ahead and close this. If you still encounter the error when deploying, please leave a comment so that we can re-open.

**Closed by aalej** 2024-11-18 19:04 UTC
Labels: type: bug, api: functions

**Comment by PickupAgency-Admin** [comment] 2024-12-09 15:39
Hi, same error today.

```
i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint .

+  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled
+  artifactregistry: required API artifactregistry.googleapis.com is enabled

Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.
```
Anybody else ?

**Comment by maganap** [comment] 2024-12-09 19:35
@aalej  Same issue with `firebase-tools@13.28.0` and a freshly created project.

What happened:

Project created earlier today. I deployed 9 functions with Node 12 using `firebase-tools@11`.

Ah hour later I switched to `firebase-tools@13.28.0` and I tried to redeploy with Node 20. It failed with this other error:

> Error: Failed to fetch Run service undefined

I read somewhere that deleting all functions from the console could solve the issue. It did. So I redeployed the 9 functions with Node 20.

A couple of hours later, I tried to deploy a 10th function and got this error. It's been 3 hours, still the same. 

I get many `200 OK` status, until I get a `429` asking for a recaptcha 😕  wft?

> GET https://runtimeconfig.googleapis.com/v1beta1/projects/some-project-develop/configs 429

`firebase deploy --only functions:singleFunction --debug --project=develop`

```
....
many 200 OK
....
[2024-12-09T18:47:58.988Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/some-project-develop/adminSdkConfig 200
[2024-12-09T18:47:58.988Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/some-project-develop/adminSdkConfig {"projectId":"some-project-develop","storageBucket":"some-project-develop.firebasestorage.app"}
[2024-12-09T18:47:58.988Z] Checked if tokens are valid: true, expires at: 1733771449090
[2024-12-09T18:47:58.988Z] Checked if tokens are valid: true, expires at: 1733771449090
[2024-12-09T18:47:58.988Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/some-project-develop/configs [none]
[2024-12-09T18:47:59.580Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/some-project-develop/configs 429
[2024-12-09T18:47:59.581Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/some-project-develop/configs "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n<html>\n<head><meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"><meta name=\"viewport\" content=\"initial-scale=1\"><title>https://runtimeconfig.googleapis.com/v1beta1/projects/some-project-develop/configs</title></head>\n<body style=\"font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px; overscroll-behavior:contain;\" onload=\"e=document.getElementById('captcha');if(e){e.focus();} if(solveSimpleChallenge) {solveSimpleChallenge(,);}\">\n<div style=\"max-width:400px;\">\n<hr noshade size=\"1\" style=\"color:#ccc; background-color:#ccc;\"><br>\n<form id=\"captcha-form\" action=\"index\" method=\"post\">\nTo continue, please type the characters below:<br><br>\n<img src=\"/sorry/image?id=6047190654086407458&amp;q=EhAqDFqFZhFkAHGCPIUHxN2eGN_23LoGIjAC_Y85bKDLLHOQZ140YPic0Cc9n2qkQQznxhf0nbUQ_8ihBW9QqHNME7k8nGBtiqAyAmNyWgFD&amp;hl=en&amp;continue=https://runtimeconfig.googleapis.com/v1beta1/projects/some-project-develop/configs\" border=\"1\" alt=\"Please enable images\"><br><br>\n<input type=\"text\" name=\"captcha\" value=\"\" id=\"captcha\" size=\"12\" style=\"font-size:16px; padding:3px 0 3px 5px; margin-left:0px;\"><br><br><br>\n<input type=\"submit\" name=\"btn-submit\" value=\"Submit\" style=\"font-size:18px; padding:4px 0;\">\n\n<input type='hidden' name='q' value='EhAqDFqFZhFkAHGCPIUHxN2eGN_23LoGIjAC_Y85bKDLLHOQZ140YPic0Cc9n2qkQQznxhf0nbUQ_8ihBW9QqHNME7k8nGBtiqAyAmNyWgFD'><input type=\"hidden\" name=\"continue\" value=\"https://runtimeconfig.googleapis.com/v1beta1/projects/some-project-develop/configs\">\n</form>\n<hr noshade size=\"1\" style=\"color:#ccc; background-color:#ccc;\">\n\n<div style=\"font-size:13px; line-break: anywhere;\">\n<b>About this page</b><br><br>\n\nOur systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href=\"#\" onclick=\"document.getElementById('infoDiv').style.display='block';\">Why did this happen?</a><br><br>\n\n<div id=\"infoDiv\" style=\"display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;\">\nThis page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href=\"//www.google.com/policies/terms/\">Terms of Service</a>. The block will expire shortly after those requests stop.  In the meantime, solving the above CAPTCHA will let you continue to use our services.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href=\"//support.google.com/websearch/answer/86640\">Learn more</a><br><br>Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly.\n</div>\n\nIP address: 2a0c:5a85:6611:6400:7182:3c85:7c4:dd9e<br>Time: 2024-12-09T18:47:59Z<br>URL: https://runtimeconfig.googleapis.com/v1beta1/projects/some-project-develop/configs<br>\n</div>\n</div>\n</body>\n</html>\n"
Unable to parse JSON: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
[2024-12-09T18:47:59.581Z] Got unexpected error from Runtime Config; it has no status code:Unable to parse JSON: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON {"name":"FirebaseError","children":[],"exit":1,"message":"Unable to parse JSON: SyntaxError: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON","status":500,"level":"debug"}

Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.

Having trouble? Try firebase [command] --help
``` 

I understand `firebase.config()` is deprecated. But I'm trying to migrate from Node 12, and trying to export my old runtime config is failing with the same `429` error:

`firebase --debug functions:config:export`
