### ISSUE TITLE
Regression of storage rules for `initializeTestEnvironment()`

### ISSUE THREAD

**Issue by daenamkim** [firebase/firebase-tools#5908] opened 2023-05-29 06:01 UTC
### [REQUIRED] Environment info

**firebase-tools:** 12.2.1

**Platform:** macOS 13.4 (22F66)

### [REQUIRED] Test case

Please see `/functions/test/storage.test.ts` from the attached file below 🙇 

[firebase-esm-report.zip](https://github.com/firebase/firebase-tools/files/11588933/firebase-esm-report.zip)

### [REQUIRED] Steps to reproduce

```sh
yarn global add firebase@12.2.1
cd functions
yarn install
yarn test
```

### [REQUIRED] Expected behavior

It should be passed since it was passed until firebase-tools `12.2.0`

### [REQUIRED] Actual behavior

```sh
  storage rules
    /uploads
*** ERROR here in v12.2.1 !!! ***
      1) "before each" hook for "should allow a valid jpg file"


  0 passing (18ms)
  1 failing

  1) storage rules
       "before each" hook for "should allow a valid jpg file":
     Error: Not Implemented
```

https://github.com/firebase/firebase-tools/assets/16159767/ce8a00b7-dfa7-4861-a76f-e7af588f8adc

**Comment by aalej** [comment] 2023-05-29 15:25
Hi @daenamkim, thanks for the detailed explanation of the issue you’re encountering and for providing a runnable test case. Really appreciate it. I was able to reproduce the issue described using the test case provided. 

From what I can tell, the cause of this issue is the same as [#5904](https://github.com/firebase/firebase-tools/issues/5904). That said, I’ll be closing this as a duplicate. Please refer to the other issue for any updates.

Feel free to ask this issue to be reopened If you feel like I’ve made a mistake here. Thanks!

**Closed by aalej** 2023-05-29 15:25 UTC
Labels: type: bug, emulators: storage
