### ISSUE TITLE
can't deploy nextjs api route

### ISSUE THREAD

**Issue by LeventeBotos** [firebase/firebase-tools#6134] opened 2023-07-16 16:30 UTC
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment] 2023-07-17 09:02
Hi @LeventeBotos, based on the title alone, I’m thinking the issue you’re reporting might be related to [#6123](https://github.com/firebase/firebase-tools/issues/6123), which is a duplicate of [#6110](https://github.com/firebase/firebase-tools/issues/6110).

If not, could you please file a new issue and specify the details using the provided template. This way, it would be more efficient in identifying the cause of the issue. That said, I'll be closing this for now.

**Closed by aalej** 2023-07-17 09:02 UTC
Labels: type: bug, integration: web frameworks
