### ISSUE TITLE
Firebase serve:  Error: Server Error. connect ETIMEDOUT 216.58.200.234:443

### ISSUE THREAD

**Issue by Symbolk** [firebase/firebase-tools#386] opened 2017-07-06 05:31 UTC
I am using Firebase CLI to develop a web app, and I have to use Shadowsocks as a proxy.

After luckily resolving the "Authentication error", finally I can assign project with "firebase use --add".

However, if I want to start a local server with "firebase serve", I got this error in my laptop:

C:\Users\Symbolk\Desktop\CrowdJigsawPuzzle>firebase serve
=== Serving from 'C:\Users\Symbolk\Desktop\CrowdJigsawPuzzle'...
Error: Server Error. connect ETIMEDOUT 216.58.200.234:443

But it works well in my PC, so I wonder how to resolve it.

**Comment by afzalarsalan** [comment] 2017-07-07 08:27
Can also confirm above error, but to a different IP address, presumbly a closer server.

**Comment by mbleigh** [comment] 2017-08-16 23:23
Duplicate of #155

**Closed by mbleigh** 2017-08-16 23:23 UTC

**Comment by roshsoftco** [comment] 2019-07-15 10:17
For me, this goes away by updating firebase tools and logging in again. Run
`npm install -g firebase-tools` then,
`firebase logout` then,
`firebase login`.

Now try deploying,
`firebase deploy`

**Comment by RidhikGovind** [comment] 2021-01-20 11:18
> For me, this goes away by updating firebase tools and logging in again. Run
> `npm install -g firebase-tools` then,
> `firebase logout` then,
> `firebase login`.
> 
> Now try deploying,
> `firebase deploy`

Thanks a lot. This really worked for me ! :+1:

**Comment by AbhisekJS** [comment] 2021-07-21 15:09
> For me, this goes away by updating firebase tools and logging in again. Run
> `npm install -g firebase-tools` then,
> `firebase logout` then,
> `firebase login`.
> 
> Now try deploying,
> `firebase deploy`

Thanks This Works

**Comment by Tarun-i-mac** [comment] 2021-07-29 08:40
> For me, this goes away by updating firebase tools and logging in again. Run
> `npm install -g firebase-tools` then,
> `firebase logout` then,
> `firebase login`.
> 
> Now try deploying,
> `firebase deploy`



> For me, this goes away by updating firebase tools and logging in again. Run
> `npm install -g firebase-tools` then,
> `firebase logout` then,
> `firebase login`.
> 
> Now try deploying,
> `firebase deploy`

thanks a lot
