### ISSUE TITLE
Cloud function does not deploy when Firestore collection name contains a space

### ISSUE THREAD

**Issue by IanRCarter** [firebase/firebase-tools#938] opened 2018-10-09 15:37 UTC
### Version info
4.2.1

### Platform Information
Windows

### Steps to reproduce
Create a cloud function with a trigger on an update to Firestore where the collection name contains a space.
I.E
exports.sendEmailConfirmation= functions.firestore
    .document('Important Documents/{docID}')
    .onUpdate(async (change, context) => {
...
})

Deploy the function using 'firebase deploy --only functions'

### Expected behavior
Function deploys correctly; Spaces are accepted in Firestore collection names.

### Actual behavior
Error message: Failed to configure trigger providers/cloud.firestore/eventTypes/document.update@firestore.googleapis.com

If you remove the space from the collection name then the function deploys.
I've tried adding %20 instead of a space which deployed however the function did not trigger when I updated a document in the desired collection.

It will be difficult for me to update the collection name to remove the space because this is in a live production application.

**Comment by laurenzlong** [comment] 2018-10-09 21:47
Thanks for reporting! This would be a bug, we've reported it to the Firestore team.

**Comment by laurenzlong** [comment] 2019-01-09 00:38
Internal bug #: 122552135

**Comment by samarthagarwal** [comment] 2019-01-15 12:52
Any updates on this? I have an app in production with many collections that have a space in the name. Is there a workaround for the time being?

**Comment by subrud** [comment] 2019-07-19 18:04
I am also facing this issue. And it's been nearly 9 months since OP opened this issue. Now I can understand why one of my developer friends was suggesting me to switch to AWS.

**Comment by envyram** [comment] 2019-08-29 19:15
Hi, I have a production system and unable to set up email triggers because of this bug. Please let me know if this issue would be resolved soon

**Comment by samtstern** [comment] 2019-08-29 22:43
Hey all I spent some time today reproducing this and I can confirm it's a real issue and adding `%20` lets me deploy but doesn't actually let the function trigger correctly.  I realize that's all old news but I will follow up with some people and see if we can figure out what's going on.

**Comment by Oz-Hershco** [comment] 2019-10-28 09:52
Hi, is there an update about this issue?

**Comment by justinchan23** [comment] 2020-01-15 18:33
im having this issue as well. any updates?

**Comment by bkendall** [comment] 2020-01-16 18:24
I bumped the internal tracking bug this morning and will follow up if there is more news...

**Comment by iamcristos** [comment] 2020-02-23 20:36
Hi I'm also having this issues as well any updates or work around

**Comment by ajaysharma91** [comment] 2020-05-22 11:41
hi, i'm also having same issue.  any updates ?

**Comment by taeold** [comment] 2020-09-01 06:20
Hi folks. We finally landed changes that allows us to deploy Cloud Functions with Firestore collection names with spaces as a trigger. Please give it a try again and let us know if you are still having issues.

My apologies for the delay. We found out that the root issue was deeply embedded in multiple services (e.g. Cloud Firestore, Cloud Functions, etc.) and required multiple releases to get it all working together nicely.)

**Comment by samtstern** [comment] 2020-09-01 09:07
@taeold 🎉 👏 👍

**Closed by samtstern** 2020-09-01 09:07 UTC
Labels: api: firestore, type: bug
