### ISSUE TITLE
Firebase Cloud Functions: Failed to delete documents

### ISSUE THREAD

**Issue by astefer** [firebase/firebase-tools#3191] opened 2021-03-05 17:17 UTC
### [REQUIRED] Environment info

**firebase-tools: 9.5.0**

**Platform: Firebase Cloud Functions, node 12**

### [REQUIRED] Test case

```
return firestoreTools.delete(path, {
    project: process.env.GCLOUD_PROJECT,
    recursive: true,
    yes: true,
    token: functions.config().fb.token,
  });
```

### [REQUIRED] Steps to reproduce

Trigger the cloud function

### [REQUIRED] Expected behavior

All documents under the given path should be deleted.

### [REQUIRED] Actual behavior

The function call fails without deleting any documents.

### Logs
```
FirebaseError: Failed to delete documents FirebaseError
    at Timeout.<anonymous> (/workspace/node_modules/firebase-tools/lib/firestore/delete.js:266:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) 
```

**Comment by joehan** [comment] 2021-03-05 18:00
Hey @astefer, thanks for reporting this. I'm not certain what's going wrong here - it seems like the calls are timing out based on the error message, but it's clearly not descriptive enough to tell why. However, it looks like you're using firebase-tools as a dependency instead of as command line utility here. We try our best to support this, but it is definitely not the main intention of this repo.

Firebase-admin is more appropriate for your use case. Here is a guide on  [how to use it to delete Firestore collections.](https://firebase.google.com/docs/firestore/manage-data/delete-data#collections)

**Comment by astefer** [comment] 2021-03-05 21:42
Okay, I see that it's not really the purpose of this package to be used in cloud functions. However, the firebase documentation is showing exactly the use case I described in this issue (https://firebase.google.com/docs/firestore/solutions/delete-collections#cloud_function)
Maybe I could provide some more information? What exactly would you need for further investigation, @joehan?
I would also like to add that this error does not happen sporadically. I get this almost every time I run the function

**Comment by samtstern** [comment] 2021-03-08 11:20
Reopening since for this one use case (recursive deletes) we do document using `firebase-tools` as a module.

@astefer is there any more information you can get on this? A more detailed stack trace? I want to help with this but as it stands there is not enough information here to debug or reproduce this issue so there won't be anything we can do.

**Comment by astefer** [comment] 2021-03-08 12:19
The issue template suggests to run the command with `--debug`. Is there a way to add this flag when calling a command programmatically?

**Comment by samtstern** [comment] 2021-03-08 12:27
Sure that would be:
```
return firestoreTools.delete(path, {
    debug: true,
    // your other options here...
});
```

**Comment by astefer** [comment] 2021-03-08 14:05
There is no additional output with `debug: true`

**Comment by samtstern** [comment] 2021-03-09 16:43
@astefer hmmm I know this is super frustrating but if we can't reproduce this (it works for me and for some others) and there are no logs or additional information on your end then it's not possible for us to debug it.

**Comment by samtstern** [comment] 2021-03-10 12:22
@astefer I'm honestly a bit suspicious. There *has* to be some debug logging, all of the operations that produce failures in the code have a `logger.debug()` entry before them. Maybe the debug logging is being lost in a Functions context but still without it there's nothing we can really do. 

That said your issue inspired me to take a look at the code which handles failures and I can see some places we can clean up the error messages. So I'll do that.

**Comment by astefer** [comment] 2021-03-10 13:05
I guess this does not help?

```
FirebaseError: Failed to delete documents FirebaseError
    at Timeout.<anonymous> (/workspace/node_modules/firebase-tools/lib/firestore/delete.js:266:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) { 
 children: [],
 context: undefined,
 exit: 1,
 original: undefined,
 status: 500
}
```

**Comment by astefer** [comment] 2021-03-10 14:03
I tried to redirect the logs but I get no output. Am I missing something?

```
const logger: winston.Logger = client.logger;
logger.stream({ start: -1 }).on('log', function (log) {
  console.log(log);
});
```

**Comment by samtstern** [comment] 2021-03-17 18:54
In #3201 I improved the error messages for a situation like yours. This will be included in the next release of the CLI. If you try again when that comes out, we may get more information.

**Closed** 2021-03-17 18:53 UTC
Labels: Needs: Attention
