### ISSUE TITLE
Firebase Emulator does not respect `functions.ignore` in `firebase.json` for automatic functions code reload / watching

### ISSUE THREAD

**Issue by sceee** [firebase/firebase-tools#5344] opened 2022-12-16 17:36 UTC
### [REQUIRED] Environment info

**firebase-tools:** 11.18.0

**Platform:** Windows, Ubuntu

### [REQUIRED] Test case

* Have a Firebase project with some Cloud Functions
* Have a `coverage` directory containing some files within the functions directory of the project
* Have a `firebase.json` with the following content:
```
{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ],
    "ignore": [
      "node_modules",
      ".git",
      "firebase-debug.log",
      "firebase-debug.*.log",
      "coverage" ////// <---- This should ignore the coverage directory
    ]
  }
}
```

### [REQUIRED] Steps to reproduce

1. Execute the Cloud Functions in the emulator using `firebase emulators:start`
2. Change some a file within the `coverage` directory

### [REQUIRED] Expected behavior

Since the `coverage` directory is listed within the ignored directories, it would be great if it would not be watched for file changes for the cloud functions code. This means:
If something in the `coverage` directory is changed, the Functions in the emulator do not reload automatically.

_Background: Coverage reports (for functions tests) are written to the file system during test runs - this causes the functions to be reloaded automatically during the test runs which is bad cause it creates timeouts etc. for subsequent tests._

### [REQUIRED] Actual behavior

Changing some file in the "ignored" `coverage` directory causes the functions to reload with the following log output:
```
+  functions: Loaded functions definitions from source: myFunction
```

**Comment by christhompsongoogle** [comment] 2022-12-20 19:17
Hi sceee, is this related to https://github.com/firebase/firebase-tools/issues/2131?

**Comment by sceee** [comment] 2022-12-20 19:37
Hi @christhompsongoogle , yeah thank you, actually it's exactly what this comment mentions: https://github.com/firebase/firebase-tools/issues/2131#issuecomment-1287525225
So it's fine to move this over to the other issue.

**Comment by christhompsongoogle** [comment] 2022-12-20 21:44
Duplicate of https://github.com/firebase/firebase-tools/issues/2131

**Closed by christhompsongoogle** 2022-12-20 21:44 UTC
Labels: api: functions, bug
