### ISSUE TITLE
Function failed on loading user code. Error message: Code in file index.js can't be loaded. Did you list all required modules in the package.json dependencies?

### ISSUE THREAD

**Issue by jidebb** [firebase/firebase-tools#2416] opened 2020-07-01 12:02 UTC
### [REQUIRED] Environment info

    "express": "^4.17.1",
    "firebase-admin": "^8.10.0",
    "firebase-functions": "^3.6.1"

macOS

### [REQUIRED] Test case

Trying to deploy function to firebase was able to do this on monday however I am unable to do it today and really unsure what I have done incorrect 
### [REQUIRED] Steps to reproduce

firebase deploy     

### [REQUIRED] Expected behavior

should deploy to firebase 

### [REQUIRED] Actual behavior

Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module '**...**' **(this would be the path of the serviceAccount)** 
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/index.js:5:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

Functions deploy had errors with the following functions:
        api
        createPosts

To try redeploying those functions, run:
    firebase deploy --only functions:api,functions:createPosts

To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.

**Comment by samtstern** [comment] 2020-07-01 12:36
@jidebb seems like you have a `require()` statement pointing to a service account that is failing.

Can you create a file called `test.js` in your `functions` folder that just looks like this:

```js
// Make this require statement identical to the other one
const svc = require('< path to service account '>);

console.log(svc)
```

Then run `node test.js`.

That will let you know if the problem is in your code or in the emulators.

**Comment by jidebb** [comment] 2020-07-01 14:52
@samtstern I have done as you advised and get the following

Require stack:
- /path to service account
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (path to service accounts/functions/test.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'path to service account/functions/test.js' ]
} 

For some reason it can't find the module

**Comment by samtstern** [comment] 2020-07-01 14:54
@jidebb ok then you're attempting to require a file that doesn't exist or is not where you think it is.  I'm sorry but if that `test.js` script failed this is not at all an issue with the Firebase CLI and I have to close this.

I would suggest posting the exact contents of the `test.js` script and the exact contents of the error you're getting on StackOverflow or some other forum where someone can help you debug your setup.

**Closed by samtstern** 2020-07-01 14:54 UTC
Labels: Needs: Attention, api: functions
