### ISSUE TITLE
NextJS <Link> and router.push has issues with browser Back Button

### ISSUE THREAD

**Issue by m-j-g** [firebase/firebase-tools#6059] opened 2023-06-29 12:51 UTC
**firebase-tools:**
12.4.2

**Platform:**
macOS
### [REQUIRED] Test case

`<Link href="/dashboard">Dashboard</Link>`

### [REQUIRED] Steps to reproduce

1.) click a nextJS Link
2.) click the browser back button
3.) hover over any link
4.) it will navigate to the link that was clicked in step 1.

### [REQUIRED] Expected behavior

When hosted on Vercel or locally, the page doesn't navigate to the first link clicked when hovering another link.

### [REQUIRED] Actual behavior

When your cursor crosses a different link after pushing back button, it navigates to the previously selected Link.

**Comment by aalej** [comment] 2023-06-29 18:58
Hi @m-j-g, thanks for reaching out. Based on the information you provided, I’m thinking that this issue might be more related to Next.js. I would recommend filing an issue to the [Next.js repository](https://github.com/vercel/next.js/issues). That said, I’ll be closing this ticket.

However if you think there is indeed issue caused by how firebase-tools integrates with the Next.js web framework, feel free to ask this to be reopened and please provide more details about this such as, but not limited to: 
- An [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) so that we can try to replicate the issue
- Verification if the issue occurs when using the emulator or if it also occurs when deployed to Firebase Hosting

**Comment by m-j-g** [comment] 2023-06-29 18:59
This only happens on Firebase hosting. Not on Vercel. So it’s not a nexts issue. Come on man. That was a lazy close

**Comment by aalej** [comment] 2023-06-29 19:45
Apologies for the misunderstanding. I initially thought you meant that you encountered the issue when hosting it on Vercel or locally. I tried to reproduce this issue earlier but I did not encounter the behavior you mentioned when using the Firebase Hosting emulator or when using `next dev`.

However, after deploying to Firebase Hosting. I encountered the behavior you mentioned. I’ll notify our team about this so that they can take a look.

**Comment by fksc** [comment] 2023-11-17 17:46
I am having the same problem.  in my experience <Link> components were reloading the page. anchor tags were doing the same and randomly they were referring to a wrong anchor.

assume you have 
#first
#second
#third anchors on your page! 

the link component correctly renders the <a href="/#first">blah</a> but when you click on them, it refreshes the page and goes to the root => "/" 

now if you click on first, second, third links randomly somehow in between one of the anchors works without refreshing the page but it is pointing to a different tag. for example when you are clicking on second link, it does not refresh but it 
 adds the /#third to the url .

This does not happen when deployed to vercel.

**Comment by leoortizz** [comment] 2023-12-18 19:49
@m-j-g Does this issue still happening with the latest `firebase-tools` and the latest Next.js version? I tried but could not reproduce. If it still happening, a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) can help a lot here.

**Closed** 2024-01-01 02:00 UTC
Labels: type: bug, Needs: Author Feedback, no-recent-activity, integration: web frameworks, reproducible

**Comment by ktpeace** [comment] 2024-06-10 18:37
I am encountering this same issue. 

If I use the <Link> component with Firebase Hosting, when I click a link in my website and then hit back, it auto-redirects me to the link again. I have only experienced this in certain Safari versions, not in Chrome or Firefox. On my iPhone 13 iOS Version 16.1.1 with Safari, this does not occur. On my coworker's iPhone 13 iOS Version 17.5.1 with Safari, the issue occurs.
