### ISSUE TITLE
Debugging a typescript project with emulator.

### ISSUE THREAD

**Issue by KristofHorvath** [firebase/firebase-tools#3321] opened 2021-04-29 17:29 UTC
### [REQUIRED] Environment info

**firebase-tools:** 9.6.0 and 9.10.0

**Platform:** Windows 10

### [REQUIRED] Test case

Debugging a typescript project.

### [REQUIRED] Steps to reproduce

Section [https://firebase.google.com/docs/functions/typescript#emulating_typescript_functions](https://firebase.google.com/docs/functions/typescript#emulating_typescript_functions) warns that in case of using typescript, you have to build before running the emulator. It works; however, if you make changes in your code, you have to stop the emulator, run the build and rerun the emulator. This is really time consuming and frustrating. So I build with tsc -w option and run the emulator in another console (with inspector for attaching a debugger). If I change something in the code, .ts files build automatically, but the inspector cannot restart due to port problem 'Starting inspector on localhost:9229 failed: address already in use'

### [REQUIRED] Expected behavior

In a javascript project, any changes in the files trigger to rerun the inspector, and there isn't any problem with the port. I expect that in typescript project as well.

### [REQUIRED] Actual behavior

In a typescript project, tsc's watch mode causes some problem restarting the inspector automatically and so debugging is unable until restarting the emulator manually.

**Comment by samtstern** [comment] 2021-04-30 11:02
@KristofHorvath can you explain a bit more what the problem is? As far as the Functions Emulator is concerned, TypeScript does not exist. We're watching the compiled JS output for changes. Based on what you're saying it seems like there's a difference between directly editing `.js` files and letting `tsc -w` produce `.js` files for you.

This does seem like a bad experience but at the moment I can't see what we could change in the emulators to make this better ... although I am open to understanding this more!

**Comment by KristofHorvath** [comment] 2021-04-30 12:02
I absolutely understand that the emulator was developed for JS, and TS is a relatively new direction that makes challenges. I hope it can be improved for TS as well. The good news is that the core functionality works with TS, too. So the emulator detects changes produced by tsc -w, and the new version of functions works well. (By the way, the linked documentation could mention using tsc -w, it already would be an improvement compared to manually building and rerunning the emulator every time.)

The problem is with debugging. Using --inspect-functions option, the emulator detects the changes and applies them; however, the inspector cannot restart, so debugging is no longer available until restarting the whole emulator (which is really time-consuming). Unfortunately, I don't understand why restarting the inspector automatically works with JS and don't with tsc -w generated files.

**Comment by samtstern** [comment] 2021-04-30 13:18
I was not able to reproduce this issue. Here's what I did:

  * New project, `firebase init functions` and `firebase init emulators`
  * In a terminal, in the `functions` dir run `tsc -w`
  * In another terminal, run `firebase emulators:start --inspect-functions`
  * Make some changes to `index.ts`, save them

Here are the logs I see, the debugger opens correctly each time:

```
$ firebase --project=demo-123 emulators:start --inspect-functions
i  emulators: Starting emulators: functions
i  emulators: Detected demo project ID "demo-123", emulated services will use a demo configuration and attempts to access non-emulated services for this project will fail.
⚠  functions: You are running the functions emulator in debug mode (port=9229). This means that functions will execute in sequence rather than in parallel.
✔  functions: Using node@12 from host.
⚠  emulators: The Emulator UI requires a project ID to start. Configure your default project with 'firebase use' or pass the --project flag.
i  functions: Watching "/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.GtRMScly/functions" for Cloud Functions...
>  Debugger listening on ws://localhost:9229/69639c12-7532-45e1-9625-74fa4489b565
>  Debugger listening on ws://localhost:9229/69639c12-7532-45e1-9625-74fa4489b565
>  For help, see: https://nodejs.org/en/docs/inspector
✔  functions[helloWorld]: http function initialized (http://localhost:5001/demo-123/us-central1/helloWorld).

┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┐
│ Emulator  │ Host:Port      │
├───────────┼────────────────┤
│ Functions │ localhost:5001 │
└───────────┴────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: None

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
 
>  Debugger listening on ws://localhost:9229/e38f8797-f734-43c4-a343-b90253698438
>  Debugger listening on ws://localhost:9229/e38f8797-f734-43c4-a343-b90253698438
>  For help, see: https://nodejs.org/en/docs/inspector
>  Debugger listening on ws://localhost:9229/771ced4a-8d7e-4284-9aa4-0963785fb9f4
>  Debugger listening on ws://localhost:9229/771ced4a-8d7e-4284-9aa4-0963785fb9f4
>  For help, see: https://nodejs.org/en/docs/inspector
```

**Comment by KristofHorvath** [comment] 2021-05-02 16:25
The steps you did are the same as what I did, except I used my old project instead of a new one. Unfortunately, neither I can reproduce the issue with a new project. I tried a few modifications which could be the difference:

- Initiating the new project with JS and migrate to TS
- Initiating Firestore as well
- Writing an onWrite-triggered function
- Initiating Hosting as well
- Using Express.js

None of them provoked the issue.

I doubt that it is useful, but these are the logs after making some changes in my old project while running tsc -w and the emulator:

```
>  Debugger listening on ws://localhost:9229/466615a0-4ec4-4541-9aa6-3200504a94f8
>  Debugger listening on ws://localhost:9229/466615a0-4ec4-4541-9aa6-3200504a94f8
>  For help, see: https://nodejs.org/en/docs/inspector
>  Debugger attached.
>  Starting inspector on localhost:9229 failed: address already in use
>  Debugger listening on ws://127.0.0.1:52435/86a6f753-7be5-42d3-a2be-2413576f3e29
>  For help, see: https://nodejs.org/en/docs/inspector
>  Debugger attached.
>  Waiting for the debugger to disconnect...
>  Debugger listening on ws://127.0.0.1:52440/6f0f3399-bef6-42ca-a3fd-efe029b491dc
>  For help, see: https://nodejs.org/en/docs/inspector
>  Debugger attached.
>  Waiting for the debugger to disconnect...
```

Even if we cannot find the cause of this issue, the documentation [Emulating TypeScript functions](https://firebase.google.com/docs/functions/typescript#emulating_typescript_functions) could improve with the debugging process. (By the way, step 5 of the previous section contains an error, "true" should be without quotes.)

**Comment by samtstern** [comment] 2021-05-05 09:37
@KristofHorvath thanks for trying to reproduce it. Since neither of us can reproduce this issue in a new project I'll close this issue. If you see something similar on a new project in the future, just let me know.

(I'll file something internally about the docs)

**Closed by samtstern** 2021-05-05 09:37 UTC
Labels: Needs: Attention
