### ISSUE TITLE
No functions emulated issue

### ISSUE THREAD

**Issue by ottob** [firebase/firebase-tools#1961] opened 2020-02-07 08:20 UTC
This is probably not a bug so Im posting instead so that others can find this solution if they run into the same issue.

All of a sudden the firebase tools could no longer find my local functions. Even though it had worked just a little while ago. And I could not figure out why it stopped working. I had the same issue with a clean git checkout of my code, and my colleagues could not reproduce it.

The symptoms: the `firebase functions:shell` exited with `No functions emulated.`. And if I tried to do a `firebase deploy` it complained about the functions existing remotely but not locally.

The cause: the cli tools does a javascript [require](https://github.com/firebase/firebase-tools/blob/8a97a3e019687193ec40d98552af7c735bc63137/src/emulator/functionsEmulatorRuntime.ts#L1079): `require(frb.cwd)` where `frb.cwd` in this case is the path to my firebase project `/Users/ottob/dev/myfbproj`. The problems was that I recently exported a google cloud service account key to json and put it in `~/dev/myfbproj.json` which is the same base name as the project folder. So the `require()` call got the json file instead of the folder as expected. Apparently this is a javascript [feature](https://stackoverflow.com/a/52200473).

The solution: rename the google cloud service account key file so it did not match the project folder name. `mv ~/dev/myfbproj.json ~/dev/gcloud_key.json`.

**Comment by samtstern** [comment] 2020-02-07 16:52
@ottob wow that's a really strange edge case I am impressed that you figured it out.  I agree though this is probably not a bug, so I am going to close this issue.

Thank you for taking the time to post it for others.

**Closed by samtstern** 2020-02-07 16:52 UTC
