### ISSUE TITLE
firebase functions:shell stalls out and doesn’t let me run function

### ISSUE THREAD

**Issue by TOMZACH** [firebase/firebase-tools#1467] opened 2019-07-03 22:38 UTC
### [REQUIRED] Environment info

CLI Version: 7.0.2
Platform: darwin
Node Version: v10.14.1
operating system: macOS

### [REQUIRED] Test case

running `sudo firebase functions:shell` inside of the functions directory results in the following output and then the script just stalls out not advancing onto the next line where I used to be able to enter in my functions name along with test data and simulate running the data. I’ve been running the same configuration for months and have kept my firebase-tools up to date.

outputs :
⚠ Your requested "node" version "8" doesn't match your global version "10"
✔ functions: Emulator started at http://localhost:5001

### [REQUIRED] Steps to reproduce

1) run `sudo firebase functions:shell` inside of functions directory

### [REQUIRED] Expected behavior

I am expecting another line to appear below where I can enter in the cloud function I would like to test along with the test data.

### [REQUIRED] Actual behavior

what results is the shell script just stays on this line

⚠ Your requested "node" version "8" doesn't match your global version "10"
✔ functions: Emulator started at http://localhost:5001

below is the debug output

[debug] [2019-07-03T22:17:31.934Z] ----------------------------------------------------------------------
[debug] [2019-07-03T22:17:31.936Z] Command: /usr/local/bin/node /usr/local/bin/firebase functions:shell
[debug] [2019-07-03T22:17:31.937Z] CLI Version: 7.0.2
[debug] [2019-07-03T22:17:31.937Z] Platform: darwin
[debug] [2019-07-03T22:17:31.937Z] Node Version: v10.14.1
[debug] [2019-07-03T22:17:31.938Z] Time: Wed Jul 03 2019 18:17:31 GMT-0400 (Eastern Daylight Time)
[debug] [2019-07-03T22:17:31.938Z] ----------------------------------------------------------------------
[debug]
[debug] [2019-07-03T22:17:31.953Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-07-03T22:17:31.953Z] > authorizing via signed-in user
[debug] [2019-07-03T22:17:31.953Z] [iam] checking project pullupanddownfirebase for permissions ["firebase.projects.get"]
[debug] [2019-07-03T22:17:31.955Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2019-07-03T22:17:31.955Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token

[debug] [2019-07-03T22:17:32.141Z] <<< HTTP RESPONSE 200
[debug] [2019-07-03T22:17:32.171Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/pullupanddownfirebase:testIamPermissions

[debug] [2019-07-03T22:17:32.421Z] <<< HTTP RESPONSE 200
[warn] ⚠ Your requested "node" version "8" doesn't match your global version "10"
[debug] [2019-07-03T22:17:32.562Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/pullupanddownfirebase

[debug] [2019-07-03T22:17:32.845Z] <<< HTTP RESPONSE 200
[debug] [2019-07-03T22:17:32.846Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/733277284165:getServerAppConfig

[debug] [2019-07-03T22:17:33.046Z] <<< HTTP RESPONSE 200
[info] ✔ functions: Emulator started at http://localhost:5001
[debug] [2019-07-03T22:17:33.057Z] [functions] Watching "/Users/a123456/Desktop/Tile Recovery Cloud Functions/cloud-functions/functions" for Cloud Functions...
[debug] [2019-07-03T22:17:33.440Z] DEBUG: Functions runtime initialized.
[debug] [2019-07-03T22:17:33.442Z] DEBUG: Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"protect_env":true,"admin_stubs":true}
[debug] [2019-07-03T22:17:33.582Z] DEBUG: firebase-admin has been stubbed.

**Comment by samtstern** [comment] 2019-07-03 23:09
@TOMZACH thanks for filing this!  This looks like a duplicate of #1456 so I am going to close this in favor of discussing more there.

**Closed by samtstern** 2019-07-03 23:09 UTC
