### ISSUE TITLE
Emulator won't start: Cannot read property 'rows' of undefined

### ISSUE THREAD

**Issue by braadworst** [firebase/firebase-tools#3910] opened 2021-11-18 11:54 UTC
### [REQUIRED] Environment info

**firebase-tools:** 9.22.0 - 9.14.0 (tried many versions)

**Platform:** macOS

### [REQUIRED] Test case

Does not apply

### [REQUIRED] Steps to reproduce
```firebase emulators:start```

### [REQUIRED] Expected behavior
Start the actual emulator

### [REQUIRED] Actual behavior
Throws an error (I am not even running a cloud function, it seems to be stumbling on that one. I have commented out all my cloud functions)
```
[debug] [2021-11-18T11:48:28.133Z] TypeError: Cannot read property 'rows' of undefined
    at new Table (/usr/local/lib/node_modules/firebase-tools/node_modules/cli-table/lib/index.js:51:15)
    at Command.actionFn (/usr/local/lib/node_modules/firebase-tools/lib/commands/emulators-start.js:47:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[error]
[error] Error: An unexpected error has occurred.
```

I've just updated firebase-tools and cannot run the emulators anymore. I am not sure which version I was running before but I went back as far as 9.14.0 and all failed with the same error. Could use some help here...

**Comment by braadworst** [comment] 2021-11-18 12:08
So with some more trail and error. I installed the latest version again 9.22.0 and also the latest firebase-admin (10.0.0) and latest firebase-functions (3.16.0). When I rename my index.js (in de functions dir) it starts to complain about it not being found. I rename it then back to index.js and let make a small change and save, it will update the and run the emulators as needed.

That made me think it was some cache thing, but restarting the emulators I have to do the same procedure, as it keeps throwing the error...

**Comment by gridcellcoder** [comment] 2021-11-18 12:56
Experiencing the same with 
```
[2021-11-18T12:51:40.283Z] TypeError: Cannot read property 'rows' of undefined
    at new Table (/usr/lib/node_modules/firebase-tools/node_modules/cli-table/lib/index.js:51:15)
    at Command.module.exports.command_1.Command.before.before.description.option.option.option.option.action [as actionFn] (/usr/lib/node_modules/firebase-tools/lib/commands/emulators-start.js:47:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
```
firebase --version
9.22.0
```
When trying to start a storage emulator.

**Comment by gridcellcoder** [comment] 2021-11-18 13:05
As a workaround for now I added a null check operator and then it works

`/usr/lib/node_modules/firebase-tools/node_modules/cli-table/lib/index.js`

 line 51
```
if (options?.rows) {
    for (var i = 0; i < options.rows.length; i++) {
      this.push(options.rows[i]);
    }
  }
```

not sure if this will break anything but it get the emulator working

**Comment by taijusanagi** [comment] 2021-11-18 14:21
Same here.

I think this is because of cli-table version update.

https://github.com/Automattic/cli-table/commit/4c3ee25e5191991b4f88dc5c4b868872670c539d#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1

This code is applied from cli-table@0.3.7.

As a workaround I added resolution in package json, and avoided this issue.

```
  "resolutions": {
    "cli-table": "0.3.6"
  },
```

**Comment by AdditionAddict** [comment] 2021-11-18 15:43
Duplicate of #3909. Keep an eye on latest PR 3907

**Comment by oodavid** [comment] 2021-11-18 15:57
Me too, am trying a downgrade

**Comment by phess101** [comment] 2021-11-18 16:46
Will be resolved by PR https://github.com/firebase/firebase-tools/pull/3907

**Comment by firephreek** [comment] 2021-11-18 17:24
Will it?  I'm using a clean install of NVM 17.1.0 (latest stable) on Windows 10 Pro (x64). Running `npm install -g firebase-tools` gives me a `package.json` file with `"cli-table": "^0.3.1"` which results in the same error:

```
[debug] [2021-11-18T17:18:16.856Z] TypeError: Cannot read properties of undefined (reading 'rows')
    at new Table (C:\Users\-------\AppData\Roaming\nvm\v17.1.0\node_modules\firebase-tools\node_modules\cli-table\lib\index.js:51:15)
    at Command.actionFn (C:\Users\-------\AppData\Roaming\nvm\v17.1.0\node_modules\firebase-tools\lib\commands\emulators-start.js:47:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: An unexpected error has occurred.
```

Attached:
 - firebase-tools/package.json
 - firebase.json
 - firebase-debug.log
[files.zip](https://github.com/firebase/firebase-tools/files/7564745/files.zip)

**Comment by phess101** [comment] 2021-11-18 19:10
Looks like cli-table just updated to 0.3.8. I haven't tested myself but it should resolve the issue

**Comment by firephreek** [comment] 2021-11-18 21:42
Just tested with `cli-table: 0.3.8` on Ubuntu WSL 2.0 (Win10x64) and on Windows Terminal, with nvm 14.0.0 and Auth/Firestore are working for me.

**Comment by bkendall** [comment] 2021-11-18 21:43
Duplicate of #3909

reinstalling firebase-tools (or waiting for the new release `9.23.0` to drop very soon) will fix this

**Closed by bkendall** 2021-11-18 21:43 UTC

**Comment by braadworst** [comment] 2021-11-19 07:32
Can confirm, 9.23.0 fixes the issue for me, props 👍
