### ISSUE TITLE
Receiving DataSnapshot instead of Change<DataSnapshot> for database.ref.onWrite

### ISSUE THREAD

**Issue by Kamshak** [firebase/firebase-tools#839] opened 2018-07-26 19:47 UTC
### Version info

"firebase-admin": "^5.13.1",
"firebase-functions": "^2.0.1",
firebase-tools@4.0.0

### Test case
Delete and redeploy all functions

```ts
export const onWriteNotifier = functions.database
  .ref('/draft-trips/{userId}/{tripId}/state').onWrite(async (change, context) => {
      console.log(change);
   });
```

package.json
``` 
  "engines": {
    "node": "8"
  },
"dependencies": {
    "firebase-admin": "^5.13.1",
    "firebase-functions": "^2.0.1",
}
``` 

### Steps to reproduce

Change the path

### Were you able to successfully deploy your functions?

No it works fine

``` 
i  functions: updating Node.js 8 function onWriteNotifier(us-central1)...
✔  functions[onWriteNotifier(us-central1)]: Successful update operation.
```

### Expected behavior

I get the Object from the docs and the typings (a Change<DataSnapshot>)

### Actual behavior

```
DataSnapshot {
  app: 
   FirebaseApp {
     firebaseInternals_: 
      FirebaseNamespaceInternals {
        firebase_: [Object],
        serviceFactories: {},
        apps_: [Object],
        appHooks_: {} },
     services_: {},
     isDeleted_: false,
     name_: '__admin__',
     options_: 
      { projectId: 'sdasdfafsd',
        databaseURL: 'https://afsdasdf.firebaseio.com',
        storageBucket: 'asasdfdsa.appspot.com',
        cloudResourceLocation: 'us-central',
        credential: [Object] },
     INTERNAL: FirebaseAppInternals { credential_: [Object], isDeleted_: false, tokenListeners_: [] } },
  instance: 'https://travelmates-staging.firebaseio.com',
  _path: '/draft-trips/c0OzwvVQW4XdfsdH2w0Ya4h1ulle2/-LFppsd_jfq43uyhMMyL/state',
  _data: 'draft' }
```

**Comment by laurenzlong** [comment] 2018-07-26 20:15
Thanks for filing! If you go to https://console.firebase.google.com/u/0/project/_/functions/list, what does it say under the "event" column for that function?

**Comment by Kamshak** [comment] 2018-07-26 20:34
Thanks for the quick reply. It says (sorry German console):
``` 
Name | Region | Trigger | Laufzeit | Zugewiesener Speicher | Ausgeführte Funktion
onWriteNotifier | us-central1 | Firebase Realtime Database (Beta) | Node.js 8 | 256 MB | onWriteNotifier
```

Inside the trigger tab it says
```
Triggertyp
Firebase Realtime Database (Beta)

Ereignistyp
write

Datenbank
dbname

Pfad
draft-trips/{userId}/{tripId}/state
```

**Comment by laurenzlong** [comment] 2018-07-26 21:38
Hi, I'm sorry I'm not able to reproduce this. Was this a onCreate or onDelete function before? We've been seeing issues of the Firebase CLI prematurely reporting successful deploys. If you try triggering the function again now ,is it a change object that gets logged?

**Comment by Kamshak** [comment] 2018-07-27 12:35
It does seem to work right now, I changed it to onUpdate ~1hr ago but i'm not sure if it was maybe working before even. Keep in mind though i deleted and reuploaded the functions twice (checking in the cloud console to make sure the functions were gone).

Not sure if it helps but i used to deploy this functions with the old version and node6 so maybe it has something to do with how the upgrades are done? I'm a bit scared to migrate prod right now

**Comment by laurenzlong** [comment] 2018-08-01 00:28
Hi, I would not recommend deleting and then re-creating function for migrating production functions, please follow our best practices for changing function triggers: https://firebase.google.com/docs/functions/manage-functions#modify-trigger. Closing this issue, as the onWrite does receive a Change object, not a DataSnapshot object.

**Closed by laurenzlong** 2018-08-01 00:28 UTC

**Comment by arockiapb** [comment] 2020-10-12 11:43
is have any possibility to write query with wildcard in JAVASCRIPT project, like below:

JAVA/NODEJS code:
export const onWriteNotifier = functions.database
  .ref('/draft-trips/{userId}/{tripId}/state').onWrite(async (change, context) => {
      console.log(change);
   });

I expected like below:
var ref = firebase.database().ref().child('/draft-trips/{userId}/{tripId}/state');
    ref.on('child_added', snap => {
      // get added new data
    });

anyone please help me..

**Comment by mbleigh** [comment] 2020-10-12 14:16
Wildcards are only possible in functions, you must listen to specific nodes
in the JavaScript SDK. You will need to structure your data to be able to
be queried from the client or use functions to denormalize the data into a
client readable structure.

**Comment by arockiapb** [comment] 2020-10-14 07:05
Thanks for your reply... is have any option to write functions in Javascript client side for my above query?

**Comment by samtstern** [comment] 2020-10-14 09:33
@arockiapb your query `firebase.database().ref().child('/group_feed/{groupId}/{entryID}');` would mean "listen to all entries in all groups".

No there is no way to do this in Firestore on the Web, and we won't be adding a feature like that as it is not an efficient query.

**Comment by arockiapb** [comment] 2020-10-14 10:10
I think you are asking me to do like below,

var ref = firebase.database().ref('group_feed');
ref.on('child_added', (snap) => {console.log(snap); });

I tried like above, but I didn't get any data while adding child datas under "/group_feed/{groupId}/{entryID}" path.

I tried with below, but I am getting all data which all are in DB under group_feed table. but I don't know how to getting latest added data in DB
ref.on('value', snap => {// get all child data});

can you please help me... I need to get latest data which is added in DB under  "/group_feed/{groupId}/{entryID}" path.
