### ISSUE TITLE
Firestore Emulator allowing two documents with same ID.

### ISSUE THREAD

**Issue by nikkothari22** [firebase/firebase-tools#2496] opened 2020-07-27 23:22 UTC
The firestore emulator is allowing two documents with the same ID to be added in a collection. (I have attached the screenshot). 

The original document was imported while starting the emulator. When I tried to fetch the document in my web app (React), the "doc.exists" property was false.

I created a new document with the same ID (keeping the old one there) and it allowed me to create a new document. Also, I was able to fetch the newly created document. 

### [REQUIRED] Environment info

**firebase-tools:** 8.6.0

**Platform:** macOS

### [REQUIRED] Test case

Creating two documents in Firestore Emulator with the same ID. One of the documents was imported from a previous export. The other was created on the Emulator UI (on Google Chrome).

### [REQUIRED] Steps to reproduce

1. Start the emulator (new, fresh version).
2. Create a test document with a specific ID in a collection.
3. Export the data (using export flag) and close it.
4. Start the emulator again, but this time importing the previously exported data. 
5. Try fetching (reading) the old document on a web application (doc.exists will be false)
6. Add a new document in the same collection with the same ID.
7. Try fetching (reading) the document again, this time it succeeds.

### [REQUIRED] Expected behavior

1. New document with same ID should not be allowed in the same collection.
2. It should be possible to fetch an already existing document from a previous import.

### [REQUIRED] Actual behavior

1. New document with same ID was created using the Emulator UI.
2. Old document wasn't being read (doc.exists = false) on running the "get()" method on a web application. New document was successfully read from the Firestore database once created. 

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/19825455/88601329-040b3c00-d08e-11ea-9429-262f40dfd8a5.png">

[firestore-debug.log](https://github.com/firebase/firebase-tools/files/4985097/firestore-debug.log)
[ui-debug.log](https://github.com/firebase/firebase-tools/files/4985098/ui-debug.log)

**Comment by samtstern** [comment] 2020-07-31 15:39
@nikkothari22 thank you for the detailed reproductions steps!  Assigning to @malcolmdeck who is on call at the moment.

**Comment by malcolmdeck** [comment] 2020-08-07 18:41
Sorry for the slow reply - this is being tracked internally as b/163146117

**Comment by yuchenshi** [comment] 2020-08-17 21:22
Would you mind sharing a dump of your previous export to help us reproduce this?

Ideally, please start from fresh and create only documents necessary to reproduce the issue, and let us know what IDs are causing the issue.

Also, kindly make sure none of the IDs contains whitespaces (leading / trailing). We've seen issues before where one of the ID have a trailing space and the other one doesn't have it. This may also happen to your case. When in doubt, try pulling out the developer console in your browser on the Firestore tab in Emulator UI and you can use code to query and collection and explore.

**Closed** 2020-09-04 01:00 UTC
Labels: Needs: Author Feedback, closed-by-bot, emulator-suite, emulators: firestore, no-recent-activity

**Comment by MohamedRed** [comment] 2020-12-08 23:30
Hi, 
My comment has nothing to do with the firebase Emulator.

I just wanted to mention when I create a new document programatically using the javascript SDK, I can then go to the firebase console and create manually a new document with the same ID by copy pasting the ID.

**Comment by s-tushar** [comment] 2021-08-09 18:38
looks like they still did not fix this issue
