### ISSUE TITLE
Add the ability to remove the Functions container cache from Artifact Registry using the CLI

### ISSUE THREAD

**Issue by TrustyTechSG** [firebase/firebase-tools#6412] opened 2023-09-28 06:01 UTC
### [REQUIRED] Environment info

**firebase-tools: 12.5.4 / 12.6.1**

**Platform: macOS**

### [REQUIRED] Test case

Minimum repo: https://github.com/TrustyTechSG/firebase-function-issue

### [REQUIRED] Steps to reproduce

1. Deploy the only http function in repo "captureGoogle".
2. Visit http function, get response with google home screenshot.
3. Do not change anything, simply deploy the function again. 
4. Visit http function, get Error **"Could not find Chrome "**, which means the install script from puppeteer not been runned correctly.
5. Update puppeteer ^21.3.4 to ^21.3.5 and deploy the function again, function works again.
6. Do not change anything, simply deploy the function again, function stop working again. 

### [REQUIRED] Expected behavior

The function should work after redeploy.

### [REQUIRED] Actual behavior

The function stopped working after redeploy.

**Comment by Sandlens** [comment] 2023-09-29 07:10
I am encountering the same issue

**Comment by aalej** [comment] 2023-09-29 13:21
Hey @TrustyTechSG, thanks for the detailed explanation of the issue you’re encountering and for providing a runnable test case. Currently, I’m unable to reproduce the error you mentioned.

From what I can tell you are able to deploy the function again without any changes, as you mentioned “Do not change anything, simply deploy the function again”. When I tried to reproduce this issue, functions deployment would get skipped because there are no changes: 
```
functions[captureGoogle(us-central1)] Skipped (No changes detected)
```

Just wanted to verify that no changes were made to the functions before redeploying, because being able to deploy functions without any change is an unexpected behavior.

**Comment by TrustyTechSG** [comment] 2023-09-29 14:08
Hi @aalej, thank you for the quick attention. Yes, no changes at all, at least on my mac, every time run:
`firebase deploy --only functions:captureGoogle`
 will get success response below
```
i  functions: preparing functions directory for uploading...
i  functions: packaged /Users/xxxx/Documents/function-issue/functions (75.71 KB) for uploading
✔  functions: functions folder uploaded successfully
i  functions: updating Node.js 18 (1st Gen) function captureGoogle(us-central1)...
✔  functions[captureGoogle(us-central1)] Successful update operation.
```

And I just double confirmed again, only redeploy with puppeteer version changes works, no changes redeploy will always get the "Could not find Chrome error".

**Comment by Sandlens** [comment] 2023-09-30 08:12
> Just wanted to verify that no changes were made to the functions before redeploying, because being able to deploy functions without any change is an unexpected behavior.

You can test that this issue still occurs by changing the function code in any way eg. adding a single space somewhere in the function, then redeploying the individual function with `firebase deploy --only functions:captureGoogle`.

The issue described by @TrustyTechSG will occur.

**Comment by colerogers** [comment] 2023-10-04 19:22
Hey folks, I did some digging around and I think this issue is popping up because the Cloud Build buildpacks (the thing that turns your code into a container image), does some caching during dependency installation. [Their official docs](https://cloud.google.com/docs/buildpacks/nodejs#using_npm) have a callout to use a `package-lock.json` to improve performance on builds. We (Firebase) save the cache directory of the built image for Cloud Build to use inside of Artifact Registry (see `Artifact Registry -> gcf-artifacts (of your function location) -> $function_name/cache`).

I tested out this theory and it seems to be working for me. If you can, try to remove the cache from Artifact Registry and retry the deployments. This basically "forces" the buildpacks to `npm install` and should correctly setup puppeteer.

I'm not sure if this should be labeled as a bug since we want caching for pretty much all builds (and so does the buildpacks team). I'll change this to a feature request to able to clean up the container cache from the CLI so it is easier to do in automation. Thanks

**Comment by colerogers** [comment] 2023-10-06 14:35
I actually just remembered that we have an experiments command that will clean up artifacts from artifact registry. To delete the cache, you need to delete the function prior to running it. This should work in automation:
```
firebase functions:delete <functionName>
firebase experiments:enable deletegcfartifacts
firebase functions:deletegcfartifacts
firebase deploy --only functions
```
closing out this issue, thanks

**Closed by colerogers** 2023-10-06 14:35 UTC
Labels: type: feature request, api: functions

**Comment by fuelkoy** [comment] 2024-11-01 11:02
@colerogers I think this should be reconsidered to be implemented another way. Deleting a production environment function before deleting the artifacts would resolve to the API endpoint being down in a production environment. This would lead to service not being available for the users. If this would happen every time a function (with `puppeteer` or similar kind of package) would need to be updated, the service would be unavailable always for a period of time.

Problems:

1. If such a function is not deployed with an empty cache, the deploy will work, but then the function will not work in usage. 
2. Production and development environments have separate artifact caches, so this can sneak into the production environment even though development would work. This makes this very error-prone. 
3. Reminding the developer always to manually locate to the GCP panel > Artifact registry and find all the functions whose cache needs to be deleted. And to do this always manually on every function deploy is not a good user experience and also does not scale. This approach would bring about other possible problems where, for example, the developer would accidentally delete the function, a folder, or a wrong cache, resulting in the function not working as expected. 

My suggestion:

As you mentioned, you can navigate to the Artifact registry and there find your function cache and delete it with no problems, and then deploy the function buildpacks by running `npm install`. Then the function works as expected. This solution should be made more straightforward and integrated into the standard workflow. To address this, I propose adding a `--no-cache` flag to the `firebase deploy` command. This would solve all previously mentioned issues.
