### ISSUE TITLE
Unknown request URI: /emulator/v1/projects/{project-id}/databases/(default)/documents

### ISSUE THREAD

**Issue by ekselys** [firebase/firebase-tools#3049] opened 2021-01-17 12:34 UTC
### Environment info
* Firebase 9.2.1
* Windows 10
* Node v12.17.0
* NPM 6.14.9

###  Test case

Trying to erase firestore data through ad hoc REST API ( [docs](https://firebase.google.com/docs/emulator-suite/connect_firestore))

This is what firestore logs print out:
```
INFO: Detected non-HTTP/2 connection.
Jan 17, 2021 10:05:04 AM io.gapi.emulators.netty.NotFoundHandler handleRequest
INFO: Unknown request URI: /emulator/v1/projects/time-work-2096c/databases/(default)/documents
```

### Steps to reproduce

* Execute `curl -v -X DELETE "http://localhost:8080/emulator/v1/projects/firestore-emulator-example/databases/(default)/documents"` (like [docs](https://firebase.google.com/docs/emulator-suite/connect_firestore) suggests, executed through Git Bash)
* Firestore does not erase data (404 not found is received)

### Expected behavior

Firestore should erase data and respond with a 200 OK message.

### Actual behavior

Received 404 Not Found, data not erased.

**Comment by samtstern** [comment] 2021-01-18 11:00
@ekselys I was not able to reproduce this.  Here's what I did:

**1. Initialize a new local project**
```
# I selected only the Firestore emulator
firebase --project=fir-dumpster init emulators
```

**2. In the emulator UI create a new Firestore document**
Just made a `/foo/bar` document

**3. Delete using `curl`**
```
$ curl -v -X DELETE "http://localhost:8080/emulator/v1/projects/fir-dumpster/databases/(default)/documents"
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> DELETE /emulator/v1/projects/fir-dumpster/databases/(default)/documents HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: application/json
< content-length: 4
<
{
}
* Connection #0 to host localhost left intact
* Closing connection 0
```

As you can see I got `HTTP 200` and in the UI my data is gone. Are you sure you're using the right project ID in the URL when you run the `curl` request?

**Comment by ekselys** [comment] 2021-01-21 18:07
Seems working now, the project ID was wrong as prjectid.
By the way, i'm facing the same problem trying to reach the endpoint from an android emulator.
Is there any restriction on the endpoint itself?
This is the code used to make the call and I receive always 404

```kotlin
        Log.d("FirebaseEmulatorsRule", "Erasing firestore data")
        val url = URL("http://localhost:8080/emulator/v1/projects/{projectID}/databases/(default)/documents")
        var connection: HttpsURLConnection? = null
        try {
            connection = url.openConnection() as? HttpsURLConnection
            connection?.run {
                Log.d("FirebaseEmulatorsRule", url.toString())
                readTimeout = 3000
                connectTimeout = 3000
                requestMethod = "DELETE"
                // Open communications link (network traffic occurs here).
                connect()
                if (responseCode != HttpsURLConnection.HTTP_OK) {
                    throw IOException("HTTP error code: $responseCode")
                }
                Log.d("FirebaseEmulatorsRule", "Firestore data erased, releasing firestore connection")
            }
        } finally {
            // Release connection
            Log.d("FirebaseEmulatorsRule", "Firestore data erased, releasing firestore connection")
            connection?.inputStream?.close()
            connection?.disconnect()
        }
```

**Comment by samtstern** [comment] 2021-01-21 18:30
@ekselys on an Android emulator `localhost` does not mean your computer it means "local to the Android emulator".  If you want to access `localhost` on the *computer* that contains the emulator you need to use the special IP address `10.2.2.2`

So 
```kt
 val url = URL("http://10.2.2.2/emulator/v1/projects/{projectID}/databases/(default)/documents")
 ```

You can see this in the docs here:
https://firebase.google.com/docs/emulator-suite/connect_firestore#android_ios_and_web_sdks

Closing because your initial issue was fixed, thanks for following up!

**Comment by ekselys** [comment] 2021-01-21 21:21
> @ekselys on an Android emulator `localhost` does not mean your computer it means "local to the Android emulator". If you want to access `localhost` on the _computer_ that contains the emulator you need to use the special IP address `10.0.2.2`
> 
> So
> 
> ```kotlin
>  val url = URL("http://10.0.2.2/emulator/v1/projects/{projectID}/databases/(default)/documents")
> ```
> 
> You can see this in the docs here:
> https://firebase.google.com/docs/emulator-suite/connect_firestore#android_ios_and_web_sdks
> 
> Closing because your initial issue was fixed, thanks for following up!

Sorry, it was just a copy&paste error in the comment, obviously i was using 10.0.2.2 as host

**Comment by samtstern** [comment] 2021-01-22 10:58
@ekselys there is no restriction on the endpoint. Can you confirm using my example that you're able to hit the endpoint using `curl`?  If so then unfortunately this is not an issue in `firebase-tools`, that would mean it's an issue in how your Android emulator is connecting to your computer's network which isn't something we can fix.

**Comment by ekselys** [comment] 2021-01-26 17:53
> @ekselys there is no restriction on the endpoint. Can you confirm using my example that you're able to hit the endpoint using `curl`? If so then unfortunately this is not an issue in `firebase-tools`, that would mean it's an issue in how your Android emulator is connecting to your computer's network which isn't something we can fix.

`curl` works fine, thanks for help

**Comment by samtstern** [comment] 2021-01-26 18:30
@ekselys thank you for confirming! Sometimes Android emulators have really wacky network issues, I really wish I could help you debug it but it's outside of my expertise.  Since we've determined the emulator endpoint itself is working correctly I am going to close this issue, I hope you find your solution!

**Closed by samtstern** 2021-01-26 18:30 UTC
Labels: Needs: Attention

**Comment by jgavazzisp** [comment] 2021-05-14 02:51
Any update on this issue team?

Facing the same problem mentioned above works using curl but not on Android (returns 404 and no data is deleted).

![image](https://user-images.githubusercontent.com/309389/118214391-bac49580-b4c3-11eb-8e9a-e08f97276ee1.png)
