### ISSUE TITLE
Hot reload not working

### ISSUE THREAD

**Issue by Meistercoach83** [firebase/firebase-tools#2761] opened 2020-10-29 18:57 UTC
Good evening! I´m writing my cloud functions in typescript - so I have to watch them with tsc -w and then do an npm run build && firebase emulators:start

Shouldn´t there be a hot reload when I change any file? 
I´m importing some shared interfaces from an frontend app - so my main-file is not in the root path but in "main": "lib/functions/src/index.js"

i´m on windows 10, node version 12.18.1

"firebase-admin": "^9.3.0",
"firebase-functions": "^3.6.1",
"firebase-tools": "^8.14.1",

 if that helps..

**Comment by samtstern** [comment] 2020-10-30 09:50
@Meistercoach83 does the `"main"` field in your `package.json` point to `lib/functions/src/index.js`?  I have a similar setup in one of my own personal projects but hot reload works fine for me.

**Comment by Meistercoach83** [comment] 2020-10-30 10:07
Yes, its pointed to that folderVon meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Sam Stern <notifications@github.com>Datum: Fr., 30. Okt. 2020, 10:50An: firebase/firebase-tools <firebase-tools@noreply.github.com>Cc: Meistercoach83 <thomas.handle@gmail.com>, Mention <mention@noreply.github.com>Betreff: Re: [firebase/firebase-tools] Hot reload not working (#2761)
@Meistercoach83 does the "main" field in your package.json point to lib/functions/src/index.js?  I have a similar setup in one of my own personal projects but hot reload works fine for me.

**Comment by Hari-07** [comment] 2020-11-08 15:53
@Meistercoach83  What OS are you on?

**Comment by samtstern** [comment] 2020-11-12 11:45
@Meistercoach83 I'm sorry but I am not able to reproduce this.  I did a brand new `firebase init functions` and then added the following setup:

**functions/package.json**
```json
{
  "name": "functions",
  "scripts": {
    "build": "tsc",
    "build:watch": "tsc -w"
  },
  "engines": {
    "node": "12"
  },
  "main": "lib/functions/src/index.js",
  "dependencies": {
    "firebase-admin": "^9.2.0",
    "firebase-functions": "^3.11.0"
  },
  "devDependencies": {
    "typescript": "^3.8.0",
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
}
```

**functions/src/index.ts**
```ts
import * as functions from 'firebase-functions';
import * as util from "../../shared/util";

export const helloWorld = functions.https.onRequest((request, response) => {
  util.helloWorld();
  response.send("Hello from Firebase!");
});
```

**shared/util.ts**
```ts
export function helloWorld() {
  console.log("Hello, World!");
}
```

Then I ran 3 terminals:

1. In `functions`: `npm run build:watch`
2. In `functions`: `firebase emulators:start`
3. Used for testing

I then tested adding `- hot!` to the strings in both `index.ts` and `util.ts` and called the function twice.

**Emulator logs**
```
i  functions: Beginning execution of "helloWorld"
>  Hello, World!
i  functions: Finished "helloWorld" in ~1s
i  functions: Beginning execution of "helloWorld"
>  Hello, World!
i  functions: Finished "helloWorld" in ~1s
i  functions: Beginning execution of "helloWorld"
>  Hello, World! - hot
i  functions: Finished "helloWorld" in ~1s
```

**http logs**
```
$ http http://localhost:5001/fir-dumpster/us-central1/helloWorld
HTTP/1.1 200 OK
connection: keep-alive
content-length: 26
content-type: text/html; charset=utf-8
date: Thu, 12 Nov 2020 11:40:10 GMT
etag: W/"1a-a1lUfHepXJL6fvFazYW9he79Ndc"
x-powered-by: Express

Hello from Firebase - hot!

samstern@samstern-macbookpro3 functions 
$ http http://localhost:5001/fir-dumpster/us-central1/helloWorld
HTTP/1.1 200 OK
connection: keep-alive
content-length: 26
content-type: text/html; charset=utf-8
date: Thu, 12 Nov 2020 11:40:22 GMT
etag: W/"1a-a1lUfHepXJL6fvFazYW9he79Ndc"
x-powered-by: Express

Hello from Firebase - hot!
```

So at this point I am confident there is not a bug in the Firebase CLI.  It's likely something to do with your local setup but as you can imagine there's almost no way I can guess what the issue is from here.

As an aside: I use a setup just like this for my personal projects.  I have used it successfully on both Windows 10 and WSL2, so I am sure our hot reload works across platforms as well.

Since I've done a full repro attempt and am not able to reproduce this, I have to close the issue as infeasible.  If you're able to reproduce this with the exact same simple setup I just described please just mention me here and I will gladly re-open the issue.

**Closed by samtstern** 2020-11-12 11:45 UTC
Labels: Needs: Attention, emulator-suite, emulators: functions

**Comment by Hari-07** [comment] 2020-11-12 11:53
@samtstern The issue could be that if he's running on wsl2 , but the project is stored in the windows file system hot reload will not work , as wsl2 does not watch it. WSL used to . https://docs.microsoft.com/en-us/windows/wsl/compare-versions

**Comment by samtstern** [comment] 2020-11-12 11:54
@Hari-07 thank you I did not know that!
