### ISSUE TITLE
-bash: /usr/local/bin/firebase: No such file or directory

### ISSUE THREAD

**Issue by Domiii** [firebase/firebase-tools#1851] opened 2019-12-06 15:20 UTC
### Intro

Recently, when doing yet another `firebase deploy` (after I used it just fine for many months), it said I was not logged in. When trying `firebase login`, it uses the command-line login (asks me for email + password in terminal), instead of opening a browser window. When doing `firebase --version`, it said some ridiculously outdated version (sorry, I forgot what it was). After removing it all, I ended up with:

```sh
$ firebase -v
-bash: /usr/local/bin/firebase: No such file or directory
```

Not even sure why it would think to look there. `npm unlink` did not do anything either.

### [REQUIRED] Environment info

**firebase-tools:** (N/A)

**OS:** MacOS Mojave 10.14.6

**Node:** v13.2.0

### [REQUIRED] Test case

Cannot test.

### [REQUIRED] Steps to reproduce

* have some old versions of firebase installed globally (not sure which)
* `$ npm uninstall -g firebase-tools`
* `$ npm unlink -g firebase-tools`
* `$ npm unlink -g firebase`
* `$ npm i -g firebase-tools`
* `$ which firebase`
   * `/usr/local/bin/firebase`
* `$ rm -rf /usr/local/bin/firebase`

```sh
$ firebase -v
-bash: /usr/local/bin/firebase: No such file or directory
```

### [REQUIRED] Expected behavior

Firebase to be installed and updated to latest version.

### [REQUIRED] Actual behavior

```sh
$ firebase -v
-bash: /usr/local/bin/firebase: No such file or directory
```

### Workaround

I can currently use `firebase-tools` just fine using: `npx firebase <deploy/login etc...>`. Also, if I do `npx firebase login` it recognizes my old login as well; does not ask me to login again. It's as though some recent change to my system overrode my working `firebase-tools` with some broken version. Not sure what it even could be. Just want to get rid of the old broken version of it all.

Most likely this was triggered by using `nvm` to switch to a different `node` version. I thought I was on latest the entire time, until I realized that `nvm` does not actually set latest to the default, meaning that after system restarts I was using an outdated `node` (v8.x.x). So changing from old node to new node (now on v13.x.x) seems to have caused this. I also distinctively remember that I went through similar pain a long time ago. Not sure why the issue reappeared.

Probably related to #873 (however I am using `nvm` to manage my node versions already).

**Comment by samtstern** [comment] 2019-12-06 16:49
@Domiii I've been in your situation before, with all the ways an `npm` module can be discovered it can be really hard to figure out where the issue is coming from!

Can you try running `readlink $(which firebase)`?  I suspect `/usr/local/bin/firebase` is not the real location of the executable.

For example on my system:
```
$ which firebase
/usr/bin/firebase
```
```
$ readlink $(which firebase)
../lib/node_modules/firebase-tools/lib/bin/firebase.js
```

**Comment by Domiii** [comment] 2019-12-07 03:12
Thank you, @samtstern!

Since the file does not exist, it does not do anything; all empty.

```
$ which firebase
$ readlink $(which firebase)
$
```

It is still odd that it tries to lookup `firebase` as `/usr/local/bin/firebase` I guess... Not sure where that is coming from.

I also found that `npx firebase login` executes instantly and is a really good work-around, while `npx firebase-tools login` does a temporary download every time before executing (it also works, but is way slower because it does not recognize the globally installed module).

**Comment by samtstern** [comment] 2019-12-09 17:24
@Domiii thanks for clarifying!  You could probably inspect your `PATH` to find out why it's looking in `/usr/local/bin/firebase` ... it does sound like you're in a very tricky situation.  However because `npx firebase login` works that confirms there's not an issue in `firebase-tools` and this is actually an issue specific to your setup.  Because of that there's not really much we can do in this repo to help, so I will close this issue.  I hope you understand!

I would suggest opening a question on StackOverflow where someone who is a more general Node/NVM expert can help get you unstuck!

**Closed by samtstern** 2019-12-09 17:24 UTC
Labels: Needs: Attention
