### ISSUE TITLE
Deploying multiple storage targets failed with unexpected error

### ISSUE THREAD

**Issue by Thammachart** [firebase/firebase-tools#4762] opened 2022-07-21 10:15 UTC
### [REQUIRED] Environment info

**firebase-tools:** 11.3.0 (The problem have occurred since 11.2.2)

**Platform:** Arch Linux, Ubuntu (GitHub Actions), macOS

### [REQUIRED] Test case

1. Initialize the project by issuing `firebase init storage` with a selected firebase project and the rest is defaults

### [REQUIRED] Steps to reproduce

1. Edit the `firebase.json` file to enclose the storage target(s) with array
```json
{
  "storage": [
    {
      "target": "t0",
      "rules": "storage.rules"
    }
  ]
}


```
2. Apply the target `t0` by issuing `firebase target:apply storage t0 <BUCKET_NAME>`
3. Deploy by issuing `firebase deploy --debug --only storage` (`--only storage` part is optional)

### [REQUIRED] Expected behavior

The deploy command finishes successfully with all storage rule targets applied in the selected firebase project

### [REQUIRED] Actual behavior

We got the output (sensitive info are redacted)
```
[2022-07-21T10:05:25.898Z] Field ".storage" in "firebase.json" is possibly invalid: should be object
[2022-07-21T10:05:25.899Z] Object ".storage[0]" in "firebase.json" is missing required property: {"missingProperty":"bucket"}
[2022-07-21T10:05:25.899Z] Field ".storage" in "firebase.json" is possibly invalid: should match some schema in anyOf
[2022-07-21T10:05:25.901Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2022-07-21T10:05:25.902Z] > authorizing via signed-in user (<REDACTED>@<REDACTED>)
[2022-07-21T10:05:25.902Z] [iam] checking project <REDACTED> for permissions ["firebase.projects.get","firebaserules.releases.create","firebaserules.releases.update","firebaserules.rulesets.create"]
[2022-07-21T10:05:25.903Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/<REDACTED>:testIamPermissions [none]
[2022-07-21T10:05:25.903Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/<REDACTED>:testIamPermissions {"permissions":["firebase.projects.get","firebaserules.releases.create","firebaserules.releases.update","firebaserules.rulesets.create"]}
[2022-07-21T10:05:27.033Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/<REDACTED>:testIamPermissions 200
[2022-07-21T10:05:27.034Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/<REDACTED>:testIamPermissions {"permissions":["firebase.projects.get","firebaserules.releases.create","firebaserules.releases.update","firebaserules.rulesets.create"]}

=== Deploying to '<REDACTED>'...

i  deploying storage 
[2022-07-21T10:05:27.035Z] >>> [apiv2][query] GET https://appengine.googleapis.com/v1/apps/<REDACTED> [none]
[2022-07-21T10:05:27.552Z] <<< [apiv2][status] GET https://appengine.googleapis.com/v1/apps/<REDACTED> 200
[2022-07-21T10:05:27.552Z] <<< [apiv2][body] GET https://appengine.googleapis.com/v1/apps/<REDACTED> {"name":"apps/<REDACTED>","id":"<REDACTED>","authDomain":"gmail.com","locationId":"us-central","servingStatus":"SERVING","defaultHostname":"<REDACTED>.uc.r.appspot.com","defaultBucket":"<REDACTED>.appspot.com","serviceAccount":"<REDACTED>@appspot.gserviceaccount.com","gcrDomain":"us.gcr.io","databaseType":"CLOUD_FIRESTORE","featureSettings":{"splitHealthChecks":true}}
[2022-07-21T10:05:27.555Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:1172:7)
    at Config.path (/home/<REDACTED>/.config/yarn/global/node_modules/firebase-tools/lib/config.js:123:45)
    at RulesDeploy.addFile (/home/<REDACTED>/.config/yarn/global/node_modules/firebase-tools/lib/rulesDeploy.js:33:46)
    at /home/<REDACTED>/.config/yarn/global/node_modules/firebase-tools/lib/deploy/storage/prepare.js:23:21
    at Array.forEach (<anonymous>)
    at default_1 (/home/<REDACTED>/.config/yarn/global/node_modules/firebase-tools/lib/deploy/storage/prepare.js:19:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async chain (/home/<REDACTED>/.config/yarn/global/node_modules/firebase-tools/lib/deploy/index.js:33:9)
    at async deploy (/home/<REDACTED>/.config/yarn/global/node_modules/firebase-tools/lib/deploy/index.js:68:5)

Error: An unexpected error has occurred.
```
---
This issue doesn't occur when one of the conditions below matches:
-  `firebase-tools@11.2.1` or earlier is used
- Use only one storage target without array enclosed in `firebase.json`
```json
{
  "storage": {
    "target": "t0",
    "rules": "storage.rules"
  }
}
```

**Comment by bkendall** [comment] 2022-07-25 23:01
Duplicate of #4752

**Closed by bkendall** 2022-07-25 23:01 UTC
Labels: emulators: storage, bug
