### ISSUE TITLE
Could not find the next executable

### ISSUE THREAD

**Issue by MiftahClassifieds** [firebase/firebase-tools#6173] opened 2023-07-25 15:23 UTC
### Environment info node 16.16.0
npm 8.11.0

**firebase-tools:** 12.4.4

**Platform:** nextjs

###  Steps to reproduce:
*1* create nextjs project
*2* firebase init
*3* firebase deploy

###  Actual behavior:
[info] 
   Thank you for trying our early preview of Next.js support on Firebase Hosting.
   During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/nextjs
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

[error] 
[error] Error: Could not find the next executable.

**Comment by aalej** [comment] 2023-07-25 16:40
Hi @MiftahClassifieds, thanks for reaching out to us. I’m using Next.js v13.4.9 and firebase-tools v12.4.4 to replicate this issue while waiting for the fix for [#6163](https://github.com/firebase/firebase-tools/issues/6163) to be released. So far, I haven’t encountered any issues while deploying. 

Let me know if I may have made a mistake or missed anything; the steps I took were:

1. Run `npx create-next-app`
2. Run `cd my-app`
3. Downgrade Next.js to `13.4.9`
3. Run `firebase init hosting --project <project_id>`
4. Run `firebase deploy`

Could you let us know which version of Next.js you’re using and share with us the output of running `firebase deploy --debug`? Passing the `--debug` flag provides a detailed log that we can use to check what caused the error. Please remove any PII (personal identifiable information) if needed.

**Comment by malikmubashar** [comment] 2023-07-26 14:20
Exectly same issue here.
I tried more than 10 time with different projects and nextjs versions but all in vain. Always shows the same error

 "Could not find the next executable".

**Comment by malikmubashar** [comment] 2023-07-26 14:21
Here are the complete log.




[debug] [2023-07-26T13:58:04.741Z] ----------------------------------------------------------------------
[debug] [2023-07-26T13:58:04.745Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\<username>\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy --debug
[debug] [2023-07-26T13:58:04.746Z] CLI Version:   12.4.6
[debug] [2023-07-26T13:58:04.746Z] Platform:      win32
[debug] [2023-07-26T13:58:04.746Z] Node Version:  v18.16.1
[debug] [2023-07-26T13:58:04.748Z] Time:          Wed Jul 26 2023 18:58:04 GMT+0900 (Time)
[debug] [2023-07-26T13:58:04.748Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-07-26T13:58:04.934Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-07-26T13:58:04.938Z] > authorizing via signed-in user (email@gmail.com)
[debug] [2023-07-26T13:58:04.940Z] [iam] checking project project01 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-07-26T13:58:04.947Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/project01:testIamPermissions [none]
[debug] [2023-07-26T13:58:04.948Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/project01:testIamPermissions x-goog-quota-user=projects/project01
[debug] [2023-07-26T13:58:04.952Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/project01:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-07-26T13:58:06.730Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/project01:testIamPermissions 200
[debug] [2023-07-26T13:58:06.732Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/project01:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-07-26T13:58:06.735Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/project01 [none]
[debug] [2023-07-26T13:58:07.341Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/project01 200
[debug] [2023-07-26T13:58:07.342Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/project01 {"projectId":"project01","projectNumber":"<number>","displayName":"user","name":"projects/project01","resources":{"hostingSite":"project01"},"state":"ACTIVE","etag":"--"}
[info] 
   Thank you for trying our early preview of Next.js support on Firebase Hosting.
   During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/nextjs
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

[error] 
[error] Error: Could not find the next executable.

**Comment by aalej** [comment] 2023-07-28 14:59
Thanks for the providing the debug logs, @malikmubashar. I tried to repro this again using Next.js v13.4.12 and firebase-tools v12.4.6, but so far I have not encountered any issues running `firebase deploy`. I’m thinking this issue might be similar to [#6187](https://github.com/firebase/firebase-tools/issues/6187). To help us verify if the cause of this is similar to #6187, could you answer the following:

1. Are you encountering a similar error message when running `firebase emulators:start`, or does it run without any issues?
2. Are you able to run `npm run dev` or `npx next dev` without any issues?
3. Does running `npm i` or `npm install` then re-deploying via `firebase deploy` produce a different behavior?
4. In your `node_modules` directory, do you see a `./bin/next` file?

**Comment by aacotroneo** [comment] 2023-07-28 19:05
More info
- I installed firebase-tools from https://firebase.tools cli (12.4.6) on a new env (osx) 
- firebase deploy shows the mentioned error. even in an old project I tried 3 months ago (in another computer) which used to work
- I uninstalled firebase-tools, and installed `npm install -g firebase-tools@12.0.0`
- Deploy worked as expected
- I re-installed npm install -g firebase-tools@12.4.6
- Deploy continues to work as expected (same version I installed with the CLI)

If I had to guess it's some initialization issue in the CLI, so it won't be easy to reproduce for people that have a working firebase env, but new users will face this issue. Or it can be anything else, haha. it's weird!

**Comment by aacotroneo** [comment] 2023-07-28 19:09
nevermind.. I reinstalled from https://firebase.tools/ and it doesn't work. So that seems to be the issue.

In the meantime people can install with npm and it should be fine.

**Comment by MiftahClassifieds** [comment] 2023-07-28 20:27
Hi,
@aalej : as you suggested to me I followed the steps you provided above with the follow config:
   Next.js v13.4.9
  firebase tools 12.4.4
  node 16.16.0
  npm 9.8.1

I install the mentionned next version both globaly -g and locally in my project:

I got same error : Could not find the next executable!
some old versions work fine as firebase-tools@11.29.0 but without internationalization (i18n) next-i18next or next-translate
when i deploy with 11.29.0 for ex .The deploy succeed but .the call to the website return 'internal error 500'
If i remove again the translation dependencies , the site become to work!

this is my log as you requested:

`PS E:\28_07_2023\m3> cd miftah
PS E:\28_07_2023\m3\miftah> firebase init

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##      
     ######    ##  ########  ######   ########  #########  ######  ######  
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##      
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  E:\28_07_2023\m3\miftah

? Are you ready to proceed? Yes
? Which Firebase features do you want to set up for this directory? Press Space to select features, then Enter to confirm your choices. Hosting: Configure 
files for Firebase Hosting and (optionally) set up GitHub Action deploys

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

? Please select an option: Use an existing project
? Select a default Firebase project for this directory: aqar-agadir (market)
i  Using project aqar-agadir (market)

=== Hosting Setup
? In which region would you like to host server-side content, if applicable? us-central1 (Iowa)
? Set up automatic builds and deploys with GitHub? No

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

+  Firebase initialization complete!

   ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                     │
   │                                          Update available 12.4.4 → 12.4.6                                           │
   │                                   To update to the latest version using npm, run                                    │
   │                                            npm install -g firebase-tools                                            │
   │   For other CLI management options, visit the CLI documentation (https://firebase.google.com/docs/cli#update-cli)   │
   │                                                                                                                     │
   │                                                                                                                     │
   ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

PS E:\28_07_2023\m3\miftah> firebase deploy

   Thank you for trying our early preview of Next.js support on Firebase Hosting.
   During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/nextjs
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X


Error: Could not find the next executable.
PS E:\28_07_2023\m3\miftah> firebase deploy --debug
[2023-07-28T20:26:21.871Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-07-28T20:26:21.876Z] > authorizing via signed-in user (ouazza422@gmail.com)
[2023-07-28T20:26:21.878Z] [iam] checking project aqar-agadir for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[2023-07-28T20:26:21.886Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/aqar-agadir:testIamPermissions [none]
[2023-07-28T20:26:21.887Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/aqar-agadir:testIamPermissions x-goog-quota-user=projects/aqar-agadir
[2023-07-28T20:26:21.892Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/aqar-agadir:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[2023-07-28T20:26:22.925Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/aqar-agadir:testIamPermissions 200
[2023-07-28T20:26:22.927Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/aqar-agadir:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[2023-07-28T20:26:22.934Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/aqar-agadir [none]
[2023-07-28T20:26:23.443Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/aqar-agadir 200
[2023-07-28T20:26:23.446Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/aqar-agadir {"projectId":"aqar-agadir","projectNumber":"343481120778","displayName":"market","name":"projects/aqar-agadir","resources":{"hostingSite":"aqar-agadir","realtimeDatabaseInstance":"aqar-agadir","storageBucket":"aqar-agadir.appspot.com","locationId":"us-central"},"state":"ACTIVE","etag":"1_e117d29a-45a3-4d08-9514-8f411667685a"}

   Thank you for trying our early preview of Next.js support on Firebase Hosting.
   During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/nextjs
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X


Error: Could not find the next executable.
PS E:\28_07_2023\m3\miftah> `

**Comment by frankl1** [comment] 2023-07-29 15:14
I am facing the same problem when deploying using Github action. The deployment is working like a charm locally on my computer using firebase cli.

**Comment by MiftahClassifieds** [comment] 2023-07-29 20:59
[https://firebasestorage.googleapis.com/v0/b/aqar-agadir.appspot.com/o/webIssues%2Fsource.issue.png?alt=media&token=14cd7fc7-dcf8-4b12-a48e-9e6bdeed5b6f](url)
I found what is causing the bug: the entry mentioned in the image --> inside firebase.json
"source" : ".",
In one of my old projects, I configured a custom nextServer, the entry is defined as follows:
"source": ".next" and I was able to successfully deploy my project; but somehow I changed it to "source": ".", and I get the same error: "Could not find the following executable"
but here using the experimental firebase cli framework, even if I change to "source": ".next" I still have the same bug until I completely remove "source" but change it to "public":" ." don't call the experimental framework to do its job. So what?!

**Comment by frankl1** [comment] 2023-07-29 21:49
Don't know why, but the configuration "source": "." is not causing problem in my case when I run `firebase deploy`.  The error appears when running the Github action for automatic deployment after a merge.

**Comment by tahamukhtar20** [comment] 2023-08-03 08:48
I faced the same problem but managed to find a solution. I was able to deploy directly using the Firebase CLI, but for some reason, using GitHub actions for the same task didn't work.

**Comment by malikmubashar** [comment] 2023-08-10 16:06
here is the debug file


[debug] [2023-08-10T15:58:28.697Z] ----------------------------------------------------------------------
[debug] [2023-08-10T15:58:28.701Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\username\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy --debug
[debug] [2023-08-10T15:58:28.702Z] CLI Version:   12.4.7
[debug] [2023-08-10T15:58:28.703Z] Platform:      win32
[debug] [2023-08-10T15:58:28.703Z] Node Version:  v18.16.1
[debug] [2023-08-10T15:58:28.705Z] Time:          Thu Aug 10 2023 20:58:28 G-00500 (Standard Time)
[debug] [2023-08-10T15:58:28.705Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-08-10T15:58:28.889Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-08-10T15:58:28.893Z] > authorizing via signed-in user (email@gmail.com)
[debug] [2023-08-10T15:58:28.894Z] [iam] checking project <projectId> for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-08-10T15:58:28.899Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/projectId:testIamPermissions [none]
[debug] [2023-08-10T15:58:28.900Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/projectId:testIamPermissions x-goog-quota-user=projects/projectId
[debug] [2023-08-10T15:58:28.902Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/projectId:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-08-10T15:58:30.845Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/projectId:testIamPermissions 200
[debug] [2023-08-10T15:58:30.847Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/projectId:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-08-10T15:58:30.851Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/projectId [none]
[debug] [2023-08-10T15:58:31.658Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/projectId 200
[debug] [2023-08-10T15:58:31.660Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/projectId {"projectId":"projectId","projectNumber":"<>","displayName":"<>","name":"projects/projectId","resources":{"hostingSite":"projectId"},"state":"ACTIVE","etag":"<>"}
[info] 
   Thank you for trying our early preview of Next.js support on Firebase Hosting.
   During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/nextjs
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

[error] 
[error] Error: Error finding next executable: failed to spawn 'npm'

**Comment by malikmubashar** [comment] 2023-08-10 16:09
producing same problem as describe in #6227 using new firebase cli version.

**Comment by dzeroone** [comment] 2023-08-13 07:36
I am also having the same issue!
Have you found any work around it?

**Comment by 8ftBeanBag** [comment] 2023-08-16 21:02
Same issue. Weirdly enough, setting the next distDir to out got me further along in the process but it still failed. 

Here's what worked.

1. Run npm run build (or whatever builds your app)
2. Rename the build file to _next (the build file is probably .next)
3. Change `source: "."` to `public: "."` in your firebase.json file
4. Go to _next/server/app and copy the index.html file to the same level as your _next directory.
5. Run `firebase deploy` for the 4793457024752 time. 

Hopefully this works for you as well. Best of luck!

**Comment by GuiltyRemnant** [comment] 2023-08-17 09:44
Thanks for sharing your solution. But i have to say, this doesnt work for me and i noticed, our setup differs in details.

By renaiming `source` to `public` in firebase.json file, the deploy process tries to upload the builded folder - yes - but with `source`, firebase-tools tries to build it itself, respecting things like the routing logic (at least, thats to my knowledge).

My index.html is in .next/server/pages - also tried to rename builded folder to _next, but that didnt work out at all. So, i have the `public` directive in my json instead of `source` and i can also provide a target for my index.html like
`"rewrites": [
      {
        "source": "**",
        "destination": "/server/pages/index.html"
      }
    ],`
which will find the index.html - but it routes everything to it, which is incorrect. I probably need something for firebase-functions, then have it like this
`"rewrites": [
      {
        "source": "**/**",
        "function": "nextjsServer"
      }
    ]`
providing the nextjsServer function on the server. I got this from [here](https://www.codeproject.com/Articles/5360871/How-to-Deploy-Next-js-to-Firebase).

I just thought, that firebase-tools would do that, so i dont need to create own functionality in my backend? Like described on this [official site](https://firebase.google.com/docs/hosting/frameworks/nextjs). Otherwise, i wouldnt need the firebase-tools.

**Comment by BorisUpheave** [comment] 2023-08-18 09:35
I'm getting the same error on mac: "Error: Error finding next executable: failed to spawn 'npm'"

Next.js v13.1.6
firebase tools 12.4.8
node 16.17.0
npm 8.15.0

**Comment by GuiltyRemnant** [comment] 2023-08-18 10:32
@BorisUpheave did you tried installing firebase tools global? `npm i -g firebase-tools`

After doing that, my error switched from "failed to spawn npm" to "Unable to find the next dep, try NPM installing?". But maybe this is all the same problem, i dont know - i am suspecting a problem resolving versions between firebase / firebase-tools / firebase-frameworks and next.js

**Comment by BorisUpheave** [comment] 2023-08-18 11:37
@GuiltyRemnant yes, getting the same error.

**Comment by GuiltyRemnant** [comment] 2023-08-19 22:53
This will be a long post (sorry), i am trying to split it down from the most to less important (so you can fix your project), but first thing is to give people the ability back to deploy their Next.JS and second thing is to give google developers the chance to fix it in future releases.

There is actually a bug with the correct dependencies (if you want to know how i came to this conclusion, read my earlier [post](https://github.com/firebase/firebase-tools/issues/6173#issuecomment-1681970663) on this page).

**Fix your project the fast way:** 
`npm i -g firebase-tools@11.29.0 ` and after that `npm i firebase@^9.9.0` and run `firebase deploy` (for the 4793457024753rd time).

**For people who want background:**
NPM will have you know about all the old stuff, you are installing, but just do it. The process is taking some time, because it will make stuff happen to your firebase functions, giving you the ability to run Next.JS on the server with routing / image optimization and stuff like that. Propably there is a chance to update certain libs after that, because now your functions are in place to do that stuff for you. :)

Why is that happening (to the most advanced framework for react), why are posts like [that](https://github.com/firebase/firebase-tools/issues/6100) are getting closed and why is this a problem since -who-knows-? I am suggesting a change in the responsability - i think, there were developer(s) for this, making cool stuff like that, but they aren't on the project anymore as it looks to me. Unfortunately.

While the idea of firebase is groundbreaking, there are concepts outside of the company, which they're not supporting at the moment.

I could write more here, but i don't think it would be fair to the very great developers, who make it happen in the first place. I wish them all the best and also i am thanking @aalej very much for the support he gave us here. Maybe he can give future developers the best of information to fix the problem. So thank you my friend.

I will end this posting by giving you the output of my console. When you dont have the functions in your project, the Next.JS is not able to work. Propably, there are even features, which only works in newer versions, like i18 features (@MiftahClassifieds mentioned here) - i didnt tested that. I am using Nextra docs template, so there are some cache specific errors specific to this add-on, which you shouldnt have in theorie, when setting up a fresh Next.JS. Obviously i changed paths and the project name.
Running `firebase deploy`:

Detected a Next.js codebase. This is an experimental integration, proceed with caution.

- info Checking validity of types  
- info Creating an optimized production build ...<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\User\my-project\my-project\node_modules\nextra\dist\plugin.mjs for build dependencies failed at 'import(importPath)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve './__temp__' in 
-errors with pathes i dont want to post here-
- info Creating an optimized production build ...<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of C:\Users\User\path-i-dont-want-to-post-here\node_modules\nextra\dist\plugin.mjs for build dependencies failed at 'import(importPath)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve './__temp__' in 'C:\Users\User\path-i-dont-want-to-post-here\node_modules\nextra\dist'
- info Creating an optimized production build
- info Compiled successfully
- info Collecting page data  
- info Generating static pages (5/5)
- info Finalizing page optimization

Route (pages)                              Size     First Load JS
┌ ○ /                                      4.02 kB         329 kB
├ ○ /404                                   182 B            80 kB
├ ○ /personal-area (358 ms)                  2.73 kB         332 kB
├   └ css/40996bb27a636251.css             246 B
└ ○ /personal-area/personal-area         2.33 kB         332 kB
+ First Load JS shared by all              79.8 kB
  ├ chunks/framework-63157d71ad419e53.js   45.2 kB
  ├ chunks/main-79a3b354e6e7341d.js        33.3 kB
  ├ chunks/pages/_app-aea6540bd27938ca.js  195 B
  └ chunks/webpack-36d12a75f0098f27.js     1.04 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)

Building a Cloud Function to run this application. This is needed due to:
 • Image Optimization
 • non-static route /personal-area
 • non-static route /personal-area/personal-area

Unable to bundle next.config.js for use in Cloud Functions, proceeding with deploy but problems may be enountered.
Die Befehlszeile ist zu lang.

npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known 
to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@3.6.5: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 1518 packages in 2m

209 packages are looking for funding
  run `npm fund` for details

=== Deploying to 'my-project'...

i  deploying functions, hosting
i  functions: preparing codebase firebase-frameworks-my-project for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
+  functions: required API cloudfunctions.googleapis.com is enabled
+  artifactregistry: required API artifactregistry.googleapis.com is enabled
+  functions: required API cloudbuild.googleapis.com is enabled
!  functions: package.json indicates an outdated version of firebase-functions. Please upgrade using npm install --save firebase-functions@latest in your functions directory.
!  functions: Please note that there will be breaking changes when you upgrade.
i  functions: Loaded environment variables from .env.
i  functions: preparing .firebase\my-project\functions directory for uploading...
i  functions: packaged C:\Users\User\my-project\my-project\.firebase\my-project\functions (220.78 MB) for uploading
i  functions: ensuring required API run.googleapis.com is enabled...
i  functions: ensuring required API eventarc.googleapis.com is enabled...
i  functions: ensuring required API pubsub.googleapis.com is enabled...
i  functions: ensuring required API storage.googleapis.com is enabled...
!  functions: missing required API eventarc.googleapis.com. Enabling now...
+  functions: required API pubsub.googleapis.com is enabled
+  functions: required API storage.googleapis.com is enabled
!  functions: missing required API run.googleapis.com. Enabling now...
+  functions: required API run.googleapis.com is enabled
+  functions: required API eventarc.googleapis.com is enabled
i  functions: generating the service identity for pubsub.googleapis.com...
i  functions: generating the service identity for eventarc.googleapis.com...
+  functions: .firebase\my-project\functions folder uploaded successfully
i  hosting[my-project]: beginning deploy...
i  hosting[my-project]: found 24 files in .firebase\my-project\hosting
+  hosting[my-project]: file upload complete
i  functions: creating Node.js 16 function firebase-frameworks-my-project:ssrmyproject(europe-west1)...
+  functions[firebase-frameworks-my-project:ssrmyproject(europe-west1)] Successful create operation.
Function URL (firebase-frameworks-my-project:ssrmyproject(europe-west1)): https://ssrmyproject-qknxhzi2ia-ew.a.run.app
i  functions: cleaning up build files...
i  hosting[my-project]: finalizing version...
+  hosting[my-project]: version finalized
i  hosting[my-project]: releasing new version...
+  hosting[my-project]: release complete

+  Deploy complete!

**Comment by alexjmoore** [comment] 2023-08-30 13:49
Not sure it is limited to Windows only, I also saw issues on my ChromeOS Debian Linux environment

**Comment by andresuarezz26** [comment] 2023-09-10 02:17
Hey I had the same error and solves it changing the firebase.json configuration. 
I changed the "public" field from "public" to "out":
"public": "out",
That solved the issue for me.

**Comment by davidgiesemann** [comment] 2023-09-15 11:32
I had to change firebase.json so it won't ignore .next folder:

...
    "ignore": [
     ...,
     "**/.*", <-- Removed this line
    ...,
    ],
...

This made my deployment run sucessfully!

**Closed as completed** 2023-09-18 15:25 UTC
Labels: type: bug, Needs: Author Feedback, Needs: Attention, integration: web frameworks

**Comment by leoortizz** [comment] 2023-09-18 15:42
Thanks everyone for providing detailed information about the issue. I was able to reproduce it and found that the root cause is in the build step performed by the CLI, where `npm root` runs multiple times. There was a 2 seconds timeout and depending on the CPU this could take longer. I submitted a fix in #6372 which will be available in the next release.

**Comment by RickWiltvank** [comment] 2024-04-18 09:44
We fixed this by using

`npm install firebase-frameworks`

After several hours of reinstalls of different versions of node, next, firebase, firebase-tools etc (which did not work)
