### ISSUE TITLE
Cannot set property config of #<Object> which has only a getter

### ISSUE THREAD

**Issue by boddy33** [firebase/firebase-tools#2301] opened 2020-05-28 19:00 UTC
### [REQUIRED] Environment info

**firebase-tools:** 8.4.0

**Platform:** Windows

### [REQUIRED] Test case

index.js

```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();

exports.testFunction = functions.https.onRequest(async (req, res) => {

  console.log(req.body);

});
```

### [REQUIRED] Steps to reproduce

the initial emulate worked fine
the initial and subsequent deploys work fine
the function works fine in production
not able to emulate locally anymore.

Console output:
```
i  emulators: Starting emulators: functions
+  functions: Using node@10 from host.
i  functions: Watching "D:\path\to\functions" for Cloud Functions...
!  functions: Cannot set property config of #<Object> which has only a getter
!  Your function was killed because it raised an unhandled error.
```

In addition to this issue, it is not clear from output what happened. Nothing in debug logs.

### [REQUIRED] Expected behavior

Emulator starts

### [REQUIRED] Actual behavior

Emulator fails to start

**Comment by samtstern** [comment] 2020-05-28 19:16
@boddy33 huh ok that's extremely strange.  Is there absolutely nothing else `firebase-debug.log`?  Or if you run the command with `--debug`?

**Comment by uditha-atukorala** [comment] 2020-05-28 20:07
Looks like this is an issue with v8.x.x. Downgrading to v7.16.2 works.

**Comment by samtstern** [comment] 2020-05-28 20:13
I have a feeling this may be related to today's firebase-functions release:
https://github.com/firebase/firebase-functions/releases/tag/v3.6.2

**Comment by uditha-atukorala** [comment] 2020-05-28 20:16
I should be something very recent. Looking at other issues, v8.x.x emulator was working at some point (and v8.4.0 was released a week ago).

**Comment by maxmayerhofer93** [comment] 2020-05-28 20:36
hi, 
have the same issue :)

**Comment by samtstern** [comment] 2020-05-28 20:44
Fix is coming in #2302 ... if it's approved and merged we'll try to release ASAP

**Comment by arjunsss** [comment] 2020-05-28 20:55
Running into the exact same issue. macOS

**Comment by AprilPolubiec** [comment] 2020-05-28 20:57
this has had me stumped for the last few hours. I have the same `index.js` as @boddy33 and it even happens when index.js is empty. Here is my firebase-debug.log:
```
[debug] [2020-05-28T19:54:42.206Z] [runtime-status] [27226] Checked functions.config() {"config":{}} 
[debug] [2020-05-28T19:54:42.206Z] [runtime-status] [27226] Error in handleMessage: {"frb":{"cwd":"/Users/aprilpolubiec/Documents/my-project/functions","projectId":"my-project","triggerId":"","emulators":{},"socketPath":"/var/folders/sh/fsnv9b8n29713r9d3kj_7w4c0000gn/T/fire_emu_27226.sock"},"opts":{"nodeBinary":"/Users/aprilpolubiec/.nvm/versions/node/v13.7.0/bin/node"}} => TypeError: Cannot set property config of #<Object> which has only a getter: TypeError: Cannot set property config of #<Object> which has only a getter
    at /Users/aprilpolubiec/.nvm/versions/node/v13.7.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:457:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/aprilpolubiec/.nvm/versions/node/v13.7.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) 
[warn] ⚠  functions: Cannot set property config of #<Object> which has only a getter
[warn] ⚠  Your function was killed because it raised an unhandled error.
```

**Comment by de1m** [comment] 2020-05-28 21:03
we are waiting curious for approval

**Closed** 2020-05-28 21:14 UTC
Labels: emulator-suite, emulators: functions, type: bug

**Comment by samtstern** [comment] 2020-05-28 21:43
The fix was just released in version `8.4.1` of `firebase-tools`

**Comment by danielhanford** [comment] 2020-05-29 02:56
thank you for that...just in time

**Comment by boddy33** [comment] 2020-05-29 08:15
validated. Thank you.

**Comment by jakubjodelka** [comment] 2020-05-29 10:02
Hello
About 2 days ago I was deploying functions and everything went without any problems, unfortunately since yesterday I am not able to do deploy. I had quite old packages:

```
    "firebase": "^5.9.2",
    "firebase-admin": "~8.9.0",
    "firebase-functions": "^3.3.0",
    "firebase-tools": "^4.0.0",
```
and I was getting the following:
![image](https://user-images.githubusercontent.com/5147492/83247049-47871e00-a1a3-11ea-8132-78d5ade39961.png)
but was able to run functions locally (--serve).

Today I've updated all of dependencies to newer versions, which in theory should include a hotfix, but unfortunately now I'm getting a new bug, the same as in this issue.

```
    "firebase": "^7.14.5",
    "firebase-admin": "~8.10.0",
    "firebase-functions": "^3.6.2",
    "firebase-tools": "^8.4.1",
```

```
[2020-05-29T09:30:46.002Z] [runtime-status] [42525] Error in handleMessage: {"frb":{"cwd":"/Users/jakub.jodelka/xxxProject/backend","projectId":"xxxProject","triggerId":"","emulators":{},"socketPath":"/var/folders/nj/4g6vwdm90bl4tmktf8hpn__00000gp/T/fire_emu_42525.sock"},"opts":{"nodeBinary":"/usr/local/bin/firebase"}} => TypeError: Cannot set property config of #<Object> which has only a getter: TypeError: Cannot set property config of #<Object> which has only a getter
    at /Users/jakub.jodelka/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:455:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jakub.jodelka/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) 
⚠  functions: Cannot set property config of #<Object> which has only a getter
⚠  Your function was killed because it raised an unhandled error.
```

I'm not able to deploy functions, but I can't even run them locally because of the same problem.


> The fix was just released in version `8.4.1` of `firebase-tools`
Should my functions deploy correctly if I have the latest versions?

**Comment by jakubjodelka** [comment] 2020-05-29 10:07
@samtstern ^
Not sure if this issue should be closed.

**Comment by samtstern** [comment] 2020-05-29 12:37
@jakubjodelka can you try clearing your `node_modules` folder and running `npm install` again?  If this keeps happening for you after that and with `firebase --version` showing `8.4.1` let me know.

**Comment by joek-coatsink** [comment] 2020-05-29 12:52
Thanks. Working for me now.

**Comment by COFFEEEADDICT** [comment] 2020-05-29 14:42
![image](https://user-images.githubusercontent.com/53411098/83272345-eec77d80-a1c2-11ea-962c-a7e14e253017.png)

**Comment by samtstern** [comment] 2020-05-29 15:30
@COFFEEEADDICT check that `firebase --version` shows `8.4.1`

**Comment by ricardomouraspl** [comment] 2020-05-29 20:21
Hi guys,

I've received this error after an update in the `firebase-functions` package (3.6.2).

In my case, the solution was to delete `/node_modules` and downgrade the `firebase-functions` to the previous version (`npm install --save firebase-functions@3.6.1`).

**Comment by iamsrujal** [comment] 2020-05-29 20:27
Hello guys,

The first check which version you've installed mine was 8.1.1
Please update firebase-tools by calling

`
sudo npm i  -g firebase-tools
`

This will install latest version 8.4.1
And It fixed my issue. 
In fact, I have installed the latest firebase function and admin 
 "firebase-admin": "8.12.1",
"firebase-functions": "3.6.1",

I hope you've fixed the issue.

**Comment by udsgit** [comment] 2020-05-30 19:13
working thanks @iamsrujal

**Comment by chamikabm** [comment] 2020-06-11 09:24
I'm still getting the issue:

**System** 
Mac OS Catalina : 10.15.4
Node: v10.21.0
Java: openjdk version "14.0.1" 2020-04-14

**Package Versions:**
"firebase-admin": "^8.12.1",
"firebase-functions": "^3.7.0",
firebase-tools@8.4.2

**The command I executed:**
 firebase emulators:start --only functions

 **Console Output:**
i  Starting emulators: ["functions"]
✔  functions: Using node@10 from host.
✔  functions: Emulator started at http://localhost:5001
i  functions: Watching "/Users/chamika/Projects/Bitsmedia/Muslim-Pro-Firebase/functions" for Cloud Functions...
⚠  TypeError: Cannot set property config of #<Object> which has only a getter
    at InitializeFunctionsConfigHelper (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:328:15)
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:448:13
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)
    at main (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:421:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:511:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
⚠  Your function was killed because it raised an unhandled error.

**Comment by mthlongwane** [comment] 2020-06-12 16:25
@chamikabm - I also continued to get the error despite following everyone's suggestions in the thread. 
I was only able to solve it by downgrading the following npm package: 
"firebase-functions": "^3.6.0"

**Comment by nmggithub** [comment] 2020-06-16 17:53
I run `sudo npm i -g firebase-tools`, and it appears to install the latest version, but running `firebase --version`yields `8.1.1`.

**Comment by LeeYang2019** [comment] 2020-06-18 01:27
> The fix was just released in version `8.4.1` of `firebase-tools`

Sorry, I've recently updated firebase-tools to 8.4.3 and then back down to 8.4.1 and am still getting the same "Cannot set property config of #<Object> which has only a getter" error.

**Comment by shaimo** [comment] 2020-06-23 18:54
I'm having this same issue and it doesn't go away even after updating firebase-tools. When I try to run the emulator it fails. In the firebase-debug.log it shows:

```
[debug] [2020-06-23T18:50:31.331Z] [runtime-status] [54019] Error in handleMessage: {"frb":{"cwd":"/Users/shaimo-mbp/dev/javascript/CryptoTracker/functions","projectId":"cryptotracker-fa488","triggerId":"","ports":{"firestore":8080},"socketPath":"/var/folders/83/c3hy2yfx53g6_f3bvwcslqcc0000gn/T/fire_emu_54019.sock"},"opts":{"nodeBinary":"/Users/shaimo-mbp/.nvm/versions/node/v10.18.1/bin/node"}} => TypeError: Cannot set property config of #<Object> which has only a getter: TypeError: Cannot set property config of #<Object> which has only a getter
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:514:19
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[warn] ⚠  functions:
[warn] ⚠  Your function was killed because it raised an unhandled error.
```

How can I fix it? Totally stuck here...

**Comment by samtstern** [comment] 2020-06-23 19:18
For those still experiencing this issue: if you can reproduce this issue on a *freshly initialized project* in a way that we can copy, file a new issue and we will try it.

**Comment by shaimo** [comment] 2020-06-23 19:22
In case it helps anyone: I had to use the explicit version to upgrade the tools and then the problem went away:
`sudo npm i -g firebase-tools@8.4.1`

**Comment by damienromito** [comment] 2020-07-02 15:38
`npm update -g firebase-tools`

**Comment by JohnGeorgiadis** [comment] 2020-07-09 14:01
**System**
Mac OS Catalina : 10.15.4
Node: v10.21.0
Java: openjdk version "14.0.1" 2020-04-14

Update as of 09/07/2020 this issues still exists while using `"firebase-admin": "^8.10.0",`. 
I had to update to `"firebase-admin": "^8.12.1",` and double check that I have `"firebase-tools": "8.4.1"

**Comment by husseinsharif** [comment] 2020-07-16 20:52
Same setup as JognGeorgiadis.  Same problem...

functions: Cannot set property config of #<Object> which has only a getter
⚠  Your function was killed because it raised an unhandled error.

Played around with different versions of various dependencies to no resolve.

**Comment by aeusse** [comment] 2020-07-16 22:13
Maybe this is helpful to somebody: My linux was using "/usr/local/lib/node_modules/firebase-tools/lib/bin/firebase.js" anytime I typed "firebase" in the console, so it was using the 7.12.0 version of the package. I changed the symbolic link, and now I'm sure that I'm using the 8.6.0 version.

```
user@machine: which firebase
/usr/local/bin/firebase
user@machine: cd /usr/local/bin
user@machine: sudo rm firebase
user@machine: sudo ln -s /usr/lib/node_modules/firebase-tools/lib/bin/firebase.js firebase
user@machine: firebase --version
8.6.0
```

The word _local_ is the key

**Comment by harvey56** [comment] 2020-07-18 12:29
A global install will install firebase-tools in '/usr/local/lib/node_modules'. However, the issue that  highlighted by OP points to a different path : '/usr/lib/node_modules/firebase-tools/'.
At the first path I had the latest version of firebase-tools 8.6.0, but version 7.0.2 at the second path.

A firebase -V returned 7.0.2

Here is a relevant comment  from a discussion here : https://stackoverflow.com/q/5926672/7461599

`installing without -g option will install a module to you working directory e.g. if you make a directory say ~/Desktop/tmp then cd ~/Desktop/tmp then do npm install appium then do ls you will see node_modules     package-lock.json because you have installed a node module appium to your working directory... super confusing because -g should essentially be the default but is not.`

What did it for me was to `npm uninstall firebase-tools`, then making sure I had the latest version installed with `-g`. Now a `firebase -V` points to the right path with the up-to-date version, and firebase emulator runs smoothly.

**Comment by D-Pagey** [comment] 2020-07-24 22:12
In case it helps, I had conflict between my global npm `firebase-tools@7.0.0` and my global yarn `firebase-tools@8.6.0`. Deleting my global npm version fixed my issue of returning `7.0.0` from `firebase -V`

**Comment by bijaykanshinew** [comment] 2020-07-25 14:43
i was getting above error due to different node version used in during 
1. project initiallization (firebase init) => node version => v8.x.x
2. project running (firebase emulators:start) => node version => v12.x.x

I solved the issue by making same node version

**Comment by Tomi-star** [comment] 2020-10-18 10:29
> Maybe this is helpful to somebody: My linux was using "/usr/local/lib/node_modules/firebase-tools/lib/bin/firebase.js" anytime I typed "firebase" in the console, so it was using the 7.12.0 version of the package. I changed the symbolic link, and now I'm sure that I'm using the 8.6.0 version.
> 
> ```
> user@machine: which firebase
> /usr/local/bin/firebase
> user@machine: cd /usr/local/bin
> user@machine: sudo rm firebase
> user@machine: sudo ln -s /usr/lib/node_modules/firebase-tools/lib/bin/firebase.js firebase
> user@machine: firebase --version
> 8.6.0
> ```
> 
> The word _local_ is the key

How do I undo sudo rm firebase

**Comment by aeusse** [comment] 2020-10-25 19:49
> > Maybe this is helpful to somebody: My linux was using "/usr/local/lib/node_modules/firebase-tools/lib/bin/firebase.js" anytime I typed "firebase" in the console, so it was using the 7.12.0 version of the package. I changed the symbolic link, and now I'm sure that I'm using the 8.6.0 version.
> > ```
> > user@machine: which firebase
> > /usr/local/bin/firebase
> > user@machine: cd /usr/local/bin
> > user@machine: sudo rm firebase
> > user@machine: sudo ln -s /usr/lib/node_modules/firebase-tools/lib/bin/firebase.js firebase
> > user@machine: firebase --version
> > 8.6.0
> > ```
> > 
> > 
> > The word _local_ is the key
> 
> How do I undo sudo rm firebase

You can't (easily). I would try to find a similar binary and place in the same path
