### ISSUE TITLE
Firestore Emulator Requests asking to update when Im using firebase-tools@latest

### ISSUE THREAD

**Issue by Raff-project10x** [firebase/firebase-tools#5058] opened 2022-10-03 19:15 UTC
### [REQUIRED] Environment info

**firebase-tools:** Firebase CLI Version: 11.13.0

**Platform:** Ubuntu 22.04

### [REQUIRED] Test case

use Firebase CLI Version 11.13.0 to start the emulator UI for a javascript application with emulators started.

### [REQUIRED] Steps to reproduce

Once the emulator is running, make some firestore requests in app.

### [REQUIRED] Expected behavior

I expect to see the list of requests being made to the Firestore Emulator.

### [REQUIRED] Actual behavior

I only see a message that asks me to update to the latest firestore tools.

![image](https://user-images.githubusercontent.com/91624514/193659745-667692e3-faf7-45a2-a5fa-7a5d3dc46ab9.png)

**Comment by bkendall** [comment] 2022-10-03 20:07
Duplicate of #5051

**Closed** 2022-10-03 20:07 UTC
Labels: bug
