### ISSUE TITLE
firebase serve --only functions gives different path structure to express()

### ISSUE THREAD

**Issue by rielzzapps** [firebase/firebase-tools#1302] opened 2019-05-16 08:30 UTC
### [REQUIRED] Version info

**firebase-tools:**
6.9.2

**firebase-admin:**

### [REQUIRED] Test case

```
const express = require('express');
const cors = require("cors")

const app = express();
app.use(cors({ origin: true }));
app.post("/:method/:action/:subaction", (req, res) => {
 return res.send(req.params)
})

```
when using
firebase serve --only functions --host 0.0.0.0 --port 8080

we call 
`hostname:8080/my-project/us-central1/my-method`

firebase will serve the function great, but the response will be:

```
{
"method": "my-project",
"action": "us-central1",
"subaction": "my-method"
}
```

But, when deployed as a function:

we call 
`functionurl/my-project/us-central1/method`

```
{
"method": "method",
}
```

Which is correct

Firebase serve forces the my-project/us-central/ path in the URL, making local serving and testing quite hard.

**Comment by samtstern** [comment] 2019-05-16 14:58
This is a duplicate of #1279 and a fix has been merged. It will be included in the next release. Thanks for reporting!

**Closed by samtstern** 2019-05-16 14:58 UTC
