### ISSUE TITLE
Storage emulator: unknown error with resumable uploads

### ISSUE THREAD

**Issue by valeriangalliat** [firebase/firebase-tools#4959] opened 2022-09-08 13:12 UTC
### [REQUIRED] Environment info

**firebase-tools:** 11.8.0
**firebase:** 9.9.4
**Platform:** macOS

### [REQUIRED] Test case

```js
// test.mjs
import {
  connectStorageEmulator,
  uploadBytesResumable,
  getStorage,
  ref,
} from 'firebase/storage'
import { initializeApp } from 'firebase/app'
import fs from 'node:fs/promises'

initializeApp({
  storageBucket: 'foo',
})

const storage = getStorage()
connectStorageEmulator(storage, '127.0.0.1', 9199)

const uploadRef = ref(storage, 'foo.txt')
const blob = Buffer.from('A'.repeat(1024 * 256 + 1)) // See #4958 for why
const uploadTask = uploadBytesResumable(uploadRef, blob)

uploadTask.on(
  'state_changed',
  snapshot => {
    console.log(snapshot)
  },
  error => {
    console.log(error.stack)
  },
  () => {
    console.log('done')
  }
)
```

### [REQUIRED] Steps to reproduce

```sh
firebase emulators:start --only storage
node test.mjs
```

### [REQUIRED] Expected behavior

Uploads successfully completes.

### [REQUIRED] Actual behavior

```
FirebaseError: Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown)
```

`error.serverResponse` is `null` in that case.

I tracked it down to [this check in Firebase storage client](https://github.com/firebase/firebase-js-sdk/blob/e34e98e73a72f77ee87d9005d6728402129deda9/packages/storage/src/implementation/requests.ts#L410), where  `x-goog-upload-status` is not set on the HTTP response from the resumable upload from the emulator.

**Side note: I think it would be useful to throw a more meaningful error here (e.g. missing `x-goog-upload-status`) instead of "an unknown error has occurred". The Firebase storage SDK throws "unknown errors" in many places where there's actually more information on what's wrong and it would greatly help debugging if more meaningful errors were thrown there... would it make sense to report that on the firebase-js-sdk repo?**

From there my guess is that the emulator should be sending `x-goog-upload-status: final` around [here](https://github.com/valeriangalliat/firebase-tools/blob/73e5fa03988fe67a8c5c5cad93d5a19778246a39/src/emulator/storage/apis/firebase.ts#L237). I'll make a PR for that.

**Comment by jquesada2016** [comment] 2022-09-08 20:13
I'm having the same issue.

**Comment by kuechlerm** [comment] 2022-09-09 09:19
I don't want to sound snarky, but I would like to point out, that the file upload functionality in the storage emulator was broken (by updates) a couple of times in the last months. My workflow heavily relies on the emulators, so this throws me off track quite a lot. I hope that there is some way to secure future updates. 
Thank you!

**Comment by Aymericr** [comment] 2022-09-09 14:49
I am having the same issue: the upload stops and throws an error after the first chunk is processed (always blocks at **262.14 kB** or `bytesTransferred:262144`)

Platform: macOS
firebase-tools: `11.8.0`
firebase: `8.2.9`

`console.log(error)` spits out:
```
FirebaseError: Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown)
```

**Comment by level18** [comment] 2022-09-10 07:54
Having the same issue as well.

**Comment by coreystanford** [comment] 2022-09-15 14:24
This is blocking my team right now, too.

**Comment by kensei18** [comment] 2022-09-25 02:00
I'm having the same issue, I hope #4960 will be merged soon.

**Comment by juane1000** [comment] 2022-09-26 17:21
Same/similar issue. When uploading multiple images simultaneously this occurs. Or on single image image upload that perhaps exceeds a certain file size. The image upload does create the entry in the storage emulator UI but when I open it the file is corrupted.

**Comment by alexstanbury** [comment] 2022-09-27 10:38
Same problems with large file uploads, I have had to rollback to 11.7.0 to get it to work as expected.

**Comment by Yuangwang** [comment] 2022-09-27 14:50
Thanks for your patience everyone, I think this issue is a duplicate of this one https://github.com/firebase/firebase-tools/issues/4927 and I merged a fix for that one https://github.com/firebase/firebase-tools/pull/5018 so that should fix the issue here too!

I'm closing this for now but please be sure to try it out once the new release is out and report back if there are any issues, we can reopen and take another look if needed then.

**Closed by Yuangwang** 2022-09-27 14:50 UTC
Labels: emulators: storage, bug
