### ISSUE TITLE
Unable to deploy firebase schedule functions

### ISSUE THREAD

**Issue by prgwar** [firebase/firebase-tools#1507] opened 2019-07-15 22:06 UTC
### [REQUIRED] Environment info

**firebase-tools:** 7.1.0

**Platform:** macOS

### [REQUIRED] Test case

Create a Project with asia-south1 as a region and try to deploy a schedule function with asia-northeast1 as the function region. 

### [REQUIRED] Steps to reproduce

firebase deploy --only functions:functionName

### [REQUIRED] Expected behavior

Cli should create the pubsub target and cloud scheduler and deploy the function.

### [REQUIRED] Actual behavior

 location must equal asia-south1 because the App Engine app that is associated with this project is located in asia-south1

But the cloud functions are not available with asia-south1 region all the project functions are deployed in asia-northeast1

Before firebase cli version, I was able to create cloud scheduler functions.

**Comment by thechenky** [comment] 2019-07-15 22:50
Hi @prgwar sorry to see you're having this issue. I'm a bit confused as to what you're trying to do - the cloud functions region that you set will be where the cloud function will be deployed, regardless of the app engine location. Also, what error are you seeing from the CLI? Can you paste the output of `firebase deploy --only functions:functionName --debug`?

**Comment by merlinnot** [comment] 2019-07-16 12:28
This is most likely a duplicate of https://github.com/firebase/firebase-tools/issues/1500

**Comment by mbleigh** [comment] 2019-07-16 16:00
This should be fixed in #1511

**Closed** 2019-07-16 16:14 UTC
Labels: Needs: Author Feedback, api: functions
