### ISSUE TITLE
Firebase Login Error

### ISSUE THREAD

**Issue by Africanus12** [firebase/firebase-tools#7412] opened 2024-07-04 15:52 UTC
When attempting to log in using `firebase login`, the process fails with the message "An unexpected error has occurred."

1. Run `firebase login` in the command prompt
2. Attempt to authenticate through the provided URL
3. Error occurs while waiting for authentication

Successful login to Firebase

 - OS: Windows [10]
 - Firebase CLI Version: [13.13]

I've already tried:
- Updating Firebase CLI
- Running as administrator
- Clearing Firebase cached credentials

**Comment by Africanus12** [comment] 2024-07-04 16:23
![Capture](https://github.com/firebase/firebase-tools/assets/129630711/1289f7c8-178f-4d7c-95ad-71ab4dc4aaaa)

**Comment by Africanus12** [comment] 2024-07-04 16:23
![Capture](https://github.com/firebase/firebase-tools/assets/129630711/50d2e772-5226-4051-b4f0-72cda9a5192c)

**Comment by aalej** [comment] 2024-07-04 18:52
Hey @Africanus12, thanks for reaching out. Could you try connecting to a different network or temporarily disabling VPN, Firewall, and proxy if you have any? From what we’ve seen before, this is usually caused by a Firewall blocking node from making requests, or a proxy misconfiguration.

If the issue still persists, could you try running `firebase login --debug` and share the output with us? Passing the `--debug` flag provides a more detailed log that we can use to check what caused the error. Please remove any PII (personal identifiable information) before sharing the contents.

**Comment by Africanus12** [comment] 2024-07-05 08:15
Hi @aalej thanks a lot, I have been able to fix the issue by using firebase login --no-localhost. I was able to solve the authentication problem. Seems the problem was from my local machine setup.

**Comment by aalej** [comment] 2024-07-05 13:22
Thanks for the update, it’s good to hear you found a solution to the issue. Since it looks like the cause of the issue is not firebase-tools, I’m going to go ahead and close this for now.  Feel free to file a new report if you encounter any issues moving forward.

**Closed by aalej** 2024-07-05 13:22 UTC
Labels: type: bug, Needs: Author Feedback, api: core
