### ISSUE TITLE
Outdated allowed SSR region

### ISSUE THREAD

**Issue by eXodes** [firebase/firebase-tools#6223] opened 2023-08-05 08:41 UTC
### [REQUIRED] Environment info

**firebase-tools:** v12.4.7

**Platform:** macOS

### [REQUIRED] Test case

`firebase.json`
```json
{
  // ...
  "hosting": {
      "source": ".",
      "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
      "frameworksBackend": {
          "region": "asia-southeast1",
          "maxInstances": 1
      }
  },
  // ...
}
```

### [REQUIRED] Steps to reproduce

1. Set firebase hosting config as above.

2. Deploy firebase hosting with experiments env
  ```bash
  FIREBASE_CLI_EXPERIMENTS="webframeworks,pintags" firebase deploy --only hosting
  ```

### [REQUIRED] Expected behavior

Functions to be deployed successfully since `asia-southeast1` supports 2nd gen functions.

### [REQUIRED] Actual behavior

Error during deployment due to unsupported allowed SSR region. 

```log
  Error: Hosting config for site web-app places server-side content in region asia-southeast1 which is not known. Valid regions are us-central1, us-west1, us-east1, europe-west1, and asia-east1
```

---

The initial motive of this implementation is stated on this PR [#5504](https://github.com/firebase/firebase-tools/pull/5504/files#r1117999662). The constant has been refactored into [frameworks/constants.ts](https://github.com/firebase/firebase-tools/blob/master/src/frameworks/constants.ts). However, currently there are more regions that supports 2nd gen functions. 

Reference: [Cloud Functions supported regions](https://firebase.google.com/docs/functions/locations#supported_regions)

**Comment by eXodes** [comment] 2023-08-09 03:31
There is a PR created to solve this issue at #6086.

**Comment by aalej** [comment] 2023-08-11 14:55
Hi @eXodes, thanks for reporting this issue and providing details about your observations. I was able to reproduce the error you mentioned. Let me inform our team about this so that they can look into the existing PR and try to bring someone here who can provide more context about this.

**Comment by al4nnw** [comment] 2023-09-18 02:02
@aalej, any updates on this matter? The region distance is causing load time issues for of our users. It's very important to address this, especially since V2 functions are already compatible with other regions.

**Comment by mfellner** [comment] 2023-10-27 09:15
Meanwhile you can use [patch-package](https://github.com/ds300/patch-package) with a diff like this (worked for me):

```diff
diff --git a/node_modules/firebase-tools/lib/frameworks/constants.js b/node_modules/firebase-tools/lib/frameworks/constants.js
index a05d65c..30f6600 100644
--- a/node_modules/firebase-tools/lib/frameworks/constants.js
+++ b/node_modules/firebase-tools/lib/frameworks/constants.js
@@ -28,6 +28,7 @@ exports.ALLOWED_SSR_REGIONS = [
     { name: "us-east1 (South Carolina)", value: "us-east1" },
     { name: "europe-west1 (Belgium)", value: "europe-west1" },
     { name: "asia-east1 (Taiwan)", value: "asia-east1" },
+    { name: "europe-west3 (Frankfurt)", value: "europe-west3" },
 ];
 exports.I18N_ROOT = "/";
 function GET_DEFAULT_BUILD_TARGETS() {
```

**Comment by mfellner** [comment] 2024-01-19 13:27
https://github.com/firebase/firebase-tools/pull/6086 was merged, can this issue be closed?

**Comment by aalej** [comment] 2024-01-19 16:34
Thanks @mfellner, seems like this issue should be fixed in [v.13.0.1](https://github.com/firebase/firebase-tools/releases/tag/v13.0.1). I'm going to go ahead and close this.

**Closed by aalej** 2024-01-19 16:34 UTC
Labels: type: bug, integration: web frameworks
