### ISSUE TITLE
JSON Post requests in functions limited to 102400 bytes

### ISSUE THREAD

**Issue by mwawrusch** [firebase/firebase-tools#671] opened 2018-02-17 04:14 UTC
### Version info

3.17.4

### Platform Information

OS X

### Steps to reproduce

Create a simple web server that accepts a post request and send a post with more than 102400 bytes of JSON data...

### Expected behavior

Accept the POST data.

### Actual behavior

{ Error
    at readStream (/Users/mwawrusch/.nvm/versions/node/v8.2.1/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:196:17)
    at getRawBody (/Users/mwawrusch/.nvm/versions/node/v8.2.1/lib/node_modules/firebase-tools/node_modules/raw-body/index.js:106:12)
    at read (/Users/mwawrusch/.nvm/versions/node/v8.2.1/lib/node_modules/firebase-tools/node_modules/body-parser/lib/read.js:76:3)
    at jsonParser (/Users/mwawrusch/.nvm/versions/node/v8.2.1/lib/node_modules/firebase-tools/node_modules/body-parser/lib/types/json.js:127:5)
    at Layer.handle [as handle_request] (/Users/mwawrusch/.nvm/versions/node/v8.2.1/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mwawrusch/.nvm/versions/node/v8.2.1/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:317:13)
    at /Users/mwawrusch/.nvm/versions/node/v8.2.1/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/mwawrusch/.nvm/versions/node/v8.2.1/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/mwawrusch/.nvm/versions/node/v8.2.1/lib/node_modules/firebase-tools/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/mwawrusch/.nvm/versions/node/v8.2.1/lib/node_modules/firebase-tools/node_modules/express/lib/middleware/init.js:40:5)
  expected: 651775,
  length: 651775,
  limit: 102400,
  message: 'request entity too large',
  status: 413,
  statusCode: 413,
  type: 'entity.too.large' }

**Comment by ChrisTalman** [comment] 2018-02-22 16:05
I've also encountered this exception. We need two things: (1) a way to specify the size limit, and (2) a way to capture the exception and suppress it if desired. Currently, the request simply timeouts, which is not great.

**Comment by jonmcgill** [comment] 2018-03-08 20:59
I'm hitting this exception as well. Has anyone tried any hacks to get around this for the time being?

**Comment by r00tat** [comment] 2018-03-09 20:08
got the same issue! also changing bodyparser does not work for me!

**Comment by jonmcgill** [comment] 2018-03-14 17:37
If anyone comes here thinking Cloud Functions in general have a 100kb body size limit, then look here: https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/136. Cloud Functions have a 10mb limit.

The Firebase development tooling has a 100kb limit, which means your testing will bomb if you're throwing larger payloads at it. But when deployed, your functions will be fine.

This tripped me up, so maybe it will help someone else out 😄

**Comment by r00tat** [comment] 2018-03-14 18:06
@jonmcgill Do you know any workaround for that?

**Comment by jonmcgill** [comment] 2018-03-14 18:11
@r00tat Unfortunately, without jumping into the `firebase-tools` package and modifying the server scripts I don't think you can solve it for the dev environment ☹️. I've got a dev project in Firebase that's totally separate from our stage and prod projects so I'm cool just deploying my functions there and testing them out "in the wild".

**Comment by r00tat** [comment] 2018-03-14 19:14
I found the source of the issue, the standard bodyParser config in `src/supervisor/worker.js`. I'll create a Merge Request.

**Comment by r00tat** [comment] 2018-03-15 15:37
It seems like the issue is already fixed in the latest version [(google-cloud/functions-emulator 1.0.0-beta.4)](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/blob/1.0.0-beta.4/src/supervisor/worker.js#L85). 
I got it working with firebase-tools@3.17.6 and @google-cloud/functions-emulator@1.0.0-beta.4 as dev dependencies.

**Comment by thechenky** [comment] 2019-01-09 01:05
Closing out since this appears to be fixed.

**Closed by thechenky** 2019-01-09 01:05 UTC

**Comment by Coletrane** [comment] 2019-06-11 12:13
Seeing the issue again now that it looks like `firebase-tools` uses its own emulators instead of [`cloud-functions-emulator`](https://github.com/googlearchive/cloud-functions-emulator) I created the pull request above

**Comment by ElhananGitHub** [comment] 2023-04-25 01:25
Im hiving this issue now...
Im using the firebase-tools...
It was already fixed?
