### ISSUE TITLE
`firebase deploy` fails if local emulator is running

### ISSUE THREAD

**Issue by guanzo** [firebase/firebase-tools#2464] opened 2020-06-18 02:25 UTC
### [REQUIRED] Version info

**node:** v12.16.2

**firebase-functions:** ^3.6.1

**firebase-tools:** 8.4.3

**firebase-admin:** ^8.10.0

### [REQUIRED] Test case

Heres a snippet of my npm `scripts`
```json
 {
  "scripts": {
    "build": "tsc",
    "serve": "firebase functions:config:get > .runtimeconfig.json && tsc -w | firebase emulators:start --only functions",
    "deploy": "firebase use prod && firebase deploy --only functions",
  },
}
```

### [REQUIRED] Steps to reproduce

1. Open a terminal, run `npm run serve`.
2. Open another terminal run `npm run deploy`.
3. 2nd terminal outputs "Error: An unexpected error has occurred."

### [REQUIRED] Expected behavior

`firebase deploy` should work while `npm run serve` is still running

### [REQUIRED] Actual behavior

`firebase deploy` errors with no meaningful error message while npm run serve is still running

![](https://i.gyazo.com/d20913cb7abb3b653fbca04f32e99be2.png)

Also, I'm not able to open `firebase-debug.log`, i get "Access denied" even when trying to open the file in the windows cmd line, opened as Administrator.

### Were you able to successfully deploy your functions?

Yes, but only after i killed the process started by `npm run serve`

**Comment by samtstern** [comment] 2020-07-16 12:18
@guanzo sorry for the super slow response here, moving this over to `firebase-tools` since it sounds like you're having a CLI issue.

I was not able to reproduce this on my machine, deploy and emulators ran successfully together.  The fact that you are unable to access `firebase-debug.log` is a sign that you may have some file permissions issues on your machine more generally.

Are you still able to reproduce this?  If so please run `firebase deploy` with the `--debug` flag and show me the logs that are printed.

**Comment by guanzo** [comment] 2020-07-16 21:49
```sh
$ npm run deploy

> functions@ deploy C:\Users\Eric\workspace\pep\optimizers\functions
> firebase use prod && firebase deploy --debug --only functions

Now using alias prod (prod-pep)
[2020-07-16T21:49:08.730Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-07-16T21:49:08.732Z] > authorizing via signed-in user
[2020-07-16T21:49:08.732Z] [iam] checking project prod-pep for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[2020-07-16T21:49:08.746Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/prod-pep:testIamPermissions
 {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}
[2020-07-16T21:49:08.785Z] Error: EPERM: operation not permitted, stat 'C:\Users\Eric\workspace\pep\optimizers\functions\firebase-debug.log'

Error: An unexpected error has occurred.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ deploy: `firebase use prod && firebase deploy --debug --only functions`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the functions@ deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eric\AppData\Roaming\npm-cache\_logs\2020-07-16T21_49_09_074Z-debug.log
```

**Comment by samtstern** [comment] 2020-07-17 15:58
Ohhhh hm I wonder if both instances of the Firebase CLI are competing to write to the same debug log?  @mbleigh or @bkendall any thoughts on what we should do in that situation?

**Comment by samtstern** [comment] 2020-07-24 15:38
@bkendall assigning to you, what should we do if two copies of the Firebase CLI are competing over one `firebase-debug.log`?  We could do something like `firebase-debug.log (1)` or we could just drop logs on the floor.

**Comment by bkendall** [comment] 2020-07-24 15:47
I would fear that we'd start cluttering up people's repositories with logs, and our default gitignore would be insufficient. But, I think if something went wrong, I'd rather have a debug log than not.

Can we do a pattern like `firebase-debug.log.<n>` rather than having a space and parenthesis? Would that be okay?

**Comment by mbleigh** [comment] 2020-07-24 15:48
That seems fine to me, but prefer `firebase-debug.<n>.log` (preserve extension)

**Closed** 2020-07-27 18:12 UTC
Labels: Needs: Attention, api: functions
