### ISSUE TITLE
`firebase emulators:start` not working on WLS on Windows 10

### ISSUE THREAD

**Issue by FezVrasta** [firebase/firebase-tools#1458] opened 2019-07-02 12:41 UTC
### [REQUIRED] Environment info

**firebase-tools:**
7.0.2

**Platform:**
WSL on Windows 10

### [REQUIRED] Test case

An empty project with the auto-generated Cloud Functions boilerplate is enough to reproduce it.

### [REQUIRED] Steps to reproduce

Run `firebase emulators:start`

### [REQUIRED] Expected behavior

I should be able to use the local environment.

### [REQUIRED] Actual behavior

It starts the local server at port 5001, if I open it in Chrome I get a `{ "status": "alive" }` response, but after 30 seconds it shuts down by itself because of a "timeout".

```
✔  functions: Emulator started at http://localhost:5001
i  Shutting down emulators.
i  Stopping functions emulator

Error: TIMEOUT: Port 5001 was not active within 30000ms
```

The project works fine when deployed to Google Cloud. I tried to run it with `sudo` also.

If I visit the demo "hello world" endpoint I get an error saying the endpoint is not available.

I tried to run it with `--debug` but no additional information is displayed during the shutdown/timeout

**Comment by samtstern** [comment] 2019-07-02 19:49
Reading this page:
https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes

It says:
```
In initial builds of the WSL 2 preview you will need to access network applications using an IP address and not using localhost
```

Then it goes on to say:
```
In the initial builds of the WSL 2 preview, you will need to access any Linux server from Windows using the IP address of your Linux distro, and any Windows server from Linux using the IP address of your host machine. This is something that is temporary, and very high on our priority list to fix.
```

So this is something that is new in WSL2 but also going to change before WSL2 is finalized, meaning that I don't think we should do anything within `firebase-tools` to accommodate this for now.

Thanks for reporting this @FezVrasta !

**Comment by FezVrasta** [comment] 2019-07-02 20:33
I'm not using WSL 2 tho, AFAIK I'm using version 1

**Comment by samtstern** [comment] 2019-07-02 20:35
@FezVrasta oh that's interesting, thanks for sharing!  Assigning to @abeisgoat since he has a Windows setup and I don't.

**Comment by amkoehler** [comment] 2019-07-15 22:03
Hi, any update on this? Running into the same problem.

**Comment by samtstern** [comment] 2019-07-17 16:09
cc @Karasuni

**Comment by Karasuni** [comment] 2019-07-17 16:11
I'm seeing this issue on Windows 10 Build 18362 running WSL 1, not WSL 2.

**Comment by RoryDungan** [comment] 2019-07-23 01:29
I've reproduced the same issue with Win 10 1903 (build 18362.239), WSL 1, firebase-tools 7.1.0 and 7.1.1. For now downgrading to 7.0.2 is fine as a workaround.

**Comment by samtstern** [comment] 2019-07-23 02:09
I have a new theory.  In 7.1.0 we introduced a dependency on "chokidar" for
file watching which is a native module.  Native modules can cause
os-specific issues.  It's possible that is why 7.1.0+ stopped working on
WSL.

**Comment by samtstern** [comment] 2019-07-23 15:36
I was able to reproduce this bug at home on my personal machine (we don't have Windows at work) so it's definitely real!  I didn't have time to start debugging but I will try that next.

**Comment by yegorius** [comment] 2019-07-25 17:01
Just a clue.
Environment:
firebase-tools 7.1.0 or 7.2.0
Arch Linux
`> node_modules/.bin/firebase serve --only functions` terminates after timeout
`> $HOME/.npm/bin/firebase serve --only functions` doesn't terminate

So it only terminates if firebase-tools are installed locally. My `npm config get prefix` is `$HOME/.npm` so if I do `npm i -g firebase-tools` everything works ok, but it doesn't work from local `node_modules` in my project directory.

**Comment by simonesestito** [comment] 2019-09-02 09:25
Issue persists with firebase-tools 7.3.0 on WSL 1.

```
Error: TIMEOUT: Port 5000 was not active within 30000ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ prod: `firebase serve --only functions`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the functions@ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/simone/.npm/_logs/2019-09-02T09_24_45_392Z-debug.log
```

WSL version: 1
firebase --version: 7.3.0
Node.js version: 12.9.0
NPM version: 6.11.2
Windows 10 Pro 1903 build 18362.295 (Stable)

**Comment by amkoehler** [comment] 2019-10-01 15:59
Can confirm the issue persists on 7.4.0 as well.

**Comment by barnu5** [comment] 2019-10-02 03:30
Emulator is unusable on WSL due to this issue.

Doesn't work on actual Windows either! https://github.com/firebase/functions-samples/issues/572

**Closed** 2019-10-07 23:59 UTC
Labels: emulator-suite

**Comment by samtstern** [comment] 2019-10-08 16:57
Ok version `7.5.0` should work well for all you Windows Linux Subsystem users out there!

**Comment by amkoehler** [comment] 2019-10-08 18:41
Thanks Sam. Working great for me now.
