### ISSUE TITLE
Firestore emulator behaviour different from cloud using dynamic field name notation

### ISSUE THREAD

**Issue by redpandatronicsuk** [firebase/firebase-tools#4712] opened 2022-07-06 12:30 UTC
### [REQUIRED] Environment info

**firebase-tools:** 11.1.0

**Platform:** macOS

### [REQUIRED] Test case

This code:

```ts
const dynamicFieldName = 'fooz';
admin.firebase().doc('foo').set({
  [`bar.${dynamicFieldName}`]: 'baz'
});
```

### [REQUIRED] Steps to reproduce

Run the above code in the cloud and emulator and you will see different behaviour.

### [REQUIRED] Expected behavior

In the cloud the data stored at `foo`:

```js
{ bar: { fooz: 'baz' } }
```

and in the emulator:

```js
{ 'bar.fooz':  'baz' }
```

### [REQUIRED] Actual behavior

Consistent behaviour for cloud and emulator.

**Comment by yuchenshi** [comment] 2022-07-11 20:20
@redpandatronicsuk Would you mind creating a self-contained reproduction (e.g. a GitHub repository) with the full initialize code (except PII or secrets) so we can look further into this?

**Comment by redpandatronicsuk** [comment] 2022-07-12 17:28
@yuchenshi Thanks for your reply. I tried to replicate the problem in a new repo and I found out the bug is not with the emulator. I get the same behaviour running the code in the emulator and functions now. The error was introduced when changing the code from

```js
admin.firebase().doc('foo').update({
  [`bar.${dynamicFieldName}`]: 'baz'
});
```

to 

```js
admin.firebase().doc('foo').set({
  [`bar.${dynamicFieldName}`]: 'baz'
}, { merge: true });
```

With `update` it produces:

```js
{ bar: { fooz: 'baz' } }
```

with `set` and option `{ merge: true }` it produces:

```js
{ 'bar.fooz':  'baz' }
```

Is that the expected behaviour? I thought `set` with `{ merge: true }` is the same as `update`, except that it doesn't throw an error if the document doesn't exist.

**Comment by yuchenshi** [comment] 2022-07-18 20:51
Yes, that's the expected behavior. See https://stackoverflow.com/questions/70183767/firestore-does-the-dot-notation-work-with-set

I'm closing this issue for now since it is not specific to emulators. For SDK questions, we'd recommend following up on StackOverflow where you can find a lot of resources and the community can also help with questions like this.

**Closed by yuchenshi** 2022-07-18 20:51 UTC
Labels: emulators: firestore, Needs: Attention, emulator-suite, bug
