### ISSUE TITLE
debug.log error

### ISSUE THREAD

**Issue by muhammadzahir14** [firebase/firebase-tools#5381] opened 2022-12-31 07:17 UTC
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

### [REQUIRED] Actual behavior

C:\Users\User\OneDrive\Desktop\BIM30603 APLIKASI\lab-8\firebase_lab8\database-debug.log

**Comment by muhammadzahir14** [comment] 2022-12-31 07:17
help me fix the error

**Comment by aalej** [comment] 2023-01-02 10:52
Hi @muhammadzahir14, I see that you filed another issue [#5382](https://github.com/firebase/firebase-tools/issues/5382) which has your debug logs. It would be more helpful if you specify other details using the provided template in a new ticket. This way, it would be more efficient in identifying the cause of the issue. That being said, I'll be closing this for now.

**Closed by aalej** 2023-01-02 10:52 UTC
Labels: bug
