### ISSUE TITLE
How to deploy a cloud function with Node 18?

### ISSUE THREAD

**Issue by nilsreichardt** [firebase/firebase-tools#5309] opened 2022-12-07 21:05 UTC
When I try to deploy a cloud function with Node 18, I'm getting this error:

```
Error: package.json in functions directory has an engines field which is unsupported. Valid choices are: {"node": 10|12|14|16}
```

Looking into the [documentation](https://cloud.google.com/functions/docs/concepts/nodejs-runtime) of Cloud Functions, Node 18 is in preview and should be supported.

How can I fix this?

Firebase Tools: `v11.17.0`

**Comment by taeold** [comment] 2022-12-10 22:19
https://github.com/firebase/firebase-tools/pull/5319

We will ship a new release of the CLI early next week!

**Comment by taeold** [comment] 2022-12-12 21:38
Released in https://github.com/firebase/firebase-tools/releases/tag/v11.18.0!

**Comment by nilsreichardt** [comment] 2022-12-13 13:38
Cool, thanks!

**Comment by drewxs** [comment] 2023-01-06 00:59
This issue still exists, any updates?

**Comment by DibyodyutiMondal** [comment] 2023-01-19 03:53
In my case, it was essential that node_modules exist in the directory. In my case, I had to symlink my workspace-level node_modules into the function project's dist directory in order to be able to run the emulator or to deploy. 

It has got something to do with discovering the backend. Without the node modules, request for some document `__functions__.yaml` or something like that fails, and stops the entire process.

**Comment by taeold** [comment] 2023-01-31 21:25
Confirmed locally that Node.js18 should work with the latest release. If you continue to have issue deploying functions with Node.js 18 runtime, I'd appreciate if you can open a new issue. Thanks!

**Closed by taeold** 2023-01-31 21:25 UTC
Labels: type: bug, api: functions

**Comment by weilinzung** [comment] 2023-03-14 13:43
Locally development is having the same issue with node v18.15.0, but deployment seems fine.

```
  "engines": {
    "node": "18"
  },
```

```
[emulators] ⬢  functions: Failed to load function definition from source: FirebaseError: package.json in functions directory has an engines field which is unsupported. Valid choices are: {"node": 10|12|14|16}
```

**Comment by DibyodyutiMondal** [comment] 2023-03-18 03:15
Could you try the following config in `firebase.json`
```
"functions": [
    {
      // ... you other settings
      "runtime": "nodejs18",
    }
  ],
```

**Comment by ee99ee** [comment] 2023-03-20 13:08
I can also confirm this is still an issue. As reported above, deployments work fine. For me, the problem is with the functions emulator.

I added `runtime` to my `firebase.json` as suggested by @DibyodyutiMondal and the `engines` block to my `package.json` as posted by @weilinzung. Neither of these worked.

### Versions
**CLI version:** 11.24.1
**Node version:** 18.14.2

### Error
```
functions
Failed to load function definition from source: FirebaseError: package.json in functions directory has an engines field which is unsupported. Valid choices are: {"node": 10|12|14|16}

Deploys to runtimes below Node.js 10 are now disabled in the Firebase CLI. Existing Node.js 8 functions will stop executing at a future date. Update existing functions to Node.js 10 or greater as soon as possible.
```

**Comment by becauseinterwebs** [comment] 2023-03-22 21:16
I'm having the same issue trying to deploy an updated Node 18 function.  It was already deployed by another developer on the team, so we know we can deploy Node 18 functions.  However, I seem unable to do it.

- CLI Version: 11.16.1
- Node Version: 18.11.0

I have 
```
"engines": {
    "node": "18"
  }
```

in my package.json and receive the error when trying to deploy:

`Error: package.json in functions directory has an engines field which is unsupported. Valid choices are: {"node": 10|12|14|16}`

If I add "runtime": "nodejs18" to my firebase.json I get an error saying I can't deploy with that runtime.

**Comment by ee99ee** [comment] 2023-03-23 04:37
@becauseinterwebs - to be clear, you're deploying, not running the emulator -- right? what's the exact command you run?

**Comment by pkitatta** [comment] 2023-04-03 12:00
Hello, any solution for this?

**Comment by benminor** [comment] 2023-04-24 20:17
Any update here?

**Comment by adelespinasse** [comment] 2023-05-01 03:55
To run the emulator, I had to change the version in `functions/package.json` to `"engines": { "node": 16 }`. Which is strange, I thought it was working before. One thing I did change was to upgrade from Node 18.13 to 18.16; apparently 18.16 has been causing other emulator problems, so maybe that's it.

Deploying worked fine for me with `"node": 18`, it was just the emulator that I had trouble with.

Putting `"runtime": "nodejs18"` in firebase.json didn't help for me; it just gave a different error message: `Error: Cannot deploy function with runtime nodejs18`. (Yes, while I was trying to run the emulator, not when deploying. I haven't tried deploying with the "nodejs18" thing.)

**Comment by kazdhicham** [comment] 2023-09-03 06:44
I have the same problem is there any solution

**Comment by CaptainCodeman** [comment] 2023-09-11 18:40
Same here - was working, now it isn't.

**Comment by justinechang39** [comment] 2023-09-22 09:32
just fixed this when I realised we had firebase-tools installed as a `devDependency` in our project, so it didn't matter what the global version was because it would always take the version installed in the project's `node_modules` folder.

**Comment by sl0wik** [comment] 2023-11-05 00:12
The issue is likely related to outdated version of Firebase client. Upgrade resolved issue in my case.

**Comment by TheRealMikeD** [comment] 2023-11-29 21:21
Getting the same error as everyone else.
firebase-tools: 12.9.1 (same version installed both globally and locally)

Can't deploy or run in emulator with node 18.

**Comment by janedouat** [comment] 2023-12-18 10:49
We were having issues deploying our cloud functions with node 18 **with cloud build**. Deploying locally always worked for us.

We did all the fixes suggested here and we were still getting errors (with node version only specified in our package.json `Error: package.json in functions directory has an engines field which is unsupported. Valid choices are: {"node": 10|12|14|16}` and then after specifying the runtime in firebase.json `Error: Cannot deploy function with runtime nodejs18`).

Our issue was solved by updating our project's "firebase community builder" image, which the last step of our cloud build instructions was using (`name: gcr.io/$PROJECT_ID/firebase`). Our last image was built anterior to node 18. Documentation is here : [https://cloud.google.com/build/docs/deploying-builds/deploy-firebase](https://cloud.google.com/build/docs/deploying-builds/deploy-firebase).

**Comment by suresh-vinsyt** [comment] 2023-12-20 12:21
It's worked for me. just make sure your local system has 18 node version.

**Comment by AlexShavkuta** [comment] 2023-12-25 15:18
This bug still occurs to me, is there any other fixes for this?
**firebase-tools:** v.13.0.2

**Comment by jcovarrubias11** [comment] 2023-12-27 20:44
I am using NVM to manage all my node versions and so I just went through all the node versions and uninstalled global firebase-tools from them all using `npm uninstall -g firebase-tools` and then switched back to node 18 and globally installed the latest firebase-tools and it worked for me.

**Comment by sorcamarian** [comment] 2024-01-07 18:06
I had the same issue and I updated **firebase-tools** from v8-9 to 13

**Comment by jambc91** [comment] 2024-02-09 18:25
dont forget to update the cli version firebase-tools(at least 13)

**Comment by superdiazzz** [comment] 2024-03-09 15:22
still happened in firebase-tools 13.4.1, firebase-functions: 4.8.0, node v18.7.0

how to solve this issue??

**Comment by rossman-x** [comment] 2024-04-07 13:48
I solved this issue by updating firebase-tools to the latest version: `npm install -g firebase-tools@13.7.1`

**Comment by MorganTrudeau** [comment] 2024-08-08 13:25
For me I can deploy with engine 18 if my computer is on node 16, but not node 18

**Comment by Ozzie-code-alt** [comment] 2024-12-28 06:44
My Issue was that i had both firebase-tools (globally) and locally (node_modules) installed. When deploying y functions it was using the deprecated one in my node_modules soo i had to run  ` yarn remove firebase-tools ` then run `yarn install firebase-tools@@13.7.1` 

this works on node 20 engine 

PS: make sure if ur using nvm use nvm20 aswell

**Comment by HlawuMaswanganyi** [comment] 2025-03-11 09:43
> I am using NVM to manage all my node versions and so I just went through all the node versions and uninstalled the global firebase-tools from them all using `npm uninstall -g firebase-tools` and then switched back to node 18 and globally installed the latest firebase-tools and it worked for me.

Had to do a similar thing, although I did not uninstall first, I just npm install firebase-tools@lates and it worked
