### ISSUE TITLE
ERROR Cloud Runtime Config is currently experiencing issues. Recaptcha blocking firebase function deploys

### ISSUE THREAD

**Issue by mlahp7** [firebase/firebase-tools#8047] opened 2024-12-09 18:57 UTC
### [REQUIRED] Environment info

**firebase-tools:**
13.26.0

**Platform:**
macOS
### [REQUIRED] Test case

After deploying a few cloud functions successfully, I am getting the error:
Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed

With the debug flag, it looks like recaptcha is failing:
![image](https://github.com/user-attachments/assets/2d127cb3-4f85-4465-9e17-3f376c791119)
### [REQUIRED] Steps to reproduce
- Deploy a cloud function 3-4 times, include debug flag 
- After a few deploys, notice that it fails almost instantly. 
- See debug log dump html referring to Captcha 
- Switch to a VPN or mobile hotspot on another network, and it works temporarily until being flagged for captcha again

### [REQUIRED] Expected behavior

It should allow us to deploy as much as we want
### [REQUIRED] Actual behavior
It fails to deploy

**Comment by shevvydj** [comment] 2024-12-09 19:29
i get the same issue

**Comment by aalej** [comment] 2024-12-09 19:48
Hey @mlahp7, thanks for reporting this. At the moment, I can't reproduce the error. I tried deploying functions but no errors are being raised. I'll check with our engineering team. Although, since this seems to be a backend issue, it might be worth reaching out to our [Firebase Support team](https://firebase.google.com/support/troubleshooter/contact).

For those encountering the error, could you please share your `firebase-debug.log`? Please remove any PII before sharing the contents. Also, what do you see if you access "https://runtimeconfig.googleapis.com/v1beta1/projects/<PROJECT_ID>/configs"?

**Comment by mlahp7** [comment] 2024-12-09 19:51
> Hey @mlahp7, thanks for reporting this. At the moment, I can't reproduce the error. I tried deploying functions but no errors are being raised. I'll check with our engineering team. Although, since this seems to be a backend issue, it might be worth reaching out to our [Firebase Support team](https://firebase.google.com/support/troubleshooter/contact).
> 
> For those encountering the error, could you please share your `firebase-debug.log`? Please remove any PII before sharing the contents. Also, what do you see if you access "https://runtimeconfig.googleapis.com/v1beta1/projects/<PROJECT_ID>/configs"?

Thanks for the speedy response. The link above triggers the captcha for me
![image](https://github.com/user-attachments/assets/9dbf5088-6263-4494-ad03-fd0b41ffbbdf)

**Comment by brendanowens** [comment] 2024-12-09 19:54
I am seeing the same issue.

**Comment by andrewtoups** [comment] 2024-12-09 19:59
This is also happening for me. Running an older version (12.9.1), but this has worked consistently before. Using a VPN worked around this for me, too.

Here's my `> firebase --debug functions:config:get` output. You can see the recaptcha page HTML response (instead of the usual json) in the last log message.

```
[2024-12-09T19:47:11.135Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2024-12-09T19:47:11.136Z] > authorizing via signed-in user ([redacted])
[2024-12-09T19:47:11.136Z] [iam] checking project [redacted] for permissions ["firebase.projects.get","runtimeconfig.configs.get","runtimeconfig.configs.list","runtimeconfig.variables.get","runtimeconfig.variables.list"]
[2024-12-09T19:47:11.138Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/[redacted]:testIamPermissions [none]
[2024-12-09T19:47:11.138Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/[redacted]:testIamPermissions x-goog-quota-user=projects/[redacted]
[2024-12-09T19:47:11.138Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/[redacted]:testIamPermissions {"permissions":["firebase.projects.get","runtimeconfig.configs.get","runtimeconfig.configs.list","runtimeconfig.variables.get","runtimeconfig.variables.list"]}
[2024-12-09T19:47:11.288Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/[redacted]:testIamPermissions 200
[2024-12-09T19:47:11.288Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/[redacted]:testIamPermissions {"permissions":["firebase.projects.get","runtimeconfig.configs.get","runtimeconfig.configs.list","runtimeconfig.variables.get","runtimeconfig.variables.list"]}
[2024-12-09T19:47:11.289Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/[redacted]/services/runtimeconfig.googleapis.com [none]
[2024-12-09T19:47:11.289Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/[redacted]/services/runtimeconfig.googleapis.com x-goog-quota-user=projects/[redacted]
[2024-12-09T19:47:11.680Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/[redacted]/services/runtimeconfig.googleapis.com 200
[2024-12-09T19:47:11.680Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/[redacted]/services/runtimeconfig.googleapis.com [omitted]
[2024-12-09T19:47:11.680Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/[redacted]/configs [none]
[2024-12-09T19:47:12.289Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/[redacted]/configs 429
[2024-12-09T19:47:12.289Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/[redacted]/configs "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n<html>\n<head><meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"><meta name=\"viewport\" content=\"initial-scale=1\"><title>https://runtimeconfig.googleapis.com/v1beta1/projects/[redacted]/configs</title></head>\n<body style=\"font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px; overscroll-behavior:contain;\" onload=\"e=document.getElementById('captcha');if(e){e.focus();} if(solveSimpleChallenge) {solveSimpleChallenge(,);}\">\n<div style=\"max-width:400px;\">\n<hr noshade size=\"1\" style=\"color:#ccc; background-color:#ccc;\"><br>\n<form id=\"captcha-form\" action=\"index\" method=\"post\">\nTo continue, please type the characters below:<br><br>\n<img src=\"/sorry/image?id=1624311564462380319&amp;q=EgRMSBkeGL-S3boGIjDzr13T2-IMy8fSQDjbfjms0D0JxZW1vj5ERqknAfkpQd7FbqJtkacGmuM-SSYCigQyAmNyWgFD&amp;hl=en&amp;continue=https://runtimeconfig.googleapis.com/v1beta1/projects/[redacted]/configs\" border=\"1\" alt=\"Please enable images\"><br><br>\n<input type=\"text\" name=\"captcha\" value=\"\" id=\"captcha\" size=\"12\" style=\"font-size:16px; padding:3px 0 3px 5px; margin-left:0px;\"><br><br><br>\n<input type=\"submit\" name=\"btn-submit\" value=\"Submit\" style=\"font-size:18px; padding:4px 0;\">\n\n<input type='hidden' name='q' value='EgRMSBkeGL-S3boGIjDzr13T2-IMy8fSQDjbfjms0D0JxZW1vj5ERqknAfkpQd7FbqJtkacGmuM-SSYCigQyAmNyWgFD'><input type=\"hidden\" name=\"continue\" value=\"https://runtimeconfig.googleapis.com/v1beta1/projects/[redacted]/configs\">\n</form>\n<hr noshade size=\"1\" style=\"color:#ccc; background-color:#ccc;\">\n\n<div style=\"font-size:13px; line-break: anywhere;\">\n<b>About this page</b><br><br>\n\nOur systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href=\"#\" onclick=\"document.getElementById('infoDiv').style.display='block';\">Why did this happen?</a><br><br>\n\n<div id=\"infoDiv\" style=\"display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;\">\nThis page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href=\"//www.google.com/policies/terms/\">Terms of Service</a>. The block will expire shortly after those requests stop.  In the meantime, solving the above CAPTCHA will let you continue to use our services.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href=\"//support.google.com/websearch/answer/86640\">Learn more</a><br><br>Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly.\n</div>\n\nIP address: 76.72.25.30<br>Time: 2024-12-09T19:47:12Z<br>URL: https://runtimeconfig.googleapis.com/v1beta1/projects/[redacted]/configs<br>\n</div>\n</div>\n</body>\n</html>\n"

Error: Unable to parse JSON: SyntaxError: Unexpected token < in JSON at position 0
```

**Comment by andrewtoups** [comment] 2024-12-09 20:04
I'm not deploying anything. That output is simply from running `firebase:config:get`

**Comment by andrewtoups** [comment] 2024-12-09 20:07
Worth noting that for me I think this started after attempting to do the above operation with a service account. After resolving this by switching to a VPN, I just attempted the same (by running `firebase logout` and then running the command from a script) and it's giving me the recaptcha page again, even if I log back in. Not sure if that's relevant to other people experiencing it but it seems like the service account triggered a false positive and permanently flagged my IP or something?

**Comment by Wackymax** [comment] 2024-12-09 21:06
Also started running into this problem today

**Comment by orbachar** [comment] 2024-12-09 21:12
same here, started getting this error few hours ago

**Comment by ivoneug** [comment] 2024-12-09 21:43
Also experiencing this issue for a few hours today. Firebase configs endpoint responds with 429 error returning captcha web page.

**Comment by SeeringPhil** [comment] 2024-12-09 21:49
Have also been experiencing this today. 

It's happening locally when trying to use the CLI and has also been happening in CD for a few hours.

**Comment by ArthurPHelios** [comment] 2024-12-09 22:08
I have been deploying constantly today without a single issue. Since 2h, I got ERROR on all firebase cli actions:
- firebase functions:config:get
Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.

- firebase deploy --only functions
Error: Unable to parse JSON: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by aalej** [comment] 2024-12-10 00:03
Apologies for any inconvenience this may have caused. Just a quick update here, our engineering team is actively investigating this issue and we're working to get this resolved. If you're encountering this error, please leave a thumbs up on the original post to help us track the impact of the issue.

**Comment by patrick-pc** [comment] 2024-12-10 05:20
same issue

**Comment by joehan** [comment] 2024-12-10 16:59
Hey all, the upstream issue that caused this should now be resolved, so I'm going to close this. If you still are experiencing this issue, please let us know ASAP.

**Closed by joehan** 2024-12-10 16:59 UTC
Labels: type: bug, api: functions, reproducible

**Comment by mortencallesen** [comment] 2025-01-17 09:32
I solved this issue by going to IAM - and assigning OWNER role to my xx-compute@developer.gserviceaccount.com.

Then i did a new deploy which ran without any errors.

Removed the OWNER Role again, and now deploys work as exprected again

**Comment by wooliet** [comment] 2025-08-01 20:56
Happening all day for me. I've only been able to deploy successfully a few times.

Both cloud function deploy and the `functions:config:get` show 503 errors throughout the process.

This is from a single gen2 cloud function deploy. Some of the API calls return 200, some 503. 

```
[2025-08-01T20:44:48.535Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/{project}/configs/waypoints/variables/key 503
[2025-08-01T20:44:48.536Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/{project}/configs/waypoints/variables/key {"error":{"code":503,"message":"The service is currently unavailable.","status":"UNAVAILABLE"}}
```
