### ISSUE TITLE
Private NPM Module as a Git Submodule Fails to Deploy Firebase Functions

### ISSUE THREAD

**Issue by crossan007** [firebase/firebase-tools#3270] opened 2021-04-09 15:52 UTC
I have a workable solution for this issue in my environment, so I'm mostly opening this ticket to save others the trouble that I went through.

### Environment info

**firebase-tools: 9.8.0**

**Platform: macOS**

### Test case

Given: 
*  A Firebase project (`./firebase.json` and `./package.json`, `./src` and `./functions/package.json`) in the root of the repository
*  A Git Submodule at `./packages/my-inhouse-package` where the mounted submodule is a valid, in-house NPM module which we don't want to publish to npmjs.org
* A local NPM package, included according to the official documentation (https://firebase.google.com/docs/functions/handle-dependencies)

Variations on package paths:
#### Scenario 1
An entry in the `./functions/package.json`'s `dependencies` node: `"my-inhouse-package":"file:./packages/my-inhouse-package`

#### Scenario 2
An entry in the `./functions/package.json`'s `dependencies` node: `"my-inhouse-package":"file:../packages/my-inhouse-package`

### Steps to reproduce

Run`firebase deploy --only functions` from the repository's root directory.

### Expected behavior

Firebase should detect that `./functions/package.json` references a NPM package "up a level" and upload the necesary files.

#### Scenario 1
If the `file:` reference item in `./functions/package.json` _does not include_ a parent-directory-path (`../`) but rather points to `"my-inhouse-package":"file:./packages/my-inhouse-package`, then the deployment fails, seemingly because NPM attempts to create a symlink to a folder within `node_modules` for the custom package but that path already exists:

```
[2021-04-09T14:30:37.977Z] <<< [apiv2][body] GET https://cloudfunctions.googleapis.com/v1/operations/<REDACTED>{"name":"operations/<REDACTED>","metadata":{"@type":"type.googleapis.com/google.cloud.functions.v1.OperationMetadataV1","target":"projects/<REDACTED>/locations/us-central1/functions/<REDACTED>","type":"UPDATE_FUNCTION","request":{"@type":"type.googleapis.com/google.cloud.functions.v1.CloudFunction","name":"projects/<REDACTED>/locations/us-central1/functions/<REDACTED>","httpsTrigger":{},"status":"ACTIVE","entryPoint":"<REDACTED>","timeout":"60s","availableMemoryMb":256,"serviceAccountEmail":"<REDACTED>@appspot.gserviceaccount.com","updateTime":"2021-04-08T19:29:26.845Z","versionId":"31","labels":{"deployment-tool":"cli-firebase"},"sourceUploadUrl":"https://storage.googleapis.com/gcf-upload-us-central1-<REDACTED>/<REDACTED>.zip?GoogleAccessId=service-<REDACTED>@gcf-admin-robot.iam.gserviceaccount.com&Expires=<REDACTED>&Signature=<REDACTED>","environmentVariables":{"FIREBASE_CONFIG":"{\"projectId\":\"<REDACTED>\",\"databaseURL\":\"<REDACTED>\",\"storageBucket\":\"<REDACTED>\",\"locationId\":\"us-central\"}"},"runtime":"nodejs12","ingressSettings":"ALLOW_ALL","buildId":"<REDACTED>"},"versionId":"33","updateTime":"2021-04-09T14:30:23Z","buildId":"<REDACTED>"},"done":true,"error":{"code":3,"message":"Build failed: npm ERR! code EEXIST\nnpm ERR! syscall mkdir\nnpm ERR! path /workspace/node_modules/<REDACTED>\nnpm ERR! errno -17\nnpm ERR! EEXIST: file already exists, mkdir '/workspace/node_modules/<REDACTED>'\nnpm ERR! File exists: /workspace/node_modules/<REDACTED>\nnpm ERR! Remove the existing file and try again, or run npm\nnpm ERR! with --force to overwrite files recklessly.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2021-04-09T14_30_00_295Z-debug.log; Error ID: beaf8772"}}
```

#### Scenario 2 
If the `file:` reference item in `./functions/package.json` _does include_ a parent-directory-path (`../`), then the deployment fails, seemingly because the referenced package cannot be found.

It is not obvious how NPM is being triggered in the build environment, but it seems to be running `npm` in the root of the project, with the `--prefix` option (i.e. `npm --prefix=./functions run build`)

Since it appears the working directory for the `npm` command here _is the root of the repository_, then we expect the directive to search the parent folder for the custom module to fail in this manner.

### WORKAROUND / SOLUTION:
After a few iterations on this config, we were able to get the custom NPM module to work via the `file:` reference _by setting the Git submodule inside the functions folder_;
`.gitmodules` contains this:
```
[submodule "packages/my-inhouse-package"]
	path = functions/packages/my-inhouse-package
	url = git@my-git-host.com:my-company/my-inhouse-package.git

```

**Comment by crossan007** [comment] 2021-04-09 16:08
Related issues:
#2547  - This issue attempts to solve the same problem by using a private npmjs package
https://github.com/firebase/firebase-tools/issues/968#issuecomment-434763319 - Using private `file:` modules with Functions

**Comment by joehan** [comment] 2021-06-23 17:22
Hey @crossan007, thanks for reporting this and finding those related issues. Unfortunately, the errors here are happening in the Cloud Build that runs during function deployment, and the maintainers of this repo aren't able to change that. We're looking at options to improve this experience going forward, but for now, the various workarounds the community has found are your best option.

#968 contains a number of reasonable solutions to this problem, and you can also refactor to use a private module.

Docs for Using Private Modules:
https://cloud.google.com/functions/docs/writing/specifying-dependencies-nodejs#using_private_modules, keeping in mind that it must be registry.npmjs.org, not any npm registry.
https://cloud.google.com/functions/docs/writing/specifying-dependencies-nodejs#including_local_nodejs_modules_as_part_of_your_deployment_package

In the interest of keeping discussion to one thread, I'm gonna close this as a duplicate of #968

**Closed by joehan** 2021-06-23 17:22 UTC
Labels: api: functions

**Comment by thomashagstrom** [comment] 2022-03-10 09:14
For anyone else finding this old issue: avoid using yarn.lock and use old slow NPM with package-lock.json instead. 
That resolved the issues for us
