### ISSUE TITLE
multipart/form-data upload emulator error Unexpected number in JSON at position 1

### ISSUE THREAD

**Issue by coffeemilkcrazy** [firebase/firebase-tools#1300] opened 2019-05-16 05:47 UTC
### [REQUIRED] Environment info

firebase -V
6.9.2

macOS

### [REQUIRED] Test case

Create cloud function as https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/http/index.js

exports.uploadFile = (req, res) => {
 please see in the example link above
};

run firebase serve

### [REQUIRED] Steps to reproduce

Create cloud function as https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/http/index.js

exports.uploadFile = (req, res) => {
 please see in the example link above
};

run firebase serve

Call the function via HTTP with multipart/form-data

### [REQUIRED] Expected behavior

Run cloud function and response

### [REQUIRED] Actual behavior

Not response and error in the emulator terminal in the log below

But run on the Google cloud (firebase deploy). It works.

(node:69079) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at FunctionsEmulator.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:80:46)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:3:12)
    at handler (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulator.js:75:43)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:112:3)
(node:69079) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:69079) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by samtstern** [comment] 2019-05-16 14:59
I believe this is a duplicate of #1277, which has a fix merged that will be included in the next release.  Thanks for reporting!

**Closed by samtstern** 2019-05-16 14:59 UTC
