### ISSUE TITLE
Firebase functions emulator does not look at transitive dependencies for requirements

### ISSUE THREAD

**Issue by lpellegr** [firebase/firebase-tools#3588] opened 2021-07-19 17:38 UTC
Firebase CLI version 9.6.1 on Fedora 34.

When you have a firebase function configured and you try serving it locally with `firebase serve`, the command crashes if you don't have `firebase-admin` and `firebase-functions` as a **direct dependency** in your _package.json_.

In my case, `firebase-admin` and `firebase-functions` are imported as a dependency of another library I include in my _package.json_. I would expect Firebase CLI checking transitive dependencies and prevent us importing required dependencies (that are already imported by transitivity) as a direct dependency.

**Comment by inlined** [comment] 2021-07-19 19:26
Node requires all dependencies you want to use to be part of your package.json. If you don't, the transitive dependency might actually be installed in another module's node_modules instead of at the root node_modules. Closing this bug as Working as Intended.

**Closed by inlined** 2021-07-19 19:26 UTC
