### ISSUE TITLE
How to solve this

### ISSUE THREAD

**Issue by thirdygayares** [firebase/firebase-tools#6685] opened 2024-01-13 02:11 UTC
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment] 2024-01-15 10:02
Hey @thirdygayares, there aren't any details provided in this report, so I'm going to go ahead and close this. Please file a new issue and specify the details using the provided template. This way, it would be more efficient in identifying the cause of the issue. Thanks!

**Closed by aalej** 2024-01-15 10:02 UTC
Labels: type: bug
