### ISSUE TITLE
`firebase serve` fails on latest version of Firebase Functions

### ISSUE THREAD

**Issue by Swivelgames** [firebase/firebase-tools#489] opened 2017-10-04 15:15 UTC
I wasn't sure if this was related to `firebase-tools` or `firebase-functions`, so I'll post it here in case it's related to one and not the other:

`firebase-tools` The latest versions of all versions of `firebase-*` related packages (global and local). I'm no longer able to use the tools:

```
$ firebase serve --only functions

=== Serving from '/Users/****/Projects/node/****'...

i  functions: Preparing to emulate functions.
⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
⚠  functions: Error from emulator. Error
    at Error.FirebaseError (/****/node_modules/firebase-tools/lib/error.js:11:17)
    at ChildProcess.<anonymous> (/****/node_modules/firebase-tools/lib/parseTriggers.js:24:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Versions:
```
$ node --version
v6.11.4

$ cat package.json | grep firebase
    "firebase-admin": "^5.4.1",
    "firebase-functions": "^0.7.0",

$ firebase --version
3.13.0

$ cat yarn.lock | grep firebase
firebase-admin@^5.4.1:
  resolved "https://registry.yarnpkg.com/firebase-admin/-/firebase-admin-5.4.1.tgz#6a930c5ed3ffceb7772394a50ba60497ec5090f6"
firebase-functions@^0.7.0:
  resolved "https://registry.yarnpkg.com/firebase-functions/-/firebase-functions-0.7.0.tgz#a3a7041601c8500d9ab81bcf92f6a391fd87028e"
```

This seems unrelated to any work that I've done on my project. Reverting to a previously known working version of my `functions` app and updating the packages results in the same output and failure to run.

**Comment by Swivelgames** [comment] 2017-10-04 18:35
Related Discussion: https://github.com/firebase/firebase-functions/issues/114

**Comment by laurenzlong** [comment] 2017-10-04 18:42
Closing as duplicate of firebase/firebase-functions#114

Lets continue to discussion there.

**Closed by laurenzlong** 2017-10-04 18:42 UTC
