### ISSUE TITLE
Calling functions.config() from JS broken on 9.19.0 when running functions emulator

### ISSUE THREAD

**Issue by ljle** [firebase/firebase-tools#3793] opened 2021-09-30 16:18 UTC
### [REQUIRED] Environment info

**firebase-tools:** 9.19.0

**Platform:** Windows with WSL2 on Arch Linux

### [REQUIRED] Test case

- No repo, see comment below.

### [REQUIRED] Steps to reproduce
- Call `functions.config()` from any JS code by importing `firebase-functions` while running the functions emulator returns an empty object.
![image](https://user-images.githubusercontent.com/696474/135492620-13bea166-6968-4fed-95e4-63304a2dbb62.png)

### [REQUIRED] Expected behavior

- `functions.config()` returns the values inside `functions/.runtimeconfig.json`.

### [REQUIRED] Actual behavior

- `functions.config()` returns an empty object. However, this does not happen after downgrading to `9.18.0`.

**Comment by ggirotto** [comment] 2021-09-30 20:38
Same here

**Comment by FelDev** [comment] 2021-09-30 21:45
I have the same issue on a mac.
Reverting to 9.18.0 fixed it.

**Comment by taeold** [comment] 2021-10-04 21:16
Can folks share the version of `firebase-functions` being used? 

I tried reproducing with the latest firebase-functions@3.15.7 and firebase-tools@9.19.0 on MacOS Big Sur without an issue.

**Comment by xwz** [comment] 2021-10-05 11:24
Seems to be removed without replacement? https://github.com/firebase/firebase-tools/compare/v9.18.0...master#diff-0366293848c53849685ead9c0871e6ab4c0b2232ebdb379ba79a6def21f99fc3L678

**Comment by ljle** [comment] 2021-10-09 16:45
> Can folks share the version of `firebase-functions` being used?
> 
> I tried reproducing with the latest firebase-functions@3.15.7 and firebase-tools@9.19.0 on MacOS Big Sur but things worked as expected.

Can confirm this fixes the issue.

I just tried it with `firebase-functions@3.15.7` and `firebase-tools@9.20.0` and the emulator loaded successfully.

It was previously failing while using `firebase-functions@3.14.1`.

**Comment by vlombardifiters** [comment] 2021-10-12 13:05
I confirm that the issue exists in v9.20.0 too.

**Comment by roblonj** [comment] 2021-10-17 13:25
@taeold i tried using firebase-functions@3.15.7 and firebase-tools@9.20.0 and it didn't work. Reverting firebase-tools@9.18.0 worked for me.

**Comment by ketansontakke** [comment] 2021-11-20 00:01
Still an issue for me after upgrading to firebase-tools@9.23.0, but only with newly created functions. All functions created prior to upgrading still worked fine for some reason and could recognize the config file. Had to revert to firebase-tools@9.18.0 for all my functions to work again.

**Comment by RCSandberg** [comment] 2021-12-06 11:12
@taeold Confirming this is still an issue on firebase-tools@9.23.0, running on Windows 10 using PowerShell (with appropriate encoding and command run to generate .runtimeconfig.json and file placed in functions folder).

**Comment by taeold** [comment] 2021-12-06 18:53
Thanks for your patience folks as we work through this issue.

AFAIK, this issue seems to be happening due to incompatible versions of the Firebase Functions SDK and Firebase CLI are used together. Specifically,

1. Using firebase-functions < 3.15.7 AND
2. Using firebase-tools > 9.19.0

You will trip against the issue described here.

I'm going to be sending out a patch to firebase-tools, and once that's released, you should be able to upgrade your Firebase CLI to get around the issue.

If you are affected with this bug BUT don't think you fall into the condition I laid out above, I'd love to hear from you. It would help me identify the root case of a possibly new issue.

**Comment by shiv-shyftbase** [comment] 2021-12-15 20:48
> > Can folks share the version of `firebase-functions` being used?
> > I tried reproducing with the latest firebase-functions@3.15.7 and firebase-tools@9.19.0 on MacOS Big Sur but things worked as expected.
> 
> Can confirm this fixes the issue.
> 
> I just tried it with `firebase-functions@3.15.7` and `firebase-tools@9.20.0` and the emulator loaded successfully.
> 
> It was previously failing while using `firebase-functions@3.14.1`.

worked for me. thanks

**Comment by taeold** [comment] 2022-03-16 21:26
This was fixed in 3.16.0.

**Closed by taeold** 2022-03-16 21:26 UTC
Labels: Needs: Attention
