### ISSUE TITLE
🐛 [firestore-bigquery-export] Support firestore-bigquery-export on emulator

### ISSUE THREAD

**Issue by kornha** [firebase/firebase-tools#6693] opened 2023-12-16 00:33 UTC
- Extension name: **\_**  firestore-bigquery-export
- Extension version: **\_** 0.1.43
- Configuration values (redact info where appropriate):
  - **\_** DATASET_ID=firestore_export
  - **\_** DATASET_LOCATION=us
  - **\_** firebaseextensions.v1beta.function/location=us-central1
  - **\_** TABLE_ID=votes
  - **\_** TABLE_PARTITIONING=DAY
  - **\_** TIME_PARTITIONING_FIELD_TYPE=omit
  - **\_** USE_NEW_SNAPSHOT_QUERY_SYNTAX=yes
  - **\_** WILDCARD_IDS=false

###  Describe the problem

When trying to run the emulator, some functions do start while others dont:

```
✔  functions[us-central1-ext-firestore-bigquery-export-ws81-fsexportbigquery]: firestore function initialized.
⚠  Unsupported function type on ext-firestore-bigquery-export-ws81-fsimportexistingdocs. Expected either an httpsTrigger, eventTrigger, or blockingTrigger.
i  functions[us-central1-ext-firestore-bigquery-export-ws81-fsimportexistingdocs]: function ignored because the unknown emulator does not exist or is not running.
⚠  Unsupported function type on ext-firestore-bigquery-export-ws81-syncBigQuery. Expected either an httpsTrigger, eventTrigger, or blockingTrigger.
i  functions[us-central1-ext-firestore-bigquery-export-ws81-syncBigQuery]: function ignored because the unknown emulator does not exist or is not running.
⚠  Unsupported function type on ext-firestore-bigquery-export-ws81-initBigQuerySync. Expected either an httpsTrigger, eventTrigger, or blockingTrigger.
i  functions[us-central1-ext-firestore-bigquery-export-ws81-initBigQuerySync]: function ignored because the unknown emulator does not exist or is not running.
⚠  Unsupported function type on ext-firestore-bigquery-export-ws81-setupBigQuerySync. Expected either an httpsTrigger, eventTrigger, or blockingTrigger.
i  functions[us-central1-ext-firestore-bigquery-export-ws81-setupBigQuerySync]: function ignored because the unknown emulator does not exist or is not running.
```
I suspect this is because fsexportbigquery is a function, and the others are cloud task triggers, which do not currently have local emulator support.

However, the documentation seems to imply I can run on an emulator: https://extensions.dev/extensions/firebase/firestore-bigquery-export

I have tried on two projects with the same issue. Am I correct about lack of emulator support, or am I missing something? I cannot find this documented. 

#### Steps to reproduce:

Try running firestore-bigquery-export on an emulator. Observe that some functions do not start and the export fails.

##### Expected result

Ability to export on emulator.

##### Actual result

Fails to run functions in an emulator and hence fails bq export.

**Comment by joehan** [comment] 2024-01-16 19:25
Hey @kornha - as you suspected, those function are not being run because there is no Cloud Tasks emulator yet. You can still test out the Firestore  triggered function that mirrors changes to BigQuery.

Closing this as a duplicate of #4884

**Closed by joehan** 2024-01-16 19:25 UTC
Labels: type: feature request
