### ISSUE TITLE
Error: Source and destination must not be the same. Next.js 14 Firebase Hosting

### ISSUE THREAD

**Issue by JwillSDP** [firebase/firebase-tools#7027] opened 2024-04-21 15:42 UTC
### [REQUIRED] Environment info

**firebase-tools:* 13.7.3*

**Platform: Windows**

### [REQUIRED] Test case

Default application created from npx create-next-app@latest --experimental-app.

default option for nextjs (app)

### [REQUIRED] Steps to reproduce

firebase deploy --only hosting --debug

### [REQUIRED] Expected behavior

Deploying the app nextjs, firebase, application in the cloud

### [REQUIRED] Actual behavior

```bash

   Thank you for trying our early preview of Next.js support on Firebase Hosting.
   During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.
   The integration is known to work with Next.js version 12 - 14.0. You may encounter errors.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/nextjs
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

[debug] [2024-04-21T15:41:10.841Z] >>> [apiv2][query] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview [none]
[debug] [2024-04-21T15:41:11.153Z] <<< [apiv2][status] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview 200
[debug] [2024-04-21T15:41:11.153Z] <<< [apiv2][body] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview {"name":"projects/v12elites/sites/v12elites/channels/AmalPreview","url":"https://v12elites--amalpreview-tl7znfe9.web.app","createTime":"2024-04-21T15:20:20.957663814Z","updateTime":"2024-04-21T15:41:01.378062977Z","retainedReleaseCount":10,"expireTime":"2024-04-28T15:41:01.378062977Z"}
[info]   ▲ Next.js 14.2.2

[info] 

[info]    Creating an optimized production build ...

[info]  ✓ Compiled successfully

[info]    Linting and checking validity of types ...

[info]    Collecting page data ...

[info]    Generating static pages (0/4) ...

[info]    Generating static pages (1/4) 

[info]    Generating static pages (2/4) 

[info]    Generating static pages (3/4) 

[info]  ✓ Generating static pages (4/4)

[info]    Finalizing page optimization ...
   Collecting build traces ...

[info] 

[info] Route (app)                              Size     First Load JS
┌ ○ /                                    141 B            87 kB
└ ○ /_not-found                          871 B          87.8 kB
+ First Load JS shared by all            86.9 kB
  ├ chunks/23-b6b066db8b1efede.js        31.4 kB
  ├ chunks/fd9d1056-2821b0f0cabcd8bd.js  53.6 kB
  └ other shared chunks (total)          1.84 kB



[info] ○  (Static)  prerendered as static content


[info] Building a Cloud Function to run this application. This is needed due to:
[info]  • non-static component /_not-found/page
[info] 
[debug] [2024-04-21T15:41:28.741Z] >>> [apiv2][query] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview [none]
[debug] [2024-04-21T15:41:29.027Z] <<< [apiv2][status] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview 200
[debug] [2024-04-21T15:41:29.027Z] <<< [apiv2][body] GET https://firebasehosting.googleapis.com/v1beta1/projects/v12elites/sites/v12elites/channels/AmalPreview {"name":"projects/v12elites/sites/v12elites/channels/AmalPreview","url":"https://v12elites--amalpreview-tl7znfe9.web.app","createTime":"2024-04-21T15:20:20.957663814Z","updateTime":"2024-04-21T15:41:01.378062977Z","retainedReleaseCount":10,"expireTime":"2024-04-28T15:41:01.378062977Z"}
[debug] [2024-04-21T15:41:29.179Z] Error: Source and destination must not be the same.
    at C:\Users\Afrosoul4eva\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\fs-extra\lib\util\stat.js:49:19
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[error] 
[error] Error: An unexpected error has occurred.


```

**Comment by aalej** [comment] 2024-04-22 11:24
Hey @JwillSDP, thanks for reaching out. Looking through the information you provided, it looks like this is a duplicate of https://github.com/firebase/firebase-tools/issues/7022. To keep a single line of communication, I’ll be closing this as a duplicate. Please refer to the other ticket for any updates.

**Closed by aalej** 2024-04-22 11:24 UTC
Labels: type: bug, integration: web frameworks
