### ISSUE TITLE
Not being the able to deploy my backend(functions)

### ISSUE THREAD

**Issue by Ishaan0310** [firebase/firebase-tools#6317] opened 2023-09-01 11:31 UTC
im not able to deploy the backend due to these errors please help my frontend is successfully deployed
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/12497398/firebase-debug.log)

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment] 2023-09-01 12:44
Hi @Ishaan0310, could you please file a new issue specifying the details using the provided template? This way, it would be more efficient in identifying the cause of the issue. It would also be helpful if you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or details on the steps to reproduce the issue so that we can try to replicate it on our end. 

One thing I noticed is that in your debug logs, it shows `Error: listen EADDRINUSE: address already in use :::8675`. Could you try to clear the process running on that address before deploying your functions to see if that would resolve the issue? That said, I'll be closing this issue.

**Closed by aalej** 2023-09-01 12:44 UTC
Labels: type: bug, api: functions
