### ISSUE TITLE
emulators:start failing on clean install

### ISSUE THREAD

**Issue by chapl** [firebase/firebase-tools#5608] opened 2023-03-16 14:46 UTC
### Environment info

**firebase-tools:** 11.24.1

**Platform:** macOS M1 13.2.1 

###  Test case

Attempting to run firebase emulators  

### Steps to reproduce

`firebase emulators:start`

### Expected behavior

The emulators to run as expected

###  Actual behavior

`⚠  ui: Fatal error occurred: 
   Emulator UI has exited with code: 1, 
   stopping all running emulators`

```
/Users/louis/.cache/firebase/emulators/ui-v1.11.4/server/server.js:569
        re"use strict";
          ^^^^^^^^^^^^

SyntaxError: Unexpected string
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1195:20)
    at Module._compile (node:internal/modules/cjs/loader:1239:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.8.0
```

###  Fix
It appears that the wrong zip is currently being pulled, I deleted the zip and folder in .cache/firebase/emulators, and copied ui-v1.11.4.zip from another machine (same specs, installed earlier this month) and there is no error, the running of the emulators is perfectly normal. The code contained by the two files is different.

[VERSION INSTALLED WITH CLI ui-v1.11.4.zip](https://github.com/firebase/firebase-tools/files/10992099/VERSION.INSTALLED.WITH.CLI.ui-v1.11.4.zip)

[VERSION COPIED ui-v1.11.4.zip](https://github.com/firebase/firebase-tools/files/10992107/VERSION.COPIED.ui-v1.11.4.zip)

**Comment by aalej** [comment] 2023-03-16 19:17
Hi @chapl, thanks for reporting this issue. I was able to reproduce the error you mentioned when using node v19.8.0. I have informed out team about this issue so that they can take a look into it. I’ll also be marking this as reproducible.

One thing I noticed is that I am unable to reproduce the issue when using other node versions such as v18.2.1.

**Comment by daniel-naegele** [comment] 2023-03-17 15:37
Can confirm this issue on `Linux 6.2.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 13 Mar 2023 17:02:08 +0000 x86_64 GNU/Linux` with `v19.8.0` and firebase-tools `11.24.0`

**Comment by pokir** [comment] 2023-03-18 14:44
I am having the same issue on `macOS 12.6 21G115 x86_64` with node `v19.8.1` using `firebase-tools` version `11.24.1`.

**Comment by gregfenton** [comment] 2023-03-18 18:33
Reminder to all:  even-numbered versions of node are Long Term Support (LTS), whereas odd numbered are "experimental".

Unless you are building something that you expect to be releasing on the (not yet released) node v20, you likely should be working with the current stable production release of node:  v18.x.

**Comment by christhompsongoogle** [comment] 2023-03-20 19:35
Thank you Greg, TIL about odd versions of Node too. In that case it's not surprising that this might have caused issues. According to https://github.com/nodejs/Release v20 is planned for 2023-04-18, so we will keep an eye out for any issues coming up.

Thanks everyone

**Comment by gregfenton** [comment] 2023-03-20 20:06
@christhompsongoogle - Note that v20 coming out does not mean that FIrebase has yet had a chance to release its support of v20.  You'll want to keep an eye on Firebase's blog and releases too 🙂

**Comment by joehan** [comment] 2023-03-21 17:40
Closing this for now, as this is expected behavior for Node 19. If you run into this, please switch to a stable version of node.

**Closed by joehan** 2023-03-21 17:40 UTC
Labels: type: bug, emulators: ui, reproducible

**Comment by Joebayld** [comment] 2023-04-16 00:29
I'm having this same issue on nodejs version v18.16.0.

**Comment by justLukass** [comment] 2023-04-18 15:38
> I'm having this same issue on nodejs version v18.16.0. Log below:
> 
> ```
> /Users/joebay/.cache/firebase/emulators/ui-v1.11.5/server/server.js:569
>         re"use strict";
>           ^^^^^^^^^^^^
> 
> SyntaxError: Unexpected string
>     at internalCompileFunction (node:internal/vm:73:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1176:20)
>     at Module._compile (node:internal/modules/cjs/loader:1218:27)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
>     at Module.load (node:internal/modules/cjs/loader:1117:32)
>     at Module._load (node:internal/modules/cjs/loader:958:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:23:47
> 
> Node.js v18.16.0
> ```

With version testing I found out that the latest supported NodeJS version is 16, not 17 or 18.

**Comment by godemodegame** [comment] 2023-04-21 15:04
The same problem for Node 16
