### ISSUE TITLE
Deprecated dependency "request@2.88.2" 

### ISSUE THREAD

**Issue by basvandorst** [firebase/firebase-tools#5511] opened 2023-02-13 12:53 UTC
Package is still using this deprecated `request` package.

https://www.npmjs.com/package/request
https://github.com/request/request/issues/3142

**Comment by bkendall** [comment] 2023-02-13 16:44
Duplicate #2215

**Comment by bkendall** [comment] 2023-02-13 16:44
Duplicate of #2215

**Comment by mahmoud-triki** [comment] 2023-03-14 17:07
Hi, could you please prioritize this? that package has been deprecated for more than 3 years. Thanks!

**Comment by joehan** [comment] 2023-03-14 17:52
@mahmoud-triki This is on our radar, and we've stopped using this dependency _almost_ everywhere in the codebase. However, the `functions:shell` command, which provides a REPL for testing out your functions, exposes `request` as part of its public API, so we cannot easily remove `request` without making a breaking change. Next time we release a major version, we plan to make this change & remove `request` - however, for now, hold tight and rest assured that this package is minimally used in `firebase-tools`

Closing this as a duplicate - please follow the discussion there.

**Closed by joehan** 2023-03-14 17:52 UTC
Labels: type: feature request, api: core
