### ISSUE TITLE
Debug breakpoints are not accessible with functions emulator

### ISSUE THREAD

**Issue by AAverin** [firebase/firebase-tools#2208] opened 2020-05-05 14:00 UTC
### [REQUIRED] Environment info

**firebase-tools:** 8.2.0

**Platform:** macOS

### [REQUIRED] Test case

Having a project, add to VSCode `launch.json` following configuration:
```
"version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach",
      "port": 9229,
      "restart": true,
      "skipFiles": [
        "<node_internals>/**"
      ]
    }
  ]
```

Start functions emulator with 
`firebase emulators:start --only functions --inspect-functions`

### [REQUIRED] Steps to reproduce

Put a breakpoint in your function code and attempt to debug.
Observe that breakpoint is greyed out and is not triggered

### [REQUIRED] Expected behavior

Debug breakpoints to stop in VS Code

### [REQUIRED] Actual behavior

Debug breakpoints do not work

**Comment by samtstern** [comment] 2020-05-05 14:06
@AAverin I am not able to reproduce this issue myself:
<img width="1440" alt="Screen Shot 2020-05-05 at 10 05 02 AM" src="https://user-images.githubusercontent.com/8466666/81075103-edeb4680-8eb7-11ea-8e36-7ec9e2a361b4.png">

Are you able to reproduce this bug if you create an empty directory, run `firebase init functions` and then try debugging the bare-bones code that we provide for you?

**Comment by AAverin** [comment] 2020-05-05 14:11
I would have to try this again, but the project I am working on is pretty fresh, I just started it a few weeks ago. The only probable difference is that I first started the project and then updated firebase-tools to latest version just now.

**Comment by samtstern** [comment] 2020-06-02 14:17
Going to close this since I was never able to reproduce.  If you're able to find a simple reproduction on a fresh project please tell me and I will re-open.

**Closed by samtstern** 2020-06-02 14:17 UTC
Labels: emulator-suite, emulators: functions
