### ISSUE TITLE
(CLI) selecting `Hosting: Configure files for Firebase Hosting and (optionally) set up GitHub Action deploys`, can't specify the command parameter due to the CLI freezing

### ISSUE THREAD

**Issue by hslee2008** [firebase/firebase-tools#6689] opened 2024-01-15 15:40 UTC
### [REQUIRED] Environment info

**firebase-tools: 13.0.2**
**Platform: Windows 11. 10**

### [REQUIRED] Test case

No need for test cases.

### [REQUIRED] Steps to reproduce

1. Run `firebase init` on any device on any project (only tested on windows)
2. Select `Hosting: Configure files for Firebase Hosting and (optionally) set up GitHub Action deploys`
3. continue...

### [REQUIRED] Expected behavior

The CLI continues after pressing enter, able to specify the next parameter.

#### LOGS

```
? Are you ready to proceed? Yes
? Which Firebase features do you want to set up for this directory? Press Space to select features, then Enter to confirm your choices. Hosting: Configure files for Firebase Hosting and
(optionally) set up GitHub Action deploys

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

i  Using project ***** (*****)

=== Hosting Setup

Your public directory is the folder (relative to your project directory) that
will contain Hosting assets to be uploaded with firebase deploy. If you
have a build process for your assets, use your build's output directory.

? What do you want to use as your public directory? .output/public
? Configure as a single-page app (rewrite all urls to /index.html)? No
? Set up automatic builds and deploys with GitHub? Yes
? File .output/public/404.html already exists. Overwrite? No
i  Skipping write of .output/public/404.html
? File .output/public/index.html already exists. Overwrite? No
i  Skipping write of .output/public/index.html

i  Detected a .git folder at C:\Users\user\******
i  Authorizing with GitHub to upload your service account to a GitHub repository's secrets store.

Visit this URL on this device to log in:
https://github.com/login/oauth/****

Waiting for authentication...

+  Success! Logged into GitHub as hslee2008

? For which GitHub repository would you like to set up a GitHub workflow? (format: user/repository) hslee2008/*****

+  Created service account github-action-****** with Firebase Hosting admin permissions.
+  Uploaded service account JSON to GitHub as secret FIREBASE_SERVICE_ACCOUNT_******.
i  You can manage your secrets at https://github.com/hslee2008/***/settings/secrets.

? Set up the workflow to run a build script before every deploy? Yes
? What script should be run before every deploy? (npm ci && npm run build) yarn && yarn generate
? What script should be run before every deploy? npm ci && npm run build

+  Created workflow file C:\Users\user\Desktop\****\.github/workflows/firebase-hosting-pull-request.yml
? Set up automatic deployment to your site's live channel when a PR is merged? Yes
? What is the name of the GitHub branch associated with your site's live channel? main

+  Created workflow file C:\Users\user\Desktop\****\.github/workflows/firebase-hosting-merge.yml

i  Action required: Visit this URL to revoke authorization for the Firebase CLI GitHub OAuth App:
https://github.com/settings/connections/applications/********************
i  Action required: Push any new workflow file(s) to your repo

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

+  Firebase initialization complete!
```

#### Specific Parts

```
? What script should be run before every deploy? (npm ci && npm run build) yarn && yarn generate
? What script should be run before every deploy? npm ci && npm run build
```

Here, after entering `yarn && yarn generate` and pressing enter, the cli doesn't move on. You have to press enter twice.

And having to press twice, you can't specify the next parameter.

**Comment by joehan** [comment] 2024-01-16 21:57
Hey @hslee2008, I wasn't able to reproduce this either on MacOS or Windows. I also checked the code controlling this and it seems to be no different than any of our other prompts, so I'm not sure why this would be happening for you. As a workaround, you can manually edit the files in `.github/workflows/` to include your desired command.

I'm gonna close this as not reproducible for now - if others run into this or can repro, feel free to open a new issue and I'll dig further.

**Closed by joehan** 2024-01-16 21:57 UTC
Labels: type: bug, api: hosting
