### ISSUE TITLE
Emulator, TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by AdditionAddict** [firebase/firebase-tools#3905] opened 2021-11-17 11:59 UTC
### [REQUIRED] Environment info

**firebase-tools:** 9.20.0

**Platform:** Windows

### [REQUIRED] Test case

```
export const truckDataRoutine = functions.pubsub.schedule('*/20 * * * *').onRun((context: any) => {
    console.log(context)
    console.log('This will be run every 20 minutes!');

    return null
})
```

### [REQUIRED] Steps to reproduce

Running
```
> npm run build && firebase emulators:start
```
to start `functions, storage, pubsub`

and calling the following URL to trigger the code above
http://localhost:5001/my-dbname/us-central1/verified-truckDataRoutine-0

causes the following error
```
i  functions: Beginning execution of "us-central1-verified-truckDataRoutine"
!  functions: TypeError: Cannot read property 'data' of undefined
    at processBackground (C:\Users\andrewa\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:519:24)
    at invokeTrigger (C:\Users\andrewa\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:610:19)
    at handleMessage (C:\Users\andrewa\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:702:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
!  Your function was killed because it raised an unhandled error.
```

I don't have any code that attempts to access a 'data' property.

### [REQUIRED] Expected behavior

Calls `truckDataRoutine` will no error

### [REQUIRED] Actual behavior

```
C:\Users\andrewa\Documents\ProofOfConceptApps\gold\functions>npm run build && firebase emulators:start

> functions@ build C:\Users\andrewa\Documents\ProofOfConceptApps\gold\functions
> tsc

i  emulators: Starting emulators: functions, firestore, pubsub
!  emulators: It seems that you are running multiple instances of the emulator suite for project my-dbname. This may result in unexpected behavior.
!  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, database, hosting, storage
+  functions: Using node@14 from host.
i  firestore: Firestore Emulator logging to firestore-debug.log
i  pubsub: Pub/Sub Emulator logging to pubsub-debug.log
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "C:\Users\andrewa\Documents\ProofOfConceptApps\gold\functions" for Cloud Functions...
+  functions[us-central1-verified-truckDataRoutine]: pubsub function initialized.
+  functions[us-central1-verified-truckSubscription]: http function initialized (http://localhost:5001/my-dbname/us-central1/verified-truckSubscription).

┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://localhost:4000                │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Functions │ localhost:5001 │ http://localhost:4000/functions │
├───────────┼────────────────┼─────────────────────────────────┤
│ Firestore │ localhost:8080 │ http://localhost:4000/firestore │
├───────────┼────────────────┼─────────────────────────────────┤
│ Pub/Sub   │ localhost:5002 │ n/a                             │
└───────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.

i  functions: Beginning execution of "us-central1-verified-truckDataRoutine"
!  functions: TypeError: Cannot read property 'data' of undefined
    at processBackground (C:\Users\andrewa\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:519:24)
    at invokeTrigger (C:\Users\andrewa\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:610:19)
    at handleMessage (C:\Users\andrewa\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:702:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
!  Your function was killed because it raised an unhandled error.
```

**Comment by idkq** [comment] 2021-11-17 20:23
Similar here....

firebase-debug.log

```
[debug] [2021-11-17T20:20:12.367Z] TypeError: Cannot read property 'rows' of undefined
    at new Table (/Users/roddy/.npm-global/lib/node_modules/firebase-tools/node_modules/cli-table/lib/index.js:51:15)
    at Command.actionFn (/Users/roddy/.npm-global/lib/node_modules/firebase-tools/lib/commands/emulators-start.js:47:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by CodeOfficer** [comment] 2021-11-17 21:38
I'm seeing a similar issue as of 5 hours ago in our app:

```
[2021-11-17T21:22:36.297Z] TypeError: Cannot read property 'rows' of undefined
    at new Table (/opt/hostedtoolcache/node/14.18.1/x64/lib/node_modules/firebase-tools/node_modules/cli-table/lib/index.js:51:15)
    at Command.actionFn (/opt/hostedtoolcache/node/14.18.1/x64/lib/node_modules/firebase-tools/lib/commands/emulators-start.js:47:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by RoryO** [comment] 2021-11-17 22:42
Looks like https://github.com/firebase/firebase-tools/pull/3908 is the root cause.

Until it's merged, commenting out lines 47-89 in `emulators-start.js` works around the issue.

**Comment by AdditionAddict** [comment] 2021-11-18 08:19
The above errors are different to mine and references `rows` and `cli-table`. Please post comments on the separate issue opened.

**Comment by AdditionAddict** [comment] 2021-11-18 09:03
I upgraded to 9.22.0 and got this cli-table error. 

Whilst commenting out 47-87 in `emulators-start.js` stops this error and I get back to my original error in `functionsEmulatorRuntime.js` of 'data' being undefined
```
[warn] !  functions: TypeError: Cannot read property 'data' of undefined
    at processBackground (C:\Users\andrewa\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:519:24)
    at invokeTrigger (C:\Users\andrewa\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:610:19)
    at handleMessage (C:\Users\andrewa\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:702:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {"metadata":{"emulator":{"name":"functions"},"function":{"name":"us-central1-verified-truckDataRoutine"},"message":"TypeError: Cannot read property 'data' of undefined\n    at processBackground (C:\\Users\\andrewa\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\lib\\emulator\\functionsEmulatorRuntime.js:519:24)\n    at invokeTrigger (C:\\Users\\andrewa\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\lib\\emulator\\functionsEmulatorRuntime.js:610:19)\n    at handleMessage (C:\\Users\\andrewa\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\lib\\emulator\\functionsEmulatorRuntime.js:702:15)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}}
[warn] !  Your function was killed because it raised an unhandled error. {"metadata":{"emulator":{"name":"functions"},"function":{"name":"us-central1-verified-truckDataRoutine"},"message":"Your function was killed because it raised an unhandled error."}}
```

**Comment by oppahansi** [comment] 2021-11-18 15:59
> I'm seeing a similar issue as of 5 hours ago in our app: (reproduced in the most recent version but also in 9.16.0)
> 
> ```
> [2021-11-17T21:22:36.297Z] TypeError: Cannot read property 'rows' of undefined
>     at new Table (/opt/hostedtoolcache/node/14.18.1/x64/lib/node_modules/firebase-tools/node_modules/cli-table/lib/index.js:51:15)
>     at Command.actionFn (/opt/hostedtoolcache/node/14.18.1/x64/lib/node_modules/firebase-tools/lib/commands/emulators-start.js:47:33)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> ```

Same here. Clean project set up. Same problem.

**Comment by phess101** [comment] 2021-11-18 16:55
I believe the later comments referring to "Cannot read property 'rows' of undefined" are caused by an unrelated issue resolved by PR https://github.com/firebase/firebase-tools/pull/3907 that prevents the emulator from actually running, not an error during execution.

**Comment by phess101** [comment] 2021-11-18 19:11
Looks like cli-table just updated to 0.3.8. I haven't tested myself but it should resolve the issue

**Comment by AdditionAddict** [comment] 2021-11-19 07:53
@phess101  I don't think it wil resolve my issue as I get a different error message. Do you know a way to install this PR so I can test and close/update this issue?

**Comment by AdditionAddict** [comment] 2021-11-19 08:18
Updates to v9.23.0 but the error `Cannot read property 'data' of undefined` persists.

Note my `https.onRequest` works but my pubsub function is the one triggering the error.

**Comment by bkendall** [comment] 2021-11-19 19:34
Okay, first - I'm skipping past any `Cannot read property 'rows' of undefined` comments - those were all for a different issue.

I _think_ what's happening here is a misunderstanding. Your function is a pubsub trigger, which expects a different set of information when it is called by pubsub. If you change the function to an http trigger (`https.onRequest`), you'd be able to call it via https as expected.

Under the hood, what's happening is that something's parsing the request to that endpoint and _expecting_ `.data` to be there since it would come from the pubsub system. But since it's not there, it crashes.

Hope this helps!

**Closed by bkendall** 2021-11-19 19:34 UTC

**Comment by idkq** [comment] 2021-11-19 21:05
> Okay, first - I'm skipping past any Cannot read property 'rows' of undefined comments - those were all for a different issue.

I can confirm that commenting lines 47-87 in emulators-start.js stops this error. 

Why was this issue closed?

**Comment by bkendall** [comment] 2021-11-19 21:16
The error from `emulators-start.js` is tied to `cli-table` which was handled in #3910. Updating the CLI to `9.23.0` will fix that issue.

`Cannot read property 'data' of undefined` is a _different_ error, which in this case comes from making a malformed HTTP call to an emulated pubsub function endpoint. Since this isn't a supported feature, I've closed the issue.

**Comment by idkq** [comment] 2021-11-19 21:28
> Cannot read property 'data' of undefined is a different error

> in this case comes from making a malformed HTTP call to an emulated pubsub function endpoint

If you see my log it breaks on `const successMessageTable = new Table();` line `emulators-start.js:47:33` which is related to instantiating the `cli-table`

**Comment by phess101** [comment] 2021-11-22 17:47
> > Cannot read property 'data' of undefined is a different error
> 
> > in this case comes from making a malformed HTTP call to an emulated pubsub function endpoint
> 
> If you see my log it breaks on `const successMessageTable = new Table();` line `emulators-start.js:47:33` which is related to instantiating the `cli-table`

Your issue is not related to the original issue reported. The original error was `functions: TypeError: Cannot read property 'data' of undefined`
