### ISSUE TITLE
Firebase CI token expires when gsuite session length enabled

### ISSUE THREAD

**Issue by Mistic92** [firebase/firebase-tools#2158] opened 2020-04-22 13:24 UTC
### [REQUIRED] Environment info

**firebase-tools:** latest ```npm install -g firebase-tools```

**Platform:** Docker node:10-alpine

### [REQUIRED] Test case
When session length is enabled on gsuite, token generated with ```firebase login:ci``` expire and is useless for CI.

### [REQUIRED] Steps to reproduce
1. Have gsuite account with enabled [session length](https://support.google.com/a/answer/7576830?hl=en)
2. Generate token using ```firebase login:ci``` and check if it's working (should)
3. Wait for expire session and when you need to login again to GPC console. 
4. Try to use token again (normal thing for CI).

### [REQUIRED] Expected behavior

CI have access to deploy hosting and use firebase tools.
### [REQUIRED] Actual behavior

CI token expire every X hours (set in gsuite admin) and is useless for CI and automated deploys. 
```
 $ firebase use --token $FIREBASE_DEPLOY_KEY $projectId
 Error: Invalid project selection, please verify project XXXXXXX exists and you have access.
```
Solution for this is allow to use Service Accounts.

**Comment by samtstern** [comment] 2020-04-22 13:32
@Mistic92 since that is an OAuth user credential I believe this is the expected behavior based on your organization's policy.

Have you tried deploying with service account credentials and `GOOGLE_APPLICATION_CREDENTIALS` instead?

**Comment by Mistic92** [comment] 2020-04-22 13:35
I'm using Gitlab CI/CD and have tried to pass credentials.json as file variable but it was not working. Is there any tutorial for this? 
I wanted to use service account from the beginning but couldn't find any example.

**Comment by mbleigh** [comment] 2020-04-22 22:35
You need to have the JSON credentials in a file on the machine, and set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to be a path to that file. After that, you should be able to run `firebase` commands without passing `--token` or logging in.

**Comment by mbleigh** [comment] 2020-04-22 22:36
Closing this issue since service accounts are supported and org policies around refresh tokens are out of scope for this repo.

**Closed by mbleigh** 2020-04-22 22:36 UTC
