### ISSUE TITLE
Firestore Emulator UI doesn't show virtual documents until full path exists

### ISSUE THREAD

**Issue by vojdan** [firebase/firebase-tools#2417] opened 2020-07-02 07:22 UTC
### [REQUIRED] Environment info

**firebase-tools:** 8.4.3

**Platform:** MacOS

### [REQUIRED] Test case

Empty firestore database with test (full unlocked) access.

### [REQUIRED] Steps to reproduce

Create a document without creating any ancestor segments, e.g. 
```
const virtualDocPath = firestore
	.collection('users')
	.doc(uid)
	.collection('someCol')
	.doc('aDoc')
	.collection('anotherCol')
	.doc('targetDoc');

await virtualDocPath.set({ test: 'data' });
```
##### Emulator (bad):
After executing the code above, the Emulator UI will not show any entries. 
##### Production (good):
Executing the same code in production will show the full (clickable) path with the note `This document does not exist, it will not appear in queries or snapshots` in all virtual documents.
##### Note:
The document in the emulator is only shown *after* we create the rest of the ancestor path, which can be after inserting the data.

### [REQUIRED] Expected behavior

Creating a virtual document can be seen in the Firestore Emulator UI, along with the message `This document does not exist, it will not appear in queries or snapshots`

### [REQUIRED] Actual behavior

Emulator UI doesn't show the documents until the full ancestor path is created.

**Comment by samtstern** [comment] 2020-07-06 14:02
@vojdan thanks for reporting this!  I believe this is a duplicate of this issue, so please check out the discussion over there:
https://github.com/firebase/firebase-tools-ui/issues/322

**Closed by samtstern** 2020-07-06 14:02 UTC
