### ISSUE TITLE
Why does firebase login:use <email> require you to be in a Firebase project?

### ISSUE THREAD

**Issue by Yukinosuke-Takada** [firebase/firebase-tools#6526] opened 2023-11-15 05:07 UTC
I wanted to see all Firebase projects that were associated with another account I've added to the firebase-cli. I used the `firebase login:use <email>` command but got some error that said I needed to be in a Firebase project. I made a firebase project (`firebase init`) just to change the account. I find it strange since other `firebase login` commands do not require you to be in a Firebase project.

### [REQUIRED] Environment info

**firebase-tools:** 12.9.0

**Platform:** macOS 14.0

### [REQUIRED] Test case

I get an error: 

```
Error: Could not determine active Firebase project directory
```

when I use command:

```bash
firebase login:use <email>
```

in a directory that is not a Firebase project.

### [REQUIRED] Steps to reproduce

Go to any directory that is not a Firebase project.

```bash
firebase login:use <email>
```

### [REQUIRED] Expected behavior

Should be able to change your account inside firebase-cli outside of Firebase projects.

### [REQUIRED] Actual behavior

Gives Error that says it requires you to be in a Firebase project

```
Error: Could not determine active Firebase project directory
```

**Comment by aalej** [comment] 2023-11-16 15:38
Hey @Yukinosuke-Takada, thanks for raising this. I was able to reproduce the error you mentioned. Let me raise this to our team to see what we can do here and try to bring someone to provide additional context about this behavior.

**Comment by aalej** [comment] 2023-11-16 18:29
I discussed this with our team, currently the `firebase login:use <email>` command tells the CLI to use the specified identity for the active Firebase project directory. It seems like this is working as intended.

However, we do agree that it is a reasonable feature to make this command work outside of a Firebase project directory. So for now I’ll be marking this as a feature request. If you’re up for it, feel free to submit a PR!

**Comment by Yukinosuke-Takada** [comment] 2023-11-20 13:16
@aalej Thanks for the reply. I've read the source code myself and understand why this was implemented like this.

I've made a PR of this feature, that makes it possible to use this command outside a Firebase project directory!

**Comment by joehan** [comment] 2023-11-30 19:24
Closing this as your PR has been merged and will roll out in the next release. Thanks for the suggestion and contribution!

**Closed by joehan** 2023-11-30 19:24 UTC
Labels: type: feature request, api: core
