### ISSUE TITLE
TTL rules creates indexes that cannot be seen in firebase console, but firebase-tools asks if they should be deleted

### ISSUE THREAD

**Issue by mortenbekditlevsen** [firebase/firebase-tools#6569] opened 2023-12-05 07:51 UTC
### [REQUIRED] Environment info

12.9.1

**firebase-tools:**

macOS

**Platform:**

### [REQUIRED] Test case

Create a TTL rule in the cloud console
Deploy an update to you firestore indexes

firebase-tools will show an error like:

i  firestore: The following field overrides are defined in your project but are not present in your firestore indexes file:
	[ttl_failure.ttl_expiration] -- (ASCENDING) (DESCENDING) (CONTAINS) TTL(ACTIVE)
	[ttl_success.ttl_expiration] -- (ASCENDING) (DESCENDING) (CONTAINS) TTL(ACTIVE)
? Would you like to delete these field overrides? Selecting no will continue the rest of the deployment. No

### [REQUIRED] Steps to reproduce

Provided above.

### [REQUIRED] Expected behavior

I would expect firebase-tools to either ignore TTL based indexes (like it appears that firebase console does) OR
Let firebase-tools provide a way to express these TTL rules.

### [REQUIRED] Actual behavior

Me, as a user, gets confused if I should try and create the indexes that are mentioned in the output from the deployment. But if I do that, will I overwrite the indexes with a version that does not actually support TTL?

**Comment by matt-oakes** [comment] 2023-12-07 11:17
As a workaround, it seems like it's possibe to specify a field override like this in your indexes JSON file and it will still be ignored in the Firebase Console:

```json
{
  "fieldOverrides": [
    {
      "collectionGroup": "yourCollectionGroup",
      "fieldPath": "yourFieldPath",
      "ttl": true,
      "indexes": [
        { "order": "ASCENDING", "queryScope": "COLLECTION_GROUP" },
        { "order": "DESCENDING", "queryScope": "COLLECTION_GROUP" },
        { "arrayConfig": "CONTAINS", "queryScope": "COLLECTION_GROUP" }
      ]
    }
  ]
}
```

As @mortenbekditlevsen said, it's not 100% clear that will not mess up the TTL index, but as nothing extra shows up in the Firebase Console and the TTL page is still showing a green tick, it seems like it would be fine.

It would be best if the Firebase CLI just ignored this index though so you didn't need to specify it as it's just an implementation detail of Firebase's TTL system really.

**Comment by matt-oakes** [comment] 2023-12-07 13:17
I have opened a simple PR #6587 to resolve this issue. With this the CLI will no longer consider deleting TTL indexes.

**Comment by JU-2094** [comment] 2023-12-12 18:25
The README needs more details for this topic. 

TTL policy does not create additional indexes. There's one configuration file for deployment here which has a misleading name as it appears is exclusively for indexes (now also TTL policies).

Firestore by default uses single-field indexes to perform many basic queries, this is what is displaying here. You can manage these single-field indexes and set index exemptions.

Let's say you don't want to index a Field (https://firebase.google.com/docs/firestore/query-data/index-overview#indexing_best_practices) , you need to add a Single-Field exemption

For this you add the FieldOverride 

```
  // Optional, disable index single-field collection group indexes
  fieldOverrides: [
    {
      collectionGroup: "posts",
      fieldPath: "myBigMapField",
      ttl: "true",   // Explicitly enable TTL on this Field.
      // We want to disable indexing so empty the indexes array
      indexes: []
    }
  ]
```

Indexing on TTL fields is enabled by default and could affect performance at higher traffic rates. 
You can add SFI exemptions 
```
  // Optional, disable index single-field collection group indexes
  fieldOverrides: [
    {
      collectionGroup: "posts",
      fieldPath: "ttlField",
      ttl: "true",
      // Disable indexing so empty the indexes array
      indexes: []
    }
  ]
```

Keeping the default indexing is what is posted above. 

You can enable TTL or disable it using this configuration file. Which will start the LRO for enabling/disabling TTL

**Comment by cedvdb** [comment] 2023-12-27 23:15
There needs to be a  documented way to define TTL policies inside a json file.

**Comment by JU-2094** [comment] 2023-12-28 19:04
PR for a small update https://github.com/firebase/firebase-tools/pull/6646 , and will update the Firebase docs with this information as well.

**Comment by joehan** [comment] 2024-01-02 18:43
Closing this issue as we've addressed the cause of the confusion here.

**Closed by joehan** 2024-01-02 18:43 UTC
Labels: type: bug, api: firestore
