### ISSUE TITLE
mysql2 is not working on V7.0.2

### ISSUE THREAD

**Issue by zer09** [firebase/firebase-tools#1508] opened 2019-07-16 02:01 UTC
### Issue
Starting from V7.0.2 the [mysql2](https://www.npmjs.com/package/mysql2) is not working as expected. The functions will just exit silently.
But it is perfectly working on V7.0.1
### [REQUIRED] Environment info

**firebase-tools:** 7.0.2

**Platform:** 5.2.0-arch2-1-ARCH

### [REQUIRED] Test case

Tried using async or callback but render the same result.

```
    this.pool.execute<RowDataPacket[]>(
      `select count(1) as c from tbl_users where uname='admin' limit 1`,
    ).then(([row]) => {
      console.log(row);  // this and the catch block below is just swallowed.
    }).catch((e) => {
      console.log(e);
    });
```

or 

```
try {
    const [row] = await this.pool.execute<RowDataPacket[]>(
      `select count(1) as c from tbl_users where uname='admin' limit 1`,
    );
console.log(row) // this and the catch block below is just swallowed.
} catch(e) {
console.log(e)
}
```

### [REQUIRED] Steps to reproduce

Tried executing the above.

### [REQUIRED] Expected behavior
It should show the content of the result or the catch error.

### [REQUIRED] Actual behavior
Nothing shows.

**Comment by bkendall** [comment] 2019-07-16 18:17
Can you provide a bit more detail? Is this in a Firebase Function that you have written? Is it triggered by an HTTP call, or another trigger? Are you seeing this behavior in production or the emulator?

Does this behavior still exist with `firebase-tools@7.1.0`?

**Comment by zer09** [comment] 2019-07-17 00:06
> Is this in a Firebase Function that you have written? Is it triggered by an HTTP call, or another trigger? 

It was triggered on the constructor, but in further testing it look like the constructor is not initiated until the actual function is triggered via HTTP call.

> Are you seeing this behavior in production or the emulator?

The emulator

> Does this behavior still exist with firebase-tools@7.1.0?

Yes

But unfortunately, I just did rollback the firebase-tools to V6.8.0 because starting from V7 every time  I call the functions, somehow it will create a new instances of it, causing to create a new database connection.

I created a minimal repo.

[This is the test route](https://github.com/zer09/jmfunc2/blob/2fe082f7532ad4b502e227e519438f42c1ffbe0a/functions/src/controller/user/user.router.ts#L12)

[This is the constructor that I was expecting to be executed at startup](https://github.com/zer09/jmfunc2/blob/2fe082f7532ad4b502e227e519438f42c1ffbe0a/functions/src/services/user.service.ts#L13-L21)

[This](https://github.com/zer09/jmfunc2/blob/2fe082f7532ad4b502e227e519438f42c1ffbe0a/functions/src/services/store.service.ts#L13-L26) get always called on every HTTP call, the expected behavior it should be called once on startup, It look like new instance is created on every call.

Thanks

**Comment by samtstern** [comment] 2019-07-17 16:19
@zer09 right now the code being reloaded in every request is the intended behavior:
https://github.com/firebase/firebase-tools/issues/1353

This is also the worst-case behavior in production, so even though we realize we need to provide more options to developers it is not technically "wrong" at the moment.

Versions `6.8.0` and before used an entirely different functions emulator than newer versions.  The old emulator was better at emulating the "hot start" functionality you're looking for but was broken in many other ways, which is why we have started this new effort.

I am going to close this issue as intended behavior (for now) please follow along with #1353 for more updates.

**Closed by samtstern** 2019-07-17 16:19 UTC
Labels: Needs: Attention

**Comment by zer09** [comment] 2019-07-17 22:21
@samtstern oh I see, I am fine with the "hot-reloading on every invocation", but I think it should also release all the resource of the previous instance, because if I am not wrong that instances will not be used again. Like on my situation when I invoke the functions it will create a new MySql connection until I cant connect anymore because the MySql server is full of unused connection.

Thanks

**Comment by samtstern** [comment] 2019-07-17 22:24
@zer09 in the emulator we don't use the instance again, ever.  Each invocation is a brand new process that communicates over a temporary one-time-use socket.  We kill the process, which should release the resources.

**Comment by zer09** [comment] 2019-07-17 22:53
@samtstern Thanks! That behavior is on V7.0.1, I just tested the latest version now and your right.
