### ISSUE TITLE
Ng deploy configuration is not working

### ISSUE THREAD

**Issue by Bamorem** [firebase/firebase-tools#7228] opened 2024-05-28 13:05 UTC
I have a project using Angular 17

I have multiple configurations in my angular.json (production, development, staging).

If I do :
- ng serve --configuration=staging it is working fine and uses the right environment.staging.ts file
- ng serve --configuration=development it is working fine and uses the right environment.ts file
- ng serve --configuration=production  it is working fine and uses the right environment.prod.ts file

But the ng build doesn't work, doesn't matter the configuration it will always use the environment.prod.ts

this is my angular.json

```{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "cli": {
    "packageManager": "npm",
    "schematicCollections": [
      "@angular-eslint/schematics"
    ]
  },
  "newProjectRoot": "projects",
  "projects": {
    "web-app": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "allowedCommonJsDependencies": [
              "google-libphonenumber",
              "moment",
              "moment-timezone"
            ],
            "outputPath": "dist/web-app",
            "index": "src/index.html",
            "browser": "src/main.ts",
            "polyfills": [
              "zone.js"
            ],
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [
              "./node_modules/bootstrap/dist/js/bootstrap.bundle.js"
            ]
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "3mb",
                  "maximumError": "4mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "outputHashing": "all",
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            },
            "staging": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "3mb",
                  "maximumError": "4mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "outputHashing": "all",
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.staging.ts"
                }
              ]
            },
            "development": {
              "optimization": false,
              "extractLicenses": false,
              "sourceMap": true
            }
          },
          "defaultConfiguration": "development"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "buildTarget": "web-app:build:production"
            },
            "development": {
              "buildTarget": "web-app:build:development"
            },
            "staging": {
              "buildTarget": "web-app:build:staging"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "buildTarget": "web-app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "polyfills": [
              "zone.js",
              "zone.js/testing"
            ],
            "tsConfig": "tsconfig.spec.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [
              "./node_modules/bootstrap/dist/js/bootstrap.bundle.js"
            ]
          }
        },
        "deploy": {
          "builder": "@angular/fire:deploy",
          "options": {
            "version": 2
          },
          "configurations": {
            "production": {
              "buildTarget": "web-app:build:production",
              "serveTarget": "web-app:serve:production"
            },
            "development": {
              "buildTarget": "web-app:build:development",
              "serveTarget": "web-app:serve:development"
            },
            "staging": {
              "buildTarget": "web-app:build:staging",
              "serveTarget": "web-app:serve:staging"
            }
          },
          "defaultConfiguration": "development"
        },
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": [
              "src/**/*.ts",
              "src/**/*.html"
            ]
          }
        }
      }
    }
  }
}```


Can someone help me with this ?

**Comment by aalej** [comment] 2024-05-28 19:21
Hey @Bamorem, thanks for reaching out. The issue you described using `ng deploy` seems to be a duplicate of this issue https://github.com/angular/angularfire/issues/3376. That said, I’ll be closing this as a duplicate. 

You should be able to set the configuration and deploy using `FIREBASE_FRAMEWORKS_BUILD_TARGET=staging firebase deploy --only hosting`.

**Closed by aalej** 2024-05-28 19:21 UTC
Labels: type: bug, integration: web frameworks
