### ISSUE TITLE
Error: Unable to detect the web framework in use

### ISSUE THREAD

**Issue by LouisDSC** [firebase/firebase-tools#6513] opened 2023-11-12 22:03 UTC
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment] 2023-11-13 11:20
Hi @LouisDSC, from what I can tell, you’re encountering an issue with the web frameworks feature. For us to be able to start our initial investigation, we would need other information. 

Could you file a new issue and specify the details using the provided template? This way, it would be more efficient in identifying the cause of the error. That being said, I'll be closing this for now.

**Closed by aalej** 2023-11-13 11:20 UTC
Labels: type: bug

**Comment by LouisDSC** [comment] 2023-11-13 11:28
`"hosting": [
{
  "source": ".",
  "ignore": [
    "firebase.json",
    "**/.*",
    "**/node_modules/**"
  ],
  "frameworksBackend": {
    "region": "asia-east1"
  }
},
{
  "target": "friendly-travels",
  "source": ".",
  "frameworksBackend": {}
}
], `

[Error: Assertion failed: resolving hosting target of a site with no site name or target name -> Deploying change in Firebase Hosting to Live site](https://stackoverflow.com/questions/75334788/error-assertion-failed-resolving-hosting-target-of-a-site-with-no-site-name-or)

**Comment by deltaepsilon** [comment] 2024-03-09 13:17
The web frameworks feature doesn't recognize the `hosting.source` attribute in `firebase.json`. Change your `hosting.source` to `hosting.public` and it should work.

```
 "hosting": {
    "public": "hosting",
    ...
 }
 ```

**Comment by deltaepsilon** [comment] 2024-03-09 13:32
> The web frameworks feature doesn't recognize the `hosting.source` attribute in `firebase.json`. Change your `hosting.source` to `hosting.public` and it should work.
> 
> ```
>  "hosting": {
>     "public": "hosting",
>     ...
>  }
> ```

Scratch that. Switching to `hosting.public` made the GitHub Action pass, but the site didn't deploy after that. I got an "index.html missing" error page from Firebase Hosting.
