### ISSUE TITLE
Firestore emulator not reading new rules (needs restart)

### ISSUE THREAD

**Issue by markgoho** [firebase/firebase-tools#2603] opened 2020-09-07 18:14 UTC
### [REQUIRED] Environment info

**firebase-tools:** `8.10.0`

**Platform:** Windows

### [REQUIRED] Steps to reproduce

Start emulator, change rules, see that the emulator log says
``` bash
i  firestore: Change detected, updating rules...
+  firestore: Rules updated.
```

### [REQUIRED] Expected behavior

New rules would be used for tests

### [REQUIRED] Actual behavior

Rules are not in fact picked up

Example (note: `visiblity` is spelled incorrectly):
``` bash
    match /posts/{postId} {
      allow read: if (resource.data.visiblity == 'public') || (resource.data.authorId == request.auth.uid)
    }
```

output of testing:
`Property visiblity is undefined on object. for 'list' @ L17`

Update rule to fix spelling error, see:
``` bash
i  firestore: Change detected, updating rules...
+  firestore: Rules updated.
```

Run test again with same output: `Property visiblity is undefined on object. for 'list' @ L17`

Quit emulator, restart emulator, rerun test, this time it passes.

**Comment by markgoho** [comment] 2020-09-07 18:32
UPDATE: This seems to be related to what one sets as their `projectId`

In the [youtube video](https://youtu.be/VDulvfBpzZE?t=540) Todd says "...make this your actual Project ID from the Firebase Console. This will ensure that new changes to the security rules will be picked up by the emulator automatically every time you change them."

However, in the [documentation on testing firestore rules](https://firebase.google.com/docs/firestore/security/test-rules-emulator) we're told: `Use unique project IDs for each test.`

It would really help if we could get clarification on when to do each and how to make sure our Emulator picks up on these changes if we decide to use a different ID for each test.

**Comment by samtstern** [comment] 2020-09-08 13:30
@markgoho thanks for following up, I will try to clarify the docs!  Closing this issue since it's not a bug in the emulator.

To be clear:

- Rules hot reloading was designed for testing interactively (hooking your app up to the suite).  So when you change the file, we update the rules for your primary project ID.
- Unit tests are meant to be automated and shouldn't depend on any 'state' such as rules reloading, you should use `@firebase/testing` to load the desired rules inside the test suite.

**Closed by samtstern** 2020-09-08 13:30 UTC
