### ISSUE TITLE
Firebase Emulator starts all emulators and then throws error related to npm cli-table

### ISSUE THREAD

**Issue by Mikephii** [firebase/firebase-tools#3913] opened 2021-11-18 06:29 UTC
Im using  firebase-tools ^9.22.0

I am importing a relatively large firestore dataset. its using 7G of ram to run. 

the emulator starts all of the services correctly, deploys all the functions, and then throws this error in firebase-debug

`[debug] [2021-11-18T06:17:29.585Z] TypeError: Cannot read property 'rows' of undefined
    at new Table (C:\Users\Mike\Documents\Code\Antler\internal\functions\node_modules\cli-table\lib\index.js:51:15)
    at Command.actionFn (C:\Users\Mike\Documents\Code\Antler\internal\functions\node_modules\firebase-tools\lib\commands\emulators-start.js:47:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[error] 
[error] Error: An unexpected error has occurred.`

the emulators stay open however and i need to close them via the task manager. I can even view the emulator UI but it just tells me that the emulators are disconnected.

**Comment by bkendall** [comment] 2021-11-18 21:42
Duplicate of #3909

reinstalling firebase-tools (or waiting for the new release `9.23.0` to drop very soon) will fix this for you.

**Closed by bkendall** 2021-11-18 21:42 UTC
