### ISSUE TITLE
Unable to upload files on Storage Emulator with v9 JS SDK

### ISSUE THREAD

**Issue by Ehesp** [firebase/firebase-tools#3780] opened 2021-09-24 09:37 UTC
### [REQUIRED] Environment info

Firebase Tools version: 9.18.0

Firebase JS SDK Version:

```
"firebase": "^9.0.1",
```

**Platform:** macOS

### [REQUIRED] Test case

```
const firebase = initializeApp({
  projectId: "test-project",
  apiKey: "foo",
  storageBucket: "default-bucket",
});

const storage = getStorage(firebase);
connectStorageEmulator(storage, "localhost", 9199);

const sRef = ref(storage, "some-child");

await uploadString(sRef, "This is my message.");
```

### [REQUIRED] Actual behavior

When triggering this code, the emulator quits with the following error in the logs:

```
[debug] [2021-09-24T09:10:07.074Z] TypeError: Cannot read property 'split' of undefined
    at handleUpload (/Users/me/.nvm/versions/node/v16.1.0/lib/node_modules/firebase-tools/lib/emulator/storage/apis/firebase.js:274:50)
```

Looking at the code:

```js
        if (uploadType == "multipart") {
            const contentType = req.header("content-type");
            if (!contentType || !contentType.startsWith("multipart/related")) {
                res.sendStatus(400);
                return;
            }
            const boundary = `--${contentType.split("boundary=")[1]}`;
            const bodyString = req.body.toString();
            const bodyStringParts = bodyString.split(boundary).filter((v) => v);
            const metadataString = bodyStringParts[0].split("\r\n")[3];

            // bodyStringParts only contains a single item
            const blobParts = bodyStringParts[1].split("\r\n");
```

**Comment by derat** [comment] 2021-12-26 17:47
I'm seeing this too (firebase 9.6.1, @firebase/rules-unit-testing 2.0.1). I traced through `lib/emulator/storage/apis/firebase.js` for a bit, but I haven't used Express.js before and `req.body` [seems complicated](https://expressjs.com/en/4x/api.html#req.body), so I didn't get any farther than seeing that the `req.body` passed to `handleUpload` appears to be a Buffer containing the string `[object Blob]`, suggesting a type error somewhere upstream.

Is there another way to get files into the storage emulator? If not, it seems like there's no way to test storage security rules (since all requests will be disallowed due to the files being missing), right?

**Comment by derat** [comment] 2021-12-26 18:18
Just to mention it, I get the same error if I call `initializeApp` and then use `connectStorageEmulator` as described [here](https://firebase.google.com/docs/emulator-suite/connect_storage#android_apple_platforms_and_web_sdks) (rather than using `withSecurityRulesDisabled`) before calling `uploadString` or `uploadBytes`.

**Comment by tonyjhuang** [comment] 2022-07-29 04:55
filed an internal bug to track, b/240635177

**Comment by Yuangwang** [comment] 2022-08-01 17:07
Hi, I'm looking into this now. Just want to confirm with anyone running into this issue -  this only happens during unit testing right? Also are you running the unit tests in a jsdom test environment? (jsdom is set by default if you're using create-react-app)

**Comment by derat** [comment] 2022-08-01 17:21
> Hi, I'm looking into this now. Just want to confirm with anyone running into this issue - this only happens during unit testing right? Also are you running the unit tests in a jsdom test environment? (jsdom is set by default if you're using create-react-app)

Yes, I saw this when calling `uploadString` during unit testing (I haven't tried to perform uploads elsewhere). I'm running tests via `vue-cli-service test:unit` using `@vue/cli-plugin-unit-jest` 4.5.17, and I believe that Jest uses jsdom by default.

Thanks for taking a look!

**Comment by Yuangwang** [comment] 2022-08-01 18:52
@derat thanks for the quick reply! I was able to reproduce this issue in a jsdom test environment as well and when I change the test environment from jsdom to node, the sample test passes without any issue. Because of this I think the problem is related to this [issue](https://github.com/firebase/firebase-js-sdk/issues/6441) in the js sdks (both issues reference the `[object Blob]` that you dug up earlier).  
My recommendation here would be to use the node testing environment (https://jestjs.io/docs/cli#--envenvironment) if you're not using any of the jsdom features and if you are then go through the recommendation on the other thread to point jsdom unit tests to the browser bundle.

**Comment by Yuangwang** [comment] 2022-08-01 18:59
I think this is a js-sdk issue rather than an emulator issue because by the time the emulator receives any data it is already misshapen in the form of `[object Blob]` so I'm closing this for now. If anyone's having issues configuring the module resolution as described, please add a comment in the other [issue](https://github.com/firebase/firebase-js-sdk/issues/6441)

**Closed by Yuangwang** 2022-08-01 18:59 UTC
Labels: emulators: storage

**Comment by derat** [comment] 2022-08-02 13:43
@Yuangwang Thanks for figuring out a workaround! I'm able to use `updateString` when running the tests under Node rather than jsdom.

In case it helps anyone else using Vue and Jest, I originally had a rule like this in my `package.json` file:

`"firebase emulators:exec --only storage \"vue-cli-service test:unit --testPathPattern ./storage*.test.ts\""`

I changed it to this:

`"firebase emulators:exec --only storage \"vue-cli-service test:unit --env=node --testPathPattern ./storage*.test.ts\""`
