### ISSUE TITLE
Failed to upload symbols

### ISSUE THREAD

**Issue by hsl9999** [firebase/firebase-tools#4015] opened 2022-01-13 01:51 UTC
### [REQUIRED] Environment info

**firebase-tools:10.0.1**

**Platform:Windows**

**firebase account: podai.shi@igg.com**

**Unity:Unity 2018.4.10 LTS**

**Java:jdk1.8.0_202**

**mobile platform:android**

**min api level:android 5.1**

**target api level:android 11.0**

**ndk:android-ndk-r16b**

**package name:com.igg.android.scriptsuntoldsecrets**

### [REQUIRED] Test case

firebase crashlytics:symbols:upload --app=1:291277698332:android:0c2c3ca11718eef9b276d9 D:\Users\IGG\Desktop\SUS\SUS_0108-105934_v1.9.2_debug-1.9.2-v100.symbols.zip

### [REQUIRED] Steps to reproduce

output:
i  Generating symbols for D:\Users\IGG\Desktop\SUS\SUS_0108-105934_v1.9.2_debug-1.9.2-v100.symbols.zip
!  [CRASHLYTICS LOG DEBUG] Invoked Crashlytics Buildtools with arguments:
        -generateNativeSymbols true
        -verbose true
        -symbolFileCacheDir C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad
        -unstrippedLibrary D:\Users\IGG\Desktop\SUS\SUS_0108-105934_v1.9.2_debug-1.9.2-v100.symbols.zip
        -symbolGenerator breakpad
[CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
[CRASHLYTICS LOG DEBUG] Skipping dumpsyms extraction, file exists: D:\Users\IGG\Desktop\.crashlytics\dump_syms.exe
[CRASHLYTICS LOG DEBUG] Breakpad symbol generator initialized: D:\Users\IGG\Desktop\.crashlytics\dump_syms.exe
[CRASHLYTICS LOG DEBUG] Zipped input file detected: D:\Users\IGG\Desktop\SUS\SUS_0108-105934_v1.9.2_debug-1.9.2-v100.symbols.zip; unzipping to temp location: C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad\unzippedLibsCache
[CRASHLYTICS LOG DEBUG] Generating native symbol files for C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad\unzippedLibsCache; writing output to: C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad
[CRASHLYTICS LOG DEBUG] Cleaning up unzip target dir: C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad\unzippedLibsCache
java.io.IOException: No native libraries found at C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad\unzippedLibsCache. Either specify the correct unstrippedNativeLibsDir or disable Crashlytics symbol uploading.
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:231)
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:212)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:151)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.doMain(CommandLineHelper.java:105)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:61)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:113)

Error: Failed to upload symbols

### [REQUIRED] Expected behavior

firebase crashlytics:symbols:upload --app=1:291277698332:android:0c2c3ca11718eef9b276d9 G:\Test\TestFirebase\1234-1.9.2-v120.symbols.zip
i  Generating symbols for G:\Test\TestFirebase\1234-1.9.2-v120.symbols.zip
i  Generated symbol file: C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-3b46df89-c7f8-48fd-a522-772f2f27b570\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad\il2cpp.dbg-arm64-c969ed28fa30961aeeb40d9d85548d266a9233c7.sym (22,815,478 bytes)
i  Uploading all generated symbols
i  Crashlytics symbol file uploaded successfully; deleting local file: C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-3b46df89-c7f8-48fd-a522-772f2f27b570\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad\il2cpp.dbg-arm-dc62944d6681324208b8855fb1900eac5b2061b6.sym

### [REQUIRED] Actual behavior

i  Generating symbols for D:\Users\IGG\Desktop\SUS\SUS_0108-105934_v1.9.2_debug-1.9.2-v100.symbols.zip
!  [CRASHLYTICS LOG DEBUG] Invoked Crashlytics Buildtools with arguments:
        -generateNativeSymbols true
        -verbose true
        -symbolFileCacheDir C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad
        -unstrippedLibrary D:\Users\IGG\Desktop\SUS\SUS_0108-105934_v1.9.2_debug-1.9.2-v100.symbols.zip
        -symbolGenerator breakpad
[CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
[CRASHLYTICS LOG DEBUG] Skipping dumpsyms extraction, file exists: D:\Users\IGG\Desktop\.crashlytics\dump_syms.exe
[CRASHLYTICS LOG DEBUG] Breakpad symbol generator initialized: D:\Users\IGG\Desktop\.crashlytics\dump_syms.exe
[CRASHLYTICS LOG DEBUG] Zipped input file detected: D:\Users\IGG\Desktop\SUS\SUS_0108-105934_v1.9.2_debug-1.9.2-v100.symbols.zip; unzipping to temp location: C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad\unzippedLibsCache
[CRASHLYTICS LOG DEBUG] Generating native symbol files for C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad\unzippedLibsCache; writing output to: C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad
[CRASHLYTICS LOG DEBUG] Cleaning up unzip target dir: C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad\unzippedLibsCache
java.io.IOException: No native libraries found at C:\Users\ADMINI~1\AppData\Local\Temp\crashlytics-b391bc36-29c9-4f15-8b6e-0a7ae4d7a423\nativeSymbols\1-291277698332-android-0c2c3ca11718eef9b276d9\breakpad\unzippedLibsCache. Either specify the correct unstrippedNativeLibsDir or disable Crashlytics symbol uploading.
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:231)
        at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:212)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:151)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.doMain(CommandLineHelper.java:105)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:61)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:113)

Error: Failed to upload symbols

**Comment by April-studio** [comment] 2022-01-19 02:40
i got the same issuse,do you fixed it?

**Comment by hsl9999** [comment] 2022-01-19 06:52
> 

No,:(

**Comment by Antonio-Iliev** [comment] 2022-02-01 11:27
I got the same error. I manage to fix it by providing the full phat to the .symbols.zip file. First, my path is not from the root but correct from the command running point.

Can you double-check your paths? It seems different.
**Steps to reproduce** path "D:\Users\IGG\Desktop\SUS\SUS_0108-105934_v1.9.2_debug-1.9.2-v100.symbols.zip"
**Expected behavior** path _"G:\Test\TestFirebase\1234-1.9.2-v120.symbols.zip"_
**Actual behavior** path "D:\Users\IGG\Desktop\SUS\SUS_0108-105934_v1.9.2_debug-1.9.2-v100.symbols.zip"

Just in case this is my setup:
- Mac OS
- Unity 2019.4.f1
- crashlytics-buildtools-2.8.0.jar
- Java - openjdk version "17.0.2" 2022-01-18
- Firebase CLI - 10.1.3

**Comment by WeiLingQiang** [comment] 2022-04-10 09:05
i got the same issuse,do you fixed it?

**Comment by joehan** [comment] 2022-04-11 20:10
This looks like a duplicate of #3930 - I'm going to close this and we can continue discussion there.

**Closed by joehan** 2022-04-11 20:10 UTC
Labels: api: crashlytics
