### ISSUE TITLE
Function deploy and getting config doesn't work on 11.2.X

### ISSUE THREAD

**Issue by aguthstuditemps** [firebase/firebase-tools#4742] opened 2022-07-14 16:04 UTC
Edit: Maybe a duplicate of #4706 ? Still happens on 11.2.2 though.

### [REQUIRED] Environment info

Since upgrading to 11.2.X I cannot deploy functions in a specific project anymore. It seems to be a problem with having an empty object in the function config. It only doesn't work on one project. When I change from our staging environment to a different one and deploy the same code, it works.

`firebase functions:config:get` also works on one environment, but crashes in another

In the debug logs it looks like I have a key `tests` set in the config, but is just set to an empty object `{}` and the processing fails. (see logs at the end)

I could fix the problem for me, by doing 
```
firebase functions:config:set 'tests.bla=blub'
firebase functions:config:unset tests
```
After that getting the functions works again. (The first line already fixed it)

Also: In versions lower than 11.2.0 the key `tests` doesn't show up at all when doing `functions:config:get`.

**firebase-tools:**
11.2.0, 11.2.1, 11.2.2

**Platform:**
Linux

### [REQUIRED] Test case

`firebase deploy --only functions` or `firebase functions:config:get`

### [REQUIRED] Steps to reproduce

push an empty config value to firebase config. No idea how to do that though
`firebase functions:config:set 'xxx={}'` doesn't complain, but doesn't actually seem to do anything or cause the bug

### [REQUIRED] Expected behavior

deploy or getting the config

### [REQUIRED] Actual behavior

for deploy:

```
...
[2022-07-14T13:38:18.083Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/XXX/configs/tests/variables {}
...
[2022-07-14T13:38:18.086Z] Got unexpected error from Runtime Config; it has no status code:Cannot read properties of undefined (reading 'map') {"level":"debug"}
```
for config get:
```
...
[2022-07-14T15:37:30.824Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/XXX/configs/tests/variables 200
[2022-07-14T15:37:30.824Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/XXX/configs/tests/variables {}
...
[2022-07-14T15:38:39.740Z] TypeError: Cannot read properties of undefined (reading 'map')
    at traverseVariables (/usr/local/lib/node_modules/firebase-tools/lib/functionsConfig.js:90:38)
    at Object.materializeConfig (/usr/local/lib/node_modules/firebase-tools/lib/functionsConfig.js:95:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 9)
    at async Object.materializeAll (/usr/local/lib/node_modules/firebase-tools/lib/functionsConfig.js:105:5)
    at async Command.actionFn (/usr/local/lib/node_modules/firebase-tools/lib/commands/functions-config-get.js:32:20)
```

**Comment by bkendall** [comment] 2022-07-14 16:25
Duplicate of #4706

**Closed by bkendall** 2022-07-14 16:25 UTC
Labels: bug
