### ISSUE TITLE
FirebaseCommandException: An error occured on the Firebase CLI when attempting to run a command. COMMAND: firebase projects:create mynotes-flutter-ectjo --json

### ISSUE THREAD

**Issue by RC-KapilDev** [firebase/firebase-tools#5583] opened 2023-03-09 14:32 UTC
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment] 2023-03-09 15:48
Hi @RC-KapilDev, I understand that there's an issue related to creating a Firebase project using the CLI. It would be more helpful if you specify the details using the provided template in a new ticket. This way, it would be more efficient in identifying the cause of the issue. That being said, I'll be closing this for now.

**Closed by aalej** 2023-03-09 15:48 UTC
Labels: type: bug
