### ISSUE TITLE
firebase serve serves an older version

### ISSUE THREAD

**Issue by ogierm** [firebase/firebase-tools#1509] opened 2019-07-16 13:35 UTC
### [REQUIRED] Environment info

**firebase-tools:** 7.1.0

**Platform:** Windows

### [REQUIRED] Test case
???

### [REQUIRED] Steps to reproduce
???
It worked yesterday perfectly and now it doesn't. Even the [deployed website](https://post-a-thread.web.app) has the correct file.

### [REQUIRED] Expected behavior
Firebase serves the files that are actually in the directory that it is supposed to serve.

### [REQUIRED] Actual behavior
For some reason it serves an old version and won't update the files, even on restarting.

![image](https://user-images.githubusercontent.com/29630575/61297946-9f13d980-a7dd-11e9-83e6-eded4af7ee30.png)
- Upper right corner: serving via npm run dev
- Lower right corner: firebase serve
- Upper left side: the file
- Lower left side: console output from firebase serve

[logs.txt](https://github.com/firebase/firebase-tools/files/3397264/logs.txt)

**Comment by samtstern** [comment] 2019-07-16 16:07
@ogierm sorry we need some more information to reproduce and debug this.

Can you show the contents of your `firebase.json` file?  Also from the logs you posted it looks like your site is served from the `public` folder.  Can you show the contents of `public/index.html` as you see it on disk?

**Comment by ogierm** [comment] 2019-07-16 16:41
[firebase.json.txt](https://github.com/firebase/firebase-tools/files/3398128/firebase.json.txt)

[index.html.txt](https://github.com/firebase/firebase-tools/files/3398134/index.html.txt)

That being said: It started working again an hour ago. No clue why though, I hadn't even restarted the task.

**Comment by samtstern** [comment] 2019-07-16 16:45
@ogierm glad it's working for you!  Since we can no longer reproduce this I am going to close the issue.  Hopefully it was just a hiccup in some tool.

**Closed by samtstern** 2019-07-16 16:45 UTC
Labels: Needs: Attention
