### ISSUE TITLE
Functions Emulator does not read parameter configuration (.env files) correctly

### ISSUE THREAD

**Issue by sceee** [firebase/firebase-tools#5313] opened 2022-12-08 09:46 UTC
### [REQUIRED] Environment info

**firebase-tools:** 11.17.0

**Platform:** Windows

### [REQUIRED] Test case

* Have an empty `.env` file:
```
```
* Have a `.env.default` file:
```
IS_STAGING=false
```
* Have a `.env.staging` file:
```
IS_STAGING=true
```
* Have `.env.local` file:
```
FUNCTIONS_EMULATOR=true
```

Have the following code in the `index.ts` that references this parameter's value:
```
...
initializeApp({
  defineBoolean('IS_STAGING')
    .equals(true)
    .thenElse("stagingbucketname", "prodbucketname")
    .toString(),
})
...
```

Have some test that calls a Cloud Function.

### [REQUIRED] Steps to reproduce

1. Just "start" the Firebase emulator using `firebase emulators:start --import=./testdata/emulatordata --project default`
-> The following warning is emitted indicating it could not load the IS_STAGING environment variable from the .env files:
```
? Enter a boolean value for IS_STAGING:
```

### [REQUIRED] Expected behavior

Is should read the variable from the `.env.default` file.

### [REQUIRED] Actual behavior

It asks for the value of the IS_STAGING environment variable.
On top of that, after entering the value when prompted, it tries to write it to a new file `.env.my-project-id` instead of the existing `.env.default` (where default is the alias).

This causes the following output and prevents the emulator from running:
```
i  functions: Created new local file .env.my-project-id to store param values. We suggest explicitly adding or excluding this file from version control.
!!  functions: Failed to load function definition from source: FirebaseError: Can't have both dotenv files with projectId (env.my-project-id) and projectAlias (.env.default) as extensions.
```

It should not write any configuration here as the `IS_STAGING` is already defined in both the `.env.default` and `.env.staging`.

**Additionally:**
If I now rename the `.env.default` and `env.staging` files to `.env.my-project-id` and `.env.my-staging-project-id`, it still prompts for the value. If I enter it, it fails to start the emulator as the value is already defined (this relates to/duplicates #5219 ):
```
? Enter a boolean value for IS_STAGING: false
i  functions: Loaded environment variables from .env, .env.my-project-id.
i  functions: Loaded environment variables from .env, .env.my-project-id.
!!  functions: Failed to load function definition from source: FirebaseError: Attempted to write param-defined key IS_STAGING to .env files, but it was already defined.
```

**Comment by aalej** [comment] 2022-12-09 16:34
This seems to be a duplicate of [#5314](https://github.com/firebase/firebase-tools/issues/5314). That said, I'll close this issue now. Thanks.

**Closed** 2022-12-09 16:35 UTC
Labels: emulators: functions, bug
