### ISSUE TITLE
 firebase bug

### ISSUE THREAD

**Issue by scopyguy** [firebase/firebase-tools#6371] opened 2023-09-17 15:23 UTC
PS C:\Users\OWNER\Desktop\audiodawah> c:\Users\OWNER\Downloads\Programs\firebase-tools-instant-win_2.exe
This tool has encountered an error.

**Comment by aalej** [comment] 2023-09-18 10:00
I’ll be closing this report as a duplicate of #6370

**Closed by aalej** 2023-09-18 10:00 UTC
Labels: type: bug
