### ISSUE TITLE
firebase login:use doesn't switch accounts

### ISSUE THREAD

**Issue by dnadawa** [firebase/firebase-tools#3775] opened 2021-09-23 14:20 UTC
### Environment info

**firebase-tools: 9.18.0**

**Platform: Windows**

### Test case

Login into firebase CLI using 2 different accounts, but cannot switch between them. Only 1st logged account is always used.

### Steps to reproduce

1. Login to the 1st account: `firebase login`
2. Login to the 2nd account: `firebase login:add`
3. View default account: `firebase login:list`
3. Switch to 2nd account: `firebase login:use <2nd account email address>`
4. View accounts: `firebase login:list` (default account doesn't change)

### Expected behavior

Switch default account to the 2nd account

### Actual behavior

When using `firebase login:use <2nd account email address>` it prints that it successfully switched account. _**(Figure 1)**_
But it is not. When we try to deploy the web using `firebase deploy --only hosting` it prints that the logged account doesn't have permissions. _**(Figure 2)**_

![image](https://user-images.githubusercontent.com/40896729/134523568-d6aca119-34f0-42d7-b808-c2bc739633df.png)
_**(Figure 1)**_

![image](https://user-images.githubusercontent.com/40896729/134524332-940c1288-4497-4571-b176-cf1aeb1e6a8b.png)
_**(Figure 2)**_

**Comment by draperunner** [comment] 2021-09-29 11:49
Duplicate of https://github.com/firebase/firebase-tools/issues/3759

**Comment by bkendall** [comment] 2021-11-30 22:01
Yup, this is a duplicate of #3759. Thanks for raising though - newer versions of the CLI should have this fixed already.

**Comment by bkendall** [comment] 2021-11-30 22:01
Duplicate of #3759

**Closed by bkendall** 2021-11-30 22:01 UTC
