### ISSUE TITLE
Unhandled Promise Rejection breaks firebase login command

### ISSUE THREAD

**Issue by joshuaSmith2021** [firebase/firebase-tools#861] opened 2018-08-08 15:24 UTC
### Version info
v4.0.3 (latest version)

### Platform Information
Linux, ran on a Raspberry Pi

### Steps to reproduce
$ firebase login

### Expected behavior
An OAuth2 popup grants access to my firebase projects.

### Actual behavior

```bash
$ firebase login --debug
[2018-08-08T15:21:48.532Z] ----------------------------------------------------------------------
[2018-08-08T15:21:48.560Z] Command:       /home/pi/.nvm/versions/node/v10.8.0/bin/node /home/pi/.nvm/versions/node/v10.8.0/bin/firebase login --debug
[2018-08-08T15:21:48.564Z] CLI Version:   4.0.3
[2018-08-08T15:21:48.565Z] Platform:      linux
[2018-08-08T15:21:48.566Z] Node Version:  v10.8.0
[2018-08-08T15:21:48.569Z] Time:          Wed Aug 08 2018 08:21:48 GMT-0700 (Pacific Daylight Time)
[2018-08-08T15:21:48.570Z] ----------------------------------------------------------------------

? Allow Firebase to collect anonymous CLI usage and error reporting information? Yes

Visit this URL on any device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=705466498&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...
(node:9871) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/pi/.nvm/versions/node/v10.8.0/lib/node_modules/firebase-tools/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe._handle.close (net.js:599:12)
(node:9871) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9871) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by joshuaSmith2021** [comment] 2018-08-08 21:25
No, that was not the problem. I still get the same error.

```bash
(node:11365) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/pi/.nvm/versions/node/v8.11.1/lib/node_modules/firebase-tools/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:11365) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11365) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by laurenzlong** [comment] 2018-08-09 18:15
this is duplicate of https://github.com/firebase/firebase-tools/issues/809 which is getting fixed in the next release.

**Closed by laurenzlong** 2018-08-09 18:15 UTC
