### ISSUE TITLE
Files bigger than 256kb fail when saving to storage emulator

### ISSUE THREAD

**Issue by Gremash** [firebase/firebase-tools#4927] opened 2022-08-26 18:52 UTC
### [REQUIRED] Environment info

**firebase-tools:** 11.8.0
**firebase NPM package:** firebase@9.9.3

**Platform:** macOS Monterey, MacBook Pro 2021 w/ Apple M1 Pro chip

### [REQUIRED] Test case

Upload a file larger than 256kb using the Javascript SDK to the Firebase Storage emulator

### [REQUIRED] Steps to reproduce

While using the storage emulator and the Firebase JavaScript SDK, upload any file larger than 256kb. The following error occurs: `Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown)`. No other information is provided and no logs are recorded. This error does not happen when using production Firebase Cloud Storage. Files smaller than 256kb do not fail. Also, files larger than 256kb can be manually uploaded via the emulator UI.

Here is the sample code:
```
const storageRef = ref(storage, `temp/${file.name}`);

const uploadTask = uploadBytesResumable(storageRef, file);

uploadTask.on(
      'state_changed',
      (snapshot) => {
        const percent = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
        setUploadPercent(percent);
      },
      (error) => { // ERROR OCCURS HERE
        setDisplayedPrompt(error.message);
        setUploading(false);
      },
    );
```

### [REQUIRED] Expected behavior

Users can uploaded files larger than 256kb while using the emulator.

### [REQUIRED] Actual behavior

Any file larger than 256kb causes the firebase storage emulator to throw an unknown error.

**Comment by mandalornl** [comment] 2022-08-29 10:07
I'm experiencing the same problem.

**Comment by michael-freling** [comment] 2022-09-01 17:11
I got the same error `Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown)` without any server response on the same version using uploadBytesResumable function.
When I downgraded the version of firebase-tools to 11.7, the error didn't happen.

I am not sure my issue exactly the same cause, though. I couldn't fix my code when I reduced the file size less than 256KB.

**Comment by peteshilling** [comment] 2022-09-01 22:33
I've started experiencing the same problem as Gremash the last day or so. Was using firebase-tools 11.2, now using 11.8. I recently updated the gcloud cli, I'm not sure if that could be related.

**Comment by willhackett** [comment] 2022-09-01 23:54
We're seeing this issue too. Looks like a regression of #4407

**Comment by macksal** [comment] 2022-09-02 03:52
Same issue when running tests in my dev and CI environments. It comes up only for larger blobs.

I've also noticed that the corresponding file is created (visible in the storage emulator UI) but it's only about 260KB, and the content type is application/octet-stream rather than the content type of the object that's actually being uploaded.

Reverting to firebase-tools 11.7 is a workaround.

**Comment by braadworst** [comment] 2022-09-14 02:02
Having this issue as well

**Comment by Yuangwang** [comment] 2022-09-26 21:37
Thanks for your patience everyone, I merged in a fix for this https://github.com/firebase/firebase-tools/pull/5018. I'm closing this for now but please be sure to try it out once the new release is out and report back if there are any issues, we can reopen and take another look if needed then.

**Closed by Yuangwang** 2022-09-26 21:37 UTC
Labels: emulators: storage, bug
