### ISSUE TITLE
All predeploy and postdeploy hooks triggered for single target deployment

### ISSUE THREAD

**Issue by duizabojul** [firebase/firebase-tools#1597] opened 2019-08-13 15:03 UTC
### [REQUIRED] Environment info

**firebase-tools:** 7.2.2

**Platform:** macOS, Windows, Ubuntu

### [REQUIRED] Test case

.firebase.json example file
```
"hosting": [
{
    "target": "production",
    "public": "dist",
    "predeploy" : "echo 'production predeploy'",
    "postdeploy" : "echo 'production postdeploy'"
},
{
    "target": "staging",
    "public": "dist",
    "predeploy" : "echo 'staging predeploy'",
    "postdeploy" : "echo 'staging postdeploy'"
},
{
    "target": "development",
    "public": "dist",
    "predeploy" : "echo 'development predeploy'",
    "postdeploy" : "echo 'development postdeploy'"
}]
```

`firebase deploy --only hosting:staging` will produce following output : 
```
production predeploy
staging predeploy
development predeploy
// STAGING DEPLOYMENT
production postdeploy
staging postdeploy
development postdeploy
```
### [REQUIRED] Steps to reproduce

- In firebase project, create multiple hosting sites and create targets accordingly with CLI. 

- Add predeploy and/or postdeploy hooks for each target in firebase.json file. 

- Deploy on firebase with one target : `firebase deploy --only hosting:your-target`. 

### [REQUIRED] Expected behavior

Only target hooks have to be triggered.

### [REQUIRED] Actual behavior

All targets predeploy and postdeploy hooks are triggered.

**Comment by bkendall** [comment] 2019-08-13 17:38
This is a duplicate of #1160 which I am reopening.

**Closed by bkendall** 2019-08-13 17:38 UTC
