### ISSUE TITLE
firebase installation

### ISSUE THREAD

**Issue by scopyguy** [firebase/firebase-tools#6370] opened 2023-09-17 15:05 UTC
PS C:\Users\OWNER\Desktop\audiodawah> c:\Users\OWNER\Downloads\Programs\firebase-tools-instant-win_2.exe
This tool has encountered an error. Please file a bug on Github (https://github.com/firebase/firebase-tools/) and include firepit-log.txt

**Comment by aalej** [comment] 2023-09-18 10:41
Hi, @scopyguy, from what I can gather, you’re encountering an error when using the standalone binary for the Firebase CLI. For us to be able to start our initial investigation, we would need other information. 

Could you file a new issue and specify the details using the provided template? This way, it would be more efficient in identifying the cause of the error. That being said, I'll be closing this for now.

**Closed by aalej** 2023-09-18 10:41 UTC
Labels: type: bug
