### ISSUE TITLE
firebase emulators: "Failed to replace env in config: ${xxx}"

### ISSUE THREAD

**Issue by rohan-sethi** [firebase/firebase-tools#1504] opened 2019-07-15 13:59 UTC
###   info
Firebase emulators does not run jest test cases , complains about replacing evn variable 
###  Environment info

**firebase-tools:** 6.9.2

**Platform:** Ubuntu 18.04

### Console Logs
      `firebase emulators:exec "yarn test"
      i  Starting emulators: ["firestore"]
      i  firestore: Logging to firestore-debug.log
      ✔  firestore: Emulator started at http://localhost:8080
      i  firestore: For testing set             
      FIREBASE_FIRESTORE_EMULATOR_ADDRESS=localhost:8080
      i  Running script: yarn test
      yarn run v1.15.2
 ###     error An unexpected error occurred: "Failed to replace env in config: ${FURY_AUTH}".
      info If you think this is a bug, please open a bug report with the information provided in       
      "/home/vinove/y/yonder/yarn-error.log".
      info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
      ⚠  Script exited unsuccessfully (code 1)
      i  Shutting down emulators.
      i  Stopping firestore emulator`

### Yarn Logs
      `Error: Failed to replace env in config: ${FURY_AUTH}
      at /usr/lib/node_modules/yarn/lib/cli.js:98047:13
      at String.replace (<anonymous>)
      at envReplace (/usr/lib/node_modules/yarn/lib/cli.js:98042:16)
      at Function.normalizeConfig (/usr/lib/node_modules/yarn/lib/cli.js:31793:69)
      at NpmRegistry.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:31823:34)
      at Generator.next (<anonymous>)
      at step (/usr/lib/node_modules/yarn/lib/cli.js:304:30)
      at /usr/lib/node_modules/yarn/lib/cli.js:315:13
      at <anonymous>`

### Command
      `firebase emulators:exec "yarn test"

Have exported Auth variable for `.npmrc` in `.bashrc` / `.profile` .  Have tried deleting the `.npmrc` but the error persist.

**Comment by abeisgoat** [comment] 2019-07-15 15:52
Thanks for the report. We'll take a look.

**Comment by abeisgoat** [comment] 2020-06-02 19:55
Dupe of #1868 let's handle it over there

**Closed by abeisgoat** 2020-06-02 19:55 UTC
Labels: emulator-suite, emulators: functions
