### ISSUE TITLE
functions.pubsub.schedule is not a function

### ISSUE THREAD

**Issue by RaheutRahwana** [firebase/firebase-tools#7878] opened 2024-10-27 10:16 UTC
### [REQUIRED] Environment info

13.23.0

**firebase-tools:**

Debian (Dev Containers)

**Platform:**

### [REQUIRED] Test case

functions/index.js:
```
"use strict";

const fireFunctions = require("firebase-functions");

exports.deleteUser = fireFunctions.https
.onCall((data, context) => console.log({ data, context }));

exports.birthDay = fireFunctions.pubsub
.schedule("0 9 * * *")
.timeZone("Asia/Jakarta")
.onRun((context) => console.log(context));
```

### [REQUIRED] Steps to reproduce

Install Docker Engine.
Install VS Code.
Install the Dev Containers extension.
Open the folder (mine is named "firebase").
Add a .devcontainer/devcontainer.json file with the following content:
```
{
    "name": "Firebase",
    "image": "mcr.microsoft.com/devcontainers/javascript-node:1-18-bookworm"
}
```
Run the `Dev Containers: Reopen in Container` command from the Command Palette (F1) or the quick actions status bar item.
Wait for the process to complete.
Open the terminal.
Install firebase-tools: `npm install -g firebase-tools`.
Log in to Firebase: `firebase login`.
Create a Firebase project directory and navigate into it.
Initialize the project: `firebase init`. I used Functions, Firestore, Hosting, and Storage, but I think functions alone is enough in this case?
Populate the functions/index.js file with a minimal, complete, and verifiable example above.
Run the project with: firebase serve -o 0.0.0.0.

### [REQUIRED] Expected behavior

`firebase serve` runs as usual, just like when I omit the `fireFunctions.pubsub.schedule` part.

### [REQUIRED] Actual behavior

```
TypeError: fireFunctions.pubsub.schedule is not a function
    at Object.<anonymous> (/workspaces/firebase/my_project/functions/index.js:10:2)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at loadModule (/workspaces/firebase/my_project/functions/node_modules/firebase-functions/lib/runtime/loader.js:40:16)
    at loadStack (/workspaces/firebase/my_project/functions/node_modules/firebase-functions/lib/runtime/loader.js:157:23)
    at /workspaces/firebase/my_project/functions/node_modules/firebase-functions/lib/bin/firebase-functions.js:56:56

⬢  functions: Failed to load function definition from source: FirebaseError: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error
```

**Comment by aalej** [comment] 2024-10-28 10:48
Hey @RaheutRahwana, thanks for the detailed report. If you're using `firebase-functions` v6.x.x,  I think the issue here might be related to how `firebase-functions` is being imported. Starting `firebase-functions` [v6.0.0](https://github.com/firebase/firebase-functions/releases/tag/v6.0.0), the default entry point of the package was changed to v2 instead of v1.

Since it looks like you're using a v1 function, could you try updating your code to explicitly import "firebase-functions/v1"? The updated code would look something like:
```js
"use strict";

const fireFunctions = require("firebase-functions/v1"); // Imports v1 functions

exports.deleteUser = fireFunctions.https
    .onCall((data, context) => console.log({ data, context }));

exports.birthDay = fireFunctions.pubsub
    .schedule("0 9 * * *")
    .timeZone("Asia/Jakarta")
    .onRun((context) => console.log(context));
```

If you're still encountering an error, could you let me know which version of `firebase-functions` you're using?

**Comment by RaheutRahwana** [comment] 2024-10-29 15:53
Hi @aalej, I just tried adding "/v1" to the import, and it fixed the problem! Thanks so much for your help.

**Comment by aalej** [comment] 2024-10-30 12:55
Awesome! Glad to hear the issue is fixed. I'll go ahead and close this, if you encounter any issues in the future, feel free to reach out to us again. Thanks!

**Closed by aalej** 2024-10-30 12:55 UTC
Labels: type: bug, Needs: Attention, emulators: functions
