### ISSUE TITLE
`functions.ignore` rule negation (!) doesn't work anymore

### ISSUE THREAD

**Issue by Bartinger** [firebase/firebase-tools#751] opened 2018-04-20 13:23 UTC
### Version info

3.18.4

### Platform Information

Linux, Ubuntu 16.04.4

### Steps to reproduce

```json
{
  "functions": {
    "source": "./",
    "ignore": [
      "*",
      "!config/**",
      "!dist/**",
      "!node_modules/**",
      "!index.js",
      "!package.json"
    ]
  }
}
```

### Expected behavior

Up until the tools version ```3.18.2``` the above configuration used to work as expected. It created a ZIP file only including those directories (config, dist, node_modules) and files (index.js, package.json).

### Actual behavior

I tested it with every version starting from ```3.17.7``` with the following results:

- ```3.17.7``` works as expected
- ```3.18.0``` cli crashes
- ```3.18.1``` works as expected
- ```3.18.2``` includes all files, https://github.com/firebase/firebase-tools/issues/734
- ```3.18.3``` results in an empty* zip 
- ```3.18.4``` results in an empty* zip

\* by empty I mean the firebase-tools create a zip file only including the ```.runtimeconfig.json```

**Comment by laurenzlong** [comment] 2018-04-27 00:14
@Bartinger I'm curious why `"*" ` is in your list of ignores. Wouldn't that match every file? Therefore it would be expected behavior that you have an empty zip? If it previously did not work that way, then that would have been a bug, which was fixed to the "correct" behavior in 3.18.3. 

I added a unit test to ensure that negation does work: https://github.com/firebase/firebase-tools/pull/755

**Comment by Bartinger** [comment] 2018-05-01 14:27
Hi @laurenzlong, sorry for the late reply. I exclude all files by default and only deploy those files which are actually required by the functions to keep the zip size as small as possible and not accidentally upload some credentials (service-account.json, .env, etc...)

I looked over #755 
Please correct me if I'm wrong but as far as I understood it, `readdirRecursive` should return a list of included files. However the unit test you added checks for the returned file to be the ignored file (`visible`). I also found that when adding a second negation rule i.e. `!.hidden` the result is an empty array.

### Result for each ignore rule:
**ignore: [],**
```
[
    "/tmp/fa00834f7f6ba06c044e/.hidden",
    "/tmp/fa00834f7f6ba06c044e/node_modules/subfile",
    "/tmp/fa00834f7f6ba06c044e/subdir/nesteddir/nestedfile",
    "/tmp/fa00834f7f6ba06c044e/subdir/node_modules/nestednodemodules",
    "/tmp/fa00834f7f6ba06c044e/subdir/subfile",
    "/tmp/fa00834f7f6ba06c044e/visible"
]
```

**ignore: ["!visible"],**
```
[
     "/tmp/7dfa98b8372fa96f273e/visible"
]
```

**ignore: ["!visible", "!.hidden"],**
```
[]
```

**Comment by mbleigh** [comment] 2018-05-01 14:59
This is how I'd expect it to behave -- it is *ignoring* every file that
*isn't* visible, then that *isn't* hidden. Since no file is both of those,
that's a null set. Ignores should be a sequence of expressions each applied
as a filter, which appears to be happening correctly here.

**Comment by Bartinger** [comment] 2018-05-01 15:44
@mbleigh Ok, I get what you mean.

But then am I correct that something like this:
```ignore: ["subdir/*", "!subdir/subfile"],```
Ignoring all files in `subdir` except `subfile` isn't possible, which is possible with gitignore with the same syntax.

**Comment by tinaliang** [comment] 2019-01-09 01:00
Expected behavior - closing this issue.

**Closed by tinaliang** 2019-01-09 01:00 UTC
