### ISSUE TITLE
Cannot install the CLI standalone binary in GitHub Actions

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-tools#1919] opened 2020-01-15 01:07 UTC
`curl -sL https://firebase.tools | bash` does not work in GitHub Actions. Adding this step to a workflow causes the workflow to get stuck without any error messages. I have also tried running this in multiple steps as follows:

```
curl -o cli.sh -L https://firebase.tools
chmod +x cli.sh
./cli.sh
```

This also gets stuck in the last step. It seems the shell script has some bug which prevents causes it to get stuck in some environments.

**Comment by abeisgoat** [comment] 2020-01-16 19:27
This is a dupe of #1874 not sure what's going on, but we'll track it over there.

**Closed by abeisgoat** 2020-01-16 19:27 UTC
