### ISSUE TITLE
Cloud Firestore  not running and function killed

### ISSUE THREAD

**Issue by derekzyl** [firebase/firebase-tools#2352] opened 2020-06-10 19:08 UTC
```
PS C:\Users\user\Desktop\crypto project\crypto-back-end\functions> firebase serve

=== Serving from 'C:\Users\user\Desktop\crypto project\crypto-back-end'...

!  Your requested "node" version "8" doesn't match your global version "13"
i  functions: Watching "C:\Users\user\Desktop\crypto project\crypto-back-end\functions" for Cloud Functions...
!  functions: The Cloud Firestore emulator is not running, so calls to Firestore will affect production.
!  functions: Cannot find module './tsconfig.json'
Require stack:
- C:\Users\user\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js
!  Your function was killed because it raised an unhandled error.
```

I've reinstalled all Firebase tools updated Firebase functions and admin. Installled typescript  locally  and in the project and as a dev dependency all hasn't worked

**Comment by samtstern** [comment] 2020-06-11 18:36
This is a duplicate of #2354 and was fixed here:
https://github.com/firebase/firebase-tools/pull/2354

The fix will be released in the next version of the CLI.  It's like you're importing something in your Functions code which does not exist, check out all your dependencies!

**Closed by samtstern** 2020-06-11 18:36 UTC

**Comment by pklitscher** [comment] 2020-06-11 22:28
@samtstern Thanks for fixing this so quick. 

Just in case the issue is more than it seems I thought I'd share the behaviour I am seeing

**index.js**
```
exports.users = require('./scripts/users');
```

**scripts/users.js** (function commented out for testing)

```
const functions = require('firebase-functions');
const { auth } = require('../init/admin');

// exports.syncAdminUser = functions.database.ref('/system/admin/{uid}')
//   .onWrite(async (fbChange, fbContext) => {
//     let uid = fbContext.params.uid
//     let state = fbChange.after.exists()
    
//     return auth.setCustomUserClaims(uid, { admin: state })
//   })


```

**init/admin.js**
```
const admin = require('firebase-admin');

admin.initializeApp();

exports.db = admin.database();
exports.messaging = admin.messaging()
exports.auth = admin.auth()
exports.storage = admin.storage()
```

This will throw the tsconfig error. 

If I comment out ```// const { auth } = require('../init/admin');``` emulators will run.

This code runs in production error free. All directories exist and refs are correct. Will this be resolved in the fix or is it something more?

Folder structure 
```
functions
  |-- init
  |    |-- admin.js
  |
  |-- scripts
  |    |-- users.js
  |
  |-- index.js
```
