### ISSUE TITLE
Storage emulator starts even if excluded in firebase.json

### ISSUE THREAD

**Issue by microcou** [firebase/firebase-tools#3599] opened 2021-07-23 13:53 UTC
### [REQUIRED] Environment info

**firebase-tools:** 9.16.0

**Platform:** Ubuntu

### [REQUIRED] Test case

- Use the CLI to initialize a firebase project
- initialize the emulators, emulate only hosting, and functions, not storage
- add Storage rules in firebase.json but NOT within emulators settings (note that there is a known issue related: [#3390](https://github.com/firebase/firebase-tools/issues/3390))

### [REQUIRED] Steps to reproduce

firebase emulators:start

### [REQUIRED] Expected behavior

All services start but not storage (as if the emulators were launched with firebase emulators:start --only hosting,functions)

### [REQUIRED] Actual behavior

Storage service also starts in emulators

**Comment by bkendall** [comment] 2021-07-23 22:22
I initialized Emulators, Hosting, and Functions, taking all the default options, including the Functions and Hosting emulators. Then after doing emulator:start, only Hosting and Functions came up.

I'm unable to replicate this. Could you provide the output of `firebase emulators:start --debug` or a clearer replication procedure?

**Comment by microcou** [comment] 2021-07-25 12:38
Thank you for your interest.
I re-ran the procedure and actually it is the presence of Storage rules specified in the firebase.json that trigger the unrequested launching of Storage emulators. 
I have edited the Test case accordingly.

**Comment by abeisgoat** [comment] 2021-07-26 18:45
Can you try this with `database` or `firestore` emulators, [this line](https://github.com/firebase/firebase-tools/blob/d460ad295626ffb0c2c8b6697c2c616e358c6a7d/src/emulator/controller.ts#L183) appears to say that we enable an emulator when either the top level `[emulateName]` key exists in `firebase.json` or `emulators.[emulatorName]` which would make me think this isn't storage specific

**Comment by microcou** [comment] 2021-07-26 20:44
I tried with the Firestore emulator and it behaves as you describe, which matches the line that you mention. So no, it is not specific to storage and it works as intended. For me this issue can be closed, I'll keep on using the --only CLI option. Thank you for your attention and for showing the line of code, that was interesting!

**Comment by abeisgoat** [comment] 2021-07-29 19:11
No worries, it's still a bug / unexpected behavior so we'll leave this open and get it sorted.

**Comment by oveddan** [comment] 2021-09-05 17:36
This issue happens for me - It only started happening recently since upgrading firebase tools to the latest verison.  It even starts up if I set the emulator to disabled in my firebase.json:

```json
{
  "database": [{
    "target": "main",
    "rules": "firebase/database.rules.json"
  }],
  "firestore": {
    "rules": "firebase/firestore.rules",
    "indexes": "firebase/firestore.indexes.json"
  },
  "storage": {
    "rules": "firebase/storage.rules"
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ],
    "runtime": "nodejs12"
  },
  "emulators": {
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 1256
    },
    "storage": {
      "enabled": false
    },
    "database": {
      "port": 9000
    },
    "pubsub": {
      "port": "8085"
    }
  }
}```

When I start the emulator, this is the final output:

─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://localhost:4000                │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Functions │ localhost:5001 │ http://localhost:4000/functions │
├───────────┼────────────────┼─────────────────────────────────┤
│ Firestore │ localhost:1256 │ http://localhost:4000/firestore │
├───────────┼────────────────┼─────────────────────────────────┤
│ Database  │ localhost:9000 │ http://localhost:4000/database  │
├───────────┼────────────────┼─────────────────────────────────┤
│ Pub/Sub   │ localhost:8085 │ n/a                             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Storage   │ localhost:9199 │ http://localhost:4000/storage   │
└───────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: 4500

**Comment by tonyjhuang** [comment] 2022-07-29 05:00
I'm going to close this as this seems to be WAI

**Closed by tonyjhuang** 2022-07-29 05:00 UTC
Labels: Needs: Attention, emulators: storage
