### ISSUE TITLE
Error: Cannot set CPU on the functions api because they are GCF gen 1

### ISSUE THREAD

**Issue by nomagick** [firebase/firebase-tools#6048] opened 2023-06-28 06:46 UTC
### [REQUIRED] Environment info

**firebase-tools: 12.4.1**

**Platform: macOS**

While running `firebase deploy functions:xxx`:

Error: Cannot set CPU on the functions api because they are GCF gen 1

While nobody set anything about CPU anywhere in my code.

**Comment by nomagick** [comment] 2023-06-28 07:11
Even when I try to deploy an v2 function it always complains `Error: Cannot set CPU on the functions api because they are GCF gen 1`

**Comment by aalej** [comment] 2023-06-28 15:33
Hi @nomagick, thanks for reaching out. I’m trying to reproduce the issue you’re encountering, but I am currently unable to replicate the behavior. Could you try running `firebase deploy functions:xxx –debug`? Passing the `--debug` flag provides more details on what could’ve caused the error. Please remove any PII (personal identifiable information) if needed.

Let me know I missed anything; the steps I took to reproduce the issue are:
1. Run `firebase init functions --project <project_id>`
2. Select Javascript
3. Uncomment the helloWorld code template in `index.js`
4. Run `firebase deploy --only functions:helloWorld`

Additionally, to help us with the investigation, could you provide the following information:

- Version of `firebase-functions` sdk you’re using
- Does the error consistently occur on every deploy?
- Are you using TypeScript or JavaScript for composing functions?
- Is the function you’re trying to update a 2nd or 1st gen function?
- If possible, share code snippets or an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)  so that we can try to replicate the issue

Thanks!

**Comment by nomagick** [comment] 2023-06-29 05:39
Hi @aalej. 

My codebase is quite complex and employs git submodules and symbolic links of directories.
The `firebase-functions` version is `4.4.0`.

The project is written in TypeScript but compiled into javascript. A predeploy hook is used to compile the code. 
The project contains both v1 functions and v2 functions. 
The deployment attempt included v1 and v2 functions; the error happened individually for all v1/v2 functions.

The error was observed from several branches of our git codebase, including `main`, which was previously without any issue. 
The error was consistent across multiple `firebase-tools` versions and multiple computers.

Somehow one particular development branch that has recently deployed v2 functions does not have this issue.
After merging this particular working branch into other branches, the issue magically went away.

So now everything seems to work.

I will try the `--debug` option if I encounter this issue again.
Thanks.

**Comment by aalej** [comment] 2023-06-29 12:22
Thanks for the additional information @nomagick. It’s good to know that the issue is now resolved. It may also be worth noting that a new version of firebase-tools was released [v12.4.2](https://github.com/firebase/firebase-tools/releases/tag/v12.4.2). I would recommend upgrading to the latest version to see if you would still encounter the issue.

That said, I’ll go ahead and close this issue for now. Let us know if you encounter the issue again while deploying your functions.

**Closed by aalej** 2023-06-29 12:22 UTC
Labels: type: bug, api: functions, Needs: Attention

**Comment by MrBns** [comment] 2023-10-29 22:09
> The error occurred when I was attempting to downgrade a function from gen2 to gen1 in order to enable the use of failurePolicy on Firebase Functions Pub/Sub trigger. To resolve it, I had to delete the function and then redeploy it to make it functional

yeah. I also tried in this way.  I have deleted the functions in console then reployed it.

**Comment by aminekha** [comment] 2023-11-16 09:49
For me, using: `const { onRequest } = require("firebase-functions/v2/https");`
instead of: `const functions = require('firebase-functions');` solved the problem

**Comment by Stillerman** [comment] 2024-10-29 20:27
fixed by making function name all lowercase

**Comment by clarkbox** [comment] 2024-12-03 18:06
i hit this bug by attempting to overwrite a v2 with a v1 function. we reverted some code, that included a refactor to v2. on redeploy, we get this cant set cpu on functions api error. the deploy task should respond with an error "cant downgrade from v2 to v1 without first deleting", as you get when attempting to upgrade v1 to v2 in place..

**Comment by tsvillain** [comment] 2025-04-16 04:50
Using a newer version of node engines worked for me.
Before:
```
  "engines": {
    "node": "18"
  }
``` 

Now:
```
  "engines": {
    "node": "22"
  }
```

**Comment by mrahkdev** [comment] 2026-04-10 08:00
deleting old functions and redeploying works for me
