### ISSUE TITLE
Firebase Emulator: Collection does not appear in emulator, but the data exists and appears in Firebase Console

### ISSUE THREAD

**Issue by mozeryansky** [firebase/firebase-tools#2455] opened 2020-07-14 07:17 UTC
My collection does not appear if the document in the collection has no fields set. I have a subcollection with data and I can't see anything, it appears empty. However, on the Firebase Console I am able to see the data.

I have a sample script which I ran against the emulator and against the remote firebase. Both added the exact same data and produced the exact same response. But the emulator shows there is no data.

### [REQUIRED] Environment info

**firebase-tools:** 8.5.0

**Platform:** macOS

### [REQUIRED] Test case

```
admin.initializeApp()
let db = admin.firestore();
db.settings({
  host: "localhost:8080",
  ssl: false
});

const userID = "user_1"
const itemID = "item_1"

const createUserRef = (userID) => {
  return db.collection("users").doc(userID);
};

const createItemRef = (userID, itemID) => {
  return createUserRef(userID).collection("items").doc(itemID);
};

const doStuff = async () => {
  const userRef = createUserRef(userID)

  const itemRef = createItemRef(userID, itemID)
  await itemRef.set({
    "value": true
  })

  const item = await itemRef.get()
  console.log(item.data())
}

doStuff()
```

### [REQUIRED] Steps to reproduce

1. Start emulator, clear all data
2. Run sample above: add data at "/users/user_1/item/item_1" = {"value:": true}
3. Go to emulator and refresh
No data appears, but as the script shows, the data exists

### [REQUIRED] Expected behavior

Show the empty collection like the Firebase Console does

### [REQUIRED] Actual behavior

Firebase Emulator shows nothing

**Comment by samtstern** [comment] 2020-07-14 07:19
@mozeryansky this is the same as this issue:
https://github.com/firebase/firebase-tools-ui/issues/273

I'm going to close this one since we're tracking it over there.  Thanks for reporting this, we're working on it!

**Closed by samtstern** 2020-07-14 07:19 UTC

**Comment by mozeryansky** [comment] 2020-07-14 07:23
Aw! I spent so much time making the sample! I even searched for it. Thanks!

**Comment by samtstern** [comment] 2020-07-14 07:26
@mozeryansky we do really appreciate the minimal and reproducible example!  That's why I was able to diagnose this as a duplicate so quickly :-)
