### ISSUE TITLE
Emulator's cloud storage function 'onFinalize' is triggered even on failed upload

### ISSUE THREAD

**Issue by bosycom** [firebase/firebase-tools#3772] opened 2021-09-22 16:38 UTC
**firebase-tools:** 9.18.0

**Platform:** Windows

### Test case

Uploading a file will trigger onFinalize in cloud storage function even if upload failed. Only tested with local emulator, not in prod.

#### 1: Create a cloud storage function:
```javascript
// functions/src/resize.ts
export const resize = functions.storage.object().onFinalize(async object => {
  // content does not matter for this bug     
  return false;
});
```
Also ```export {resize} from "./resize";``` from your functions/src/index.ts (or js)

#### 3: Upload a test file from web sdk

```javascript
    const upload = async () => {
        const storageRef = ref(storage, 'test/cover.webp');

        const bytes = new Uint8Array([0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x2c, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x21]);
        uploadBytes(storageRef, bytes, {contentType: "image/webp"}).then((snapshot) => {
            console.log('Uploaded an array!');
        });
    }
```

Make sure there is no storage rule allowing this upload.

This will trigger the following error as expected:

```
FirebaseError: Firebase Storage: User does not have permission to access 'test/cover.webp'. (storage/unauthorized)
{"error":{"code":403,"message":"Permission denied. No WRITE permission."}}
```

### Expected behavior

Expected that onFinalize is not triggered.

### Actual behavior

Actual behavior is that onFinalize is triggered despite the failed upload.
According to [official doc](https://firebase.google.com/docs/functions/gcp-storage-events#trigger-function-on-storage-changes) that must not happen:

"onFinalize Sent when a new object (or a new generation of an existing object) is successfully created in the bucket. This includes copying or rewriting an existing object. A failed upload does not trigger this event." 

### Impact
The fact that onFinalize is triggered on a failed upload causes the function to crash, because it cannot process the file that was supposed to exist in the storage.

**Comment by tonyjhuang** [comment] 2022-07-29 04:56
Filed internal bug to track, b/240635178

**Comment by Yuangwang** [comment] 2022-08-01 15:22
I'm closing this for now since I've been unable to reproduce this now. I'm hoping it might have been fixed in another pr. Please download the latest version of firebase-tools and let me know if this is still an issue.

**Closed by Yuangwang** 2022-08-01 15:22 UTC
Labels: emulators: storage

**Comment by Mod5ied** [comment] 2024-05-10 14:51
Oga reopen this bug
