### ISSUE TITLE
firebase-tools-win.exe failed to start

### ISSUE THREAD

**Issue by alrowaihi** [firebase/firebase-tools#1888] opened 2020-01-01 09:23 UTC
### [REQUIRED] Environment info

**firebase-tools:**  firebase-tools-win.exe  10.17.0

**Platform:** Win 10

### [REQUIRED] Test case

Trying to launch the file

### [REQUIRED] Steps to reproduce

I downloaded both files 
firebase-tools-instant-win.exe
firebase-tools-win.exe
and tried to launch them with and without run as administrator 
also , I right clicked and chose properties , then checked (unblock) 

I also tried to force running the app by writing in cmd 
cmd /c "set __COMPAT_LAYER=RUNASINVOKER && start "" "firebase-tools-instant-win.exe

### [REQUIRED] Expected behavior

it should launch and show the terminal command line screen
### [REQUIRED] Actual behavior
when double clicking , it showed a warning of unknown publisher , when I clicked allow , a terminal screen showed up for 1 second and disappeared ,

**Comment by alrowaihi** [comment] 2020-01-01 19:01
if there is an answer for this issue , that's good for incoming users , 

however , I solved the issue by installing first node.js , then ran this code in cmd in a directory from my choice ( npm install -g firebase-tools ) 

this tutorial is good for beginners , and I hope it's not against rules here :
https://www.youtube.com/watch?v=DYfP-UIKxH0&list=PLl-K7zZEsYLkPZHe41m4jfAxUi0JjLgSM

**Comment by abeisgoat** [comment] 2020-01-03 19:59
I would expect the window to flash and close for `firebase-tools-win.exe` can you confirm the same behavior is happening for the `-instant` build?

**Comment by abeisgoat** [comment] 2020-01-03 20:00
I think this is a dupe of #1826, let's handle it there.

**Closed by abeisgoat** 2020-01-03 20:00 UTC
Labels: firepit
