### ISSUE TITLE
Storage useEmulator setting is being ignored using client side JS SDK

### ISSUE THREAD

**Issue by alexstanbury** [firebase/firebase-tools#3527] opened 2021-06-23 15:39 UTC
### [REQUIRED] Environment info

firebase --version 9.14.0

macOS

### [REQUIRED] Test case

Not feasible

### [REQUIRED] Steps to reproduce

Initialise app using existing staging app config
Set `firebase.storage().useEmulator('localhost', 9199)`
Attempt to upload a file to `gs://default-bucket`
Get 403 permission denied error

Next...

Initialise app using existing staging app config
Set `firebase.storage().useEmulator('localhost', 9199)`
Attempt to upload a file to a bucket URL that exists on firebase staging environment
File uploads correctly

### [REQUIRED] Expected behavior

The file should be uploaded to the storage emulator.

### [REQUIRED] Actual behavior

It still seems to be using my firebase hosted staging storage bucket.

**Comment by alexstanbury** [comment] 2021-06-23 15:50
Here's what is output in the console:

```POST https://firebasestorage.googleapis.com/v0/b/default-bucket/o?name=portal-client-portal-client-portal-portal%2Fmy-filename.xlsx 400
{...}
index.js:1 FirebaseError: Firebase Storage: An unknown error occurred, please check the error payload for server response. (storage/unknown)
{
  "error": {
    "code": 400,
    "message": "Permission denied. Could not access bucket default-bucket. Please enable Firebase Storage for your bucket by visiting the Storage tab in the Firebase Console and ensure that you have sufficient permission to properly provision resources.",
    "status": "ACCESS_BUCKET"
  }
}```

**Comment by samtstern** [comment] 2021-06-23 16:09
@alexstanbury could you show a little more of your JS code? Mainly I'd like to see where you initialize Firebase, where you call `useEmulator` and then where you try to access to Storage.

**Comment by alexstanbury** [comment] 2021-06-23 16:28
Sure, I've condensed and simplified the production code but logic remains the same. (I'm using redux-firebase which is where getFirebase() comes from)

```import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/firestore';
import 'firebase/storage';
import 'firebase/functions';

let firebaseConfig = {
  apiKey: 'mykeyhere',
  authDomain: 'myapp.firebaseapp.com',
  projectId: 'myapp',
  storageBucket: 'myapp.appspot.com',
  messagingSenderId: '1234567890',
  appId: 'myappidhere',
  measurementId: 'BLAHBLAH,
};

if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig);
}

const db = firebase.firestore();
const functions = firebase.functions();

if (window.location.hostname === 'localhost') {
  firebase.storage().useEmulator('localhost', 9199);
  db.useEmulator('localhost', 8080);
  firebase.auth().useEmulator('http://localhost:9099/');
  functions.useEmulator('localhost', 5001);
} 

```

```

const getBlobFile = async (blobUrl) => {
  const response = await fetch(blobUrl);
  return response.blob();
};

const storage = getFirebase().app().storage('gs://default-bucket');
const path = `/id/name`;
const ref = storage.ref(path);
const fileUrl = 'my/long/file/blob/url;
const file = await getBlobFile(fileUrl);
await ref.put(file);
const downloadURL = await ref.getDownloadURL();

```

**Comment by samtstern** [comment] 2021-06-23 16:31
@alexstanbury thanks! Can you try replacing `firebase.storage().useEmulator('localhost', 9199)` with:

```js
const storage = getFirebase().app().storage('gs://default-bucket').useEmulator('localhost', 9199)
```

The `useEmulator()` setting is per instance of Storage and I _think_ you're using two separate instances.

**Comment by alexstanbury** [comment] 2021-06-23 16:38
Thanks for the quick reply, that works! I see what's happening now, I guess I need to create a wrapper function that will take care of setting useEmulator on each different bucket before returning the storage instance I want to upload to, I have 7...

**Comment by samtstern** [comment] 2021-06-23 16:39
@alexstanbury glad it works! I am going to take this bug and add it to a list of feedback for us to consider changing the behavior. We _thought_ that doing per-instance settings would be more friendly to power users but you're not the first one to fall into this trap.

Closing this bug for now, since everything is working as intended from a Firebase perspective.

**Closed by samtstern** 2021-06-23 16:39 UTC
Labels: Needs: Attention, emulator-suite, emulators: storage
