### ISSUE TITLE
Error: Server Error. connect ETIMEDOUT 172.217.27.138:443

### ISSUE THREAD

**Issue by Symbolk** [firebase/firebase-tools#414] opened 2017-07-31 03:27 UTC
### Version info

Firebase cli 3.9.1

### Steps to reproduce

Currently I am serving under Shadosocks proxy, I can successfully login and serve "by accident"(or by luck,), most time when I run "firebase list" it turns out to be annoying "Authentication Error", which is a long lasting open issue #155 . (I really hope the maintainer of firebase figure it out, or lots of us have to abandon firebase)

When I run "firebase login" under PAC Mode of Shadowsocks and then switch to Global Mode,"firebase list" this time, it successfully lists my projects:
```sh
D:\workspace\CrowdJigsawPuzzle>firebase list
┌─────────────────────┬───────────────────────┬─────────────┐
│ Name                │ Project ID / Instance │ Permissions │
├─────────────────────┼───────────────────────┼─────────────┤
│ JigsawDev (current) │ jigsawdev-b917c       │ Owner       │
├─────────────────────┼───────────────────────┼─────────────┤
```
However, when I run "firebase serve", it says that:

```
D:\workspace\CrowdJigsawPuzzle>firebase serve
=== Serving from 'D:\workspace\CrowdJigsawPuzzle'...

Error: Server Error. connect ETIMEDOUT 172.217.27.138:443
```

### Expected behavior

The project should be served successfully since "firebase list" works.

### Actual behavior

After trying a few times, it works but I still want to know why.
```
D:\workspace\CrowdJigsawPuzzle>firebase serve

=== Serving from 'D:\workspace\CrowdJigsawPuzzle'...

i  hosting: Serving hosting files from: ./
+  hosting: Local server: http://localhost:5000

```

**Comment by mbleigh** [comment] 2017-08-16 23:24
Duplicate of #155

**Closed by mbleigh** 2017-08-16 23:24 UTC
