### ISSUE TITLE
[Firebase Functions][Node 10+] Amount of RAM is not appropriate when changing ram to 2+ GB

### ISSUE THREAD

**Issue by clementdevos** [firebase/firebase-tools#3876] opened 2021-10-29 14:23 UTC
Hello !

We've encountered a quirk with the database/HTTPS firebase functions.
When deploying with more than 2GB of RAM, node environment variable max_old_space_size is not set to an appropriate value, leading to OOM errors like
```
 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node] 
```

### [REQUIRED] Version info

**node:** 14

**firebase-functions:** 3.16.0

**firebase-tools:** 9.21.0

**firebase-admin:** ^9.7.0

### [REQUIRED] Steps to reproduce

Deploy any https function with

```
functions
.runWith({ memory: '2GB', timeoutSeconds: 540 })
.region('europe-west1') //optional region
    .https.onRequest
```

### [REQUIRED] Expected behavior

Functions should be deployed with the appropriate NODE_OPTIONS = --max_old_space_size=4096  environment variable

    ### [REQUIRED] Actual behavior

* The NODE_OPTIONS variable is not set and defaults to roughly 1.5GB of RAM
* `firebase deploy` command has no options to set the variable in the CLI, we need to set it in the Google Cloud Platform GUI
*  The option is reseted with every deployment.

There is a stackoverflow question about this issue https://stackoverflow.com/questions/67158368/deploy-firebase-functions-on-node-14-runtime-with-increased-memory

Do you think a fix is possible?

Cheers !

### Were you able to successfully deploy your functions?

Yes

**Comment by taeold** [comment] 2021-11-08 18:46
Dup of https://github.com/firebase/firebase-tools/issues/3716

**Comment by taeold** [comment] 2021-11-08 19:34
@clementdevos This is a important nudge - I appreciate you kicking this issue at us again!

**Comment by bkendall** [comment] 2021-11-08 21:13
Duplicate of #3716

**Closed** 2021-11-08 21:12 UTC
