### ISSUE TITLE
Include auto-generated type definitions in the package

### ISSUE THREAD

**Issue by MysteryBlokHed** [firebase/firebase-tools#5585] opened 2023-03-10 14:42 UTC
Someone on the DefinitelyTyped repository requested types for this package (DefinitelyTyped/DefinitelyTyped#64485), but I noticed it’s already written in TypeScript.
Would it be possible to include TypeScript’s auto-generated declarations in the published npm package?

**Comment by bkendall** [comment] 2023-03-10 15:16
Duplicate #2378

**Comment by bkendall** [comment] 2023-03-10 15:16
Duplicate of #2378

**Closed by bkendall** 2023-03-10 15:16 UTC
Labels: type: feature request
