### ISSUE TITLE
[Hosting] Warnings when deploying to live and preview channels via GitHub pull requests

### ISSUE THREAD

**Issue by testak-m** [firebase/firebase-tools#6979] opened 2024-04-09 18:57 UTC
### [REQUIRED] Environment info

**firebase-tools:** v13.7.1

**Platform:** macOS

### [REQUIRED] Test case

Deploy to live & preview channels via GitHub pull requests

### [REQUIRED] Steps to reproduce

This one.
https://firebase.google.com/docs/hosting/github-integration

### [REQUIRED] Expected behavior

No errors or warnings are output.

### [REQUIRED] Actual behavior

A warning will be output.

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: FirebaseExtended/action-hosting-deploy@v0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by aalej** [comment] 2024-04-10 10:32
Hey @testak-m, thanks for reaching out. From what I can gather, this issue looks like a duplicate of https://github.com/FirebaseExtended/action-hosting-deploy/issues/341. To better track this, please leave a comment or a thumbs up on the original issue. I’ll be closing this as a duplicate.

**Closed by aalej** 2024-04-10 10:32 UTC
Labels: type: bug, api: hosting

**Comment by testak-m** [comment] 2024-04-10 16:49
@aalej 
sorry.
I know and asked the firebase-tools repository for help.
The reason is that a pull request has already been submitted and reviewed, but it has been left unmerged for a long time.
https://github.com/FirebaseExtended/action-hosting-deploy/pull/344

Can this be supported with firebase-tools members?

**Comment by testak-m** [comment] 2024-04-10 16:53
You may wonder why you should help.
The reason is clear: firebase-tools has a dependency on FirebaseExtended/action-hosting-deploy.
https://github.com/firebase/firebase-tools/blob/b03e1ef43b2795c1c412e6b6457c688350f45838/src/init/features/hosting/github.ts#L36
