### ISSUE TITLE
Firestore Emulator times out when using merge option

### ISSUE THREAD

**Issue by Yuripetusko** [firebase/firebase-tools#1293] opened 2019-05-14 23:48 UTC
### [REQUIRED] Environment info

**firebase-tools: 6.9.1**

**Platform: macOS**

### [REQUIRED] Test case

```
test('Should not time out but it does', async () => {
    const db = await setup();

    expect.assertions(1);

    await db
      .collection('tests')
      .doc('db78f802-1efb-4674-bbf9-3b97f4180240')
      .delete();

    await expect(
      db
        .collection('tests')
        .doc('db78f802-1efb-4674-bbf9-3b97f4180240')
        .set(
          {
            alpha: { '43280116-7275-11e9-a923-1681be663d3e': 'alpha' },
          },
          { merge: true }
        )
    ).toAllow();
  });
```

### [REQUIRED] Steps to reproduce

```
- `firebase emulators:start --only firestore`
- `FIREBASE_FIRESTORE_EMULATOR_ADDRESS=127.0.0.1:8080 jest`
```

### [REQUIRED] Expected behavior

It would allow to set object, given security rules are allowing it

### [REQUIRED] Actual behavior

`Timeout - Async callback was not invoked within the 50000ms timeout specified by jest.setTimeout.Error: `

**Comment by samtstern** [comment] 2019-05-14 23:50
Thanks for the report @Yuripetusko, sounds like a bug.

FYI your command could be expressed as just `firebase emulators:exec --only firestore "jest"`, we automatically start the emulators, run your command with the correct env vars, and then stop them.

**Comment by Yuripetusko** [comment] 2019-05-14 23:50
Works if i set `merge: false` or if I try to set simple value like `alpha: true`

**Comment by Yuripetusko** [comment] 2019-05-14 23:53
And it only times out if Document wasn't created previously. If I create object first (`merge: false`) and then set it with `merge: true` then it passes fine

**Comment by Yuripetusko** [comment] 2019-05-14 23:55
So this works: 

```
 test('Should not time out but it does', async () => {
    const db = await setup();

    expect.assertions(1);

    await db
      .collection('tests')
      .doc('db78f802-1efb-4674-bbf9-3b97f4180240')
      .set(
        {
          alpha: { beta: 'delta' },
        },
        { merge: false }
      );

    await expect(
      db
        .collection('tests')
        .doc('db78f802-1efb-4674-bbf9-3b97f4180240')
        .set(
          {
            alpha: { omega: 'delta' },
          },
          { merge: true }
        )
    ).toAllow();
  });
```

**Comment by Yuripetusko** [comment] 2019-05-14 23:58
Actually.. it's when I set key as UUID ??

SO this works:


```

test('Should not time out but it does', async () => {
    const db = await setup();

    expect.assertions(1);

    await expect(
      db
        .collection('tests')
        .doc('db78f802-1efb-4674-bbf9-3b97f4180240')
        .set(
          {
            alpha: { alpha: 'delta' },
          },
          { merge: true }
        )
    ).toAllow();
  });
```


But this times out 


```
test('Should not time out but it does', async () => {
    const db = await setup();

    expect.assertions(1);

    await expect(
      db
        .collection('tests')
        .doc('db78f802-1efb-4674-bbf9-3b97f4180240')
        .set(
          {
            alpha: { '43280116-7275-11e9-a923-1681be663d3e': 'delta' },
          },
          { merge: true }
        )
    ).toAllow();
  });
```

**Comment by ryanpbrewster** [comment] 2019-05-15 03:34
Thanks for the repro, digging into what's going on inside. Seems like something subtle.

**Comment by ryanpbrewster** [comment] 2019-05-15 03:47
Duplicate of https://github.com/firebase/quickstart-nodejs/issues/66

The issue here is caused by the way we sanitize the emulator before publishing it. I finally have a solution for this and I'm hopeful we can get it out in a release or two.

I imagine it's not always possible (and I hate even suggesting it), but one workaround is to avoid hyphens in your map keys.

**Comment by Yuripetusko** [comment] 2019-05-29 09:31
I have more timeout issues in emulator, this time I am not using hyphens in mpa keys, should I create a new issue or I can post it here?

**Comment by samtstern** [comment] 2019-05-29 13:53
Please file a new issue if you think it's a new bug, thanks!

**Comment by ryanpbrewster** [comment] 2019-06-07 22:24
This should be fixed by https://github.com/firebase/firebase-tools/pull/1380

**Comment by samtstern** [comment] 2019-06-26 17:41
Closing this since #1380 has been merged and there are no additional reports.

**Closed by samtstern** 2019-06-26 17:41 UTC
Labels: emulator-suite, emulators: firestore, type: bug
