### ISSUE TITLE
Firepit Builds for Windows have been failing since 7.6.0

### ISSUE THREAD

**Issue by skjagini** [firebase/firebase-tools#1796] opened 2019-11-14 05:37 UTC
### [REQUIRED] Environment info
**Platform**: Windows 10

**firebase-tools:**
firebase-tools: The one provided over here: https://firebase.google.com/docs/cli/#install-cli-windows

**Platform:**

### [REQUIRED] Test case
I am just trying to launch the emulator

### [REQUIRED] Steps to reproduce
After downloading the firebase-tools-instant-win.exe and tried various commands with no difference

firebase-tools-instant-win.exe firebase init
firebase-tools-instant-win.exe firebase login

I tried launching the emulator by double clicking, which prompted windows defender to confirm the action, which I rightly did and tried above the commands again thereafter as well.
![Annotation 2019-11-14 003651](https://user-images.githubusercontent.com/17683681/68829448-ec626380-0676-11ea-98fe-05a93c959a32.png)

### [REQUIRED] Expected behavior
Should launch the emulator or should give error/warning

### [REQUIRED] Actual behavior
I don't see no any response from the above command.

**Comment by bkendall** [comment] 2019-11-14 16:32
Could you give it a try with `--debug`? Maybe that will print something useful?

Paging Dr @abeisgoat ...

**Comment by samtstern** [comment] 2019-11-14 16:39
@abeisgoat also is the WIndows Defender prompt a bug?  I thought we got around that with code signing.

**Comment by abeisgoat** [comment] 2019-11-17 20:19
Once you've confirmed the defenders prompt what do you see?

**Comment by ericti** [comment] 2019-11-22 14:01
D:\Download>firebase-tools-instant-win.exe firebase init

D:\Download>firebase-tools-instant-win.exe firebase login

D:\Download>firebase-tools-instant-win.exe firebase --debug

D:\Download>firebase-tools-instant-win.exe --debug

D:\Download>firebase-tools-instant-win.exe

D:\Download>firebase-tools-instant-win.exe -help

D:\Download>firebase-tools-instant-win.exe -debug




didn't see anything, my OS : win10

**Comment by muhammadkamranlatifraza** [comment] 2019-11-22 20:13
well dear if you are having bad luck as i was i'm gonna assume that your firebase installation with npm is also not working, because of some Windows 10 error, 
here is what i did to get my firebase working........

1. I installed npm and firebase with it just like the documentation says......
2. I opened it with CMD with firebase login.... gives me error
3. opened Powershell with administrative privilege and try firebase command
4. shows an error something about this system cannot perform script something to do with Powershell's Execution Policies and shows a Microsoft site address. 
5. I followed the link into site where info About Execution Policies were given and how to change them.
6. i unrestricted policies and ran firebase..... IT WORKED

Hope its helpful for you as well

**Comment by abeisgoat** [comment] 2019-11-25 19:18
@ericti What happens when you double click the exe, not run it from the terminal?

**Comment by clicksrv** [comment] 2019-12-02 17:16
I have exactly the same issue as well. Double click or terminal, nothing works. Will try out @muhammadkamranlatifraza's workaround.

**Comment by ericti** [comment] 2019-12-03 14:22
> @ericti What happens when you double click the exe, not run it from the terminal?

Nothing happened, try 2 different Win10, same, nothing's happened

**Comment by skjagini** [comment] 2019-12-11 05:45
Hi, sorry for late reply, I am using npm based emulator to get around this issue. Thanks

**Comment by muhammadkamranlatifraza** [comment] 2019-12-11 13:15
i just found out that my previous workaround didn't uploaded the files somehow it didn't gave me an error but nothing was uploaded to cloud functions.... 
I found the problem in my username in windows 8.1 as it used a special character which is not accessible for CMD....
my username in windows was: Kam^Ran   
then i created another username with simple name and it worked....
firebase-tools-instant-win.exe still wont work..... but who need it now :-P

**Comment by radikpsb** [comment] 2019-12-16 12:55
I have exactly the same problem on Windows 10, v7.10.0 doesn't work either. For me this issue is blocking because I can't use npm. Crashlytics Beta is deprecated and it's cruicial to make it work until March, 2020. Any ideas when it could be fixed?

**Comment by arnegebert** [comment] 2019-12-18 10:11
Same issue here just now, Windows 10, got a Windows defender pop-up, neither double-clicking or 'firebase-tools-instant-win.exe firebase login' does anything. 
Npm seems to work though.

**Comment by saqibsoftwares** [comment] 2020-01-02 11:08
same problem firebase-tools-instant-win.exe does nothing on windows 10, not responding to any command. In addition, when you double click on exe file it will close as soon as its opens.

**Comment by Winkster** [comment] 2020-01-02 17:28
Hardcore Win pro chiming in here. I can confirm that firebase-tools-instant-win.exe does absolutely nothing. It creates an 11kb entry in \windows\prefetch and then instantly returns to command line. Zero. Zilch. Nada. No other file handles are being opened, no new processes are created. The executable is just one big fat 100MB NOP.

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free      
Original Install Date:     10/27/2019, 8:38:49 PM
System Boot Time:          1/1/2020, 1:42:40 PM
System Manufacturer:       LENOVO
System Model:              81TF
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1792 Mhz
BIOS Version:              LENOVO 5NCN46WW, 2/27/2019
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,227 MB
Available Physical Memory: 6,297 MB
Virtual Memory: Max Size:  24,880 MB
Virtual Memory: Available: 3,487 MB
Virtual Memory: In Use:    21,393 MB
Page File Location(s):     C:\pagefile.sys
Hotfix(s):                 7 Hotfix(s) Installed.
                           [01]: KB4533002
                           [02]: KB4516115
                           [03]: KB4521863
                           [04]: KB4524569
                           [05]: KB4525419
                           [06]: KB4532441
                           [07]: KB4530684
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by abeisgoat** [comment] 2020-01-03 20:01
Hi folks,

Sorry for the slow response over the holiday season. I'm investigating this ASAP and will let ya'll know when I have some more information.

I apologize again for the delay.

**Comment by abeisgoat** [comment] 2020-01-03 20:41
Alright, I've confirmed I can repro this on my test machine, looking into causes.

**Comment by abeisgoat** [comment] 2020-01-03 22:17
Okie dokie, good news and bad news. Good news is that this regression was introduced between version `7.5.0` and `7.6.0` of the CLI and luckily, that version bump wasn't the biggest we've done. The bad news is that it's still ~100 commits to 186 files totally almost 10k code changes and any of those could be at fault haha.

I'll do my best to track down what change caused this and since it's breaking both instant and regular binary builds for (some users) it'll be high-priority for me until we sort it.

**Comment by abeisgoat** [comment] 2020-01-07 20:03
Alright, so I can (still) confirm that the current release builds for Windows are acting unexpectedly, however new manual builds seem to work fine which suggests that this regression has to do with the automated build step in our CI flow and may be Cloud Build, it's also possible that our `firepit-builder` docker image isn't up to date with the latest `pipeline.js` updates which is causing some unexpected split.

**Comment by abeisgoat** [comment] 2020-01-07 21:18
So I'm still not 100% sure what's causing this, but I made a bunch of Windows-related fixes to our build pipeline and now I can't produce broken builds anymore, so we're gonna ship another release this week and we'll see if the pipeline updates fix it, if the builds are still broken, then it must be something in Docker / Cloud Build messing with us.

**Comment by abeisgoat** [comment] 2020-01-16 19:26
Alright, everything is confirmed fixed with latest release. Please file if this issue persists.

**Closed by abeisgoat** 2020-01-16 19:26 UTC
Labels: Needs: Attention, firepit, platform: windows

**Comment by P4z** [comment] 2020-04-25 23:37
Same on Windows 10 with `firebase-tools-instant-win.exe` v8.1.1. 😢 

```
B:\SRC\firebase-quickstart-js>firebase --debug
################################################################################################################################################################

     Welcome to...
   ######## #### ########  ######## ########     ###     ######  ########  ##
   ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##        ##
   ######    ##  ########  ######   ########  #########  ######  ######    ##
   ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
   ##       #### ##     ## ######## ########  ##     ##  ######  ########  ##


################################################################################################################################################################

~ Let's make sure your Firebase CLI is ready...
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (C:\snapshot\firepit\welcome.js:115:27)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12)

>
```

First I run `firebase-tools-instant-win.exe` in `cmd.exe` as an admin and it output several lines about preparation. Every next invocation results with error quoted above.

**Comment by krishnakanthpps** [comment] 2020-05-16 06:13
@P4z  How did you get it work?

**Comment by msyagami** [comment] 2020-05-20 11:11
Same issue with @P4z , but it works when you install it via npm.

**Comment by toomanylogins** [comment] 2020-10-05 13:56
I have exactly the same issue with the latest version. When I run the command line nothing happens I do not get any output with any of the commands eg firebase-tools-instant-win.exe --debug
This is on Windows 10.
Paul

**Comment by QQbit** [comment] 2021-09-18 15:16
2021 it still not work on windows 10 
![image](https://user-images.githubusercontent.com/63203418/133893624-9b289414-3151-466f-87cc-0a67e67a8617.png)

**Comment by Almax27** [comment] 2021-11-25 17:41
Same issue here, however this occurred for me when moving firebase-tools-instant-win.exe between drives.

I have 4 physical drives, one of which is split into two partitions. 

Drive A (Part1) - C:\   (I can copy here, and run successfully - this is my windows drive)
Drive A (Part2) - F:\   (where the exe was originally run - and still works)
Drive B,C,D - Copying the exe to any of these drives and running it results in the following error:

![image](https://user-images.githubusercontent.com/1354634/143484010-dd6185e2-9715-4d35-a837-2522e4f4a54c.png)
