### ISSUE TITLE
firebase deploy fails when functions dependencies are missing

### ISSUE THREAD

**Issue by markhobson** [firebase/firebase-tools#716] opened 2018-04-04 15:21 UTC
### Version info

3.18.0

### Platform Information

Linux, Ubuntu 17.10

### Steps to reproduce

When `npm install` **has not** been run in `/functions`:
```
firebase deploy
```

### Expected behavior

Application is deployed to Firebase.

### Actual behavior

```
$ yarn firebase deploy --debug
[2018-04-04T13:56:13.457Z] ----------------------------------------------------------------------
[2018-04-04T13:56:13.460Z] Command:       /usr/bin/node /home/mark/Projects/foobar/node_modules/.bin/firebase deploy --debug
[2018-04-04T13:56:13.460Z] CLI Version:   3.18.0
[2018-04-04T13:56:13.460Z] Platform:      linux
[2018-04-04T13:56:13.460Z] Node Version:  v8.11.1
[2018-04-04T13:56:13.460Z] Time:          Wed Apr 04 2018 14:56:13 GMT+0100 (BST)
[2018-04-04T13:56:13.460Z] ----------------------------------------------------------------------

[2018-04-04T13:56:13.468Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-04-04T13:56:13.469Z] > authorizing via signed-in user
[2018-04-04T13:56:13.471Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/foobar  
  
 Wed Apr 04 2018 14:56:13 GMT+0100 (BST)
[2018-04-04T13:56:14.091Z] <<< HTTP RESPONSE 200 server=nginx, date=Wed, 04 Apr 2018 13:56:14 GMT, content-type=application/json; charset=utf-8, content-length=135, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-04-04T13:56:14.093Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/foobar/tokens  
  
 Wed Apr 04 2018 14:56:14 GMT+0100 (BST)
[2018-04-04T13:56:14.746Z] <<< HTTP RESPONSE 200 server=nginx, date=Wed, 04 Apr 2018 13:56:14 GMT, content-type=application/json; charset=utf-8, content-length=271, connection=close, x-content-type-options=nosniff, strict-transport-security=max-age=31536000; includeSubdomains, cache-control=no-cache, no-store
[2018-04-04T13:56:16.032Z] TypeError: Invalid Version: undefined
    at new SemVer (/home/mark/Projects/foobar/node_modules/semver/semver.js:291:11)
    at compare (/home/mark/Projects/foobar/node_modules/semver/semver.js:578:10)
    at Function.lt (/home/mark/Projects/foobar/node_modules/semver/semver.js:612:10)
    at /home/mark/Projects/foobar/node_modules/firebase-tools/lib/checkFirebaseSDKVersion.js:46:18
    at initializePromise (/home/mark/Projects/foobar/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/home/mark/Projects/foobar/node_modules/rsvp/dist/rsvp.js:1039:33)
    at /home/mark/Projects/foobar/node_modules/firebase-tools/lib/checkFirebaseSDKVersion.js:38:12
    at tryCatch (/home/mark/Projects/foobar/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/mark/Projects/foobar/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/mark/Projects/foobar/node_modules/rsvp/dist/rsvp.js:508:7)

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
Arguments: -c /home/mark/Projects/foobar/node_modules/.bin/firebase deploy --debug
Directory: /home/mark/Projects/foobar
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/mark/Projects/foobar/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Comments

Commit e1405a9a522505b93b6b4f465e124e4cd67d4213 introduced a check for a stale SDK which introduced this bug. The problem is that the spawned `npm outdated firebase-functions --json=true` command fails in `/functions` if the npm dependencies haven't been installed yet, as `output['firebase-functions'].current` is `undefined`.

A further observation is that [checkFirebaseSDKVersion.js](https://github.com/firebase/firebase-tools/blob/adb3f0988b92885765d97d351ce7de154249dbf2/lib/checkFirebaseSDKVersion.js#L21) assumes that the functions directory is always `/functions`, even though it can be configured in `firebase.json` under `functions.source`.

**Comment by laurenzlong** [comment] 2018-04-05 18:04
Duplicate of https://github.com/firebase/firebase-tools/issues/715

**Closed by laurenzlong** 2018-04-05 18:04 UTC
