### ISSUE TITLE
Firestore emulator does not work in Cypress

### ISSUE THREAD

**Issue by prescottprue** [firebase/firebase-tools#1975] opened 2020-02-14 21:15 UTC
### [REQUIRED] Environment info

**firebase-tools:** 7.13.0

**Platform:** macOS

### [REQUIRED] Test case

1. Pull [this sample repo](https://github.com/prescottprue/firestore-emulator-cypress)
1. Run `yarn install`
1. As described in the README run the following:
    1. Start the emulators: `yarn emulators`
    1. In a new terminal window, seed the emulated databases with data: `yarn seed`
    1. Start the app by running: `yarn start`
    1. Visit `localhost:3000` in your browser - notice that data loads from both emulated databases

You should see projects from Firestore and RTDB appear in the view. This is expected - the next section covers what is unexpected

### [REQUIRED] Steps to reproduce

1. Follow the previous section
1. In another terminal window, open the test runner by running: `yarn test`
1. Run the projects tests by clicking on "Projects.spec.js"

At this point the data does not load from the Firestore emulator within Cypress even though they will load in the browser (pictured below). This error appears in the console of the window opened by Cypress:
![image](https://user-images.githubusercontent.com/2992224/73963581-d1963880-48cd-11ea-9ed6-bf4009284659.png)

![image](https://user-images.githubusercontent.com/2992224/73964898-5d10c900-48d0-11ea-915b-cc42b2fcba3c.png)

### [REQUIRED] Expected behavior

The expected behavior is that the Firestore emulator works within a browser window Cypress the same way it does in a normal browser - the same way RTDB emulator works

An issue was also [filed on the Cypress Repo](https://github.com/cypress-io/cypress/issues/6350)

### [REQUIRED] Actual behavior

Connecting to the Firestore emulator within browser window opened by Cypress does work the way it does in a default browser. When attempting to open the app in Cypress it shows the "Could Not reach Firestore backend" error:

![image](https://user-images.githubusercontent.com/2992224/73963581-d1963880-48cd-11ea-9ed6-bf4009284659.png)

Happens in both Chrome and Electron

This issue has also been mentioned by another user [in this stackoverflow post](https://stackoverflow.com/questions/59336720/cant-use-cypress-to-test-app-using-using-firestore-local-emulator).

**Comment by samtstern** [comment] 2020-02-14 23:15
I am not familiar with Cypress, but is there something here that leads you to believe this is an issue with the Firebase emulators or the Firebase CLI?  Can you see network traffic going out to the right host/port but the emulators not responding?  To my (untrained) eye it seems like the issue is likely to be inside Cypress since this works in a "standard" web testing setup.

**Comment by ppalyga** [comment] 2020-02-15 12:21
I also run into the same problem, having the newest version of Java and Cypress 4.0.2 installed. I was able to make it work by using `experimentalForceLongPolling: true` flag in firestore.settings.

**Comment by wvanderdeijl** [comment] 2020-02-17 05:29
That is the same workaround we are using in cypress. I think the underlying problem is that Cypress is intercepting all network traffic so it can monitor and sometimes mock. However, the webchannel protocol used by firestore has multiple replies over the same http request. The Cypress code cannot handle this and will only forward the first reply and ignore the rest.
For more info see https://github.com/cypress-io/cypress/issues/2374

**Comment by samtstern** [comment] 2020-02-18 17:12
@wvanderdeijl thanks for pointing this out!  Since Cypress is intercepting all network requests we can't   support any issues caused by that.  So I am going to close this in favor of looking for a solution from the Cypress team over at https://github.com/cypress-io/cypress/issues/2374

**Closed by samtstern** 2020-02-18 17:12 UTC
Labels: Needs: Author Feedback
