### ISSUE TITLE
Firebase deploy deploying all functions even if nothing changed

### ISSUE THREAD

**Issue by iq-dot** [firebase/firebase-tools#6879] opened 2024-03-14 16:30 UTC
firebase-tools: 12.9
firebase: 10.5

Platform: Linux

[REQUIRED] Test case
create v1 function and put in folder1
create another v1 function and put in folder2
create index.js at src/
import func1 and func2 and export as { api: { func1, func2 } }
Set your deploy command to firebase deploy --project ${npm_config_project} --force 
[REQUIRED] Steps to reproduce
Deploy functions
Make no changes and redeploy functions
[REQUIRED] Expected behavior
Should not redeploy anything the second time if no changes

[REQUIRED] Actual behavior
All functions are deployed

This is a re-open of this issue: https://github.com/firebase/firebase-tools/issues/6634

Further details on why:

Hello I am reopening this as removing the --force flag does not help at all, in fact I have seen it can skip deployments even with the --force flag.

I am struggling to debug this and the only 3 things I can point to based on the hashing code that firebase-tools use:

- the code output after typescript and esbuild is different each time (could not replicate locally)
- the env variables are somehow different
- the JSONification of the env variables the firebase tools uses is not always in the same order
- the Circle CI environment is somehow affecting things

I have tried to SSH into my CI build machines and running the command manually, running once, deploys it all (even though nothing has changed), however if I run it again then it does skip deployment.

Here are my esbuild config:

```js
import * as esbuild from 'esbuild'

const args = process.argv.slice(2)
const watch = args.includes('--watch') || false

const ctx = await esbuild.context({
  entryPoints: ['./build/index.js'],
  bundle: true,
  minify: true,
  outdir: 'dist',
  platform: 'node',
  target: 'node16',
  format: 'esm',
  external: ['./node_modules/*'],
});

if (watch) {
  await ctx.watch()
  console.log('watching...')
} else {
  await ctx.rebuild()
  await ctx.dispose()
  console.log('build done')
}
```

This is my tsconfig:

```json
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "compilerOptions": {
  "module": "ES2022", 
  "resolveJsonModule": true,
  "outDir": "./build/",
    "include": ["src/**/*"],
    "exclude": ["src/**/*.test.ts", "**/__mocks__/**/*", "**/node_modules/**/*"],
  }
```

Any help on getting to the bottom of this is really appreciated as our deploys are very slow due full deployments.

**Comment by inlined** [comment] 2024-03-27 18:56
I was able to reproduce this when adding params. Will look into it today and it will hopefully be fixed in next week's CLI update.

**Comment by inlined** [comment] 2024-03-27 18:58
This is strange... I've reproduced once after adding params, but it was stable after that. I can scan the code for anything suspicious but without a reliable repro I may have some difficulty

**Comment by iq-dot** [comment] 2024-03-27 19:34
What kind of params did you add? I've seen it rarely work on our CI but 9 out of 10 times it does a full update, I just can't figure out what the issue is. If I ssh into our CI box and deploy, the first deploy is full but the subsequent ones are fine but if I re-create another build using the same code, it does a full update.

Are you also using CircleCI to reproduce or a different method?

**Comment by inlined** [comment] 2024-03-27 20:03
I added string params, but it shouldn't make a difference since they're all strings in dotenv anyway. I'm trying to reproduce locally; Circle CI isn't officially in our scope, so I'm trying to reproduce it on my machine

**Comment by inlined** [comment] 2024-03-27 22:59
TIL that if you use --only with a function or codebase it disables noops. Does that apply to your case?

**Comment by iq-dot** [comment] 2024-03-27 23:08
Nope I don't use --only, I always deploy all functions. I have also tried
with and without --force flag and no difference either.

Could it be an ordering issue with JSONification of env params?

Does the deployment pick up all env variables in the build machine or just
those defined in an .env file?

**Comment by inlined** [comment] 2024-03-27 23:28
I just realized you might be expecting the feature to work differently than it does. Are you expecting that changes to folder1 won't deploy functions in folder2?

The hash check is against the entire source upload (plus dotenv and secret verions). Changes to either folder1 or folder2 will affect all functions in the codebase and change the hash. There's no way to know that your code in folder2 hasn't somehow reached in and modified the code in folder1 without building our own interpreter (e.g. what if folder2 had a utility function that folder1 depended on?). This is why we introduced [codebases](https://firebase.google.com/docs/functions/organize-functions?gen=2nd#organize_functions_in_codebases). If you're able to split your code into multiple codebases, you'll quickly benefit from noops. I fully recognize that this isn't always easily doable since we do not currently support monorepos for common utilities/types; that's a request that's been on our back-burner for a while. We've had some setbacks in implementing it but may be able to pick it up again in a few months.

**Comment by iq-dot** [comment] 2024-03-27 23:39
That is exactly what I assumed and your explanation makes a lot of sense.

When deploying the output log states that it's checking which functions
have changed to determine what to upload so I assumed it was checking based
on per function.

So the only way is to split it into codebases otherwise changing any
function code will deploy all? Have I understood that correctly?

**Comment by inlined** [comment] 2024-03-28 00:22
That's correct. If your node module changes, all functions in that node module are updated because there's no way to rule out side effects. I'll add a warning to our documentation about this.

I'm closing the bug to remove it from our tracker, but I can check my GitHub inbox if you post extra comments.

**Closed by inlined** 2024-03-28 00:22 UTC
Labels: type: bug, api: functions, reproducible
