### ISSUE TITLE
Emulator export only the first 20 entries from authentication

### ISSUE THREAD

**Issue by neuberoliveira** [firebase/firebase-tools#3546] opened 2021-07-02 18:57 UTC
In my last issue (#3421) i think was my fault, but i go deep and now i thought it was a bug.
Iam using emulator with this 2 flags `--import emulator-snapshot` and `--export-on-exit emulator-snapshot` and was working fine, then sundelly every time o login, sms, i got a new uid, of course i was using the same phone number, because of this i open #3421

Now i realize that emulator was not saving all data from authentication, its saving only the first 20 results, and trying to paginate it somehow, so after 20 entries my new created user is truncated when i stop emulator, so in the next run it loads only these 20 entries, and this was the real cause of the #3421.

### Environment info

**firebase-tools:** 9.1.0

**Platform:** MacOS

### Steps to reproduce

Use this file to import initial data to the emulator, note that it has 21 accounts.
<details>
  <summary>accounts.json</summary>

  ```json
  {
    "kind": "identitytoolkit#DownloadAccountResponse",
    "users": [
      {
        "localId": "0BwoekNt9BOwGnMa6G4fuwFPFyy1",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000001",
            "rawId": "+5500000000001"
          }
        ],
        "phoneNumber": "+5500000000001",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "0PMAAn87mDcJrrShGnJhCg4cQR02",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000002",
            "rawId": "+5500000000002"
          }
        ],
        "phoneNumber": "+5500000000002",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "0Rgji3TqmJaYfsKZuDkcpqK6XLv2",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000003",
            "rawId": "+5500000000003"
          }
        ],
        "phoneNumber": "+5500000000003",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "0SYxeD5n2DVta3Q8oRg0cXdzkqi2",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000004",
            "rawId": "+5500000000004"
          }
        ],
        "phoneNumber": "+5500000000004",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "0ThKajZEmjWZmBHodkqOB5VEVQF3",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000005",
            "rawId": "+5500000000005"
          }
        ],
        "phoneNumber": "+5500000000005",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "0hQQBam7eBdnJzFmasMYbfhvQqu2",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000006",
            "rawId": "+5500000000006"
          }
        ],
        "phoneNumber": "+5500000000006",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "13TiHcGgxcXF3EvDaltqWOc2fFo1",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000007",
            "rawId": "+5500000000007"
          }
        ],
        "phoneNumber": "+5500000000007",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "1VccoXvob5MUHxsFxr6kVwdBN4f1",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000008",
            "rawId": "+5500000000008"
          }
        ],
        "phoneNumber": "+5500000000008",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "1WKXqVIH6lVw0alrGJdEEg71y2f1",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000009",
            "rawId": "+5500000000009"
          }
        ],
        "phoneNumber": "+5500000000009",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "1XHhiysPY6VV9ClDPr8mnNZ2whk2",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000010",
            "rawId": "+5500000000010"
          }
        ],
        "phoneNumber": "+5500000000010",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "1pdn7CxWzvPq4AwSznco3zn3LZH2",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000011",
            "rawId": "+5500000000011"
          }
        ],
        "phoneNumber": "+5500000000011",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "2cvrQwyn3aTJw8g3P29CaEiNyXJ3",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000012",
            "rawId": "+5500000000012"
          }
        ],
        "phoneNumber": "+5500000000012",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "2kv2J2eSmSV4xz6WhFfPLb4mvoZ2",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000013",
            "rawId": "+5500000000013"
          }
        ],
        "phoneNumber": "+5500000000013",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "2ulkPmiFXGUUzFvortu234360ax2",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000014",
            "rawId": "+5500000000014"
          }
        ],
        "phoneNumber": "+5500000000014",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "31MqB8EcHiYFPIenP1T5SFwCSHl2",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000015",
            "rawId": "+5500000000015"
          }
        ],
        "phoneNumber": "+5500000000015",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "3NyiYhcAgtTsIdzPTeHTvCxZUJ52",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000016",
            "rawId": "+5500000000016"
          }
        ],
        "phoneNumber": "+5500000000016",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "3Xi90neuUVezizvFM5KS5MVroCp1",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000017",
            "rawId": "+5500000000017"
          }
        ],
        "phoneNumber": "+5500000000017",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "3xWbZ0RUTsdAFWC4T7uY7rcIaBx2",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000018",
            "rawId": "+5500000000018"
          }
        ],
        "phoneNumber": "+5500000000018",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "42W4jxmKIKXgvCaxleaWE76b1mk1",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000019",
            "rawId": "+5500000000019"
          }
        ],
        "phoneNumber": "+5500000000019",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "4G4oPPWGERYgQzVyYDirD7fOznN2",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000020",
            "rawId": "+5500000000020"
          }
        ],
        "phoneNumber": "+5500000000020",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      },
      {
        "localId": "l66nzp6wgfeexxud0cuy00mf",
        "createdAt": "1625090557444",
        "lastLoginAt": "1625090557443",
        "providerUserInfo": [
          {
            "providerId": "phone",
            "federatedId": "+5500000000021",
            "rawId": "+5500000000021"
          }
        ],
        "phoneNumber": "+5500000000021",
        "validSince": "1625248834",
        "emailVerified": false,
        "disabled": false
      }
    ]
  }
  ```
</details>

Stop emulator and check the `accounts.json` now. Its contents was overwrited with exported data, but note that last entry with ID `l66nzp6wgfeexxud0cuy00mf` and phone number `+5500000000021` are missing and at the end we have this property `"nextPageToken": "4G4oPPWGERYgQzVyYDirD7fOznN2"`

### Expected behavior
Export all data from emulator, so i can get the same uid when login and then keep using the data i fill in my last session

### Actual behavior
Exporting only the first 20 entries from authentication.

**Comment by samtstern** [comment] 2021-07-05 14:27
@neuberoliveira you mention you're using `firebase-tools: 9.1.0` which is fairly old, I believe this issue was fixed here:
https://github.com/firebase/firebase-tools/issues/3231

Could you try updating to the latest version of the CLI and then trying again?

**Comment by neuberoliveira** [comment] 2021-07-06 15:54
seems that all data are being exported in 9.14, thanks for the attention.

**Comment by neuberoliveira** [comment] 2021-07-13 16:14
hi, iam reopening this cause i dont know if its better to open a new issue or not. It work as expected now and dump all users to the `emulator-snapshot/auth_export/accounts.json` but.......

if the filesize of `emulator-snapshot/auth_export/accounts.json` is more then 100kb the emulator wont start and gives the error 413 entity too large

![Screen Shot 2021-07-13 at 12 57 31](https://user-images.githubusercontent.com/3378304/125487302-77a0e139-3c39-405b-b5cf-c9d4353173ec.png)

then i shrink some data in the file until it becomes to 100kb and it works
![Screen Shot 2021-07-13 at 13 10 25](https://user-images.githubusercontent.com/3378304/125487479-6da74bb3-8ffc-49eb-8d8d-4356c5baf5d6.png)

**Comment by yuchenshi** [comment] 2021-07-13 16:35
Duplicate of #3570.

**Closed by yuchenshi** 2021-07-13 16:35 UTC
Labels: Needs: Attention, emulator-suite, emulators: auth
