### ISSUE TITLE
Testing a pubsub trigger function in shell fails

### ISSUE THREAD

**Issue by shaibt** [firebase/firebase-tools#6502] opened 2023-11-09 14:53 UTC
### [REQUIRED] Environment info

**firebase-tools:**
 12.4.2

**firebase-functions:**
4.4.1

**Platform:**
Mac OSX

### [REQUIRED] Test case

I have a ver2 function that has a pubsub trigger. When deploying it and publishing a message to the topic the function runs properly.
When trying to envoke the function from `firebase functions:shell` it fails.

### [REQUIRED] Steps to reproduce
Build a ver2 pubsub function. Try triggering it manually in shell.

### [REQUIRED] Expected behavior

function will run.

### [REQUIRED] Actual behavior

```
firebase > myfucntion()
i  functions: Loaded environment variables from .env.*****.

'Successfully invoked function.'

firebase > ⚠  functions: TypeError: Cannot read properties of undefined (reading 'messageId')
    at new Message (/Users/s****/Developer/*****/functions-media/node_modules/firebase-functions/lib/v2/providers/pubsub.js:65:31)
    at func (/Users/s****/Developer/*****/functions-media/node_modules/firebase-functions/lib/v2/providers/pubsub.js:127:40)
    at /Users/s****/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:524:16
    at runFunction (/Users/s****/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:506:15)
    at runCloudEvent (/Users/s****/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:523:11)
    at processBackground (/Users/s****/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:490:16)
    at /Users/s****/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:689:27
    at Layer.handle [as handle_request] (/Users/s****/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/s****/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/s****/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:140:7)
⚠  Your function was killed because it raised an unhandled error.
Uncaught Error: socket hang up
    at connResetException (node:internal/errors:692:14)
    at Socket.socketOnEnd (node:_http_client:478:23)
    at Socket.emit (node:events:539:35)
    at Socket.emit (node:domain:537:15)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET'
}
```

**Comment by aalej** [comment] 2023-11-09 16:15
Hi @shaibt, thanks for reaching out. I am unable to reproduce the issue you’re encountering. I created a function by following the steps [here](https://firebase.google.com/docs/functions/pubsub-events?gen=2nd), but no errors were raised when I started the functions shell and invoked the function. As a first troubleshooting step, could you try updating to the latest version of firebase-tools which is currently [v12.8.1](https://github.com/firebase/firebase-tools/releases).

If you still encounter the issue after updating to the latest version of firebase-tools, could you provide code snippets of the function you’re trying to invoke?

**Comment by shaibt** [comment] 2023-11-09 16:24
Hi @aalej,
Upgrading to firebase CLI 12.8.1 solved the issue and the emulator is running the manually envoked function.

**Comment by aalej** [comment] 2023-11-09 17:01
That's good to hear, thanks for letting us know. For now, I'll go ahead and close this issue. If you encounter any errors moving forward, feel free to ask this to be re-opened.

**Closed by aalej** 2023-11-09 17:01 UTC
Labels: type: bug, Needs: Attention, emulators: functions
