### ISSUE TITLE
Functions Emulator should support Node 19

### ISSUE THREAD

**Issue by benedelstein** [firebase/firebase-tools#5363] opened 2022-12-22 21:12 UTC
Hi, https functions in the firebase shell are returning weird timeout errors. Someone else mentioned this in a recent previous [issue](https://github.com/firebase/firebase-tools/issues/5227#issuecomment-1345765885)

### [REQUIRED] Environment info

**firebase-tools:** 11.19.0 (but also tried 11.16.1, 11.17.0)
**firebase-functions:** 4.0.2

**Platform:** mac (M1)

### [REQUIRED] Test case

```
import * as functions from "firebase-functions";

export const testFunction = functions.https.onRequest((req,res) => {
    console.log('ok');
    res.send('ok');
})

export const testAsync = functions.https.onRequest(async (req,res) => {
    await new Promise(r => setTimeout(r, 10000)); // wait 10s
    res.send('ok');
})
```

### [REQUIRED] Steps to reproduce

`firebase functions:shell`
`> testFunction()`
`> testAsync()`

### [REQUIRED] Expected behavior

function completes with 200 
`RESPONSE RECEIVED FROM FUNCTION: 200, ok`

### [REQUIRED] Actual behavior

The function `testFunction` returns successfully, but then a few seconds later (not 60s) it shows a timeout error (sometimes 2 timeout errors). 
```
RESPONSE RECEIVED FROM FUNCTION: 200, ok
⚠  functions: Your function timed out after ~60s. To configure this timeout, see
      https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation.
⚠  Your function was killed because it raised an unhandled error.
⚠  functions: Your function timed out after ~60s. To configure this timeout, see
      https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation.
⚠  Your function was killed because it raised an unhandled error.
```
It doesn't specify what the unhandled error is here. 

For a longer running async function (`testAsync`), the function times out before it can return, and the error is ECONNRESET. But I'm awaiting the promise, and the delay is only 10s (less than the timeout of 60), so it shouldn't exit the function before that work completes?
```
⚠  functions: Your function timed out after ~60s. To configure this timeout, see
      https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation.
⚠  Your function was killed because it raised an unhandled error.

RESPONSE RECEIVED FROM FUNCTION: 500, {
  "code": "ECONNRESET"
}
```

**Comment by aalej** [comment] 2022-12-23 14:34
Hi @benedelstein, thanks for the information you provided. Using your provided code snippet, I followed the steps you mentioned and after waiting a few minutes(5 minutes or so), I did not encounter any timeout errors. I am using `firebase-tools` version 11.19.0 and `firebase-functions` version 4.1.1. 

For now, could you try updating to the latest version of `firebase-functions`, and if the issue persists after doing so, could you provide me with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or more details on the steps you took so that I can reproduce the issue?

**Comment by benedelstein** [comment] 2022-12-25 00:41
Hi @aalej thanks for your reply. I upgraded to 4.1.1 and that didn't work, so I tried a fresh project to create a minimal example and am still getting the same error.

I posted the example here https://github.com/benedelstein/testFirebase

I only set up the functions emulator (no firestore auth etc), using fully updated libraries. I'm using typescript too
```
npm run shell

> testAsync()
```
also attached my firebase-debug.log for this example.
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/10299292/firebase-debug.log)

**Comment by taeold** [comment] 2022-12-27 23:39
I'm taking a look, and I can reliably reproduce the issue when I'm using Node 19.

For immediate terms, I recommend that you use Node 18 for local development and testing. We normally don't support odd numbered major releases, and will likely test and fix any issues with Node 20 when that arrives.

I'm leaving the ticket open and changing the title to match the discovered bug. It's a bit low priority bug since we normally don't invest in support odd-numbered node release.

**Comment by benedelstein** [comment] 2022-12-28 00:23
confirmed that downgrading to node 18 worked. Thanks, @taeold !

**Comment by gjones604** [comment] 2023-12-01 19:49
> I'm taking a look, and I can reliably reproduce the issue when I'm using Node 19.
> 
> For immediate terms, I recommend that you use Node 18 for local development and testing. We normally don't support odd numbered major releases, and will likely test and fix any issues with Node 20 when that arrives.
> 
> I'm leaving the ticket open and changing the title to match the discovered bug. It's a bit low priority bug since we normally don't invest in support odd-numbered node release.

Attempting to deploy local development functions using node v18 results in failure due to the cli expecting at most node v16.

```
deploying functions

Error: package.json in functions directory has an engines field which is unsupported. Valid choices are: {"node": 10|12|14|16}
```

Meanwhile GCP console states that node v16 is deprecated and that functions should be updated to at least node v18.

**How can we use CI/CD and use at least node v18 at the sametime?**

**Comment by joehan** [comment] 2023-12-05 19:07
@gjones604 - I think you may be on a very old version of firebase-tools - the error message you are seeing was updated 8 months ago (https://github.com/firebase/firebase-tools/commit/254dc8b06b58d7c8eb0e64695db7079954639f2b). Please update your CI/CD pipeline to use the latest version of firebase-tools, which supports node 18 and node 20.

Going to close this issue out - as @taeold mentioned, we don't support odd versions of Node since they are not LTS

**Closed by joehan** 2023-12-05 19:07 UTC
Labels: type: feature request, emulators: functions
