### ISSUE TITLE
Program not working when using "-P" option

### ISSUE THREAD

**Issue by olivierchatry** [firebase/firebase-tools#172] opened 2016-06-21 12:01 UTC
Hello,
I'm using firebase-cli in a docker container. I'm processing data, and would like to put some values inside a firebase to indicate the state of the processing.

To do that, I'm using the CLI tool. I generated a token using the login:ci ( and verified the token is working by executing some commands using it ). 

My problems is, as soon as I want to use "database:update", or for the matter, any command that use an actual firebase, I get this error : 
> "error": "Firebase error. Please ensure that you spelled the name of your Firebase correctly"

I pass the "-P" option, using the value returned by "firebase list".

When I turn debug on, I get this :

```js
 "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "undefined.firebaseio.com",
        "port": 443,
        "hostname": "undefined.firebaseio.com",
        "hash": null,
        "search": "?auth=[edited]",
        "query": "auth=[edited]",
        "pathname": "/users.json",
        "path": "/users.json?auth=[edited]",
        "href": "https://undefined.firebaseio.com/users.json?auth=[edited]"
      },
      "method": "GET",
      "headers": {}
    }
```

Where "undefined" should normally be my project name. This behavior happen on linux and windows, any chance I do something wrong ?

**Comment by mbleigh** [comment] 2016-06-21 17:20
I'm not able to reproduce this on my own project, I ran:

    firebase database:get / -P <my_project_id>

...and it worked just fine. Are you specifying the **project id** (*not* the instance/firebaseio subdomain) when you make the command?

**Comment by olivierchatry** [comment] 2016-06-21 18:29
I'm not sure if it is the right way of doing, but I'm getting the ID by
doing a list using the CLI tool, but the ID is the name as the firebaseio
subdomain.

Is there anyway to get this ID other than using the list command ?

**Comment by mbleigh** [comment] 2016-06-21 19:22
The project id is often the same as the instance name, it's just not universally the case. If it's different, `firebase list` will show two names for it.

Do you have a `.firebaserc` in the directory you're running the command from? If so, what are the contents? Are you able to run the command from your local machine, just not from the CI machine?

**Comment by olivierchatry** [comment] 2016-06-21 19:39
I do not have a firerc file. I tried on my computer, same result :(

**Comment by mbleigh** [comment] 2016-06-21 20:35
It seems like this could use some personal debugging help. I'd encourage you to [reach out to Firebase Support](https://firebase.google.com/support/contact/troubleshooting/) so we can actually discuss your exact commands/projects etc. and see if we can debug this thing. Since I'm unable to reproduce, I'm going to close the issue here.

**Closed by mbleigh** 2016-06-21 20:35 UTC

**Comment by olivierchatry** [comment] 2016-06-28 14:12
Ok, I have done some debugging, checked out firebase-tool, and it really seems like the "project" options is never really used. 

If I do a "database:get", using a token and -P option, everything get parsed correctly ( stepped into the code ). So we endup with an "option" object that looks correct ( at least it contains valid value ). 

I then put a breakpoint iside "database-get", in action function, inside the promise ( line  64 ), where the URL is actually generated : 

```js
var url = utils.addSubdomain(api.realtimeOrigin, options.instance) + path + '.json?';
```

I think the problem is here : options.instance is `undefined` for me. I think the correct line should be :

```js
var subDomain = options.project || options.instance; // get "-P" option value first, else fallback to project folder data.
var url = utils.addSubdomain(api.realtimeOrigin, subDomain ) + path + '.json?';
```

**Comment by olivierchatry** [comment] 2016-06-28 14:47
Note : I'm not sure about the whole requireAuth, but from the output / code it seems to verify if the token is valid and setup everything correctly.
