### ISSUE TITLE
Unable to Point Firebase Functions Emulator to Directory Outside Web Client's Root

### ISSUE THREAD

**Issue by TS22082** [firebase/firebase-tools#5961] opened 2023-06-11 18:56 UTC
### [REQUIRED] Environment info

firebase-tools: 12.3.1
Platform: M1 Mac OS

### [REQUIRED] Test case

- ios client
- android client

- web client
  - src
  - firebase.json (source: ../br_functions/functions)
- br_functions
  - functions
    - index.js   

### [REQUIRED] Steps to reproduce

1.) Set up web, Android, iOS, and functions projects and deploy. 
  - All projects work together, and the same functions are called from iOS, Android, and web clients.
 
2.) Set up the development environment for the web client.

3.) Unable to point the emulator to the `functions` folder located outside the root directory of the web client.
  - Works only when the `functions` folder is copied to the root directory.
  - The web client's front end root directory should be kept separate from the backend.

### [REQUIRED] Expected behavior

- I should be able to point the functions' emulator to works from any directory.

```
    "functions": {
      "port": 5001,
      "source": "../br_functions/functions" // This does not work, still looks for functions in web client root
    }
```

**Comment by joehan** [comment] 2023-06-13 18:47
Closing this as a duplicate of #653 - the folks there have come up with some workarounds for this, and keeping this discussion in one place helps us make a case that we ought to prioritize supporting different directory structures.

**Closed by joehan** 2023-06-13 18:47 UTC
Labels: type: bug, emulators: functions
