### ISSUE TITLE
app distribution error

### ISSUE THREAD

**Issue by junddao** [firebase/firebase-tools#7188] opened 2024-05-17 07:39 UTC
### [REQUIRED] Environment info

**firebase-tools:**
13.7.3

**Platform:**
macOS
### [REQUIRED] Test case
when I try to distribute my app in firebase app distribute, verification error.
(all case have error.  - manual upload and use fastlane)

### [REQUIRED] Steps to reproduce
1. build apk
2. upload apk into firebase app distribute
3. occur error during verify

### [REQUIRED] Expected behavior
successfully upload.

### [REQUIRED] Actual behavior
failed upload

if try to upload use fastlane, can see this log.
```
+-------------------------------------------------------------+
|                      fastlane summary                       |
+------+----------------------------------------+-------------+
| Step | Action                                 | Time (in s) |
+------+----------------------------------------+-------------+
| 1    | default_platform                       | 0           |
| 2    | Switch to ios                          | 0           |
|      | before_send_slack_message lane         |             |
| 3    | slack                                  | 0           |
| 4    | cocoapods                              | 4           |
| 5    | Switch to ios flutter_build_ios lane   | 0           |
| 6    | flutter build ipa --flavor staging -t  | 209         |
|      | lib/main_staging.dart -                |             |
| 💥   | firebase_app_distribution              | 347         |
| 8    | slack                                  | 0           |
+------+----------------------------------------+-------------+

[16:20:07]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [!] It took longer than expected to process your IPA, please try again. (FastlaneCore::Interface::FastlaneCrash)
    https://github.com/fastlane/fastlane/issues/22033 [open] 4 💬
    5 minutes ago

➡️  [deliver][pilot] use altool instead of using iTMSTransporter for Xcode 14
    https://github.com/fastlane/fastlane/pull/20631 [closed] 58 💬
    15 Sep 2022

➡️  Firebase App Distribution: 202 Response with Processing Error Doesn't Fail Lane
    https://github.com/fastlane/fastlane/issues/18590 [closed] 6 💬
    26 Oct 2021

and 4 more at: https://github.com/fastlane/fastlane/search?q=It%20took%20longer%20than%20expected%20to%20process%20your%20IPA%2C%20please%20try%20again.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] It took longer than expected to process your IPA, please try again. (FastlaneCore::Interface::FastlaneCrash)
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-plugin-firebase_app_distribution-0.9.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:265:in `poll_upload_release_operation'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-plugin-firebase_app_distribution-0.9.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:61:in `run'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:69:in `block (2 levels) in parsing_binding'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Users/miro/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
        from /Users/miro/.rbenv/versions/3.3.0/bin/fastlane:25:in `load'
        from /Users/miro/.rbenv/versions/3.3.0/bin/fastlane:25:in `<main>'
```

**Comment by michaelvillanda-nx** [comment] 2024-05-17 07:47
Also encountering the same issue

```
INFO [2024-05-17 09:35:06.23]: 🔐 Authenticating with --firebase_cli_token parameter
INFO [2024-05-17 09:35:06.39]: 📡 Uploading the IPA.
INFO [2024-05-17 09:35:30.70]: 🕵️ Validating upload…

ERROR [2024-05-17 09:40:51.22]: It took longer than expected to process your IPA, please try again.
```

Tried also uploading manually getting the ff error

![image](https://github.com/firebase/firebase-tools/assets/107019485/927f8b20-8aea-48fc-9c82-2b1c27da484c)

**Comment by jaceknijaki** [comment] 2024-05-17 08:17
I have same problem when trying to upload AAB using cli
```
firebase appdistribution:distribute artifacts/app-prod-release.aab \
    --app "***" \
    --groups "***" \
    --release-notes "${RELEASE_NOTES}"
  
i  uploading binary...

Error: failed to upload release. Task index 0 failed: timed out after 300000ms.
```

**Comment by junddao** [comment] 2024-05-17 08:18
refer to this.

https://status.firebase.google.com/incidents/t1HKQ1ACyGpThDf2dNJv

**Comment by jansencalderon** [comment] 2024-05-17 08:35
I have the same problem on bitrise

**Comment by TaniiSR** [comment] 2024-05-17 10:05
Same issue is facing

**Comment by looptheloop88** [comment] 2024-05-17 10:35
Thanks for the reports. Per checking, there’s an ongoing issue where uploading APK/IPA files via console or CLI is failing. Our engineering team is currently working on resolving this issue.

Apologies for the inconvenience this may have caused. We will update this thread once the issue is resolved or keep an eye out on the status dashboard to get more information about the progress of the issue. Thank you.

**Comment by florent37** [comment] 2024-05-17 12:08
same issue also uploading an apk

**Comment by looptheloop88** [comment] 2024-05-17 12:33
Thanks for patiently waiting. The issue is now resolved. https://status.firebase.google.com/incidents/t1HKQ1ACyGpThDf2dNJv

**Comment by junddao** [comment] 2024-05-17 12:41
> Thanks for patiently waiting. The issue is now resolved. https://status.firebase.google.com/incidents/t1HKQ1ACyGpThDf2dNJv

Thank you for your quick response. @looptheloop88

**Closed** 2024-05-17 12:41 UTC
Labels: type: bug, api: appdistribution
