### ISSUE TITLE
Firebase Error

### ISSUE THREAD

**Issue by gkhnyrdm** [firebase/firebase-tools#6390] opened 2023-09-21 19:43 UTC
[debug] [2023-09-21T19:33:34.521Z] ----------------------------------------------------------------------
[debug] [2023-09-21T19:33:34.523Z] Command:       /usr/local/bin/firebase /Users/gokhanyordem/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase deploy --only functions --debug
[debug] [2023-09-21T19:33:34.523Z] CLI Version:   12.5.2
[debug] [2023-09-21T19:33:34.524Z] Platform:      darwin
[debug] [2023-09-21T19:33:34.524Z] Node Version:  v16.16.0
[debug] [2023-09-21T19:33:34.532Z] Time:          Thu Sep 21 2023 22:33:34 GMT+0300 (GMT+03:00)
[debug] [2023-09-21T19:33:34.533Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-09-21T19:33:34.626Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-09-21T19:33:34.631Z] > authorizing via signed-in user (mtglobalyazilim@gmail.com)
[debug] [2023-09-21T19:33:34.633Z] [iam] checking project mtglobal-b32ab for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[debug] [2023-09-21T19:33:34.638Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/mtglobal-b32ab:testIamPermissions [none]
[debug] [2023-09-21T19:33:34.639Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/mtglobal-b32ab:testIamPermissions x-goog-quota-user=projects/mtglobal-b32ab
[debug] [2023-09-21T19:33:34.640Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/mtglobal-b32ab:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}
[debug] [2023-09-21T19:33:35.763Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/mtglobal-b32ab:testIamPermissions 200
[debug] [2023-09-21T19:33:35.767Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/mtglobal-b32ab:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}
[debug] [2023-09-21T19:33:35.769Z] >>> [apiv2][query] POST https://iam.googleapis.com/v1/projects/mtglobal-b32ab/serviceAccounts/mtglobal-b32ab@appspot.gserviceaccount.com:testIamPermissions [none]
[debug] [2023-09-21T19:33:35.770Z] >>> [apiv2][body] POST https://iam.googleapis.com/v1/projects/mtglobal-b32ab/serviceAccounts/mtglobal-b32ab@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[debug] [2023-09-21T19:33:36.784Z] <<< [apiv2][status] POST https://iam.googleapis.com/v1/projects/mtglobal-b32ab/serviceAccounts/mtglobal-b32ab@appspot.gserviceaccount.com:testIamPermissions 200
[debug] [2023-09-21T19:33:36.787Z] <<< [apiv2][body] POST https://iam.googleapis.com/v1/projects/mtglobal-b32ab/serviceAccounts/mtglobal-b32ab@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[info] 
[info] === Deploying to 'mtglobal-b32ab'...
[info] 
[info] i  deploying functions 
[info] ✔  functions: Finished running predeploy script. 
[debug] [2023-09-21T19:33:36.796Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/mtglobal-b32ab [none]
[debug] [2023-09-21T19:33:37.401Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/mtglobal-b32ab 200
[debug] [2023-09-21T19:33:37.404Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/mtglobal-b32ab {"projectId":"mtglobal-b32ab","projectNumber":"452911081105","displayName":"MtGlobal","name":"projects/mtglobal-b32ab","resources":{"hostingSite":"mtglobal-b32ab","realtimeDatabaseInstance":"mtglobal-b32ab-default-rtdb","storageBucket":"mtglobal-b32ab.appspot.com","locationId":"us-central"},"state":"ACTIVE","etag":"1_0e47ea6c-8f04-4245-83ec-e5ceec3a8409"}
[info] i  functions: preparing codebase default for deployment 
[info] i  functions: ensuring required API cloudfunctions.googleapis.com is enabled... 
[info] i  functions: ensuring required API cloudbuild.googleapis.com is enabled... 
[info] i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled... 
[debug] [2023-09-21T19:33:37.410Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/cloudfunctions.googleapis.com [none]
[debug] [2023-09-21T19:33:37.410Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/cloudfunctions.googleapis.com x-goog-quota-user=projects/mtglobal-b32ab
[debug] [2023-09-21T19:33:37.421Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/runtimeconfig.googleapis.com [none]
[debug] [2023-09-21T19:33:37.423Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/runtimeconfig.googleapis.com x-goog-quota-user=projects/mtglobal-b32ab
[debug] [2023-09-21T19:33:37.430Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/cloudbuild.googleapis.com [none]
[debug] [2023-09-21T19:33:37.432Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/cloudbuild.googleapis.com x-goog-quota-user=projects/mtglobal-b32ab
[debug] [2023-09-21T19:33:37.437Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/artifactregistry.googleapis.com [none]
[debug] [2023-09-21T19:33:37.439Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/artifactregistry.googleapis.com x-goog-quota-user=projects/mtglobal-b32ab
[debug] [2023-09-21T19:33:38.659Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/cloudfunctions.googleapis.com 200
[debug] [2023-09-21T19:33:38.660Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/cloudfunctions.googleapis.com [omitted]
[info] ✔  functions: required API cloudfunctions.googleapis.com is enabled 
[debug] [2023-09-21T19:33:38.671Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/runtimeconfig.googleapis.com 200
[debug] [2023-09-21T19:33:38.672Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/runtimeconfig.googleapis.com [omitted]
[debug] [2023-09-21T19:33:38.674Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/cloudbuild.googleapis.com 200
[debug] [2023-09-21T19:33:38.674Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/cloudbuild.googleapis.com [omitted]
[info] ✔  functions: required API cloudbuild.googleapis.com is enabled 
[debug] [2023-09-21T19:33:38.740Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/artifactregistry.googleapis.com 200
[debug] [2023-09-21T19:33:38.740Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/mtglobal-b32ab/services/artifactregistry.googleapis.com [omitted]
[info] ✔  artifactregistry: required API artifactregistry.googleapis.com is enabled 
[debug] [2023-09-21T19:33:38.742Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/mtglobal-b32ab/adminSdkConfig [none]
[debug] [2023-09-21T19:33:39.220Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/mtglobal-b32ab/adminSdkConfig 200
[debug] [2023-09-21T19:33:39.220Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/mtglobal-b32ab/adminSdkConfig {"projectId":"mtglobal-b32ab","databaseURL":"https://mtglobal-b32ab-default-rtdb.firebaseio.com","storageBucket":"mtglobal-b32ab.appspot.com","locationId":"us-central"}
[debug] [2023-09-21T19:33:39.222Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/mtglobal-b32ab/configs [none]
[debug] [2023-09-21T19:33:40.569Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/mtglobal-b32ab/configs 200
[debug] [2023-09-21T19:33:40.570Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/mtglobal-b32ab/configs {}
[debug] [2023-09-21T19:33:40.578Z] Validating nodejs source
[debug] [2023-09-21T19:33:41.207Z] checkFunctionsSDKVersion encountered error: Unexpected end of JSON input {}
[debug] [2023-09-21T19:33:41.210Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "eslint --ext .js,.ts .",
    "build": "tsc",
    "build:watch": "tsc --watch",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "16"
  },
  "main": "src/index.ts",
  "dependencies": {
    "firebase-admin": "^10.0.2",
    "firebase-functions": "^3.18.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.25.4",
    "firebase-functions-test": "^0.2.0",
    "typescript": "^4.5.4"
  },
  "private": true
}
[debug] [2023-09-21T19:33:41.211Z] Building nodejs source
[info] i  functions: Loading and analyzing source code for codebase default to determine what to deploy 
[debug] [2023-09-21T19:33:41.212Z] Could not find functions.yaml. Must use http discovery
[debug] [2023-09-21T19:33:41.231Z] Found firebase-functions binary at '/Users/gokhanyordem/StudioProjects/mtglobaladmin/node_modules/.bin/firebase-functions'
[info] Serving at port 8321

[debug] [2023-09-21T19:33:41.786Z] Got response code 400; body Failed to generate manifest from function source: SyntaxError: Cannot use import statement outside a module
[info] shutdown requested via /__/quitquitquit

[error] 
[error] Error: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error

This is my firebase_debug.log

please help me?

**Comment by aalej** [comment] 2023-09-22 10:59
Hi @gkhnyrdm, based on this log `SyntaxError: Cannot use import statement outside a module`, it looks like you’re encountering an error because you’re trying to use the `import` syntax instead of `require`. If you want to use ES modules, try adding `"type": "module"` to your `package.json`.

If the above suggestion does not work, could you file a new issue and specify the details using the provided template? This would make it easier to troubleshoot and identify the cause of the error. That being said, I'll be closing this for now.  Thanks!

**Closed by aalej** 2023-09-22 10:59 UTC
Labels: type: feature request

**Comment by gkhnyrdm** [comment] 2023-09-22 11:17
{
  "name": "functions",
  "scripts": {
    "lint": "eslint --ext .js,.ts .",
    "build": "tsc",
    "build:watch": "tsc --watch",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "16"
  },
  "main": "src/index.ts",
  "dependencies": {
    "firebase-admin": "^10.0.2",
    "firebase-functions": "^3.18.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.25.4",
    "firebase-functions-test": "^0.2.0",
    "typescript": "^4.5.4"
  },
  "private": true
}


this is my package.json
using typescript
