### ISSUE TITLE
storage.onFinalize function can't download storage file inside emulator (returns CONTENT_DOWNLOAD_MISMATCH).

### ISSUE THREAD

**Issue by giorgenes** [firebase/firebase-tools#3486] opened 2021-06-12 06:13 UTC
I'm writing specs for a function that is triggered on `storage.onFinalize`. The function simply downloads the file and creates some firestore objects based on the content of the file.
The function works in production.

The test file uploads a file using the admin SDK, which correct triggers the function on the emulator. The issue happens when the function tries to download the file which causes "content mismatch" error:

```
"RequestError: The downloaded data did not match the data from the server. To be sure the content is the same, you should download the file again.\n    at PassThrough.onComplete (/Users/giorgenes/work/openfit/firebase/functions/node_modules/@google-cloud/storage/build/src/file.js:1001:43)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5) {\n  code: 'CONTENT_DOWNLOAD_MISMATCH'\n}"}
```

It seems the file comes back as empty, even trying to download the file from the UI just gives an empty screen.

### [REQUIRED] Environment info

**firebase-tools:** 9.12.0 (Also happens on 9.12.1).

**Platform:**  macOS

### [REQUIRED] Test case

Function:

```javascript
exports.batchLoadExercises = functions.storage
  .object()
  .onFinalize(async (object) => {
    const fileBucket = object.bucket; // The Storage bucket that contains the file.
    const filePath = object.name; // File path in the bucket.
    const fileName = path.basename(filePath);

    const bucket = admin.storage().bucket(fileBucket);
    const tempFilePath = path.join(os.tmpdir(), fileName);

  // THIS IS WHERE THE ERROR HAPPENS IN THE EMULATOR
    await bucket
      .file(filePath)
      .download({ destination: tempFilePath })
      .catch(functions.logger.log);
    functions.logger.log('Image downloaded locally to', tempFilePath);

  // does something with the file
  });
```

Test file

```javascript
  it('test ', async () => {
    // this correctly triggers the upload in the emulator
    await storage.bucket('default-bucket').upload('file.json', {
      destination: 'file.json',
    });
  });
```

### [REQUIRED] Steps to reproduce

1. Create the provided function
2. Add the specified unit test
3. Run the mocha tests under the emulator with `firebase emulators:exec`
4. Observe the MISMATCH_ERROR in the console log when the function is triggered

### [REQUIRED] Expected behavior

I expect the file to be downloaded correctly by the function.

### [REQUIRED] Actual behavior

The `download()` function return a mismatch content error inside the function.

**Comment by samtstern** [comment] 2021-06-15 10:12
@giorgenes thanks for filing! I think this is a duplicate of #3469, or at least the root cause looks to be the same. Let's track this there.

**Closed by samtstern** 2021-06-15 10:12 UTC
