### ISSUE TITLE
Firestore emulator is not working (Expression never evaluated)

### ISSUE THREAD

**Issue by AndroidNils** [firebase/firebase-tools#2264] opened 2020-05-21 09:20 UTC
### Environment info
* `firebase --version: 8.4.0` (same issue with 8.3.0 and 8.2.0)
* Platform: macOS Catalina 10.15.4

### Test case
Firestore rules:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /Test/{testId} {
      allow read, write: if isLoggedIn();
    }

    function isLoggedIn() {
        return request.auth.uid != null
    }
  }
}
```

### Steps to reproduce
1. Run `firebase emulators:start --only firestore`
2. Go to `http://localhost:8080/emulator/v1/projects/projektName:ruleCoverage.html`

### Expected behavior
Firestore emulator should working.

### Actual behavior
Normally I test my security rules for Firestore with the Firestore emulator. Until a few weeks ago, everything worked wonderfully. I changed nothing and now the Firestore emulator is freaking out. I can't use `request` and `resources` anymore.

All Firestore tests are failing.

If i visit http://localhost:8080/emulator/v1/projects/projektName:ruleCoverage.html, I get this message: `Expression never evaluated`

![image](https://user-images.githubusercontent.com/24459435/82543700-424b2300-9b54-11ea-9f67-b9c4837779fb.png)

I already tried:
* Restart computer
* Delete `node_modules` and run `npm install`
* Create new folder & run `firebase init` --> Same issue
* Go to an old commit (when everything worked) in my project

**Comment by samtstern** [comment] 2020-06-02 14:16
@AndroidNils sorry for the delayed response.  Can you show the test you're running that fails and how you're running it exactly?

**Comment by AndroidNils** [comment] 2020-06-04 19:39
## Rules:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{documents=**} {
      allow read, write: if true;
    }
  }
}
```

## Test
I use for testing `jest`. Version is `24.9.0`

```
const { setupDB, teardown } = require('../spec/helpers');

describe('test rules', () => {
    let db;

    const homeworkCollectionName = "Homework";
    const homework = {
        courseID: "englishId",
        title: "title",
    }

    afterAll(async () => {
        await teardown();
    });

    describe('Add Homework', () => {
        test('allow user to add a homework)', async () => {
            db = await setupDB("user");
            homeworkRef = db.collection(homeworkCollectionName);
            await expect(homeworkRef.add(homework)).toAllow();
        });
    });
});
```

<details>
<summary>helpers.js</summary>

```
const { mockData } = require('./mock_data');
const firebase = require('@firebase/testing');
const fs = require('fs');

module.exports.setupDB = async (uid) => {
  const projectId = `rules-spec-${Date.now()}`;
  
  let auth;
  if(uid) {
    auth = { uid: uid };
  }

  const app = await firebase.initializeTestApp({
    projectId,
    auth,
  });

  const db = app.firestore();

  // Write mock documents before rules
  let data = mockData();
  for (const key in data) {
    const ref = db.doc(key);
    await ref.set(data[key]);
  }

  // Apply rules
  await firebase.loadFirestoreRules({
    projectId,
    rules: fs.readFileSync('firestore.rules', 'utf8')
  });

  return db;
};

module.exports.teardown = async () => {
  Promise.all(firebase.apps().map(app => app.delete()));
};

expect.extend({
  async toAllow(x) {
    let pass = false;
    try {
      await firebase.assertSucceeds(x);
      pass = true;
    } catch (err) { }

    return {
      pass,
      message: () => 'Expected Firebase operation to be allowed, but it failed'
    };
  }
});

expect.extend({
  async toDeny(x) {
    let pass = false;
    try {
      await firebase.assertFails(x);
      pass = true;
    } catch (err) { }
    return {
      pass,
      message: () =>
        'Expected Firebase operation to be denied, but it was allowed'
    };
  }
});
```
</details>

## Result
![image](https://user-images.githubusercontent.com/24459435/83802745-a10fb100-a6ab-11ea-95fa-40df42c0123a.png)

**Comment by samtstern** [comment] 2020-06-05 20:03
@AndroidNils I was not able to reproduce this as you said.  The only thing I did different was remove the `mockData` bit of your `helpers` file since I didn't have the data.

```
> jest test.spec.js

 PASS  ./test.spec.js
  test rules
    Add Homework
      ✓ allow user to add a homework) (1349ms)
```

**Comment by samtstern** [comment] 2020-06-05 20:12
Here's my rules coverage:
<img width="494" alt="Screen Shot 2020-06-05 at 4 10 18 PM" src="https://user-images.githubusercontent.com/8466666/83918642-2a27f600-a747-11ea-9bb6-99707cc021f5.png">

Just to make sure we're on the same page here's my `package.json`:
```
{
  "name": "fbt-2264",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest test.spec.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@firebase/testing": "^0.20.0",
    "jest": "^24.9.0"
  }
}
```

So I'm not sure why it's failing for you but I don't think there's an actual bug in the emulators.  Closing this as not reproducible for now, let me know if you discover something else.

**Closed by samtstern** 2020-06-05 20:12 UTC
Labels: Needs: Attention, emulator-suite, emulators: firestore
