### ISSUE TITLE
Firebase functions emulator fails to start with FirebaseError: HTTP Error: 403, Permission denied on resource project demo-project

### ISSUE THREAD

**Issue by just7mile** [firebase/firebase-tools#5718] opened 2023-04-21 06:21 UTC
### [REQUIRED] Environment info

**firebase-tools:** 11.28.0

**Platform:** MacOS

### [REQUIRED] Test case

After upgrading to the version 11.28.0, emulator suit fails to start with the error `functions: Failed to load function definition from source: FirebaseError: HTTP Error: 403, Permission denied on resource project demo-project.`.

Double checked by downgrading to the version 11.27.0 and **it works with the version 11.27.0.**

### [REQUIRED] Steps to reproduce

Start an emulator suite for a demo project (staring with `demo-`).

### [REQUIRED] Expected behavior

Should start all emulators.

### [REQUIRED] Actual behavior

Functions emulator fails with the error `functions: Failed to load function definition from source: FirebaseError: HTTP Error: 403, Permission denied on resource project demo-project.`.

**Comment by aalej** [comment] 2023-04-24 12:53
Hi @just7mile, thanks for reaching out to us. Could you provide more details on how to reproduce the issue, such as how you're setting up the functions source directory, are you running a command similar to `firebase emulators:start --project demo-proj`?

**Comment by just7mile** [comment] 2023-04-24 17:28
> Thanks for providing the config files and the code snippet you used to run the emulator. I tried replicating the issue you mentioned using `firebase-tools` v11.28.0 on a macOS machine, but I did not encounter any errors running the emulator that uses a demo-project.
> 
> Could you provide the contents of your `firebase-debug.log` file so that we can have a better understanding of what might be causing this? Also, would it be possible if you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) so that I can reproduce the issue?

I think the problem is with the secrets as `firebase-debug.log` shows:
```
[debug] [2023-04-24T17:19:26.665Z] >>> [apiv2][query] GET https://secretmanager.googleapis.com/v1/projects/demo-project/secrets/EMAIL_PASSWORD [none]
[debug] [2023-04-24T17:19:27.101Z] <<< [apiv2][status] GET https://secretmanager.googleapis.com/v1/projects/demo-project/secrets/EMAIL_PASSWORD 403
[debug] [2023-04-24T17:19:27.101Z] <<< [apiv2][body] GET https://secretmanager.googleapis.com/v1/projects/demo-project/secrets/EMAIL_PASSWORD {"error":{"code":403,"message":"Permission denied on resource project demo-project.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Google developer console API key","url":"https://console.developers.google.com/project/demo-project/apiui/credential"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"CONSUMER_INVALID","domain":"googleapis.com","metadata":{"service":"secretmanager.googleapis.com","consumer":"projects/demo-project"}}]}}
[error] ⬢  functions: Failed to load function definition from source: FirebaseError: HTTP Error: 403, Permission denied on resource project demo-project. {"metadata":{"emulator":{"name":"functions"},"message":"Failed to load function definition from source: FirebaseError: HTTP Error: 403, Permission denied on resource project demo-project."}}
```

It seems to ignore local secrets file, because in the `functions` folder I have a `.secret.local` file with the `EMAIL_PASSWORD` in it. I commented out `defineSecret(...)` and it worked.

**Comment by aalej** [comment] 2023-04-25 16:26
Thanks for the additional information @just7mile. It looks like the issue you're experiencing is similar to [#5520](https://github.com/firebase/firebase-tools/issues/5520). Though your issue may not be the same since you mentioned that you encountered no errors when using `firebase-tools` v11.27.0. 

I tried using `defineSecret(...)` as you mentioned and I was able to reproduce the error on v11.28.0 and I also encountered the error on v11.27.0. Would it be okay if you could provide a sample functions code snippet so that I can try to make this work on v11.27.0?

**Comment by just7mile** [comment] 2023-04-25 17:31
Sure! I use [nodemailer](https://www.npmjs.com/package/nodemailer) to send emails. Here is my `functions/src/index.ts`:
```ts
import { defineSecret, defineString } from 'firebase-functions/params';
import { runWith } from 'firebase-functions/v1';
import { createTransport } from 'nodemailer';

const emailLogin = defineString('EMAIL_LOGIN');
const emailPassword = defineSecret('EMAIL_PASSWORD');

export const sendEmail = runWith({
  memory: '128MB',
  secrets: [emailPassword],
  maxInstances: 1,
}).https.onRequest(async (_, resp) => {
  try {
    const emailer = createTransport({
      service: 'gmail',
      auth: { user: emailLogin.value(), pass: emailPassword.value() },
    });

    await emailer.sendMail({
      from: `Demo Project Team <${emailLogin.value()}>`,
      to: 'email@example.com', // should be a real email address.
      subject: 'Hello there!',
      text: 'Just testing...',
    });
    resp.send('ok');
  } catch (e) {
    const { error } = await import('firebase-functions/logger');
    error(e);
    resp.send(JSON.stringify(e));
  }
});
```
The configurations are mentioned in this [comment](https://github.com/firebase/firebase-tools/issues/5718#issuecomment-1520117410) and I run the emulators using the mentioned script. The `EMAIL_LOGIN` is located in the `functions/.env` file and the `EMAIL_PASSWORD` is located in the `functions/.secret.local`.

**Comment by colerogers** [comment] 2023-04-25 18:52
Hi @just7mile it looks like this issue is similar to the issue that @aalej linked above - #5520

Can you try the workaround posted in that thread to unblock you for the time being? You'd just need to comment out the `defineSecret(..)`, replace `secrets: [emailPassword]` with `secrets: ['EMAIL_PASSWORD],`, and use `process.env. EMAIL_PASSWORD` to access it.

I'm going to close this issue as a duplicate so we can redirect everyone to the other issue. Thanks and sorry that you ran into this

**Closed by colerogers** 2023-04-25 18:52 UTC
Labels: type: bug, Needs: Attention, emulators: functions

**Comment by abegehr** [comment] 2023-06-26 17:29
I ran into the same issue. In-case you want to keep a similar syntax as with `defineSecret()`, you can do something like this:

```typescript
const slackWebhookUrl = { name: 'SLACK_WEBHOOK_URL', value: () => process.env.SLACK_WEBHOOK_URL as string }

export const handler = region('europe-west1')
  .runWith({ secrets: [slackWebhookUrl].map((secret) => secret.name) })
  .https.onCall(async (name, context) => {
    // …
    await sendSlackMessage(slackWebhookUrl.value(), { … })
  })
```
Works as expected in emulator with `demo-`-project.

**Comment by pepoospina** [comment] 2024-05-06 08:22
That workaround is not the easiest. Simply define the secrets in .secret.local as empty vars in your .env file
