### ISSUE TITLE
emulator events missing properties

### ISSUE THREAD

**Issue by jsmusgrave** [firebase/firebase-tools#2982] opened 2020-12-30 01:27 UTC
### [REQUIRED] Environment info

**firebase-tools:**
9.1.0

**Platform:**

MacOS Catalina
10.15.7

### [REQUIRED] Test case

```
import * as functions from 'firebase-functions';

import * as admin from 'firebase-admin';
admin.initializeApp();

export const createUserRecord = functions.auth
  .user()
  .onCreate((user, context) => {
	console.log(JSON.stringify(context));
	return Promise.resolve();
  });
```

### [REQUIRED] Steps to reproduce
Create a user.
Observe the log to see the context which contains no timestamp.

### [REQUIRED] Expected behavior

Expected to see timestamp and eventId properties on the context provided when a user is created.
Base upon: https://firebase.google.com/docs/reference/functions/cloud_functions_.eventcontext

No timestamp or eventId property is provided on the context provided when a user is created.

### [REQUIRED] Actual behavior

I observe:
```
:17:48
I
function[createUserRecord]
Beginning execution of "createUserRecord"
18:17:48
I
function[createUserRecord]
{
  "eventType": "google.firebase.auth.user.create",
  "resource": {
    "service": "firebaseauth.googleapis.com"
  },
  "params": {}
}
18:17:48
I
function[createUserRecord]
Finished "createUserRecord" in ~1s
```

**Comment by samtstern** [comment] 2020-12-30 10:31
@jsmusgrave thank you for reporting, this looks like it's a duplicate of https://github.com/firebase/firebase-tools/issues/2752 so  let's just track it there.

**Closed by samtstern** 2020-12-30 10:31 UTC
