### ISSUE TITLE
Firestore emulator console: path containing non-existing document not shown

### ISSUE THREAD

**Issue by loucou** [firebase/firebase-tools#2607] opened 2020-09-09 09:32 UTC
### [REQUIRED] Environment info

**firebase-tools:**
8.10.0

**Platform:**
Windows

### [REQUIRED] Test case

	async function writeLandmark() {
		var bridgeRef = db.collection("cities").doc("SF").collection("landmarks").doc("bridge");
		await bridgeRef.set({ name: "The Golden Gate Bridge" });
	};

### [REQUIRED] Steps to reproduce

- prereq: "cities" collection and "SF" document must NOT exist
- call writeLandmark

### [REQUIRED] Expected behavior

The "bridge" document is created. The "SF" document should be displayed in italics to match with the real Firestore console

### [REQUIRED] Actual behavior

When opening the Firestore emulator console, there is no cities collection displayed, so it looks like the "bridge" was not created, but it was
Note: when typing the path manually: "/cities/SF/landmarks/bridge", the document is visible.

**Comment by samtstern** [comment] 2020-09-09 10:04
@loucou this is a duplicate of https://github.com/firebase/firebase-tools-ui/issues/273

Please follow along there!

**Closed by samtstern** 2020-09-09 10:04 UTC

**Comment by loucou** [comment] 2020-09-09 11:31
Thank you for pointing this out. Sorry I missed the original issue.
