### ISSUE TITLE
v12.5.4 Emulator Does Not Update / Set Existing Document From Functions

### ISSUE THREAD

**Issue by Teeskid** [firebase/firebase-tools#6374] opened 2023-09-18 16:26 UTC
### [REQUIRED] Environment info

**firebase-tools: 12.5.4**

**Platform: Parrot OS Electro ara - Linux (Debian)**

### [REQUIRED] Test case
On document write (set or update) from functions emularor

### [REQUIRED] Steps to reproduce
Create a project and setup firestore & functions emulator
Create a document using the functions emulator
Try writing a doc from the function by calling set / update

### [REQUIRED] Expected behavior
The document is expected to be written successfully

### [REQUIRED] Actual behavior
An error is thrown which halters the function execution

{"verifications":{"app":"MISSING","auth":"VALID"},"logging.googleapis.com/labels":{"firebase-log-type":"callable-request-verification"},"severity":"DEBUG","message":"Callable request verification passed"}
>  Error: 2 UNKNOWN: 
>      at callErrorFromStatus (/home/teeskid/projects/jikstel-web/cloud/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
>      at Object.onReceiveStatus (/home/teeskid/projects/jikstel-web/cloud/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
>      at Object.onReceiveStatus (/home/teeskid/projects/jikstel-web/cloud/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
>      at Object.onReceiveStatus (/home/teeskid/projects/jikstel-web/cloud/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
>      at /home/teeskid/projects/jikstel-web/cloud/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
>      at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
>  for call at
>      at ServiceClientImpl.makeUnaryRequest (/home/teeskid/projects/jikstel-web/cloud/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
>      at ServiceClientImpl.<anonymous> (/home/teeskid/projects/jikstel-web/cloud/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
>      at /home/teeskid/projects/jikstel-web/cloud/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:227:29
>      at /home/teeskid/projects/jikstel-web/cloud/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
>      at repeat (/home/teeskid/projects/jikstel-web/cloud/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
>      at /home/teeskid/projects/jikstel-web/cloud/node_modules/google-gax/build/src/normalCalls/retries.js:118:13
>      at OngoingCallPromise.call (/home/teeskid/projects/jikstel-web/cloud/node_modules/google-gax/build/src/call.js:67:27)
>      at NormalApiCaller.call (/home/teeskid/projects/jikstel-web/cloud/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
>      at /home/teeskid/projects/jikstel-web/cloud/node_modules/google-gax/build/src/createApiCall.js:84:30 {
>    code: 2,
>    details: '',
>    metadata: Metadata {
>      internalRepr: Map(1) { 'content-type' => [Array] },
>      options: {}
>    },
>    note: 'Exception occurred in retry method that was not classified as transient'
>  }

**Comment by HansiMou** [comment] 2023-09-18 22:24
Hey @Teeskid , can you provide more info what you did so that I can reprodce?

I just retried with the same version as you. I used a [sample code](https://github.com/firebase/quickstart-testing/blob/master/cs-walkthrough/functions/index.js) with an extra logging statement. Write to a firestore `carts/{doc1}/items/{doc2}` does trigger(attachment#1) the function emulator which also updated(attachment#2) the document.
![image](https://github.com/firebase/firebase-tools/assets/5841309/2a563b52-0aea-47ee-ae62-f13d2aca86b0)

![image](https://github.com/firebase/firebase-tools/assets/5841309/6b1f2eb8-02fe-436d-81b8-10d83a34a748)

**Comment by Teeskid** [comment] 2023-09-20 06:40
@aalej It worked for me later too. I have found the issue was where i created a v2 trigger onDocumentWritten with multiple globs, I just tried it up head, didn't know weather it was supporred. I have to make for individual globs, like in apps{id} and networks/{netId}. I would have used apps{id},networks/{netId} with single trigger and check for id/netId strings. Thanks.
#Solved

**Comment by aalej** [comment] 2023-09-21 11:11
Good to know the issue is now solved. Thanks @HansiMou for looking into this and @Teeskid for sharing your resolution. I'm gonna go ahead and close this issue.

**Closed by aalej** 2023-09-21 11:11 UTC
Labels: type: bug, emulators: firestore, Needs: Attention, emulators: functions

**Comment by Teeskid** [comment] 2023-09-21 11:47
@HansiMou Thanks so much. One more thing, can I combine two or more docs from different collections separated by coma or pipe somehow?
I appreciate.
