### ISSUE TITLE
Firebase CLI doesn't work with npx from v12.0.0

### ISSUE THREAD

**Issue by yaroslavnikiforov** [firebase/firebase-tools#7052] opened 2024-04-26 12:14 UTC
Starting from version 12.0.0 firebase commands stopped working with npx.

### [REQUIRED] Environment info

**firebase-tools:** 13.7.5

**Platform:** macOS
**node:** v18.18.2
### [REQUIRED] Test case

npx firebase --help

### [REQUIRED] Steps to reproduce

1. Uninstall globally installed firebase-tools if you have it: npm uninstall -g firebase-tools.
2. Install the latest version of firebase-tools in some of the projects: npm install firebase-tools.
3. Run the following command: npx firebase --help

### [REQUIRED] Expected behavior

Expected to work like with firebase-tools < 12.0.0

### [REQUIRED] Actual behavior

sh: /Users/myuser/projects/example/node_modules/.bin/firebase: Permission denied

**Comment by aalej** [comment] 2024-04-26 17:25
Hey @yaroslavnikiforov, thanks for reaching out. I’m unable to reproduce the error you mentioned. I tried following the steps you provided, but I was able to run `npx firebase --help` without any issues. A couple of solutions to try here would be:

1. Reinstallation by running `npm uninstall firebase-tools` then `npm install firebase-tools`
2. Adding the missing permission to execute the file

Try running `cd /Users/myuser/projects/example/node_modules/.bin`, then `ls -l | grep firebase` to see if you’re missing any permissions. 

Since this looks more like a permission issue in your system rather than an issue with the CLI, I’m going to close this.

**Closed by aalej** 2024-04-26 17:25 UTC
Labels: type: bug, api: core

**Comment by yaroslavnikiforov** [comment] 2024-04-26 17:56
Thanks for the reply @aalej. 
`ls -l | grep firebase` prints the following:
```
lrwxr-xr-x  1 yaroslav  staff  37 Apr 26 15:41 firebase -> ../firebase-tools/lib/bin/firebase.js
lrwxr-xr-x  1 yaroslav  staff  51 Apr 26 15:41 firebase-functions -> ../firebase-functions/lib/bin/firebase-functions.js
```

What permissions are missing here and how to add them?
An important point for this problem is not having firebase-tools installed globally. And it also works fine for me when version is <= 11.30.0.
