### ISSUE TITLE
'Error: An unexpected error has occurred' on function deployment when failed gen2 function deployments exist

### ISSUE THREAD

**Issue by KurtMar** [firebase/firebase-tools#5093] opened 2022-10-09 00:38 UTC
### [REQUIRED] Environment info

**firebase-tools:** 11.14.1

**Platform:** MacOS Monterey 12.5.1

### [REQUIRED] Test case

Any failed function deployment (in my case a first deployment of a gen2 function) followed by another otherwise passing deployment (in my case an nth deployment of a gen1 function).

### [REQUIRED] Steps to reproduce

Unfortunately cannot reproduce a failed function deployment.

### [REQUIRED] Expected behavior

Should deploy function successfully.

### [REQUIRED] Actual behavior

Produces the following error:

```
[debug] [2022-10-09T00:07:30.901Z] TypeError: Cannot read properties of undefined (reading 'service')
    at /Users/developer/.nvm/versions/node/v16.17.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:198:113
    at Array.map (<anonymous>)
    at loadExistingBackend (/Users/developer/.nvm/versions/node/v16.17.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:198:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.existingBackend (/Users/developer/.nvm/versions/node/v16.17.0/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:174:9)
    at async prepare (/Users/developer/.nvm/versions/node/v16.17.0/lib/node_modules/firebase-tools/lib/deploy/functions/prepare.js:138:115)
    at async chain (/Users/developer/.nvm/versions/node/v16.17.0/lib/node_modules/firebase-tools/lib/deploy/index.js:33:9)
    at async deploy (/Users/developer/.nvm/versions/node/v16.17.0/lib/node_modules/firebase-tools/lib/deploy/index.js:69:5)
[error] 
[error] Error: An unexpected error has occurred.
```

### Workaround

Delete any failed function deployments from the google cloud console and deploy again.

### Possible fix

Add undefined checks around line https://github.com/firebase/firebase-tools/blob/master/src/deploy/functions/backend.ts#L531 since fn.serviceConfig is possibly undefined.

**Comment by taeold** [comment] 2022-11-02 00:07
I'm going to close this as duplicate of https://github.com/firebase/firebase-tools/issues/4800.

Feel free to re-open if I'm mistaken.

**Closed by taeold** 2022-11-02 00:07 UTC
Labels: api: functions, bug
