### ISSUE TITLE
Parameterized configuration Not Loaded in Firebase Function Emulator During Testing with Emulator

### ISSUE THREAD

**Issue by unxavi** [firebase/firebase-tools#6871] opened 2024-03-12 05:51 UTC
### [REQUIRED] Environment info

**firebase-tools:** 13.4.1

**Platform:** macOS

### [REQUIRED] Test case

https://firebase.google.com/docs/functions/config-env?gen=1st#params

```
const { onRequest } = require('firebase-functions/v2/https');
const { defineInt, defineString } = require('firebase-functions/params');

// Define some parameters
const welcomeMessage = defineString('WELCOME_MESSAGE');

export const helloWorld = onRequest((req, res) => {
    res.send(`${welcomeMessage.value()}! I am a function.`);
  }
);
```

### [REQUIRED] Steps to reproduce

1. Define environment variables in .env.local and .env.<project_ID> for WELCOME_MESSAGE.
2. Use the Firebase Emulator to run a test suite with the command: `npm run build && firebase emulators:exec 'npm test'.`
3. Observe that while the emulator logs indicate environment variables are loaded 
`i  functions: Loaded environment variables from .env.my-project, .env.local.`
 the values for WELCOME_MESSAGE are empty during test execution, leading to test failures.

### [REQUIRED] Expected behavior

Environment variables defined in .env.local and .env.<project_ID> should be correctly loaded and accessible within the test suite, allowing the test to pass by correctly utilizing the values for WELCOME_MESSAGE.

### [REQUIRED] Actual behavior

During the execution of the test suite with Firebase Emulators, environment variables WELCOME_MESSAGE is unexpectedly empty, despite emulator logs indicating that they were loaded from .env.my-project, .env.local. This behavior leads to failing tests that rely on these environment variables for execution.

However, using `npm run build && firebase emulators:start` seems to work as expected and the value of the variables are present.

**Comment by aalej** [comment] 2024-03-12 12:02
Hey @unxavi, thanks for the detailed report. Sorry to hear you encountered this issue. I’m trying to reproduce this locally, but so far I haven’t encountered the same behavior. I’m able to load the environment variables during testing.

I created this [repo](https://github.com/aalej/issues-6871) to try and replicate this, let me know in case I may have missed anything or made a mistake in the setup. By any chance, if you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), please share it as it would help us narrow down the cause of the issue.

Also, could you share your `firebase-debug.log` file? It contains a detailed log that we can use to check what caused the issue. Please remove any personal identifiable information(PII) before sharing the file.

**Comment by unxavi** [comment] 2024-03-12 17:01
Hi @aalej thanks for your response. Maybe is me who is making something wrong.

I have realize that using `fetch` api is working as expected. I was using node16 from before and I was making a mock for the request and response and that way the `helper` functions doesn't seem to see the env variables.

But anyways I have made a pull request on your repository of a failing test, the case would be of setting up for example a service to send emails and unit test it. You can see that my `helper` test does not load the value of the env files.

**Comment by inlined** [comment] 2024-03-13 03:38
The repro doesn't reproduce a failure as described. The actual test against the function passes I can even confirm it with your log statement:

```
console.log
      Hello message from local! I am a function. From your demo project with clientId ClientId123
```

The failing test is trying to load the utility method directly in the jest process, which doesn't have the params injected.

**Comment by aalej** [comment] 2024-03-13 17:04
Hey @unxavi, I tried to reproduce this issue again after merging the PR you created(thanks for submitting that). Similar to what’s mentioned above, it looks like the test is failing because it’s trying to access a parameterized variable outside a Cloud Function's runtime and execution. 

Since this currently looks like it’s working as intended, I’m going to go ahead and close the issue. However, if you feel like the current repro we have may be different from the issue you’re encountering, feel free to ask this to be reopened and share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) with us so that we can investigate further.

**Closed by aalej** 2024-03-13 17:04 UTC
Labels: type: bug, Needs: Attention, emulators: functions

**Comment by unxavi** [comment] 2024-03-15 04:48
@aalej I understand that and if I found anything else I will get back to you.

The thing is that the "old" system "Environment configuration" using the `config()` which was the recommended way, that use to work correctly doing this kind of tests where you don't pass through the cloud function itself. Now migrating a big project from the old recommended way to the new way it's pain.
