### ISSUE TITLE
Download script failing in CircleCI with linux/12.5.3

### ISSUE THREAD

**Issue by NicholasGWK** [firebase/firebase-tools#6346] opened 2023-09-08 20:42 UTC
### [REQUIRED] Environment info

Using the download script via `curl -sL https://firebase.tools | upgrade=true bash`

Doesn't install, but is attempting to install 12.5.3
**firebase-tools:**

**Platform:** Linux, cimg/android:2023.06 from CircleCI

### [REQUIRED] Test case

Run a docker container with the image: `docker run -it cimg/android:2023.06`
Run `curl -sL https://firebase.tools | bash` from the shell

### [REQUIRED] Steps to reproduce

Start a container, run the script

### [REQUIRED] Expected behavior

The script installs firebase-tools successfully

### [REQUIRED] Actual behavior

```
-- Checking your machine type...
-- Downloading binary from https://firebase.tools/bin/linux/latest
######################################################################## 100.0%#=#=#
-- Setting permissions on binary...
bash: line 255: /usr/local/bin/firebase: cannot execute binary file: Exec format error
```

To verify, I manually curl'd the 12.5.2 binary in the same container, and it works as expected

**Comment by ewilliamsfleetio** [comment] 2023-09-08 20:55
I am also able to reproduce this in Circle CI with the same image.

**Comment by Takadimi** [comment] 2023-09-08 20:58
We're seeing the same thing on our pipelines for what it's worth!

CircleCI image:
```
...
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: large
...
```

**Comment by joehan** [comment] 2023-09-08 21:03
Hey all, looking into this now - we ran into a minor issue during the release, which I thought I manually fixed - clearly, I did not do so successfully.

**Comment by joehan** [comment] 2023-09-08 21:21
Reuploaded these via our release pipeline , which builds these artifacts on Cloud Build- I had previously done so manually with artifacts built on a Mac, and I think that was the cause of the issue. Closing since these should be working as normal now, but I'll keep an eye on this issue and reopen if there are any other problems.

**Closed by joehan** 2023-09-08 21:21 UTC
Labels: type: bug

**Comment by Takadimi** [comment] 2023-09-08 21:44
Issue appears resolved for our CI -- thanks @joehan!

**Comment by joehan** [comment] 2023-09-08 21:51
Thanks for confirming!

**Comment by ewilliamsfleetio** [comment] 2023-09-11 12:58
We are up-and-running again! Thanks!
