### ISSUE TITLE
Unable to access URLs other than googleapis.com from Firebase emulator using fetch()

### ISSUE THREAD

**Issue by beepsoft** [firebase/firebase-tools#1503] opened 2019-07-14 21:09 UTC
### [REQUIRED] Environment info

**firebase-tools:** 7.1.0

**Platform:** macOS 10.13.6

### [REQUIRED] Test case

```
import 'cross-fetch/polyfill';

export const fetchTest = functions
    .region(config.firebaseRegion)
    .https.onRequest((request: Request, response: Response) => {
        fetch("https://www.wikipedia.org/", {
            method: 'GET',
        }).then(value => {
            console.log("Fetched: ", value);
        }).catch(reason => {
            console.log("Fetch failed: ", reason);
        });

        fetch("https://googleapis.com/foo", {
            method: 'GET',
        }).then(value => {
            console.log("Fetched: ", value);
        }).catch(reason => {
            console.log("Fetch failed: ", reason);
        });
        response.send("Done");
    });
```
### [REQUIRED] Steps to reproduce

I tried to run the above code in the emulator like this:

`firebase emulators:start --only functions`

then called the fetchTest function from the browser via the URL provided by the emulator.

### [REQUIRED] Expected behavior

I expected to be able to connect to external URLs via fetch. When deploying fetchTest to the firebase cloud the fetches work for any URL.

### [REQUIRED] Actual behavior

This is the output when invoking fetchTest in the emulator (http://localhost:5001/fetch-proj/europe-west1/fetchTest):

```
⚠  Unknown network resource requested!
   - URL: "https://www.wikipedia.org/"
⚠  Google API requested!
   - URL: "https://googleapis.com/foo"
   - Be careful, this may be a production service.
```
The emulator (https://github.com/firebase/firebase-tools/blob/0586ee1e23adc64b0fe8607a026ba472a6bd7d2e/src/emulator/functionsEmulatorRuntime.ts) seems to only allow access to googleapis.com URLs and nothing else. 

```
  if (href && !history[href]) {
    history[href] = true;
    if (href.indexOf("googleapis.com") !== -1) {
      new EmulatorLog("SYSTEM", "googleapis-network-access", "", {
        href,
        module: bundle.name,
      }).log();
    } else {
      new EmulatorLog("SYSTEM", "unidentified-network-access", "", {
        href,
        module: bundle.name,
      }).log();
    }
  }
```

**Comment by samtstern** [comment] 2019-07-15 16:34
@beepsoft are your network requests actually failing or are you just seeing warnings in the console?  The warnings are currently the expected behavior since we want to make sure people understand when they are potentially accessing production resources.

**Comment by beepsoft** [comment] 2019-07-15 20:15
Now that you are asking: the request actually goes through - I can see it in the logs of the called service - but I cannot get back the result, it fails with the warning.

**Comment by abeisgoat** [comment] 2019-07-15 20:45
The warnings do not block network I/O, they simply log it. The more likely issue is that you're not handling your promises correctly so the function container is closing before the network operations are done (we still see the logs though because those are created synchronously).

Let's take a look at your code....

```js
import 'cross-fetch/polyfill';

export const fetchTest = functions
    .region(config.firebaseRegion)
    // Your HTTPS function does not return a promise
    // (either explicitly or by being flagged as "async")
    .https.onRequest((request: Request, response: Response) => {
        // You begin your network I/O using the async fetch method
        // You then use that promise with .then() to log out a fetched value.
        fetch("https://www.wikipedia.org/", {
            method: 'GET',
        }).then(value => {
            console.log("Fetched: ", value);
        }).catch(reason => {
            console.log("Fetch failed: ", reason);
        });
       // This structure would normally be okay, but cloud function are ephemeral
       // When your function is "done" the container is likely to die.
       // In a database (or other trigger) we assume a function is done when the promise
       // either returns void or upon resolution of a returned promise.
       // In HTTPS functions, we assume the function is done when the HTTP connection
       // is closed. This can be done explicitly (via response.end(), response.json()) or via...

        response.send("Done");

        // By calling send() you're saying "this is ALL my responses content" and then 
        // you're closing the request.  There are other ways to send chunks of data which
        // don't close the request, but you're not doing those, so the connection closes.
        // Once it's closed the cloud functions emulator believes you're done so it kills the
        // function container. 

        // This code *may* work in production since function containers can live longer than
        // one invocation but it will be inconsistent. If you move your response.send() into the
        // final .then() of your network call you'll see the request waiting to close until the network
        // I/O completes and it will behave as expected.
    });
```

Anywho, to make a short story long, this is not a bug on our side, just async code being tricky like it be.

**Closed by abeisgoat** 2019-07-15 20:45 UTC
Labels: Needs: Attention, emulator-suite, emulators: functions

**Comment by beepsoft** [comment] 2019-07-15 20:50
@abeisgoat Thanks, you are right. If I put response.send("Done"); in the then() and catch() clauses then it prints the logs correctly and returns "Done" to the browser. My bad ...

**Comment by abeisgoat** [comment] 2019-07-15 22:00
No worries, glad I was right! Happy coding :)
