### ISSUE TITLE
firebase login error Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309

### ISSUE THREAD

**Issue by anvilation** [firebase/firebase-tools#2611] opened 2020-09-12 01:58 UTC
### Environment info

**firebase-tools:** 8.10.0

**Platform:** Windows running Node 14.2.0

### Steps to reproduce
When I attempting to run firebase login I receive the following error:
`
 firebase login --debug
i  Firebase optionally collects CLI usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.

? Allow Firebase to collect CLI usage and error reporting information? (Y/n) Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309
`
If I attempt to use firebase login --reauth it will give me an error message:
`❯ firebase login --reauth --debug

Visit this URL on this device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=xxx

Waiting for authentication...
Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309`

This will provide me with a populate - and send me back to a URL 
http://localhost:9005/?state=yyy&code=xxxA&scope=email%20https://www.googleapis.com/auth/userinfo.email%20openid%20https://www.googleapis.com/auth/cloudplatformprojects.readonly%20https://www.googleapis.com/auth/firebase%20https://www.googleapis.com/auth/cloud-platform&authuser=0&prompt=consent

This has not found. 

And because I am not able to auth (or register an auth) I am not able to init my project.

**Comment by anvilation** [comment] 2020-09-12 02:06
I found a work-around of sorts. If I am really quick on the keyboard to answer the first prompt - then the CLI will launch the browser and authenticate me

**Comment by samtstern** [comment] 2020-09-18 10:21
@anvilation this is a duplicate of https://github.com/firebase/firebase-tools/issues/1772 which is a Windows/Node issue and not a Firebase issue.

**Closed by samtstern** 2020-09-18 10:21 UTC
