### ISSUE TITLE
Emulator createSessionCookie problem

### ISSUE THREAD

**Issue by omlifeapp** [firebase/firebase-tools#2973] opened 2020-12-27 22:42 UTC
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

### [REQUIRED] Actual behavior

Auth emulator problem when signIn with web sdk and the pass the idtoken to the admin sdk.

FirebaseAuthError: An internal error has occurred. Raw server response: "{"error":{"code":400,"message":"Invalid JSON payload received. /validDuration should be string","errors":[{"message":"Invalid JSON payload received. /validDuration should be string","reason":"invalid","domain":"global"}],"status":"INVALID_ARGUMENT"}}"
>      at FirebaseAuthError.FirebaseError [as constructor] (/home/thecloud/omlife/applications/http/functions/node_modules/firebase-admin/lib/utils/error.js:44:28)
>      at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/home/thecloud/omlife/applications/http/functions/node_modules/firebase-admin/lib/utils/error.js:90:28)
>      at new FirebaseAuthError (/home/thecloud/omlife/applications/http/functions/node_modules/firebase-admin/lib/utils/error.js:149:16)
>      at Function.FirebaseAuthError.fromServerError (/home/thecloud/omlife/applications/http/functions/node_modules/firebase-admin/lib/utils/error.js:188:16)
>      at /home/thecloud/omlife/applications/http/functions/node_modules/firebase-admin/lib/auth/auth-api-request.js:1526:49
>      at processTicksAndRejections (internal/process/task_queues.js:93:5)
>      at async UserRecordAuthRepository.createSessionCookie (/home/thecloud/omlife/applications/http/functions/lib/infrastructure/domain/userRecord/user.record.auth.repository.js:21:16)
>      at async CreateSessionCookieService.invoke (/home/thecloud/omlife/applications/http/functions/lib/application/services/auth/session/create.session.cookie.service.js:14:16)
>      at async SignInService.invoke (/home/thecloud/omlife/applications/http/functions/lib/application/services/auth/auth/sign.in.service.js:21:37)
>      at async signIn (/home/thecloud/omlife/applications/http/functions/lib/application/controllers/api/public/auth/auth.controller.js:47:37) {
>    errorInfo: {
>      code: 'auth/internal-error',
>      message: 'An internal error has occurred. Raw server response: "{"error":{"code":400,"message":"Invalid JSON payload received. /validDuration should be string","errors":[{"message":"Invalid JSON payload received. /validDuration should be string","reason":"invalid","domain":"global"}],"status":"INVALID_ARGUMENT"}}"'
>    },
>    codePrefix: 'auth'
>  }

Please tell me what is this error?? It's  not clear what it means this error.

With no firebase emulator it can be very painful to code and test

**Comment by samtstern** [comment] 2020-12-28 10:39
@omlifeapp please fill out the issue template when filing an issue, we can't help you without more information.  Based on the limited error message you provided I think this is a duplicate of this issue:
https://github.com/firebase/firebase-admin-node/issues/1084

please follow along there.

**Closed by samtstern** 2020-12-28 10:39 UTC
