### ISSUE TITLE
New Firebase UI not working within WSL(2)

### ISSUE THREAD

**Issue by zachary-russell** [firebase/firebase-tools#2272] opened 2020-05-21 22:50 UTC
High level the web UI is not working in WSL. 

### [REQUIRED] Environment info

**firebase-tools:**
8.4.0

**Platform:**
Windows 10 with WSL (Ubuntu 20.04)

### [REQUIRED] Test case

Create a new Firebase project.

### [REQUIRED] Steps to reproduce

1. Firebase Init selecting an existing project (or a new one) w/ only enabling firestore and emulator use default settings.
2. Run `firebase emulators:start`
3. Go to the web UI link (localhost:4000 in my case)

### [REQUIRED] Expected behavior

Display the web UI

### [REQUIRED] Actual behavior

Get "Unable to connect" error.

```
firebase emulators:start --debug
[2020-05-21T22:48:25.711Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-05-21T22:48:25.712Z] > authorizing via signed-in user
i  emulators: Starting emulators: firestore {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: firestore"}}
[2020-05-21T22:48:25.729Z] [hub] writing locator at /tmp/hub-client-dashboard-495a3.json
⚠  functions: The functions emulator is configured but there is no functions source directory. Have you run firebase init functions? {"metadata":{"emulator":{"name":"functions"},"message":"The functions emulator is configured but there is no functions source directory. Have you run \u001b[1mfirebase init functions\u001b[22m?"}}
[2020-05-21T22:48:25.756Z] Ignoring unsupported arg: projectId {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: projectId"}}
[2020-05-21T22:48:25.756Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: auto_download"}}
[2020-05-21T22:48:25.756Z] Starting Firestore Emulator with command {"binary":"java","args":["-Duser.language=en","-jar","/home/zach/.cache/firebase/emulators/cloud-firestore-emulator-v1.11.4.jar","--host","localhost","--port",8080,"--rules","/home/zach/foo/firestore.rules"],"optionalArgs":["port","webchannel_port","host","rules","functions_emulator","seed_from_export"],"joinArgs":false} {"metadata":{"emulator":{"name":"firestore"},"message":"Starting Firestore Emulator with command {\"binary\":\"java\",\"args\":[\"-Duser.language=en\",\"-jar\",\"/home/zach/.cache/firebase/emulators/cloud-firestore-emulator-v1.11.4.jar\",\"--host\",\"localhost\",\"--port\",8080,\"--rules\",\"/home/zach/foo/firestore.rules\"],\"optionalArgs\":[\"port\",\"webchannel_port\",\"host\",\"rules\",\"functions_emulator\",\"seed_from_export\"],\"joinArgs\":false}"}}
i  firestore: Firestore Emulator logging to firestore-debug.log {"metadata":{"emulator":{"name":"firestore"},"message":"Firestore Emulator logging to \u001b[1mfirestore-debug.log\u001b[22m"}}
[2020-05-21T22:48:26.589Z] API endpoint: http:// {"metadata":{"emulator":{"name":"firestore"},"message":"API endpoint: http://"}}
[2020-05-21T22:48:26.589Z] localhost:8080
If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:

   export FIRESTORE_EMULATOR_HOST=localhost:8080

Dev App Server is now running.

 {"metadata":{"emulator":{"name":"firestore"},"message":"localhost:8080\nIf you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:\n\n   export FIRESTORE_EMULATOR_HOST=localhost:8080\n\nDev App Server is now running.\n\n"}}
⚠  hosting: The hosting emulator is configured but there is no hosting configuration. Have you run firebase init hosting? {"metadata":{"emulator":{"name":"hosting"},"message":"The hosting emulator is configured but there is no hosting configuration. Have you run \u001b[1mfirebase init hosting\u001b[22m?"}}
[2020-05-21T22:48:26.777Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: auto_download"}}
[2020-05-21T22:48:26.777Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: port"}}
[2020-05-21T22:48:26.777Z] Starting Emulator UI with command {"binary":"node","args":["/home/zach/.cache/firebase/emulators/ui-v1.0.0/server.bundle.js"],"optionalArgs":[],"joinArgs":false} {"metadata":{"emulator":{"name":"ui"},"message":"Starting Emulator UI with command {\"binary\":\"node\",\"args\":[\"/home/zach/.cache/firebase/emulators/ui-v1.0.0/server.bundle.js\"],\"optionalArgs\":[],\"joinArgs\":false}"}}
i  ui: Emulator UI logging to ui-debug.log {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI logging to \u001b[1mui-debug.log\u001b[22m"}}
[2020-05-21T22:48:26.849Z] Web / API server started at http://localhost:4000
 {"metadata":{"emulator":{"name":"ui"},"message":"Web / API server started at http://localhost:4000\n"}}

┌───────────────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! View status and logs at http://localhost:4000 │
└───────────────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Firestore │ localhost:8080 │ http://localhost:4000/firestore │
└───────────┴────────────────┴─────────────────────────────────┘
  Other reserved ports: 4400, 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
```

**Comment by gugahoi** [comment] 2020-05-31 12:27
I've just updated to `8.4.1` of `firebase-tools` and the UI showed up without a problem. Have WSL2 and Ubuntu 20.04 as well with `firebase-tools` installed inside Ubuntu. I am able to hit the UI fine on port 4000.

**Comment by samtstern** [comment] 2020-06-02 16:17
@zachary-russell I just tried this on my personal laptop (Windows 10 + WSL2 Debian) and was not able to reproduce this.  I'm going to close this for now, if you can find any more information to help us reproduce let me know.

**Closed by samtstern** 2020-06-02 16:17 UTC
Labels: emulator-suite, emulators: ui, platform: windows
