### ISSUE TITLE
enoent: client-reference-manifest.js on firebase deploy with next 13.4.10

### ISSUE THREAD

**Issue by Retroscilo** [firebase/firebase-tools#6136] opened 2023-07-16 20:53 UTC
### Environment info

**firebase-tools:** 12.4.4

**Platform:** MacOS Ventura 13.4.1

###  Test case

Clone this repo or run npx create-next-app {app name}
```
https://github.com/Retroscilo/firebase-issue-enoent
```

### Steps to reproduce

**Be sure to have a firebase project with hosting linked to your cli**

````
pnpm install
````
```
firebase experiments:enable webframeworks
```
```
firebase init hosting
```
```
firebase deploy
````

### Expected behavior

Successful deploy

### Actual behavior

> Route (app)                                Size     First Load JS
> ┌ ○ /                                      4.92 kB        82.4 kB
> └ ○ /favicon.ico                           0 B                0 B
> + First Load JS shared by all              77.5 kB
>   ├ chunks/43e2ea16-9531e6ae7a6ea89d.js    50.5 kB
>   ├ chunks/783-76c4f6565d5676e6.js         25.1 kB
>   ├ chunks/main-app-ad2d25f40c0d6de4.js    211 B
>   └ chunks/webpack-76fd8b39fe914c29.js     1.65 kB
> 
> Route (pages)                              Size     First Load JS
> ─ ○ /404                                   182 B          75.5 kB
> + First Load JS shared by all              75.3 kB
>   ├ chunks/framework-510ec8ffd65e1d01.js   45 kB
>   ├ chunks/main-c65570355d71a9c0.js        28.4 kB
>   ├ chunks/pages/_app-c4c131a3a3a69845.js  195 B
>   └ chunks/webpack-76fd8b39fe914c29.js     1.65 kB
> 
> 
> ○  (Static)  automatically rendered as static HTML (uses no initial props)
> 
> 
> **[2023-07-16T20:35:47.505Z] Error: ENOENT: no such file or directory, open '/Users/loictorres/Desktop/firebase-issue-enoent/.next/server/client-reference-manifest.js'**
> 
> Error: An unexpected error has occurred.

**Comment by aalej** [comment] 2023-07-17 09:50
Hi @Retroscilo, thanks for the detailed report! From what I can tell, the cause of this issue is the same as [#6135](https://github.com/firebase/firebase-tools/issues/6135). That said, I’ll be closing this as a duplicate. Please refer to the other issue for any updates.

Feel free to ask this to be reopened If you feel like I’ve made a mistake here.

**Closed by aalej** 2023-07-17 09:50 UTC
Labels: type: bug, integration: web frameworks
