### ISSUE TITLE
Cleanup Artifact Registry after deploy function v1 and v2

### ISSUE THREAD

**Issue by absemetov** [firebase/firebase-tools#5935] opened 2023-06-05 07:58 UTC
Node.js 18 (1st Gen)
I disabled one of the projects, but I still received a bill for the $3.50 fee.
In the Google cloud console, I found out that this is a payment for the Artifact Registry.
(https://console.cloud.google.com/artifacts).
For example, if you deploy the function 3 times, the storage volume will increase to 567.4 MB
Directory structure 3 images in: **gcf-artifacts/function-ID/cache** One of them has the tag **latest**
Related issues [#3404](https://github.com/firebase/firebase-tools/issues/3404)

I found comment in [src](https://github.com/firebase/firebase-tools/tree/858695fd07ee0b4d858ba3bf62617de252c28377/src)/[deploy](https://github.com/firebase/firebase-tools/tree/858695fd07ee0b4d858ba3bf62617de252c28377/src/deploy)/[functions](https://github.com/firebase/firebase-tools/tree/858695fd07ee0b4d858ba3bf62617de252c28377/src/deploy/functions)
/containerCleaner.ts
```
 // GCFv1 for AR has the following directory structure
  // Hostname: <region>-docker.pkg.dev
  // Directory structure:
  // gcf-artifacts/
  //     +- <function ID>
  //     +- <function ID>/cache
  // We leave the cache directory alone because it only costs
  // a few MB and improves performance. We only delete the cache if
  // the function was deleted in its entirety.
```
a few MB??? What a performance?

**Comment by aalej** [comment] 2023-06-06 15:11
Hi @absemetov, sorry to hear that you’re running into this issue. I understand that it's concerning that you are being charged for the usage of Artifact Registry for each function deployment. 

I’m currently trying to reproduce this issue, and I would like to verify a few things. First, could you please let us know which version of firebase-tools you’re using? I’m currently using v12.3.0.

Second, when I tried deploying functions multiple times as you mentioned, I did not see an increase in the size of the image. Are you deploying the same functions without any changes, or are you doing something different for each deployment?

If I may have misunderstood you in any way, please let me know.

**Comment by absemetov** [comment] 2023-06-06 17:09
Hi @aalej, I use firebase-tools v12.3.0. region **europe-central2**.
For example, I'm deploying the same function without any changes. I don't think that changes in the code of the function affect anything. My function code is https://github.com/absemetov/rzk-com-ua/blob/master/functions/bot/index.js

**Comment by absemetov** [comment] 2023-06-10 08:54
I migrated to 2nd gen. Artifact Registry also growing fast...

**Comment by Applitom** [comment] 2023-06-10 12:35
Hello,
I'm facing the same problem.  Deploying my functions and `gcf-artifacts/function-ID/cache` getting bigger.
Myfirebase CLI version is `12.3.1`and  tried to run `firebase functions:deletegcfartifacts` but doesn't seem like it delete something, I still see the same files after running the command. 
Can I safely delete these folders to avoid extra charges?

Thanks,
Tomer.

**Comment by colerogers** [comment] 2023-06-13 20:22
Hey folks! This looks like it is working as intended. The firebase CLI cleans up the function folder in artifact registry so that we can stay as close to the free tier as possible ([see pricing](https://cloud.google.com/artifact-registry/pricing)). If you look at that page, you're only charged $0.10/Month per GB above the 500MB free tier for storage.

We leave the /cache part so that subsequent deploys are faster due to how container images are layered together at build time. You should be able to delete the folder manually without having function runtime problems, but the deploys will be slower. 

I'm going to close out this issue. Let me know if I made a mistake and there actually is a bug here. Thanks!

**Comment by colerogers** [comment] 2023-06-15 17:37
@absemetov can you figure out what directory inside artifact registry is 35GB? Is it the cache? Are you only using firebase functions and don't have anything else inside artifact registry? If you delete everything manually and re-deploy, are you still seeing this issue?

I'm not able to reproduce this on my end and your issue seems to be isolated so I'm not sure if this is a bug that firebase introduced. Thanks

**Comment by absemetov** [comment] 2023-06-17 09:17
@colerogers I only use firebase functions. Yes, it's cache. Strange behavior if you load a function with a period of 10-15 minutes, a new image is not created, but if you load after more than 30 minutes, a new image is created. Screenshot attached
![AR](https://github.com/firebase/firebase-tools/assets/735924/f32e2598-33a0-469a-b2fa-8b3b72a1a5f0)

**Comment by KoheiKanagu** [comment] 2023-09-20 06:01
I have the same issue. 
However, in another function, there was only one image with the 'latest' tag.

<img width="753" alt="スクリーンショット 2023-09-20 14 55 39" src="https://github.com/firebase/firebase-tools/assets/6175794/a99d7d07-2dc8-4e91-b4ff-2a86289a83b2">

**Comment by colerogers** [comment] 2023-09-21 19:52
@absemetov You can safely delete the cache. Like I said above, we keep the cache to speed up deployments of functions, but feel free to manually remove it.

@KoheiKanagu Similar to @absemetov, if you'd like to delete the cache directory, that's perfectly fine. We keep it around for improved speed.

Since this seems to be working as intended, I'm going to close this issue out.

**Closed by colerogers** 2023-09-21 19:52 UTC
Labels: type: bug, api: functions, Needs: Attention

**Comment by KoheiKanagu** [comment] 2023-09-22 04:11
Thank you. I understand the meaning of "cache" now.

Looking at the Cloud Build logs, it took longer to build when there was no cache.
