### ISSUE TITLE
Sveltekit dev module variable is true on prod deployment

### ISSUE THREAD

**Issue by danielfrg** [firebase/firebase-tools#5962] opened 2023-06-12 02:44 UTC
### [REQUIRED] Environment info

**firebase-tools:** 11.28.0 and the latest [Github Action](https://github.com/FirebaseExtended/action-hosting-deploy)

**Platform:**

### [REQUIRED] Test case

Any sveltekit project that uses the [dev module](https://kit.svelte.dev/docs/modules#$app-environment-dev)

### [REQUIRED] Steps to reproduce

For example I use it to show stuff in the UI when I am in dev mode:

```
{#if dev}
   ... stuff ...
{/if}
```

### [REQUIRED] Expected behavior

In prod the content should be ignored since the dev variable is false. This works fine with doing a regular svelte build. For example doing an static build and deploying that to firebase. When using the frameworks this variable is set to `true` for some reason.

### [REQUIRED] Actual behavior

When doing firebase deploy it doesn't seem to set this variable for some reason, probably because the adaptar is ignored. Not 100% sure why.

**Comment by caidanw** [comment] 2023-06-28 20:08
I was having trouble with this as well and finally found the answer after some research. It looks like what is happening is that somewhere in the firebase-tools codebase (not sure where yet) the env var `NODE_ENV` is being set to `development` instead of `production`.

My research let me to find that when running `firebase deploy` and checking the build output in the `.svelte-kit/output` dir, I can see dev specific code and the presence of `.svelte-kit/output/server/chunks/dev-ssr.js`. I can also see the presence of `.firebase/[PROJECT-ID]/functions/chunks/dev-ssr.js` as well.

I found a few other github issues that referenced a similar problem but with the env var `FIREBASE_FRAMEWORKS_BUILD_TARGET`
- https://github.com/firebase/firebase-tools/issues/5907
- https://github.com/firebase/firebase-tools/issues/6041
- https://github.com/firebase/firebase-tools/issues/5896

There is a lot of mention in those tickets that the issue related to `FIREBASE_FRAMEWORKS_BUILD_TARGET` has been fixed in firebase-tools `v12.3.0`, which was weird since I am on `v12.4.1`.

I tried using `FIREBASE_FRAMEWORKS_BUILD_TARGET=production firebase deploy` but that didn't help. After investigating the code I came across the env var `NODE_ENV` in:
https://github.com/firebase/firebase-tools/blob/3d3f5ef4ee2a57d9749b86a11ffb94a98776bbc3/src/frameworks/utils.ts#L296-L303

Now vite should already be setting `NODE_ENV=production` when you use `vite build` (in your `npm run build` script). So it's very confusing why this isn't being set properly.

Regardless of what is happening, you can fix the issue to have firebase build sveltekit in production mode by using:
```bash
NODE_ENV=production firebase deploy
```

**Comment by anhtuank7c** [comment] 2023-10-14 14:42
@caidanw I am using github action to automatically deploy firebase hosting app.
Is there any configuration for github action workflow to set env to production as your solution?

**Comment by anhtuank7c** [comment] 2023-10-19 09:38
Thank you so much @caidanw 🎉

**Comment by phcoliveira** [comment] 2023-11-01 15:06
I have a related issue, and I am not sure if I should create another ticket for it.

When I first used `firebase init hosting` and configured it to serve a SvelteKit app, I had a nice surprise whe I ran `firebase emulators:start`. Given that `hosting` is also a service to be emulated, firebase used `vite build` for compiling a production app to be served via an `ssr` function.

It was a nice surprise because I wasn't expecting to access the app via a hosting function from the emulator, but that was good.

However, that was not ideal for development because further changes were not noticed by the browser, as the app served was built in production mode.

So I came up with this script, to emulate everything else but hosting in order to access the app via `vite dev` instead of an `ssr` function.
```
"scripts: {
  "dev": "firebase emulators:exec --ui --only=auth,database,firestore,functions 'vite dev'"
}
```

So far, so good. I could access the app with HMR in dev mode.

Now, I don't know what I did, but running `firebase emulators:start` for all services does NOT build the app in production mode anymore. Somehow the `hosting` service starts `vite dev` on its own and serves it from there. So both ports (`5173` from `vite dev` and `5000` from `hosting`) serves the same content. And changes are reflected on both ports as well.

And I am afraid this will be reproduced in my production environment, with `hosting` spawning a `vite dev` to serve from it.

Can you please make a similar experiment to make sure that `firebase emulators:start`, using `hosting` properly configured for handling SvelteKit, does use `vite build` and served the application in production mode?

Thank you!

**Comment by phcoliveira** [comment] 2023-11-01 15:26
I used `NODE_ENV=production firebase emulators:start` and the `hosting` built the app in production mode. So I guess my problem was fixed.

I didn't do it in the first time I tried, but it does not seem important to know why that happened.

**Closed** 2024-01-23 14:03 UTC
Labels: type: bug, integration: web frameworks
