### ISSUE TITLE
firebase.config() exists in functions but empty when called from webapp

### ISSUE THREAD

**Issue by anandrishabh1** [firebase/firebase-tools#2466] opened 2020-07-17 00:24 UTC
### [REQUIRED] Environment info

**firebase-tools:**
8.4.3

**Platform:**
macOS
### [REQUIRED] Test case

1. Set a function config on the local machine:
`firebase functions:config:set app.environment="prd"`

2. Deploy functions and check if the config is set by logging functions.config()
![image](https://user-images.githubusercontent.com/24405046/87734839-5cdafa80-c799-11ea-8900-09e65e6a8bf1.png)

3. console.log(functions.config()) before firebase.initializeApp in webapp:
![image](https://user-images.githubusercontent.com/24405046/87735112-2ce02700-c79a-11ea-9082-3bea8f698484.png)
**Output is an empty dictionary**

### [REQUIRED] Steps to reproduce
Same as above

### [REQUIRED] Expected behavior
Functions.config() should return the set config in order to change the firebase config based on project that webapp is deployed in order to achieve staging/prod/testing environment differentiation.

### [REQUIRED] Actual behavior
functions.config() is an empty dictionary which leads to a loss of access to app.environment resulting in no control over differentiation between firebase environments

**Comment by samtstern** [comment] 2020-07-17 11:12
@anandrishabh1 when you say "in webapp" do you mean from a website using the Firebase JS SDK?  If so that's the intended behavior, `functions.config()` is **only** available in the Cloud Functions environment, it uses the Cloud Runtime Configuration API.

If you want config for your web app, try Remote Config:
https://firebase.google.com/docs/remote-config/use-config-web

Closing this as it doesn't seem like it's a Firebase CLI issue.

**Closed by samtstern** 2020-07-17 11:12 UTC
