### ISSUE TITLE
Auth Emulator: Fails to import users when data size is > 100KB

### ISSUE THREAD

**Issue by mgreenw** [firebase/firebase-tools#3607] opened 2021-07-26 13:53 UTC
### [REQUIRED] Environment info

**firebase-tools:** 9.16.0

**Platform:** macOS 11.2.3

### [REQUIRED] Test case

Add at least 500 auth users to a fresh hosted firebase project

### [REQUIRED] Steps to reproduce

1. Generate test case data
2. Export those users with `firebase auth:export accounts.json`
3. Start a new firebase emulator with `firebase emulators:start --import ./emulators/local --export-on-exit`
4. Exit the emulator, and then copy `accounts.json` to the correct location in the new emulator export (`auth_export/accounts.json`).
5. Start up the emulator again

### [REQUIRED] Expected behavior

The auth emulator to start and import all of the users.

### [REQUIRED] Actual behavior

```log
Error: Error during Auth Emulator import: Received HTTP status code: 413
{
  "message": "request entity too large",
  "limit": 100000,
  "received": 126634,
  "type": "entity.too.large"
}
error Command failed with exit code 1.
```

**Comment by yuchenshi** [comment] 2021-07-27 00:09
Duplicate of #3577.

**Closed by yuchenshi** 2021-07-27 00:09 UTC
Labels: emulators: auth
