### ISSUE TITLE
HTTP Error: 403, Read access to project <project-name> was denied: please check billing account associated and retry

### ISSUE THREAD

**Issue by daniel18acevedo** [firebase/firebase-tools#5992] opened 2023-06-15 20:53 UTC
OS: ubuntu

Platform:

Test case
I create a simple firebase project, enable storage service

Steps to reproduce
1. Generate a service account for the firebase project
2. Create a new keys
3. Set that key as an action secret in a github repository
4. Use the github action w9jds/firebase-action@master with GCP_SA_KEY

Expected behavior
Storage rules gets deployed

Actual behavior
There was an issue deploying your functions. Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again. If this issue persists, please contact support.

Error: HTTP Error: 403, Read access to project '' was denied: please check billing account associated and retry

**Comment by aalej** [comment] 2023-06-16 10:24
Hi @daniel18acevedo. From what I can tell, the error being raised is the same as the one you previously encountered in [#5955](https://github.com/firebase/firebase-tools/issues/5955), which was fixed in firebase-tools v12.4.0. 

Seems like the cause of this issue is that the GitHub Action for w9jds/firebase-action currently uses firebase-tools v11.30.0. I would recommend filing an issue in their [repository](https://github.com/w9jds/firebase-action/issues) so they can take a look into this and upgrade to the latest version.

That said, I’ll be closing this ticket. Let me know if you feel like I’ve made a mistake here, and if the issue is reproducible when using the latest version of firebase-tools. Thanks!

**Closed by aalej** 2023-06-16 10:24 UTC
Labels: type: bug, api: storage
