### ISSUE TITLE
TypeError: Cannot read property 'wanted' of undefined (I can't deploy Firebase, again)

### ISSUE THREAD

**Issue by davidaimes077** [firebase/firebase-tools#1589] opened 2019-08-08 15:54 UTC
Error on terminal: https://gist.github.com/davidaimes077/306f978a1b7193a020d2ab075631ae47

File containing the error:
https://gist.github.com/davidaimes077/f0e3c973589428e85a129e6ffdf68b4c

**Comment by bkendall** [comment] 2019-08-08 16:11
Please follow the template when filling out issues. It makes it much, much easier to debug your issue.

That said:
* I see you're using node 12 - there are some known quirks about 12 and we generally recommend using 8 or 10.
* You're using an old CLI version. Did you try upgrading it?
* Normally, I'd ask what your `npm` version is at this point, but it may not matter because...
* This is a duplicate of #1469. Upgrade `firebase-tools` to at least [`7.1.0`](https://github.com/firebase/firebase-tools/releases/tag/v7.1.0) and the issue will go away.

**Closed by bkendall** 2019-08-08 16:11 UTC

**Comment by knitesh** [comment] 2019-11-19 18:04
Upgrading to latest firebase-tools resolves this error
npm i -g firebase-tools@latest
