### ISSUE TITLE
Firebase emulator removes manually entered document references

### ISSUE THREAD

**Issue by dave0111** [firebase/firebase-tools#6161] opened 2023-07-19 18:13 UTC
### [REQUIRED] Environment info

MacOS Ventura, 13.4.1(c), Firebase CLI 12.4.4

**firebase-tools:**
12.4.4

**Platform:**
macOS

### [REQUIRED] Test case

Adding a new document, with a field of type reference, causes the emulator to revert that field to type string, and removing any value added, replacing it with an empty string.
Changing the type baco to reference, and adding again the value, once the document is already created causes the emulator to behave as expected, saving the field and the correct type and value.

### [REQUIRED] Steps to reproduce
1. Start firebase emulators `firebase emulators:start`
2. Connect to Firebase emulators web UI via localhost:4000
3. Add first sample collection in Firestore emulator (sample1)
4. Add example document to sample1
5. Add second sample collection in Firestore emulator (sample2)
6. Add example document in that sample2, also adding a field of type reference, pointing to the other document: `sample1/{document id}`

When clicking "Save", the field remains, but its type is changed to string, and its value is changed to an empty string

### [REQUIRED] Expected behavior

When a new document is created, any field manually added during document creation, of type reference and value, should retain that data.

### [REQUIRED] Actual behavior

When the new document is saved, all fields of type "reference" are reverted to type "string" and any associated value is deleted and replaced with an empty string

**Comment by aalej** [comment] 2023-07-20 13:31
Hi @dave0111, thanks for reporting this issue. I was able to replicate the behavior you mentioned. When creating a new document and adding a field with type `reference`, the value is set to a blank string and the type is set to `string`. 

I’ll raise this issue to our team so that we can investigate what’s causing this.

**Comment by aalej** [comment] 2023-07-20 18:44
Just and update here, discussed this issue with our team and it looks like this is a duplicate of [#554](https://github.com/firebase/firebase-tools-ui/issues/554). Please refer to the other issue for any updates.

**Closed by aalej** 2023-07-20 18:44 UTC
Labels: type: bug, emulators: firestore, reproducible
