### ISSUE TITLE
firebase-admin is installed but emulator not finding it

### ISSUE THREAD

**Issue by epomatti** [firebase/firebase-tools#1264] opened 2019-05-09 19:15 UTC
This problem started after I updated to `6.9.1`.

### [REQUIRED] Environment info

**firebase-tools:** 6.9.1

**Platform:** Windows 10 and 8

### [REQUIRED] Test case

**Minimal:** `firebase serve --only functions,hosting`

**Verifiable:** I was expecting the hosting and functions to startup normally since I did run `npm install` for the Node/Functions project, however the emulator is accusing that the package `firebase-admin` is not installed. I checked the directory and it is there.

**Complete:** https://github.com/epomatti/cbpq-firebase

### [REQUIRED] Steps to reproduce

```
git clone https://github.com/epomatti/cbpq-firebase.git
cd cbpq-firebase/functions
npm install
cd ..
firebase serve --only functions,hosting
```

### [REQUIRED] Expected behavior

Functions and hosting should be started, since firebase-admin is installed.

```
D:\ambientes\pomatti\cbpq-firebase\functions\node_modules>dir firebase-admin

09/05/2019  15:51    <DIR>          .
09/05/2019  15:51    <DIR>          ..
30/01/2019  15:28            23.786 CHANGELOG.md
09/05/2019  15:51    <DIR>          lib
04/05/2017  16:06            11.357 LICENSE
09/05/2019  15:51             4.072 package.json
07/08/2018  17:53             2.760 README.md
               4 files(s)         41.975 bytes
               3 folders(s)   31.983.542.272 bytes available
```

### [REQUIRED] Actual behavior

Error below is displayed and functions are not started.

**"The Cloud Functions emulator requires the module "firebase-admin" to be installed. This package is in your package.json, but it's not available. You probably need to run "npm install" in your functions directory."** 

Complete stack:

```
D:\ambientes\pomatti\cbpq-firebase>firebase serve --only functions,hosting
+  functions: Using node@10 from host.
+  functions: Emulator started at http://localhost:5001
i  functions: Watching "D:\ambientes\pomatti\cbpq-firebase\functions" for Cloud Functions...
i  hosting: Serving hosting files from: public
+  hosting: Local server: http://localhost:5000
!  The Cloud Functions emulator requires the module "firebase-admin" to be installed. This package is in your package.json, but it's not available. You probably need to run "npm install" in your functions directory.
i  functions: Your functions could not be parsed due to an issue with your node_modules (see above)
```

**Comment by abeisgoat** [comment] 2019-05-09 19:27
Duplicate of #1262 which will be fixed in next CLI release

**Closed by abeisgoat** 2019-05-09 19:27 UTC

**Comment by samtstern** [comment] 2019-05-10 23:45
Version `6.9.2` has been released with this fix.
