### ISSUE TITLE
Hosting emulator requires both login and permissions, but others don't

### ISSUE THREAD

**Issue by filipesilva** [firebase/firebase-tools#1861] opened 2019-12-12 10:45 UTC
Hi there 👋 

I'm trying to setup the emulators on a couple of projects but am running into a snag. It seems like the hosting emulator requires both login and certain permissions on the project, whereas the other emulators don't. I think this is a bug because the behaviour runs contrary to the purpose and use cases of the emulators.

This is a bit of a problem for me as a developer, and member of a larger team, because it means I must have firebase project permissions I wouldn't need otherwise. In fact I shouldn't have these permissions at all.

It is also a problem for CI environments because now the CI machine also needs to both login and have permissions, which implies some mechanism for secret sharing. I'd also need to have access to CI configuration to add the secret and keep it up to date. It's common enough for CI providers to support secret sharing, but it sounds like an unnecessary attack vector.

Lastly this also makes it hard to provide reproducible environments for open source projects. The repro provided (https://github.com/filipesilva/firebase-emulator-test) will work for me but not for anyone else.

The workaround is to use all emulators but the hosting one, and then use something else to serve (like the npm `serve` package). When using this workaround, I also need to match any firebase functionality like `public` and `rewrites` on the replacement server. This is a bit onerous and hurts the fidelity of the testing environment, but works. 

### [REQUIRED] Environment info

**firebase-tools:** 7.9.0

**Platform:** Ubuntu

### [REQUIRED] Test case

```
git clone https://github.com/filipesilva/firebase-emulator-test
cd firebase-emulator-test
```

### [REQUIRED] Steps to reproduce

```
yarn firebase emulators:start --only functions,firestore,database,pubsub
yarn firebase emulators:start --only hosting
```

### [REQUIRED] Expected behavior

Both emulator commands run successfully.

### [REQUIRED] Actual behavior

All other emulators run successfully:
```
~/s/firebase-emulator-test (master|✔) [130] $ yarn firebase emulators:start --only functions,firestore,database,pubsub
yarn run v1.17.3
$ /home/filipesilva/sandbox/firebase-emulator-test/node_modules/.bin/firebase emulators:start --only functions,firestore,database,pubsub
i  emulators: Starting emulators: functions, firestore, database, pubsub
⚠  Your requested "node" version "8" doesn't match your global version "12"
✔  functions: Emulator started at http://localhost:5001
i  firestore: Serving ALL traffic (including WebChannel) on http://localhost:8080
⚠  firestore: Support for WebChannel on a separate port (8081) is DEPRECATED and will go away soon. Please use port above instead.
i  firestore: Emulator logging to firestore-debug.log
✔  firestore: Emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
i  database: Emulator logging to database-debug.log
✔  database: Emulator started at http://localhost:9000
i  database: For testing set FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000
i  pubsub: Emulator logging to pubsub-debug.log
✔  pubsub: Emulator started at http://localhost:8085
i  functions: Watching "/home/filipesilva/sandbox/firebase-emulator-test/functions" for Cloud Functions...
✔  All emulators started, it is now safe to connect.
```

But the hosting emulator runs does not:
```
~/s/firebase-emulator-test (master|✔) [130] $ yarn firebase emulators:start --only hosting --debug
yarn run v1.17.3
$ /home/filipesilva/sandbox/firebase-emulator-test/node_modules/.bin/firebase emulators:start --only hosting --debug
[2019-12-12T10:22:17.809Z] ----------------------------------------------------------------------
[2019-12-12T10:22:17.811Z] Command:       /usr/bin/node /home/filipesilva/sandbox/firebase-emulator-test/node_modules/.bin/firebase emulators:start --only hosting --debug
[2019-12-12T10:22:17.812Z] CLI Version:   7.9.0
[2019-12-12T10:22:17.812Z] Platform:      linux
[2019-12-12T10:22:17.812Z] Node Version:  v12.13.0
[2019-12-12T10:22:17.812Z] Time:          Thu Dec 12 2019 10:22:17 GMT+0000 (Greenwich Mean Time)
[2019-12-12T10:22:17.812Z] ----------------------------------------------------------------------
[2019-12-12T10:22:17.812Z] 
[2019-12-12T10:22:17.817Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-12-12T10:22:17.818Z] > attempting to authenticate via app default credentials
[2019-12-12T10:22:17.870Z] ! auto-auth error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
[2019-12-12T10:22:17.871Z] > no credentials could be found or automatically retrieved

Error: Command requires authentication, please run firebase login
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If I have a login, but do not have permissions for the project, instead I get `Error: HTTP Error: 403, The caller does not have permission`.

**Comment by samtstern** [comment] 2019-12-12 16:51
@filipesilva thanks for the very clear and well-researched feedback!  This is actually a duplicate of the recently filed #1854 which includes a description of why the hosting emulator currently requires auth/internet and what we can do to fix it.

Let's continue this discussion there.

**Closed by samtstern** 2019-12-12 16:51 UTC
Labels: emulators: hosting

**Comment by filipesilva** [comment] 2019-12-12 17:07
I had seen that one but wasn't super confident that both `firebase serve` and the emulator were suffering from the same thing. Thanks for the confirmation, I'll add the emulator details there!
