### ISSUE TITLE
Issue with Emulators when uploading multiple images to Storage

### ISSUE THREAD

**Issue by FrancescoBia** [firebase/firebase-tools#3979] opened 2022-01-02 18:00 UTC
### [REQUIRED] Environment info

**firebase-tools:** 10.0.1

**Platform:** macOS Monterrey (M1)

### [REQUIRED] Test case

I'm trying to upload a list of images to Storage and retrieve the URLs. I'm running a web app with React + Redux.
Some notes:
1.  I've tried the code below **without** running the Emulators and **the issue does NOT occur**, so it seems like it's an issue related to the Emulators themselves.
2. The issue occurs when multiple files are selected. It works fine with one. By trying to upload a list of images, a seemingly  arbitrary number of images fail (sometimes none fails, but always at least 1 succeed).
3.  The upload of the images does seem to succeed, but I'm not able to retrieve the URLs as wanted
4. every time an image URL doesn't get printed out, a log like this shows: `{"result":{"permit":true},"id":22,"status":"ok"}`, which unfortunately doesn't however indicate an issue (strangely suggests the opposite).

### [REQUIRED] Steps to reproduce

1. select 1+ images with a <input type="file" ... /> HTML selector
2. try to upload the images with the following code:
```
const testUploadImage =
	(fileList) => async (dispatch) => {
		const fileListArray = Object.values(fileList)
		fileListArray.map((imageFile) => {
			uploadImageToStorage(imageFile).then((url) => {
				console.log(url)
			})
		})
	}

const uploadImageToStorage = (imageBlob) => {
	return new Promise((resolve, reject) => {
		const imageRef = storageRef(storage, `images/${imageBlob.name}/`)

		uploadBytes(imageRef, imageBlob)
			.then(() => {
				getDownloadURL(imageRef).then((url) => {
					resolve(url)
				})
			})
			.catch(function (error: any) {
				console.log(error)
				reject()
			})
	})
}
```

### [REQUIRED] Expected behavior

expect the console to log N urls (per N images uploaded)

### [REQUIRED] Actual behavior

not all URLs are printed out

```
[debug] [2022-01-02T17:30:26.556Z] ----------------------------------------------------------------------
[debug] [2022-01-02T17:30:26.557Z] Command:       /usr/local/bin/node /usr/local/bin/firebase emulators:start
[debug] [2022-01-02T17:30:26.558Z] CLI Version:   10.0.1
[debug] [2022-01-02T17:30:26.558Z] Platform:      darwin
[debug] [2022-01-02T17:30:26.558Z] Node Version:  v16.13.1
[debug] [2022-01-02T17:30:26.558Z] Time:          Sun Jan 02 2022 18:30:26 GMT+0100 (Central European Standard Time)
[debug] [2022-01-02T17:30:26.559Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-01-02T17:30:26.586Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-01-02T17:30:26.587Z] > authorizing via signed-in user (francesco.bianchi91@gmail.com)
[info] i  emulators: Starting emulators: auth, database, storage {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: auth, database, storage"}}
[debug] [2022-01-02T17:30:26.593Z] [hub] writing locator at /var/folders/2z/0v42927d7596xbvzx7rssft00000gn/T/hub-substratum-c6585.json
[debug] [2022-01-02T17:30:26.598Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/substratum-c6585 [none]
[debug] [2022-01-02T17:30:26.894Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/substratum-c6585 200
[debug] [2022-01-02T17:30:26.894Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/substratum-c6585 {"projectId":"substratum-c6585","projectNumber":"966383420012","displayName":"substratum-development","name":"projects/substratum-c6585","resources":{"hostingSite":"substratum-c6585","realtimeDatabaseInstance":"substratum-c6585","storageBucket":"substratum-c6585.appspot.com","locationId":"europe-west"},"state":"ACTIVE"}
[debug] [2022-01-02T17:30:26.894Z] database rules config:  [{"instance":"substratum-c6585","rules":"/Users/francescobianchi/Documents/GitHub/substratum/database.rules.json"}]
[debug] [2022-01-02T17:30:26.895Z] Ignoring unsupported arg: projectId {"metadata":{"emulator":{"name":"database"},"message":"Ignoring unsupported arg: projectId"}}
[debug] [2022-01-02T17:30:26.895Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"database"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2022-01-02T17:30:26.896Z] Ignoring unsupported arg: rules {"metadata":{"emulator":{"name":"database"},"message":"Ignoring unsupported arg: rules"}}
[debug] [2022-01-02T17:30:26.896Z] Starting Database Emulator with command {"binary":"java","args":["-Duser.language=en","-jar","/Users/francescobianchi/.cache/firebase/emulators/firebase-database-emulator-v4.7.3.jar","--host","localhost","--port",9000],"optionalArgs":["port","host","functions_emulator_port","functions_emulator_host"],"joinArgs":false} {"metadata":{"emulator":{"name":"database"},"message":"Starting Database Emulator with command {\"binary\":\"java\",\"args\":[\"-Duser.language=en\",\"-jar\",\"/Users/francescobianchi/.cache/firebase/emulators/firebase-database-emulator-v4.7.3.jar\",\"--host\",\"localhost\",\"--port\",9000],\"optionalArgs\":[\"port\",\"host\",\"functions_emulator_port\",\"functions_emulator_host\"],\"joinArgs\":false}"}}
[info] i  database: Database Emulator logging to database-debug.log {"metadata":{"emulator":{"name":"database"},"message":"Database Emulator logging to \u001b[1mdatabase-debug.log\u001b[22m"}}
[debug] [2022-01-02T17:30:28.928Z] 18:30:28.927 [NamespaceSystem-akka.actor.default-dispatcher-5] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
 {"metadata":{"emulator":{"name":"database"},"message":"18:30:28.927 [NamespaceSystem-akka.actor.default-dispatcher-5] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started\n"}}
[debug] [2022-01-02T17:30:29.094Z] 18:30:29.094 [main] INFO com.firebase.server.forge.App$ - Listening at localhost:9000
 {"metadata":{"emulator":{"name":"database"},"message":"18:30:29.094 [main] INFO com.firebase.server.forge.App$ - Listening at localhost:9000\n"}}
[debug] [2022-01-02T17:30:30.197Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"storage"},"message":"Ignoring unsupported arg: port"}}
[debug] [2022-01-02T17:30:30.447Z] Temp file directory for storage emulator: /var/folders/2z/0v42927d7596xbvzx7rssft00000gn/T/firebase/storage/blobs {"metadata":{"emulator":{"name":"storage"},"message":"Temp file directory for storage emulator: /var/folders/2z/0v42927d7596xbvzx7rssft00000gn/T/firebase/storage/blobs"}}
[debug] [2022-01-02T17:30:31.445Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2022-01-02T17:30:31.445Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: port"}}
[debug] [2022-01-02T17:30:31.445Z] Starting Emulator UI with command {"binary":"node","args":["/Users/francescobianchi/.cache/firebase/emulators/ui-v1.6.4/server.bundle.js"],"optionalArgs":[],"joinArgs":false} {"metadata":{"emulator":{"name":"ui"},"message":"Starting Emulator UI with command {\"binary\":\"node\",\"args\":[\"/Users/francescobianchi/.cache/firebase/emulators/ui-v1.6.4/server.bundle.js\"],\"optionalArgs\":[],\"joinArgs\":false}"}}
[info] i  ui: Emulator UI logging to ui-debug.log {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI logging to \u001b[1mui-debug.log\u001b[22m"}}
[debug] [2022-01-02T17:30:31.492Z] Web / API server started at localhost:4000
 {"metadata":{"emulator":{"name":"ui"},"message":"Web / API server started at localhost:4000\n"}}
[debug] [2022-01-02T17:30:31.710Z] >>> HTTP REQUEST PUT http://localhost:9000/.settings/rules.json?ns=substratum-c6585  
 {
	"rules": {
		"testAuth": {
			".read": "auth.uid != null",
			".write": "auth.uid != null"
		},
		"collections": {
			"$collection": {
				".read": "auth.uid != null",
				".write": "auth.uid != null"
			}
		},
		"users": {
			"$user": {
				".read": "auth.uid === $user",
				".write": "auth.uid === $user"
			}
		},
		"workspaces": {
			"$workspace": {
				".read": "data.child('adminId').val() === auth.uid",
				".write": "(data.child('adminId').val() !== null) ? (data.child('adminId').val() === auth.uid) : (auth.uid != null)"
			}
		},
		"auth-codes": {
			".read": true,
			".write": true
		},
		"invites": {
			"$invite-code": {
				".read": true,
				".write": false
			}
		}
	}
}

[debug] [2022-01-02T17:30:32.442Z] <<< HTTP RESPONSE 200 {"content-length":"15","content-type":"application/json; charset=utf-8","access-control-allow-origin":"*","cache-control":"no-cache","x-firebase-project-id":"substratum-c6585","x-firebase-project-number":"123456789","x-firebase-uuid":"9b8df98c-5ad5-4fb0-8039-2b2e0ab6c4cd"}
[info] 
┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://localhost:4000                │
└─────────────────────────────────────────────────────────────┘

┌────────────────┬────────────────┬────────────────────────────────┐
│ Emulator       │ Host:Port      │ View in Emulator UI            │
├────────────────┼────────────────┼────────────────────────────────┤
│ Authentication │ localhost:9099 │ http://localhost:4000/auth     │
├────────────────┼────────────────┼────────────────────────────────┤
│ Database       │ localhost:9000 │ http://localhost:4000/database │
├────────────────┼────────────────┼────────────────────────────────┤
│ Storage        │ localhost:9199 │ http://localhost:4000/storage  │
└────────────────┴────────────────┴────────────────────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
 
[info] {"result":{"permit":true},"id":21,"status":"ok"}
{"result":{"permit":true},"id":22,"status":"ok"}
{"result":{"permit":true},"id":23,"status":"ok"}
{"result":{"permit":true},"id":24,"status":"ok"} {"metadata":{"emulator":{"name":"storage"},"message":"{\"result\":{\"permit\":true},\"id\":21,\"status\":\"ok\"}\n{\"result\":{\"permit\":true},\"id\":22,\"status\":\"ok\"}\n{\"result\":{\"permit\":true},\"id\":23,\"status\":\"ok\"}\n{\"result\":{\"permit\":true},\"id\":24,\"status\":\"ok\"}"}}
[info] {"result":{"permit":true},"id":27,"status":"ok"}
{"result":{"permit":true},"id":28,"status":"ok"} {"metadata":{"emulator":{"name":"storage"},"message":"{\"result\":{\"permit\":true},\"id\":27,\"status\":\"ok\"}\n{\"result\":{\"permit\":true},\"id\":28,\"status\":\"ok\"}"}}

```

**Comment by abeisgoat** [comment] 2022-01-10 21:14
Interesting, this is probably due to the overlapping of async upload requests and something is not handling that routing properly.

**Comment by tonyjhuang** [comment] 2022-03-14 21:27
This is likely a duplicate of https://github.com/firebase/firebase-tools/issues/3915

**Comment by maxcorrads** [comment] 2022-04-16 13:47
> 

Is there any update on this?

**Comment by tonyjhuang** [comment] 2022-07-29 04:34
internal tracking bug, b/211308355

**Comment by tonyjhuang** [comment] 2022-07-29 04:36
Closing in favor of #3915

**Closed by tonyjhuang** 2022-07-29 04:36 UTC
Labels: type: bug, emulator-suite, emulators: storage
