### ISSUE TITLE
 Cloud Function and a Serverless VPC Access connector must be located in the same region.

### ISSUE THREAD

**Issue by ianitsky** [firebase/firebase-tools#4780] opened 2022-07-25 18:47 UTC
### [REQUIRED] Environment info

**firebase-tools: 11.3.0

**Platform: Ubuntu

### [REQUIRED] Test case

Create a VPC and add on runWith and execute:

firebase deploy --only functions

`
const runtimeOpts: RuntimeOptions = {
    vpcConnector: functions.config().vpc_connector.name,
    vpcConnectorEgressSettings: 'PRIVATE_RANGES_ONLY'
}
`

`functions.runWith(runtimeOpts)`

### [REQUIRED] Steps to reproduce

Create a VPC and add on runWith and execute:

firebase deploy --only functions

`const runtimeOpts: RuntimeOptions = {
    vpcConnector: functions.config().vpc_connector.name,
    vpcConnectorEgressSettings: 'PRIVATE_RANGES_ONLY'
}
functions.runWith(runtimeOpts)

### [REQUIRED] Expected behavior

Must works.

### [REQUIRED] Actual behavior

Throw error on terminal and show follow error on log:

[debug] [2022-07-15T15:27:12.832Z] <<< [apiv2][body] PATCH https://cloudfunctions.googleapis.com/v1/projects/*/locations/us-central1/functions/* {"error":{"code":400,"message":"The request has errors","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"vpc_connector","description":"A Cloud Function and a Serverless VPC Access connector must be located in the same region."}]}]}}

The upload works fine on version 11.1.0

**Comment by moldy530** [comment] 2022-08-01 18:50
I'm seeing this as well on v11.4.1 of firebase tools with the firebase-functions sdk v3.22

**Comment by taeold** [comment] 2022-08-03 18:31
Hey @ianitsky @moldy530 - thanks for taking time to report an issue.

Asking the obvious questions 

1) Can you give it another try with `v11.4.2` CLI (released yesterday). We fixed a load of issues with function configuration in the release.

2) What is the region of the function (which, I presume is the same region of the VPC). Do you happen to be deploying the function to multiple regions w/ options like `regions: ['us-central1', 'europe-west4']`?

I tried deploying a function with very simple VPC setup (function in `us-central1`, vpc connector also in `us-central1`) using the latest Functions SDK & CLI and wondering if there is a bug is hiding in more advanced setup.

**Comment by coolbho3k** [comment] 2022-08-03 19:16
We're getting this problem too. Updated to v11.4.2 CLI as well.

**Comment by taeold** [comment] 2022-08-03 19:20
@coolbho3k Do you have time to

1) Share snippets your `firebase-debug.log` from the failed deployment? Using `--debug` flag  should force generate `firebase-debug.log` if there aren't any.

2) Snippet of your source code that sets up the VPC connector on the function?

I'm trying to reproduce the issue w/o success using latest Firebase CLI / Functions SDK and wondering what I'm doing wrong. It would be especially helpful for me to inspect the payload we are sending to Google Cloud Function - that should include the vpc setting which seems to be what's going awry here.

**Comment by coolbho3k** [comment] 2022-08-03 20:16
@taeold Thanks for the reply!

Essentially here is the function:
```
export const testFunction = functions
  .runWith({
    timeoutSeconds: 540,
    memory: '8GB',
    vpcConnector: 'our-vpc-connector',
    vpcConnectorEgressSettings: 'PRIVATE_RANGES_ONLY',
  })
  .pubsub.topic('our-topic')
  .onPublish(async (msg: any, _context: any) => {
    // function contents
  });
```

With `our-vpc-connector` being replaced with our VPC connector and `our-topic` being replaced by a topic.

**We are currently working around the issue by just removing the VPC connector options from `runWith`. This is OK, as the VPC Connector setting on the Cloud Function persists despite it being missing from the function argument.** 

Keep in mind that we are actually currently on an older version of the SDK, 3.17.2, but we have the newest CLI, v11.4.2. We can try updating, but we were having some separate issues with a newer version and need to figure that out. Deployment was working fine until recently, though, despite the older SDK. It seems like this issue may be affecting newer SDKs too?

I'm actually not sure if I should post the whole `firebase-debug.log` as it may have some sensitive info, but here's an edited snippet from it showing the entire error. References to the project, topic, VPC connector, and function name were changed, but everything else is the same including regions:

```
{
  "endpoint": {
    "id": "testFunction",
    "project": "OUR_PROJECT",
    "region": "us-central1",
    "entryPoint": "testFunction",
    "platform": "gcfv1",
    "runtime": "nodejs14",
    "eventTrigger": {
      "eventType": "google.pubsub.topic.publish",
      "retry": false,
      "eventFilters": {
        "resource": "projects/OUR_PROJECT/topics/our-topic"
      }
    },
    "availableMemoryMb": 8192,
    "timeoutSeconds": 540,
    "vpc": {
      "connector": "projects/OUR_PROJECT/locations/$REGION/connectors/our-vpc-connector",
      "egressSettings": "PRIVATE_RANGES_ONLY"
    },
    "environmentVariables": {
      "VERSION": "aaaaaaaaa",
      "FIREBASE_CONFIG": "{\"projectId\":\"OUR_PROJECT\",\"databaseURL\":\"https://OUR_PROJECT.firebaseio.com\",\"storageBucket\":\"OUR_PROJECT.appspot.com\",\"locationId\":\"us-west2\"}",
      "GCLOUD_PROJECT": "OUR_PROJECT"
    },
    "codebase": "default",
    "labels": {
      "deployment-tool": "cli-firebase"
    }
  },
  "op": "create",
  "original": {
    "name": "FirebaseError",
    "children": [],
    "context": {
      "function": "projects/OUR_PROJECT/locations/us-central1/functions/testFunction"
    },
    "exit": 1,
    "message": "Failed to create function projects/OUR_PROJECT/locations/us-central1/functions/testFunction",
    "original": {
      "name": "FirebaseError",
      "children": [],
      "context": {
        "body": {
          "error": {
            "code": 400,
            "message": "The request has errors",
            "status": "INVALID_ARGUMENT",
            "details": [
              {
                "@type": "type.googleapis.com/google.rpc.BadRequest",
                "fieldViolations": [
                  {
                    "field": "vpc_connector",
                    "description": "A Cloud Function and a Serverless VPC Access connector must be located in the same region."
                  }
                ]
              }
            ]
          }
        },
        "response": {
          "statusCode": 400
        }
      },
      "exit": 1,
      "message": "HTTP Error: 400, The request has errors",
      "status": 400
    },
    "status": 500
  }
}
```

**Comment by coolbho3k** [comment] 2022-08-03 21:33
I notice in `environmentVariables`, `FIREBASE_CONFIG` was set to `us-west2` where the function is actually in `us-central1`.

Locally, my $FIREBASE_CONFIG doesn't include a `locationId`, so not sure where that's coming from.

**Comment by taeold** [comment] 2022-08-03 21:44
@coolbho3k I notice that:

```
      "connector": "projects/OUR_PROJECT/locations/$REGION/connectors/our-vpc-connector",
``

Is `$REGION` manual redaction or what we actually send to GCF?

Per `locationId` - I think that alludes to your App Engine project location (which isn't important in this case, but is important sometimes 🤔)

**Comment by coolbho3k** [comment] 2022-08-03 23:59
@taeold $REGION is not a redaction. I'm not sure if that uses the $REGION environment variable on my local machine. I can maybe try my local environment variable $REGION to `us-central1`.

Today, some people on our team can deploy just fine, others are running into this same issue. Everyone is on the same old SDK version, but probably different Firebase CLIs. Weird.

**Comment by moldy530** [comment] 2022-08-04 02:34
Sorry for the delay here, I'm also still seeing the error on the latest version of firebase-tools and my PATCH request in the firebase-debug also shows `$REGION` in the path for the vpc connector

**Comment by taeold** [comment] 2022-08-04 23:41
Uh oh - thanks for the updates @moldy530 @coolbho3k.

Unfortunately, I found a bug in our code:

https://github.com/firebase/firebase-tools/blob/191ef886585b1f7fa1957f6200bc1272ac28f264/src/deploy/functions/runtimes/node/parseTriggers.ts#L366

I will try to ship a fix asap, but I think the fix will be released at the earliest Monday of next week.

As you already know, few workarounds until then:

1) Pin Firebase CLI to the working version 11.1.0
2) Update your Firebase Functions SDK to the latest version.

Thanks for your help finding the bug and apologies for the inconvenience.

**Comment by coolbho3k** [comment] 2022-08-05 17:05
@taeold Great find, thanks!

**Closed** 2022-08-05 17:29 UTC
Labels: api: functions, Needs: Author Feedback, bug
