### ISSUE TITLE
Emulator Functions Regression - Initial Function Requests Time Out

### ISSUE THREAD

**Issue by dereekb** [firebase/firebase-tools#6765] opened 2024-02-13 00:23 UTC
### [REQUIRED] Environment info

**firebase-tools:13.2.1**

**Platform:macOS**

### [REQUIRED] Test case

I recently updated a number of firebase dependencies on my library and noticed that hitting the emulator's Firebase functions took a long time and would often time out and be left with an internal error.

I realized that if I turned my wifi/internet connection off that they would run quickly again. I kept noticing the following line:

```
⚠  External network resource requested!
   - URL: "http://169.254.169.254/computeMetadata/v1/universe/universe_domain"
```

This is followed by the function timing out:

```
i  Your function timed out after ~60s. To configure this timeout, see
      https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation.
i  Request to function failed: Error: socket hang up
```

I dug around and found out that this request was being made through gcp-metadata and timing out since it can't reach the specified IP which I'm guessing is an internal IP to Google Cloud.

I run the emulators in a Docker container and think that the environment is triggering some part of gcp-metadata or the firebase emulators to believe it is running on a Google Cloud instance and is timing out. I didn't notice this behavior while on firebase-tools version `11.17.0`.

I checked the versions of gcp-metadata:

```
dereekb@dbMBP dbcomponents % npm ls gcp-metadata google-auth-library 
@dereekb/dbx-components@10.0.17 /Users/dereekb/development/git/dbcomponents
├─┬ @google-cloud/firestore@7.3.0
│ └─┬ google-gax@4.3.0
│   └─┬ google-auth-library@9.6.3
│     └── gcp-metadata@6.1.0
├─┬ @google-cloud/pubsub@4.2.0
│ └─┬ google-auth-library@9.6.3
│   └── gcp-metadata@6.1.0
├─┬ firebase-admin@12.0.0
│ └─┬ @google-cloud/storage@7.7.0
│   └─┬ google-auth-library@9.6.3
│     └── gcp-metadata@6.1.0
├─┬ firebase-tools@13.2.1                            <---- imports older dependencies
│ ├─┬ @google-cloud/pubsub@3.7.5
│ │ ├─┬ google-auth-library@8.9.0
│ │ │ └── gcp-metadata@5.3.0
│ │ └─┬ google-gax@3.6.1
│ │   └─┬ google-auth-library@8.9.0
│ │     └── gcp-metadata@5.3.0
│ └─┬ google-auth-library@7.14.1
│   └── gcp-metadata@4.3.1          <---- version 4.3.1
├── gcp-metadata@5.3.0
└─┬ google-auth-library@8.9.0
  └── gcp-metadata@5.3.0 deduped
```

For now as a work around I am using the environment variable `GCE_METADATA_HOST` to set the host to 0.0.0.0 for the docker container so that the request fails immediately.

```
⚠  External network resource requested!
   - URL: "http://0.0.0.0/computeMetadata/v1/universe/universe_domain"
 - Be careful, this may be a production service.
```

In the newer versions of gcp-metadata (^5.3.0) I'd be able to use `METADATA_SERVER_DETECTION=none`.

### [REQUIRED] Steps to reproduce
You can run the project at https://github.com/dereekb/dbx-components on version v10.0.17 (version v10.0.18 will have the workaround added to the Dockerfile). Run both the server `./serve-server.sh` and web client `./serve-web.sh` and go to `http://localhost:9010/demo/app/profile/view`. Change the profile info to kick off a firebase functions request.

### [REQUIRED] Expected behavior
Emulator functions should not attempt to connect to or time out while trying to reach "http://169.254.169.254/computeMetadata/v1/universe/universe_domain".

### [REQUIRED] Actual behavior
The first emulator function invocation attempts to reach 169.254.169.254 and times out after 60 seconds, causing the initial invocation to return an internal error.

**Comment by naoina** [comment] 2024-02-13 15:23
I encountered the same issue and probably it is caused by [this changes](https://github.com/googleapis/gax-nodejs/pull/1552) of google-gax v4.3.0.
I backed to use google-gax v4.2.1, then it works well even if firebase-tools v13.2.1.

**Comment by joehan** [comment] 2024-02-15 17:06
Thanks for reporting this! This call is to the compute metadata server, which will only ever work on cloud compute instances. Ideally, google-gax would smoothly handle uses outside of cloud, so I've opened https://github.com/googleapis/gax-nodejs/issues/1566

**Comment by inlined** [comment] 2024-03-08 19:52
A fix will hopefully come out in next week's CLI release. In the meantime you can work around the issue by putting `METADATA_SERVER_DETECTION=none` in `$YOUR_FUNCTIONS_DIRECTORY/.env.local`

**Comment by inlined** [comment] 2024-03-10 23:23
Closing as the fix is in next week's release.

**Closed by inlined** 2024-03-10 23:23 UTC
Labels: type: bug, emulators: functions

**Comment by apeiniger** [comment] 2024-04-04 14:12
I'm seeing the same behavior in the newest version (13.6.1):

![image](https://github.com/firebase/firebase-tools/assets/2005574/ce3524ee-7b76-4d93-805f-b8b0757f21cd)

Tried to fix it via the env variable mentioned above but it doesn't work.

Any ideas what could cause this?

**Comment by Akronae** [comment] 2024-04-08 15:10
Same issue with `firebase-tools@13.0.3` on Windows WSL.
However it's not happening on MacOS.
![image](https://github.com/firebase/firebase-tools/assets/17302866/ee59e0cb-1a63-499c-ab9a-2566fcc4ebbf)

**Comment by EnduringBeta** [comment] 2024-05-10 21:07
> A fix will hopefully come out in next week's CLI release. In the meantime you can work around the issue by putting `METADATA_SERVER_DETECTION=none` in `$YOUR_FUNCTIONS_DIRECTORY/.env.local`

The timeout this issue refers to is still happening to me in GitHub Actions, and this `.env.local` suggestion did not fix it.

**Comment by glorat** [comment] 2024-06-30 04:03
Just to note I have also run into this issue if I'm using a local development environment with no GCP (firebase nor application default) credentials and am running the emulator under a demo project. The `GCE_METADATA_HOST="0.0.0.0"` trick also works for me. 

I'm on latest `firebase-tools` of 13.12.0

Since I have this reproduced on my local laptop, ping me if further diagnostics are needed to figure out what's up

**Comment by james-dellow** [comment] 2024-08-06 15:04
I'm encountering this on firebase-tools 13.15.0 running on Windows 11. Neither METADATA_SERVER_DETECTION="none" or GCE_METADATA_HOST="0.0.0.0" worked. I'm only using functions, firestore, hosting in the emulator.

**Comment by EnduringBeta** [comment] 2024-08-06 20:44
@inlined Should this issue be reopened? I and several others are reporting that we're still dealing with the same behavior.

**Comment by afmeirelles** [comment] 2024-08-08 23:56
> @inlined Should this issue be reopened? I and several others are reporting that we're still dealing with the same behavior.

I do think so. In my case, I'm running the emulator inside a docker container that has no credentials as well, so even with the ENV VARs set, I get the error 'GaxiosError: request to http://0.0.0.0/computeMetadata/v1/universe/universe-domain failed, reason: connect ECONNREFUSED 0.0.0.0:80\'

**Comment by james-dellow** [comment] 2024-08-16 22:41
The METADATA_SERVER_DETECTION override isn't working for me. I've resolved this temporarily:

- Not calling functions.config() when running on the emulator
- Editing google-auth-library\build\src\auth\googleauth.js to return false on _checkIsGCE(), as it was trigging the call to the metadata endpoint.

Change to this function:

I'll open a separate issue for this.

**Comment by jirawatee** [comment] 2024-09-21 15:35
I also found this issue with Firebase CLI v13.18.0 and I fixed by adding "GCE_METADATA_HOST=localhost:8080" to .env.local

Hope this help :)

**Comment by EnduringBeta** [comment] 2024-10-02 21:22
@joehan I suggest this issue be reopened. It may have a workaround, but people are still encountering it.

**Comment by EduardJoy** [comment] 2024-10-09 09:39
Greetings!

This issue is still happening as of this moment.

<img width="841" alt="image" src="https://github.com/user-attachments/assets/9ebc4f8f-4076-4ba3-a1b2-a5b39fbad4fd">

**Comment by rahul-sekhar** [comment] 2024-10-13 17:22
The `METADATA_SERVER_DETECTION` override didn't work for me either. I don't see this env variable being checked in the codepath in gcp-metadata 6.1.0.

I'm instead forcing the GCP residency check to false, and this seems to be working for me:
```
import { setGCPResidency } from "gcp-metadata";

if (process.env.FUNCTIONS_EMULATOR !== undefined) {
  console.log("Running in emulator mode - forcing GCP residency to false");
  setGCPResidency(false);
}
```

**Comment by rahul-sekhar** [comment] 2024-10-13 17:49
I found the root cause on my end and no longer need to use the fix above. We were using `FIREBASE_TOKEN` to run the emulators on our CI, which is now deprecated. If I switch to using a service account and `GOOGLE_APPLICATION_CREDENTIALS` instead, I don't see the issue any more.

**Comment by lukasvan3l** [comment] 2024-12-17 13:08
I'm seeing my emulator make requests to `http://169.254.169.254/computeMetadata/v1/universe/universe_domain`
From this thread I presume this entire request shouldn't be made on non-GCP systems.

The reason it is being called I traced through these functions:
* `getGCPResidency()`
* `setGCPResidency()`
* `detectGCPResidency()`
* `isGoogleCloudServerless()`
* `!!process.env.K_SERVICE

In my case, process.env.K_SERVICE is filled with the name of my Firebase Functions 2nd gen, and therefor the code thinks it's running on GCP Serverless. This shouldn't be the case.

Hope this can be fixed! I've been running into it since migrating to 2nd gen.
