### ISSUE TITLE
Emulator for storage

### ISSUE THREAD

**Issue by rohaanmd** [firebase/firebase-tools#2987] opened 2021-01-02 10:24 UTC
Emulator for storage

Please submit feature requests through our [support page](https://firebase.google.com/support/contact/bugs-features/).

**Comment by samtstern** [comment] 2021-01-05 10:26
@rohaanmd this is a duplicate of https://github.com/firebase/firebase-tools/issues/1738, see the discussion there.

**Closed by samtstern** 2021-01-05 10:26 UTC
