### ISSUE TITLE
NX Firebase hosting integration

### ISSUE THREAD

**Issue by barack98** [firebase/firebase-tools#6623] opened 2023-12-18 14:51 UTC
When I try to deploy an angular standalone app
I get the following error

_Could not determine the web framework in use.

Error: Unable to detect the web framework in use, check firebase-debug.log for more info._

How can I easily integrate Firebase with my NX monorepos
Is there a workaround this

**Comment by aalej** [comment] 2023-12-18 15:54
This seems to be a duplicate of #6049. That said, I’ll go ahead and close this for now. Please refer to the other issue for any updates.

**Closed by aalej** 2023-12-18 15:54 UTC
Labels: type: feature request, integration: web frameworks
