### ISSUE TITLE
Functions deployment: TIMEOUT: Port 5000 was not active within 30000ms

### ISSUE THREAD

**Issue by Karasuni** [firebase/firebase-tools#1517] opened 2019-07-17 16:00 UTC
### [REQUIRED] Environment info

**firebase-tools:** 7.1.0

**Platform:** Ubuntu on WSL on Windows 10
`nvm` with either node 10 or node 12

### [REQUIRED] Test case

Any firebase functions code (using the pre-7.1.0 template).

### [REQUIRED] Steps to reproduce

Run either `npm run serve` in the functions directory or 
```npm run build && firebase serve --only functions```

### [REQUIRED] Expected behavior

Functions should be deployed.

### [REQUIRED] Actual behavior

The functions failed to deploy. The error highlights a timeout for using port 5000.

> > functions@ serve /home/user/project/functions
> > npm run build && firebase serve --only functions
> 
> 
> > functions@ build /home/user/project/functions
> > tsc
> 
> ✔  functions: Using node@10 from host.
> 
> **Error: TIMEOUT: Port 5000 was not active within 30000ms**
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! functions@ serve: `npm run build && firebase serve --only functions`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the functions@ serve script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!    /home/user/.npm/_logs/2019-07-17T15_38_56_166Z-debug.log

### Notes

I've verified this issue on `node 10` and `node 12` using `npm 6.9.0`.
The port is not being used by another process.
Deployment of 'only hosting' using the same port is successful.
Reverting to the previous version `7.0.2` resolves the issue.

This issue was also observed, reported and discussed by another user at [StackOverflow](https://stackoverflow.com/questions/57070483/firebase-serve-only-functions-doesnt-work/57079786).

**Comment by samtstern** [comment] 2019-07-17 16:09
@Karasuni thanks for filing this, this seems to be a duplicate of #1458 so let's discuss there.

**Closed by samtstern** 2019-07-17 16:09 UTC

**Comment by Karasuni** [comment] 2019-07-17 16:30
@samtstern Are you sure this is the same issue?

I'm seeing this issue on Windows 10 Build 18362 running WSL 1, not WSL 2.

Also the issue I reported is with firebase-tools 7.1.0 but does not occur with 7.0.2.

**Comment by samtstern** [comment] 2019-07-17 16:33
@Karasuni yes it was reported in #1458 WSL1 (my initial assumption of WSL2 was wrong).  It's definitely interesting that this does not happen in 7.0.2 for you but I do think this will be the same root cause in the end, we just need to get some more testing done on WSL.

For now most signs point to this being the same issue, however once we start to fix the issue we will find out for sure.  I'll definitely re-open this issue if necessary!
