### ISSUE TITLE
Emulator socket fails on Windows with EACCES

### ISSUE THREAD

**Issue by jkarst** [firebase/firebase-tools#1280] opened 2019-05-13 05:22 UTC
### [REQUIRED] Environment info

**firebase-tools:**6.9.2

**Platform:**Windows

### [REQUIRED] Test case

With 6.9.2 I try to emulate functions locally and get this whenever I call a function:

`!  Your requested "node" version "8" doesn't match your global version "10"
+  functions: Emulator started at http://localhost:5000
i  functions: Watching "[removed]" for Cloud Functions...
!  Default "firebase-admin" instance created!
i  functions: HTTP trigger initialized at http://localhost:5000/[removed]/us-central1/helloWorld
i  functions: Beginning execution of "helloWorld"
!  Default "firebase-admin" instance created!
>  events.js:174
>        throw er; // Unhandled 'error' event
>        ^
>
>  Error: listen EACCES: permission denied C:\Users\Work\AppData\Local\Temp\firebase_emulator_invocation_10596.sock
>      at Server.setupListenHandle [as _listen2] (net.js:1253:19)
>      at listenInCluster (net.js:1318:12)
>      at Server.listen (net.js:1416:5)
>      at Function.listen (C:\Users\Work\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\application.js:618:24)
>      at Promise (C:\Users\Work\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:359:46)
>      at new Promise (<anonymous>)
>      at C:\Users\Work\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:332:15
>      at Generator.next (<anonymous>)
>      at C:\Users\Work\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71
>      at new Promise (<anonymous>)
>  Emitted 'error' event at:
>      at emitErrorNT (net.js:1297:8)
>      at process._tickCallback (internal/process/next_tick.js:63:19)
>      at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
>      at startup (internal/bootstrap/node.js:283:19)
>      at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

This behaviour was not present in 6.8.0 and I just verified that 6.8.0 works.

I even reinstalled Windows to double check (don't worry, it was time to do it anyway).

Note that I'm running firebase tools as the administrator, so not sure where the permission denied error is coming from.

Also note that when I run a basic express server:

`const express = require('express')
const app = express()
const port = "c:\temp\f.sock"

app.get('/', (req, res) => res.send('Hello World!'))

app.listen(port, () => console.log(`Example app listening on port ${port}!`))`

I get the same error.  

### [REQUIRED] Steps to reproduce

1. Install firebase tools@6.9.2
2. Init a new project with just functions
3. Uncomment the helloWorld function example
4. Emulate the function locally with firebase serve command
5. Call the localhost function url
6. Notice the crash

### [REQUIRED] Expected behavior

The function should run.

### [REQUIRED] Actual behavior

The function crashes.

**Comment by wzFLE** [comment] 2019-05-13 06:12
Same here. Downgraded firebase-tools to 6.9.0 to test, same crashing behavior

**Comment by abeisgoat** [comment] 2019-05-13 14:31
Thanks for the report @jkarst, looks like we've got a handful of Windows-exclusive issues. I'll dive into issues on there specifically today. Sorry for the inconvience, in the meantime feel free to `npm install -g firebase-tools@6.8.0` to roll back to the old emulator.

**Comment by JavierPAYTEF** [comment] 2019-05-14 20:22
I can confirm this is happening for me as well. Reverting to the previous version resolved the issue.
My stack trace is the same and I also have Node 10 installed instead of Node 8.

**Comment by epomatti** [comment] 2019-05-14 20:44
Same here with 6.9.2 on Windows and Node 10. Reverted back to 6.8.0.

**Comment by brendanosborne** [comment] 2019-05-15 04:29
Seeing the same issue. @epomatti how do you revert?

**Comment by ryanpbrewster** [comment] 2019-05-15 04:30
You should be able to downgrade via `npm install --global firebase-tools@6.8.0` (drop the `--global` flag if you're not installing it globally).

**Comment by epomatti** [comment] 2019-05-15 04:32
> 
> 
> Seeing the same issue. @epomatti how do you revert?

Run `npm install -g firebase-tools@6.8.0`

**Comment by brendanosborne** [comment] 2019-05-15 04:45
Thanks @epomatti and @ryanmeier - I'm back in business until this is resolved.

**Comment by abeisgoat** [comment] 2019-05-16 15:54
Alright, I've found a fix for this and will hopefully get it in for the `6.9.3` release this week!

**Comment by samtstern** [comment] 2019-05-16 18:18
Fix for this has been merged and will be included in the next release.

**Closed** 2019-05-16 18:18 UTC
Labels: emulator-suite, platform: windows, type: bug

**Comment by vdGitAway** [comment] 2019-05-20 05:24
> > Seeing the same issue. @epomatti how do you revert?
> 
> @brendanosborne run `npm install -g firebase-tools@6.8.0`... all of 6.9.x releases are broken in some way until now, you have to go 6.8.0.

Thanks. Spent many hours on this, thinking it was my fault.

**Comment by epomatti** [comment] 2019-05-20 13:38
@vdGitAway I've upgraded to **6.10.0** and it is working for me until now. It fixed this bug and many others. Give it a try.

If you have any problems delete `node_modules` directory.

I also had to include the following dev dependency, otherwise the code would not run:

```
  "devDependencies": {
    "firebase-functions-test": "^0.1.6"
  }
```

Since you're on it, run `npm outdated` and `npm update` too to get the latest versions for your dependencies.

**Comment by dreadrocksean** [comment] 2020-05-03 03:57
I'm having this issue and I'm on 8.2.0

**Comment by sadranyi** [comment] 2020-08-05 21:39
I am still seeing this issue as of today.
Windows 10 
Node 10
latest firebase-tools

**Comment by amebrahimi** [comment] 2021-07-28 06:30
I have this issue too I'm on windows 10 
Node v16.5.0
firebase 9.16.0
