### ISSUE TITLE
Auth emulator cannot handle (backup or emulate) large numbers of users > ~500

### ISSUE THREAD

**Issue by george43g** [firebase/firebase-tools#3755] opened 2021-09-14 09:10 UTC
### [REQUIRED] Environment info

**firebase-tools:** 9.12.0

**Platform:** macOS

### [REQUIRED] Test case

Write a simple loop that uses `faker` to generate 2k fake email accounts in Auth emulator using the admin SDK lib.

### [REQUIRED] Steps to reproduce

1. Start all emulators with backup export enabled
2. create 2k unique users by creating them manually with a local node script
3. shut down all emulators gracefully
4. try starting all emulators again with backup import - it will crash

This is even worse if onCreate triggers exist - memory leaks happen and emulator may crash before all users have been made

### [REQUIRED] Expected behavior

Run smoothly without memory leaks, high CPU usage or crashes.

I *personally* don't think Auth emulator was meant to handle huge numbers of users, as only a few hundred are really needed to run most kinds of tests. However, some startups/use cases require full database import and if you write a script to do this, this should be possible to do with the emulator. There are currently options to import accounts into real auth from JSON but not officially into Auth emulator.

### [REQUIRED] Actual behavior
 

```
Error: Error during Auth Emulator import: Received HTTP status code: 413
{
  "message": "request entity too large",
  "limit": 100000,
  "received": 130826,
  "type": "entity.too.large"
}
```
The `--debug` doesn't provide much more, than obviously saying the accounts.json import file is too large:
```
 {"metadata":{"emulator":{"name":"firestore"},"message":"8080\nIf you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:\n\n   export FIRESTORE_EMULATOR_HOST=localhost:8080\n\nDev App Server is now running.\n\n"}}
i  auth: Importing config from /Users/george/repos/blockframes/.firebase/emulator/auth_export/config.json {"metadata":{"emulator":{"name":"database"},"message":"Importing config from /Users/george/repos/blockframes/.firebase/emulator/auth_export/config.json"}}
i  auth: Importing accounts from /Users/george/repos/blockframes/.firebase/emulator/auth_export/accounts.json {"metadata":{"emulator":{"name":"database"},"message":"Importing accounts from /Users/george/repos/blockframes/.firebase/emulator/auth_export/accounts.json"}}
i  emulators: Shutting down emulators. {"metadata":{"emulator":{"name":"hub"},"message":"Shutting down emulators."}}
i  functions: Stopping Functions Emulator {"metadata":{"emulator":{"name":"functions"},"message":"Stopping Functions Emulator"}}
i  firestore: Stopping Firestore Emulator {"metadata":{"emulator":{"name":"firestore"},"message":"Stopping Firestore Emulator"}}
[2021-09-14T09:03:33.490Z] *** shutting down gRPC server since JVM is shutting down
 {"metadata":{"emulator":{"name":"firestore"},"message":"*** shutting down gRPC server since JVM is shutting down\n"}}
[2021-09-14T09:03:33.501Z] *** server shut down
 {"metadata":{"emulator":{"name":"firestore"},"message":"*** server shut down\n"}}
i  auth: Stopping Authentication Emulator {"metadata":{"emulator":{"name":"auth"},"message":"Stopping Authentication Emulator"}}
i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}
[2021-09-14T09:03:33.896Z] FirebaseError: Received HTTP status code: 413
{
  "message": "request entity too large",
  "limit": 100000,
  "received": 130826,
  "type": "entity.too.large"
}
    at IncomingMessage.<anonymous> (/Users/george/repos/blockframes/node_modules/firebase-tools/lib/emulator/auth/index.js:123:35)
    at IncomingMessage.emit (events.js:323:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Error: Error during Auth Emulator import: Received HTTP status code: 413
{
  "message": "request entity too large",
  "limit": 100000,
  "received": 130826,
  "type": "entity.too.large"
}
```

**Comment by yuchenshi** [comment] 2021-11-22 22:03
Duplicate of #3570

**Closed by yuchenshi** 2021-11-22 22:03 UTC
